### ISSUE TITLE
新版插件只有全局模式？

### ISSUE THREAD

**Issue by 286700234** [xiaorouji/openwrt-passwall2#1]
新版插件只有全局模式？

**Comment by xiaorouji** [comment]
是的，请灵活使用分流

**Comment by yaotthaha** [comment]
现在全部转向 Ray 的分流了吗

**Comment by snakwu** [comment]
@xiaorouji 
希望还可以像以前一样，多种代理模式，这样方便，特别是GFW模式，谢谢！
ps：以后luci-app-passwall2分到这了？

**Comment by xiaorouji** [comment]
https://www.v2fly.org/config/routing.html#ruleobject
