### ISSUE TITLE
最新编译的passwall2解析ipv6 dns问题，请老大看一下！谢谢！

### ISSUE THREAD

**Issue by sontjer** [xiaorouji/openwrt-passwall2#105]
发现一个问题：
1、smartdns：开启1053和5335两个端口作为adg上游，
2、adg：重定向53端口到adg，adg监听端口为5300。
3、在passwall2中开启了IPv6透明代理(TProxy)，直连dns协议自选为127.0.0.1：5300，只要重启openwrt后就无法解析ipv6，只能先选择直连dns协议为自动，再手动改为127.0.0.1：5300。不知道是不是算个bug

**Comment by lededev** [comment]
smartdns已经具备了adg的功能，passwall2也已经具备了adg的功能，因此没必要套一个adg。
建议直接用passwall2的，因为只需要维护和更新geosite.dat单个数据源就足够了。
![image](https://user-images.githubusercontent.com/30518126/167696285-6502689f-f449-4a0d-8515-3f84b7c27c51.png)

**Comment by sontjer** [comment]
谢谢回复！明白了。请问黑洞的数据来源是不是也是geosite.dat？需要额外升级数据文件吗？

**Comment by lededev** [comment]
passwall2的geosite.dat数据来源是
https://github.com/Loyalsoldier/v2ray-rules-dat
AD这条规则的定义是：`geosite:category-ads-all`
黑洞是出站数据协议，具体看XRay的[手册](https://xtls.github.io/config/outbounds/blackhole.html)解释

**Comment by sontjer** [comment]
非常之感谢！干净，清爽，啥套娃也不需要了，简直人类福音啊！
