### ISSUE TITLE
关于新增的hotplug重启的疑问

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-passwall2#106]
关于https://github.com/xiaorouji/openwrt-passwall2/pull/100
知道想要达成的目的，但是不确认是否具备普适性。
比方，如果多线网络，或者对于对外的interface命名为非“wan”的，是否有用？

**Comment by lededev** [comment]
我没有多线网络环境，估计未来几年也不会有，所以我的PR只能局限于我的网络环境。
也算是抛砖引玉吧，也许就有更具普适性的多线网络环境的用户继续提交代码呢。

**Comment by SakuraFallingMad** [comment]
哦哦，那么能不能调整成任意interface的ifup都触发重启，这样是不是更适合任意环境

**Comment by lededev** [comment]
那不是局域网内连接到网关网口的随便一台电脑或者路由器、交换机、AP一开机，都要断开外网链接重启一次。当然，似乎设置为**强制链路**可以不触发hotplug。
我这个PR的目的是网关上电之后，一旦能访问互联网了，第一时间重启psw2建立链路以便能访问谷歌或者Github这类网站，让其它脚本能正常进行数据更新。
而不是频繁断网玩，我这里没相关的多网线环境做测试，就不贸然凭空改动了。
