### ISSUE TITLE
关于passwall2订阅的问题

### ISSUE THREAD

**Issue by dhobii** [xiaorouji/openwrt-passwall2#108]
你好，我以前用passwall，现在换成passwall2，发现订阅功能和以前一不样了，功能失效，有办法解决不呢？

我和朋友共有3台VPS，自己做了个PHP的订阅连接，自动判断3台VPS的剩余流量数，订阅只输出剩余流量最多的节点信息。每个节点的备注名是不一样的。

用passwall时，每次更新订阅，能使用剩余流量最多的节点。

现在使用passwall2，更新订阅后，由于节点备注名不一样了，分流中的默认，会变成“直连”，必须要手动设置才能使用。

能不能在程序中加个判断，除了默认的“分流总切点”以外，存在其它节点时，把分流中的默认，自动设置到已有的节点呢？

谢

**Comment by lxmicode** [comment]
也发现，订阅功能失效

**Comment by vinwinchen** [comment]
部分ss的订阅失败。
