### ISSUE TITLE
passwall2和UnblockNeteaseMusic有冲突，同时开启会导致无法播放网易云

### ISSUE THREAD

**Issue by chris7395328** [xiaorouji/openwrt-passwall2#110]
如果开了同时打开，网易云会直接全部音乐都播放不了，但是手动在客户端代理设置UnblockNeteaseMusic的5200端口就可以正常使用
不然只能关闭其中一个后网易云才能播放了。
之前旧版的passwall和ssr+都没有这个问题
大概是因为UnblockNeteaseMusic本身就是ip劫持来达到效果的，和passwall2的嗅探分流冲突了
请问有没有解决的方法？

**Comment by iceyheart** [comment]
确实有这个问题。客户端代理设置是什么意思？我在PC网易云程序上手动设置代理也并没有效果

**Comment by YV-z** [comment]
同问，希望可以兼容
