### ISSUE TITLE
内存占用比1要高，经常OOM卡死

### ISSUE THREAD

**Issue by xcf13363175** [xiaorouji/openwrt-passwall2#111]
最新源码+Hysteria，512M硬路由
Fri May 13 08:10:27 2022 kern.err kernel: [22631.039140] Out of memory: Kill process 18290 (xray) score 297 or sacrifice child
Fri May 13 08:10:27 2022 kern.err kernel: [22631.048012] Killed process 18290 (xray) total-vm:4990268kB, anon-rss:125020kB, file-rss:0kB

**Comment by xcf13363175** [comment]
测试了Vless也会一直漏

**Comment by jh0072110** [comment]
硬路由完完全全不建议用2

**Comment by xcf13363175** [comment]
感觉2还可以优化一下，同样是1代的xray分流+Hysteria模式，不会OOM。
另外发现2代配合smartdns可以正常DOT，1代不行。

**Comment by xcf13363175** [comment]
发现问题了，和softethervpn冲突。
结束进程就正常了。表现为内存不漏了，并且慢慢恢复到正常值。不然会10秒少1M内存，直到OOM。
UDP设置了直连，并且不转发所有端口

**Comment by 0987363** [comment]
pve，虚拟机给2g，直通225 b3网卡
没有安装softethervpn
问题一样，一段时间后，也出现内存溢出
tcp跟udp都是转发除了bt端口以外的所有端口

**Comment by vinwinchen** [comment]
连接数无限增长导致内存大量占用。

**Comment by DrWindays** [comment]
acrh17，不用swap会oom，swap1G启用后，4个客户端同时放1080视频暂时还没有崩

**Comment by 0987363** [comment]
升级到最新固件后，每天定时重启，暂时没崩

**Comment by a904055262** [comment]
连接数上来就崩，换回passwall1了。。

**Comment by small-white-rabbit** [comment]
差不多的问题，现在暂时使用ssrp
