### ISSUE TITLE
编译x86出现如下错误

### ISSUE THREAD

**Issue by pangfeng161** [xiaorouji/openwrt-passwall2#112]
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'tcping', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'xray-core', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'v2ray-geoip', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'v2ray-geosite', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'brook', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'hysteria', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'naiveproxy', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'shadowsocks-rust-sslocal', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'simple-obfs', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'v2ray-core', which does not exist
WARNING: Makefile 'package/feeds/passwall2/luci-app-passwall2/Makefile' has a dependency on 'v2ray-plugin', which does not exist

**Comment by jh0072110** [comment]
U need git clone packages

**Comment by dhobii** [comment]
你这是依赖缺失啊，你下载依赖没有？
git clone https://github.com/xiaorouji/openwrt-passwall.git package/xiaorouji
svn export https://github.com/xiaorouji/openwrt-passwall2/trunk/luci-app-passwall2 package/xiaorouji/luci-app-passwall2

**Comment by pangfeng161** [comment]
> 你这是依赖缺失啊，你下载依赖没有？ git clone https://github.com/xiaorouji/openwrt-passwall.git package/xiaorouji svn export https://github.com/xiaorouji/openwrt-passwall2/trunk/luci-app-passwall2 package/xiaorouji/luci-app-passwall2

解决了,谢谢,新版使用还可以,但没有老版的功能齐全比如指定某台设备不走节点

**Comment by lededev** [comment]
> 解决了,谢谢,新版使用还可以,但没有老版的功能齐全比如指定某台设备不走节点

这么设置试试
https://github.com/xiaorouji/openwrt-passwall2/discussions/103

**Comment by pangfeng161** [comment]
> > 解决了,谢谢,新版使用还可以,但没有老版的功能齐全比如指定某台设备不走节点
> 
> 这么设置试试 #103
简单事情复杂化,还是希望和老版设置一样
