### ISSUE TITLE
第三方规则

### ISSUE THREAD

**Issue by lxmicode** [xiaorouji/openwrt-passwall2#113]
希望在订阅规则中可以多一个，添加第三方规则。
![1652756926](https://user-images.githubusercontent.com/43111963/168720412-29455721-299c-4964-a65c-69409276e043.png)

**Comment by xcf13363175** [comment]
自己改就可以，我改了只要cn和private的geoip

**Comment by skullcrossbones** [comment]
希望在订阅规则中可以多一个，添加第三方规则。
或者可以给到一个模板 谢谢 麻烦可以增加下pw2的wiki谢谢
