### ISSUE TITLE
tcping不支持ipv6

### ISSUE THREAD

**Issue by hswmartin** [xiaorouji/openwrt-passwall2#118]
包里面那个tcping不支持测试ipv6地址，可以换个支持ipv6的tcping吗？

**Comment by yaotthaha** [comment]
可以啊，是你的问题吧

**Comment by hswmartin** [comment]
> 可以啊，是你的问题吧

你打开tcping ipv6的节点能显示 延迟？

**Comment by yaotthaha** [comment]
tcping 本身没问题，luci不知道，也有可能luci有bug

**Comment by hswmartin** [comment]
> 



> tcping 本身没问题，luci不知道，也有可能luci有bug

![image](https://user-images.githubusercontent.com/21002122/175456545-dc149f96-3118-47b6-ac5c-c84f29030b3f.png)
我这个版本不行呢？你是哪个版本的tcping

**Comment by yaotthaha** [comment]
> > 
> 
> > tcping 本身没问题，luci不知道，也有可能luci有bug
> 
> ![image](https://user-images.githubusercontent.com/21002122/175456545-dc149f96-3118-47b6-ac5c-c84f29030b3f.png) 我这个版本不行呢？你是哪个版本的tcping

```
root@OpenWrt:~# tcping -v
tcping: unrecognized option: v
tcping version 0.3
Usage: tcping [-fqhv] [-p port] [-c count] [-i interval] [-t timeout] destination
-p port         Port number (default port 80)
-c count        How many times to connect
-i interval     Delay between each connect
-f              Flood connect (no delays)
-q              Quiet, only returncode
-t              Set timeout when connecting
-h              This help text
```

**Comment by yaotthaha** [comment]
https://github.com/Lienol/tcping

**Comment by hswmartin** [comment]
> https://github.com/Lienol/tcping

好的，谢谢，我换这个编译一下
