### ISSUE TITLE
Whatsapp Voice call & Desktop app [NOT WORKING]

### ISSUE THREAD

**Issue by bobby091983** [xiaorouji/openwrt-passwall2#13]
Passwall is a great tool. But I am facing a problem with a WhatsApp voice call that does not connect at all. And Whatsapp Desktop app keeps disconnecting needs to refresh it every time to get new messages.

I am using nanopi with passwall , using SSR servers. I have tried the following things so far but nothing has worked. 
1. Complete re-flash
2. DNS to google 
3. Changing CDU servers
none of the above methods fix the issue.

But when I am using CLASH for windows and Andriod I don't face the same problem with the same CDU servers. 

some screenshots are attached.

![image](https://user-images.githubusercontent.com/74587765/158312151-29a61542-e4e5-4c33-a28f-d308264470e0.png)

![image](https://user-images.githubusercontent.com/74587765/158312311-e330e0c2-bbb9-42ab-84d9-49bd7f9b8560.png)

**Comment by xiaorouji** [comment]
In most cases, the voice use UDP, please check you UDP proxy is normal?

**Comment by bobby091983** [comment]
Thank you for your reply. Yes UDP is normal and working fine. 
It always disconnects after idle for 2-3 mins, then I need to open the desktop APP and Mobile Phone app same time to get it to reconnect and receive the new message. If I don't do like that i cannot get new messages or media.

**Comment by bobby091983** [comment]
Can you help me with how can I change to Xray? I was not able to find the option to change to Xray.

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/159695098-efba92cd-7e36-4b55-b2d3-09511b304756.png)
Choose Xray.
