### ISSUE TITLE
请问passwall还在维护吗

### ISSUE THREAD

**Issue by tiantaichenhui** [xiaorouji/openwrt-passwall2#131]
好久没编译固件 今天准备编译更新固件的 才发现passwall没有了 现在只有2了
https://github.com/xiaorouji/openwrt-passwall 这个连接原先是passwall的库 现在好像变成了依赖包
请问还有维护passwall么

**Comment by jh0072110** [comment]
https://github.com/xiaorouji/openwrt-passwall

**Comment by tiantaichenhui** [comment]
> https://github.com/xiaorouji/openwrt-passwall/tree/luci

非常谢谢兄弟解答 鞠躬
