### ISSUE TITLE
最新版编译，每次重启后都无法连接网络

### ISSUE THREAD

**Issue by 0987363** [xiaorouji/openwrt-passwall2#134]
lede+passwall2
6月9号编译，lede跟passwall2都是最新源码
pppoe拨号

每次重启后
可以解析dns，可以ping，但是无法进行tcp连接，包括路由器自身和其他电脑
尝试添加延迟启动，问题一样
但网络实际上是通的

这是刚刚重启后路由器上的测试
```
root@OpenWrt:~# nslookup qq.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   qq.com
Address: 61.129.7.47
Name:   qq.com
Address: 183.3.226.35
Name:   qq.com
Address: 123.151.137.18


root@OpenWrt:~# curl qq.com
curl: (7) Failed to connect to qq.com port 80 after 1 ms: Connection refused
root@OpenWrt:~# nslookup google.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   google.com
Address: 172.217.25.14


root@OpenWrt:~# curl google.com
curl: (7) Failed to connect to google.com port 80 after 0 ms: Connection refused

root@OpenWrt:~#ping 114.114.114.114
PING 114.114.114.114 (114.114.114.114): 56 data bytes
64 bytes from 114.114.114.114: seq=0 ttl=66 time=36.954 ms
```

重新关闭再打开passwall2后网络正常
改用srr+重启则没问题

passwsall2配置大概如下
```
使用分流
启用socks
其他基本全默认
```

**Comment by iceyheart** [comment]
今天更新固件后遇见了同样的问题。启动passwall和passwall2都失败，似乎是和dnsmasq之间产生了问题。

**Comment by nudewolf** [comment]
same issue

**Comment by tobarcn** [comment]
一样的问题,必须手动关闭再打开一次

**Comment by tobarcn** [comment]
唉,看了个把小时源码,防火墙,总算找到问题了

iptable.sh start在passwall2,passwall2_server两个启动脚本中分别被执行了一次,导致规则重复添加联网不正常

这个时候手动关闭和启动一次服务,就会执行一次iptable.sh stop清理防火墙规则再启动,这个时候联网就正常了

修复办法直接把/etc/init.d/passwall2_server删了

**Comment by 0987363** [comment]
看了下，2个地方都是引用的/etc/init.d/passwall2

我是openwrt拨号，所以把/etc/rc.d/S99zzz_passwall2删掉就行了

**Comment by davidtall** [comment]
same issue

**Comment by davidtall** [comment]
感觉是这个提交后引起的 https://github.com/xiaorouji/openwrt-passwall2/commit/c2d8fd8ac861e5610899fcfe70dcfa43099d73ca

**Comment by davidtall** [comment]
1,按照楼上的方法，删除 /etc/rc.d/S99zzz_passwall2 后在面板修改配置后点保存和应用就无法重启插件了
2,无法连接网络，是因为openwrt重启后，wan拨号联网先于passwall2插件的boot启动，所以插件会 先restart，再start，启动了两个实例就冲突了
3，正确的处理办法是在 /usr/share/passwall2/app.sh 的start 函数头部中加入去重代码，防止重复执行
```
	if [ "$(ps | grep /tmp/etc/passwall2 | grep -v grep)" != "" ]; then
		echolog "程序已启动，无需重复启动!"
    	return 0
	fi
```
@xiaorouji

**Comment by adfnkjasd** [comment]
> 1,按照楼上的方法，删除 /etc/rc.d/S99zzz_passwall2 后在面板修改配置后点保存和应用就无法重启插件了 2,无法连接网络，是因为openwrt重启后，wan拨号联网先于passwall2插件的boot启动，所以插件会 先restart，再start，启动了两个实例就冲突了 3，正确的处理办法是在 /usr/share/passwall2/app.sh 的start 函数头部中加入去重代码，防止重复执行
> 
> ```
> if [ "$(ps | grep /tmp/etc/passwall2 | grep -v grep)" != "" ]; then
>    echolog "程序已启动，无需重复启动!"
>    return 0
> fi
> ```
> 
> @xiaorouji

谢谢大佬，所以只要更新到最新源码就能解决了是吗

**Comment by zycshiniye** [comment]
> 

最新的也有这个问题哦

**Comment by davidtall** [comment]
管理已经合并了我提交的PR，用最新的代码重新编译就可以了
