### ISSUE TITLE
分流模式，cpu就100%，卡死

### ISSUE THREAD

**Issue by klhh** [xiaorouji/openwrt-passwall2#136]
只要使用xray分流模式，cpu就100%，卡死，换回不分流的就正常
 PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 7743     1 root     D    6360m 335%  70% /tmp/etc/passwall2/bin/xray run -c /tmp/etc/passwall2/global.json

**Comment by nudewolf** [comment]
same issues

**Comment by maxmib** [comment]
erx,openwrt 22.03,相同问题
