### ISSUE TITLE
准备好迁移到nftables了吗？

### ISSUE THREAD

**Issue by lededev** [xiaorouji/openwrt-passwall2#137]
OpenWrt将从iptables迁移到nftables，passwall2准备好了吗，届时nftset将取代ipset。

**Comment by lededev** [comment]
今天已经将旧版iptables取消默认防火墙设置了
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=35fec487e30f05c81bd135326a993dad7f861812
原先的旧版iptables-legacy包被改名为iptables-zz-legacy

**Comment by xiaorouji** [comment]
请帮忙测试一下 [nft_dev](https://github.com/xiaorouji/openwrt-passwall2/tree/nft_dev) 分支

**Comment by xiaorouji** [comment]
finished.
