### ISSUE TITLE
百度等国内网站会从节点走，版本为openwrt5.10.120+passwall2最新

### ISSUE THREAD

**Issue by microdockman** [xiaorouji/openwrt-passwall2#138]
重新编译安装非旧版本升级
所有设置重新设置一遍
在百度输入ip会出现节点ip而不是国内的运营商ip
dns选项如下

![Capture](https://user-images.githubusercontent.com/31898637/174606552-e4ea6c91-8f2d-40f0-a57c-74c0698914d3.PNG)

**Comment by microdockman** [comment]
相同设置，passwall正常
![Capture](https://user-images.githubusercontent.com/31898637/174647970-80b483c7-b093-4b5c-b6dc-86292a9909f3.PNG)

**Comment by iceyheart** [comment]
直接选择节点会造成此现象，请选择xray分流

**Comment by chancat87** [comment]
> 相同设置，passwall正常 ![Capture](https://user-images.githubusercontent.com/31898637/174647970-80b483c7-b093-4b5c-b6dc-86292a9909f3.PNG)

你这个界面是passwall1吗?
如果是2的话和我不一样啊，我的没有ins检测，dns设置里也没有ipv6选项。
