### ISSUE TITLE
官方源码无办法运行！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall2#15]
![QQ图片20220315233106](https://user-images.githubusercontent.com/5343595/158414360-fdf48e4e-c47b-4de2-a297-c10671a1d0e0.png)
日志空白，国内外网都上不了！

**Comment by xiaorouji** [comment]
你是不是把执行文件权限弄没了

**Comment by snakwu** [comment]
@xiaorouji  官方最新源码直接编译出来的。应该不存在权限问题吧

**Comment by snakwu** [comment]
@xiaorouji  另外请问，我只需要gfw域名代理，是不是应该自己建一个规则，然后域名里面填geosite:gfw，然后这规则模式选我自己加的节点就可以了？

**Comment by yaotthaha** [comment]
对

**Comment by snakwu** [comment]
> 

问题是现在运行不起来！

**Comment by yaotthaha** [comment]
日志？

**Comment by snakwu** [comment]
> 

日志空白，打上开关，完全没有运行起来！然后重启op，无论打不打上开关，国内外都无网！

**Comment by xiaorouji** [comment]
那你得自己找原因，别人都能行

**Comment by xiaorouji** [comment]
> 日志？或者检查一下ray的权限
> 
> 还有V2ray v5以上的版本重写了cli，不知道passwall2兼容了没有

在v2ray没有发布正式版v5之前都不会刻意去做最新支持。

**Comment by LitCcc** [comment]
刚刚用官方源码编译的运行没问题，检查下依赖有没有下全，passwall2 的仓库里没有需要的依赖，你需要 git clone 一下 passwall 的仓库补全依赖

**Comment by snakwu** [comment]
> 那你得自己找原因，别人都能行

权限没问题，我节点是xray节点，但我发现，一选上passwall2默认会选上v2ray，会不会是xray的v2ray冲突了？

**Comment by snakwu** [comment]
> 刚刚用官方源码编译的运行没问题，检查下依赖有没有下全，passwall2 的仓库里没有需要的依赖，你需要 git clone 一下 passwall 的仓库补全依赖

已经是补全的

**Comment by xiaorouji** [comment]
命令行执行 /etc/init.d/passwall2 restart 看看就知道了

**Comment by snakwu** [comment]
> 命令行执行 /etc/init.d/passwall2 restart 看看就知道了
![QQ图片20220316125847](https://user-images.githubusercontent.com/5343595/158520471-cd601e8b-a5d7-407d-a09a-d69380407fd4.png)
![QQ图片20220316130145](https://user-images.githubusercontent.com/5343595/158520478-718f384a-de7f-4539-bb95-b0761ad52ef3.png)
![QQ图片20220316130156](https://user-images.githubusercontent.com/5343595/158520484-ef46968a-e322-4ffa-92a4-ba856b28efd2.png)
![QQ图片20220316130234](https://user-images.githubusercontent.com/5343595/158520489-a3f8bb65-190a-46d9-8d2e-650e40a6abe8.png)

**Comment by snakwu** [comment]
@xiaorouji 
我还发现，在界面上，点那个主开关，没有用，一用/etc/init.d/passwall2 restart，界面上的v2ray状态就显示正在运行，但国内外上不了网

**Comment by xiaorouji** [comment]
证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行

**Comment by snakwu** [comment]
> 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行

但不知道为什么运行不起来

**Comment by yaotthaha** [comment]
> > 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行
> 
> 但不知道为什么运行不起来,我也没有太多东西，就是官方源码加上passwall2,然后编译，哦还有一点，我用的是自己内网的dns，但这个dns之前passwall1,一直用到现在是没有什么问题的，其它，没其它了！

大佬都说了uci-default没有执行，你先执行然后重启试试

**Comment by snakwu** [comment]
> > > 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行
> > 
> > 
> > 但不知道为什么运行不起来，我也没有太多东西，就是官方源码加上passwall2，然后编译，哦还有一点，我用的是自己内网的dns，但这个dns之前passwall1，一直用到现在是没有什么问题的，其它，没其它了！
> 
> 大佬都说了uci-default没有执行，你先执行然后重启试试

正常来说，我设置好后，然后打开，就会自己执行的吧，所以这里有问题

**Comment by yaotthaha** [comment]
> > > > 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行
> > > 
> > > 
> > > 但不知道为什么运行不起来，我也没有太多东西，就是官方源码加上passwall2，然后编译，哦还有一点，我用的是自己内网的dns，但这个dns之前passwall1，一直用到现在是没有什么问题的，其它，没其它了！
> > 
> > 
> > 大佬都说了uci-default没有执行，你先执行然后重启试试
> 
> 正常来说，我设置好后，然后打开，就会自己执行的吧，所以这里有问题

uci-default是在安装是执行，且只会执行一次

**Comment by snakwu** [comment]
> > > > > 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行
> > > > 
> > > > 
> > > > 但不知道为什么运行不起来，我也没有太多东西，就是官方源码加上passwall2，然后编译，哦还有一点，我用的是自己内网的dns，但这个dns之前passwall1，一直用到现在是没有什么问题的，其它，没其它了！
> > > 
> > > 
> > > 大佬都说了uci-default没有执行，你先执行然后重启试试
> > 
> > 
> > 正常来说，我设置好后，然后打开，就会自己执行的吧，所以这里有问题
> 
> uci-default是在安装是执行，且只会执行一次

那我现在应该怎么做？

**Comment by snakwu** [comment]
> 证明 [uci-defaults](https://github.com/xiaorouji/openwrt-passwall2/tree/main/luci-app-passwall2/root/etc/uci-defaults) 没有执行

终于找到问题所在了，是因为我自己增加了一个gfw规则，然后geoip和geosite没有geosite:gfw和geoip:gfw字段， 所以引起了passwall2没有启动，请问，我如果要用gfw模式，我应该怎么做？
还有一个问题，以前一个udp是直接连自己自定的dns去解释的，现在只有一个tcp，我在那里填我自己内网的dns地址，无效

**Comment by snakwu** [comment]
现在的新版本，是接管了所有流量那怕是国内外的都接管了，再经过xray分流出去，这样的会不会影响整体体验，特别是ipv6，不应访是需要出国的流量才接管出去吗？

**Comment by xiaorouji** [comment]
要用gfw可以用[这个](https://github.com/Loyalsoldier/v2ray-rules-dat)规则。
DNS的话，直连DNS会使用Dnsmasq里面的第一条DNS转发的DNS服务器。

**Comment by snakwu** [comment]
> 要用gfw可以用[这个](https://github.com/Loyalsoldier/v2ray-rules-dat)规则。 DNS的话，直连DNS会使用Dnsmasq里面的第一条DNS转发的DNS服务器。

收到大佬，是不是git他的geoip.dat，geosite.dat替换内置的？如果是这样，希望可以像passwall1那样可以增加个自己定义规则下载路径，谢谢！
关于dns，直连是用dnsmasp转发的第一条的话，在我没有设置dnsmasp的dns转发下，他是用那个？
那代理的是不是用dns模块里的dns？可否能像passwall那样增加一个udp请求本地dns？又或tcp模式支持请求本地dns，而不是经过节点去请求，谢谢

**Comment by xiaorouji** [comment]
自定义规则这个可以考虑加入。
DNS方面其实不用太过折腾，直接V2ray一把梭搞掂

**Comment by snakwu** [comment]
> 自定义规则这个可以考虑加入。 DNS方面其实不用太过折腾，直接V2ray一把梭搞掂
    首先多谢大佬的回复和接纳，自定义规则这个是为了方便使用的是gfw模式的人，因为全局的话，所有不在china的列表都转走了，不竟在本地弄了防投毒的dns后，很多不需要机场的网址都能打开了，只是特别的网才需要转发，比如ipv6test的网址都让转走了，当然也可以把网址加进直连，但反之还不如gfw+自定义列表，需要的就加代理。
 
    DNS的话，也希望可以接纳，为什么这样说呢，因为我是在本地，弄了一个只负责外面的网的dns，从速度和效果上来说，都比用远程去请求1111，8888，9999，的dns要快，我用passwall1自己亲测很长一段时间得出的结论，所以希望可以用udp，最好也有tcp的协义直接请求本地dns功能，有条件的可以直接请求，没条件的可以远程请求，这样就两全其美了，再次谢谢大佬。

**Comment by snakwu** [comment]
> 自定义规则这个可以考虑加入。 DNS方面其实不用太过折腾，直接V2ray一把梭搞掂

 首先多谢大佬的回复和接纳，自定义规则这个是为了方便使用的是gfw模式的人，因为全局的话，所有不在china的列表都转走了，不竟在本地弄了防投毒的dns后，很多不需要机场的网址都能打开了，只是特别的网才需要转发，比如ipv6test的网址都让转走了，当然也可以把网址加进直连，但反之还不如gfw+自定义列表，需要的就加代理。
 
    DNS的话，也希望可以接纳，为什么这样说呢，因为我是在本地，弄了一个只负责外面的网的dns，从速度和效果上来说，都比用远程去请求1111，8888，9999，的dns要快，我用passwall1自己亲测很长一段时间得出的结论，所以希望可以用udp，最好也有tcp的协义直接请求本地dns功能，有条件的可以直接请求，没条件的可以远程请求，这样就两全其美了，再次谢谢大佬。

**Comment by snakwu** [comment]
> 自定义规则这个可以考虑加入。 DNS方面其实不用太过折腾，直接V2ray一把梭搞掂

 首先多谢大佬的回复和接纳，自定义规则这个是为了方便使用的是gfw模式的人，因为全局的话，所有不在china的列表都转走了，不竟在本地弄了防投毒的dns后，很多不需要机场的网址都能打开了，只是特别的网才需要转发，比如ipv6test的网址都让转走了，当然也可以把网址加进直连，但反之还不如gfw+自定义列表，需要的就加代理。
     DNS的话，也希望可以接纳，为什么这样说呢，因为我是在本地，弄了一个只负责外面的网的dns，从速度和效果上来说，都比用远程去请求1111，8888，9999，的dns要快，我用passwall1自己亲测很长一段时间得出的结论，所以希望可以用udp，最好也有tcp的协义直接请求本地dns功能，有条件的可以直接请求，没条件的可以远程请求，这样就两全其美了，再次谢谢大佬。

**Comment by xiaorouji** [comment]
已经在最新源码加入

**Comment by snakwu** [comment]
> 已经在最新源码加入

收到大佬

**Comment by snakwu** [comment]
> 已经在最新源码加入

大佬，这个直连的dns是不是有问题？应该怎么设置？为什么我选了直连dns，但是远程还要设置？
![image](https://user-images.githubusercontent.com/5343595/163009037-98deaff3-e095-4fa4-81b0-f4e54ce15142.png)
![image](https://user-images.githubusercontent.com/5343595/163009130-2f68e3fb-e851-41bf-87c6-2b548dab43e7.png)

**Comment by snakwu** [comment]
> 已经在最新源码加入

我大概明白了，直连的dns，就是直连的列表用的dns，代理的dns就是用的远程的dns
可不可以代理的dns，也可以用本地dns？

**Comment by snakwu** [comment]
> 已经在最新源码加入

刚才体验了一把passwall2,有两个问题：
1，希望远程dns可以使用内网地址的dns。
2，关了ipv6代理，整个ipv6都无法使用了，但如果打开ipv6代理，就正常，但是我的节点不支持ipv6，开了ipv6代理后，我又不能访问国外了。。。很尴尬！
