### ISSUE TITLE
申请增加节点订阅更新功能：每间隔几小时更新一次

### ISSUE THREAD

**Issue by yanghonghao6789** [xiaorouji/openwrt-passwall2#151]
![Screenshot_2022-07-22-15-39-18-99_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/73630536/180389523-4ce5ea88-a0a5-4318-9745-c9c11537de43.jpg)
![Screenshot_2022-07-22-15-39-28-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/73630536/180389548-8319caa1-d234-4f48-9275-57acf9e1739a.jpg)
节点不稳定 需要经常更新，现在只能这样设置 同一节点订阅地址设置不同时间段更新，如果增加一个间隔几小时一更新就完美了，现在这个情况订阅名不能一样，导致节点列表一大堆重复节点

**Comment by raincoast** [comment]
+1，希望能检测到失效就更新

**Comment by HomeQi** [comment]
> +1，希望能检测到失效就更新

有个办法，实测可用，操作如下：
打开订阅定时更新，然后新建一个定时更新crontab的bash脚本，替换掉pass自带的crontab脚本
0 */3 * * * lua /usr/share/passwall2/subscribe.lua start cfg208b02 > /dev/null 2>&1 && sleep 5 && /root/add_crontab_passwall2.sh
脚本参考（参数替换掉）↑，如果有啥问题可以直接问，看到会回复。

**Comment by HomeQi** [comment]
需要定时更新的可以自行参考如下bash脚本，crontab命令中添加定时执行即可，自行测试OK 若有问题欢迎留言！
```
#!/bin/bash

# 从crontab命令中获取所有条目
crontab_entries=$(crontab -l)

# 定义正则表达式模式，匹配"cfg"开头并后面跟随任意6个字符
Refresh_pattern="0 5 \* \* 3 lua /usr/share/passwall2/subscribe\.lua start cfg.{6} > /dev/null 2>&1 &"

# 在crontab条目中查找匹配的行
refresh_matches=$(echo "$crontab_entries" | grep -E "$Refresh_pattern")

# 检查是否有匹配的刷新任务
if [ -n "$refresh_matches" ]; then
    # 需要替换对内容
    replace_time="0 \*\/3 \* \* \*"
    append_command="& sleep 13 && /root/add_crontab_passwall2.sh"
    # 截取matches中前9个字符并替换成replace_time
    updated_matches=$(echo "${refresh_matches}${append_command}" | sed -E "s/^.{9}/$replace_time/")
    # 删除刷新的任务
    (crontab -l | grep -v -F "$refresh_matches") | crontab -
    # 添加定时刷新的新任务
    (crontab -l ; echo "$updated_matches") | crontab -
fi
```bash
