### ISSUE TITLE
Passwall2最新固件无法使用

### ISSUE THREAD

**Issue by caoolong** [xiaorouji/openwrt-passwall2#159]
求大佬帮忙看一下，折腾了好久。。救救孩子吧
![屏幕截图 2022-09-06 021558](https://user-images.githubusercontent.com/96583504/188499635-6952a082-ae56-4377-be05-399f70e0543c.png)
![屏幕截图 2022-09-06 021538](https://user-images.githubusercontent.com/96583504/188499638-52303217-2915-4179-b097-fc86a8a9c351.png)

**Comment by caoolong** [comment]
![image](https://user-images.githubusercontent.com/96583504/188501220-208420ed-2d69-4691-b140-e459bfc2815e.png)

**Comment by xwcoco** [comment]
提示很清楚，未安装iptables，找个安装包安装一下。

**Comment by caoolong** [comment]
编译时默认就有勾选的，检查过了> 提示很清楚，未安装iptables，找个安装包安装一下。

**Comment by hu-boss** [comment]
这个问题解决了吗，我也是这个问题，已经安装了IPset也是不行

**Comment by caoolong** [comment]
没有解决，估计是还没适配新固件导致的，我已经回滚21.02了，目前正常使用> 这个问题解决了吗，我也是这个问题，已经安装了IPset也是不行
> 
>

**Comment by ZhelinCheng** [comment]
> 没有解决，估计是还没适配新固件导致的，我已经回滚21.02了，目前正常使用> 这个问题解决了吗，我也是这个问题，已经安装了IPset也是不行
> 
> >

兄弟你好，我使用21.02安装passwall2，安装时提示我有许多依赖没有，你遇到过吗 @caoolong

**Comment by caoolong** [comment]
> 这个问题解决了吗，我也是这个问题，已经安装了IPset也是不行
> 
> 

解决了，opkg install iptables-nft即可

**Comment by caoolong** [comment]
> > 没有解决，估计是还没适配新固件导致的，我已经回滚21.02了，目前正常使用> 这个问题解决了吗，我也是这个问题，已经安装了IPset也是不行
> 
> > 
> 
> > >
> 
> 
> 
> 兄弟你好，我使用21.02安装passwall2，安装时提示我有许多依赖没有，你遇到过吗 @caoolong 

如果不是编译固件时交叉编译插件的话也会有你说的提示，我记得讨论区有个教程，那个教程有列出依赖名称，你按照教程的去opkg install就可以了

**Comment by ZhelinCheng** [comment]
试试安装iptables-nft 并重启，重启后关闭主开关再打开试试
