### ISSUE TITLE
使用Passwall2以后，打王者出现问题，一直重连。

### ISSUE THREAD

**Issue by feidaodu** [xiaorouji/openwrt-passwall2#160]
因为速度快，我就用了Passwall2，但是发现一个问题。

我只要开启了Passwall2，打王者时，只要匹配成功，加载排位时，王者系统就会显示一直重连，重连7次都进不去游戏。。打这一把
我只有停了Passwall2，才能进去。。

这种情况，我在使用Openclash，并使用Fake-ip模式时，也出现过。。
在OpenClash上，我的解决方案是换成Redir模式，就OK了，一切正常。

是不是Passwall2做分流时，也是默认使用类似于Fake-ip模式？

**Comment by chancat87** [comment]
> 

请问，你说的Redir是指高级设置里面tcp代理方式那个吗
