### ISSUE TITLE
识别BT流量似乎会失效

### ISSUE THREAD

**Issue by AshinLin** [xiaorouji/openwrt-passwall2#163]
![image](https://user-images.githubusercontent.com/13843885/189414389-f942a8f9-d3a8-4746-a9c5-28d54781f4c2.png)
![image](https://user-images.githubusercontent.com/13843885/189414688-22007907-dea0-4f7e-a9cc-fc5af957fc7c.png)

![image](https://user-images.githubusercontent.com/13843885/189414451-561fada6-7f22-4582-9f4a-de051c69ecc0.png)

好像识别BT流量会失效，分流已经设置了直连，但是我用transmission下载的时候，发现走了代理。

OpenWrt版本22.03.0-rc5

**Comment by chancat87** [comment]
> 确实有问题，我的VPS直接被封了，明明设置的直连。



> 确实有问题，我的VPS直接被封了，明明设置的直连。

直接在vps里设置封禁bt端口吧，有脚本的。这个插件问题非常多

**Comment by AshinLin** [comment]
我换回openwrt-passwall了，旧版的是没问题的

**Comment by chancat87** [comment]
> 我换回openwrt-passwall了，旧版的是没问题的

1吗？

**Comment by rsgdn** [comment]
我也是这样，但只是一部分Bt流量走节点，大概三分之一到一半，目前只能在bt的分流规则的源地址加入局域网ip才能生效
![屏幕截图 2022-11-19 185623](https://user-images.githubusercontent.com/20219112/202847368-55a4396f-e0f2-43a1-a58d-8ed22abba708.png)
最后本来想用10.10.0.0/32的，但是没起作用，害有更好的解决办法？

**Comment by yanghonghao6789** [comment]
看看geosite的规则 
![image](https://user-images.githubusercontent.com/73630536/204071849-ff813c31-3b65-4db6-ac61-abc68a4b5919.png)
![image](https://user-images.githubusercontent.com/73630536/204071856-fe21fb6f-feac-4f11-bd22-744e642d0cef.png)
https://github.com/v2fly/domain-list-community/tree/master/data
这个链接里有详细的分流规则 自己弄就好 pw默认的泰拉跨  需要自己修改 我改好之后 分流很正确

**Comment by chancat87** [comment]
感谢🙏

在 2022-11-26 12:10:40，yanghonghao6789 ***@***.***> 写道：


看看geosite的规则


https://github.com/v2fly/domain-list-community/tree/master/data
这个链接里有详细的分流规则 自己弄就好 pw默认的泰拉跨 需要自己修改 我改好之后 分流很正确
