### ISSUE TITLE
OpenWrt 22.03.0不支持iptables 

### ISSUE THREAD

**Issue by hu-boss** [xiaorouji/openwrt-passwall2#165]
OpenWrt 22.03.0不支持iptables 
Firewall4 现已替代 firewall3 成为 OpenWrt 镜像中的默认防火墙配置软件. Firewall4 使用了 nftables 而不是 iptables 来配置 Linux 的网络过滤器。
passwall2需要iptables 才能启动，希望能尽快适配OpenWrt 22.03.0

**Comment by ZhelinCheng** [comment]
原来是不支持，怪不得。问一下兄弟22.2能完美支持passwall2吗？

**Comment by ZhelinCheng** [comment]
试试iptables-nft，我就是用的这个解决的

**Comment by davidtall** [comment]
> 试试iptables-nft，我就是用的这个解决的

使用immortalwrt 源码编译22.03，选择了iptables-nft ，还需要选择iptables-zz-legacy 吗？

**Comment by davidtall** [comment]
> OpenWrt 22.03.0不支持iptables Firewall4 现已替代 firewall3 成为 OpenWrt 镜像中的默认防火墙配置软件. Firewall4 使用了 nftables 而不是 iptables 来配置 Linux 的网络过滤器。 passwall2需要iptables 才能启动，希望能尽快适配OpenWrt 22.03.0

passwall1 已经支持nftables 了，不知道passwall2什么时候安排上

**Comment by hu-boss** [comment]
最新的passwall2到底支持openwrt 22.03了吗，怎么刚试了下还是提示，系统未安装iptables或ipset,无法透明代理。安装 了ipset也不行

**Comment by xiaorouji** [comment]
请帮忙测试一下 [nft_dev](https://github.com/xiaorouji/openwrt-passwall2/tree/nft_dev) 分支

**Comment by hu-boss** [comment]
> 请帮忙测试一下 [nft_dev](https://github.com/xiaorouji/openwrt-passwall2/tree/nft_dev) 分支

分支的git地址跟原来的是一样的，不知道要怎么编译新版本

**Comment by davidtall** [comment]
> > 请帮忙测试一下 [nft_dev](https://github.com/xiaorouji/openwrt-passwall2/tree/nft_dev) 分支
> 
> 分支的git地址跟原来的是一样的，不知道要怎么编译新版本

git clone -b nft_dev https://github.com/xiaorouji/openwrt-passwall2.git

**Comment by xiaorouji** [comment]
passwall2不会自动安装 透明代理所需依赖，你可能还需另外安装：
dnsmasq_full_nftset
nftables
kmod-nft-socket
kmod-nft-tproxy
kmod-nft-nat

**Comment by hu-boss** [comment]
> passwall2不会自动安装 透明代理所需依赖，你可能还需另外安装： dnsmasq_full_nftset nftables kmod-nft-socket kmod-nft-tproxy kmod-nft-nat

我是个菜鸟，很多东西搞不明白，你说的插件dnsmasq_full_nftset，nftables我也找不到，希望有大神帮忙测试一下吧

**Comment by hcym** [comment]
下午编译的1和2都正常了，master分支，肯定是nft这些，

**Comment by hu-boss** [comment]
> 下午编译的1和2都正常了，master分支，肯定是nft这些，

我又试了一次，安装了那些依赖，还是不行。你用的是自己编译的openwrt还是官方的，能具体说下你是怎么弄的吗

**Comment by hcym** [comment]
自己编译，用的官方master分支，应该是最新的，除了p1p2还有大雕的ssp，v2raya，都正常使用。前天确实不能用，

**Comment by xiaorouji** [comment]
finished.
