### ISSUE TITLE
 编译openwrt之前 运行 make menuconfig 有个错误提

### ISSUE THREAD

**Issue by lsq726** [xiaorouji/openwrt-passwall2#166]
echo 'src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git' >>feeds.conf.default
echo 'src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall.git;packages' >>feeds.conf.default

 编译openwrt之前 运行 make menuconfig 有个错误提

tmp/.config-package.in:55236:error: recursive dependency detected!
tmp/.config-package.in:55236:   symbol PACKAGE_libgd is selected by PACKAGE_libgd-full
tmp/.config-package.in:55270:   symbol PACKAGE_libgd-full depends on PACKAGE_libgd
For a resolution refer to Documentation/kbuild/kconfig-language.rst
--

**Comment by mand-byte** [comment]
把openwrt全删了，重新拉，你之前编译过别的插件，导致编译后的配置不干净

**Comment by lsq726** [comment]
> 把openwrt全删了，重新拉，你之前编译过别的插件，导致编译后的配置不干净

3q 回头试试
