### ISSUE TITLE
NAT 类型问题

### ISSUE THREAD

**Issue by ChenStormstout** [xiaorouji/openwrt-passwall2#167]
![image](https://user-images.githubusercontent.com/19796806/189513294-c651e848-8b38-4220-a31d-442d2c63e62c.png)
所有关闭规则，只有默认是直连。
原本使用full-clone NAT加速使switch测试NAT类型变为了A，但是使用passwall2就让NAT类型变为了B。还有国服守望先锋的语音服务器连不上（通常由网络引起），游戏本身没问题。如果选择不代理任何UDP端口则NAT为A，但是语音还是有问题。奇怪的是switch的的下载速度测试也会到达一个很高的值，实际下载又没有那么快。
https://github.com/xiaorouji/openwrt-passwall/issues/2083#issue-1363110180
我在passwall的那边也提了相同的问题。
https://github.com/xiaorouji/openwrt-passwall/issues/2083#issuecomment-1239700431
给出的方案实际上没能解决。

**Comment by luoxiaohei** [comment]
遇到了一样的问题，开了passwall全局模式之后好像所有流量都被nat了。由于我的OpenWrt是以旁路网关方式部署在树莓派上的，性能比较一般，导致国内网速掉的很厉害，从千兆直接掉到百兆了。
