### ISSUE TITLE
勾选路由器本机代理后国内网站就无法访问了

### ISSUE THREAD

**Issue by 759071793** [xiaorouji/openwrt-passwall2#171]
勾选路由器本机代理后国内网站就无法访问了
使用immortalwrt master分支编译的固件
拉取最新的passwall2,，测试多次均无法访问，目前使用v2raya暂时代替中。。
希望大佬能看看。

**Comment by 363843342** [comment]
一样问题，好像要等更新了，不知道什么bug，只要是"直连"都无法连接

**Comment by 759071793** [comment]
> 一样问题，好像要等更新了，不知道什么bug，只要是"直连"都无法连接

passwall已经更新了支持了，passwall2没人PR
