### ISSUE TITLE
ros openwrt双软路由搭配adguardhome使用，关于dns设置与passwall2分流的最优解？

### ISSUE THREAD

**Issue by xiaoyaozhilv** [xiaorouji/openwrt-passwall2#173]
现在的网络环境，esxi下搭建了ros、openwrt，另在ubuntu服务器装了adguradhome；ip地址分别：ros：x.x.x.1，op：x.x.x.2；ad：x.x.x.3。
ros设置：ip为x.x.x.1，dns为114.114.114.114；dhcp的网关为x.x.x.2，dns为x.x.x.3。
op设置：ip为x.x.x.2，网关为x.x.x.1,dns为x.x.x.1。
ad设置：ip为x.x.x.3，网关为x.x.x.2，dns为x.x.x.1。 ad的dns设置里，上游 DNS 服务器设置为op的ip，即x.x.x.2。

看网上很多说法，ros和ad的dns解析缓存都比较强大。而passwall2的优势又在于分流。不知道是否优势最大化发挥出来了，想跟大佬及大家请教是否还有更优解？

**Comment by skullcrossbones** [comment]
dns建议8.8.8.8
8.8.4.4
但有个问题是speedtest无法测速 咋整
