### ISSUE TITLE
希望能像1一样加入代理模式

### ISSUE THREAD

**Issue by adfnkjasd** [xiaorouji/openwrt-passwall2#184]
现在2的纯分流虽然有direct分流，但整体模式还是走的全局，国内流量也会通过passwall2走一遍判断，这就导致软中断过高，CPU一开下载基本上占用就3-40%了，另一边1就不会有这样的问题，但1的性能确实不太行。
![QQ截图20221124170157](https://user-images.githubusercontent.com/39746646/203745934-da0adfe4-712e-43cc-8f06-8fe258db260d.jpg)
![QQ截图20221124165926](https://user-images.githubusercontent.com/39746646/203745943-bc47eff9-0447-451c-8ddb-3787904c519b.jpg)
![QQ截图20221124165949](https://user-images.githubusercontent.com/39746646/203745947-2064af29-3111-49de-9744-35ac5d5b1f76.jpg)

**Comment by adfnkjasd** [comment]
补充，带宽是联通1000兆，speedtest跑满千兆CPU占用不到20%，软路由自组，CPU是i5-4670t，网卡是XL710，多队列支持，已设置均衡

**Comment by yangfang043** [comment]
没配置好吧，我N1 都不会

**Comment by adfnkjasd** [comment]
> 没配置好吧，我N1 都不会

不是的 你看第一张图代理模式，走的是全局代理，然后检测到direct再分流到国内

**Comment by yangfang043** [comment]
> > 没配置好吧，我N1 都不会
> 
> 不是的 你看第一张图代理模式，走的是全局代理，然后检测到direct再分流到国内

你要把路由规则贴出来看看。 优先级不要搞错了。

**Comment by adfnkjasd** [comment]
> > > 没配置好吧，我N1 都不会
> > 
> > 
> > 不是的 你看第一张图代理模式，走的是全局代理，然后检测到direct再分流到国内
> 
> 你要把路由规则贴出来看看。 优先级不要搞错了。

![Screenshot_20221209-061046_Chrome](https://user-images.githubusercontent.com/39746646/206578173-bd141b1d-e766-41bf-9cb0-3aa311559b08.jpg)
![Screenshot_20221209-061028_Chrome](https://user-images.githubusercontent.com/39746646/206578202-e1176801-500d-4a6f-9bd9-1f72d3ef7685.jpg)
优先级应该不会有错的，都是默认设置，只是删了TVB和网飞的规则

**Comment by chenyajunai** [comment]
我用分流，部分网站还是会走代理，我还是喜欢passwall的订阅规则，那个好用

**Comment by LitCcc** [comment]
还真是，N5105国内跑满千兆cpu占用直接70%+😂
希望内加入不代理国内的模式

**Comment by jh0072110** [comment]
那么问题就来了…那为什么不用1……

**Comment by adfnkjasd** [comment]
> 

前面说了啊，性能不太行，我也不知道为什么 按理说同样xray内核性能差别应该不大，但1跑节点速度就只有3-400，油管10w上下，2的话节点跑满宽带，油管也是能20w往上

**Comment by adfnkjasd** [comment]
> 那么问题就来了…那为什么不用1……

前面说了啊，性能不太行，我也不知道为什么 按理说同样xray内核性能差别应该不大，但1跑节点速度就只有3-400，油管10w上下，2的话节点跑满宽带，油管也是能20w往上

**Comment by CaiMiao** [comment]
+1票支持分模式，最好能把“全局直连+路由单独透明+仅使用ACL”的组合安排上

目前的使用场景是：
- 大原则是各个设备自行爬梯，只对不便自行爬梯的设备透明
- 网络环境为全家十几号人+一堆租户使用
- PW2在入户主路由开启，鉴于网络环境复杂+其他人上网行为不可控，出于安全+稳定角度（避免梯子一崩全家断网），需要真全局直连（目前通过*ray的路由直连会降低性能；通过不代理tcp/udp 1-65535端口可实现伪直连，但也会使路由自身无法透明，且根据日志信息，依然有大量的dns请求通过了*ray）
- 路由需测速以及定期访问外部资源，所以需要不被上一条需求扯后腿的透明
- ACL控制游戏机等不方便自己爬梯的设备走透明

**Comment by xingmiye** [comment]
我觉得没必要，实现想要那就用1好了。
我测试过无论用1的CN列表以外的代理模式，还是用2的，用国内测速跑满宽带，CPU占用都高，然后占用都差不多，没啥区别，因为用的MosDns+AdGuardHome分流，可以查看解析记录的，记录就是国内数据该走国内还是走国内，访问国外就是走国外，分流效果很好。难道就是因为我手动配置，用上了dns分流，所以没有楼主这种情况？我也不知道。我反正觉得现在这样挺好的，没必要加入1那样的代理模式。

觉得没必要加入，还有一个重要的原因，1和2的TCP代理方式，默认都是REDIRECT，因为我的节点支持ipv6，所以要用TPROXY的代理方式+勾选ipv6透明代理。这样的结果导致1如果继续用CN列表以外的代理模式，重启后会有代理失效的问题，必须要手动重启一次1，才能重新正常，无论我是在1的高级设置里面延迟多久启动，都不行，重启系统还是会不正常。
然后我测试在系统——启动项——本地启动脚本用下面的命令来自动延迟重启，而且那么多次。。。。
```
sleep 30 && /etc/init.d/passwall restart
sleep 60 && /etc/init.d/passwall restart
sleep 120 && /etc/init.d/passwall restart
sleep 180 && /etc/init.d/passwall restart
```
又或者在系统——启动项——本地启动脚本用下面的命令
```
uci set passwall.@global_forwarding[0].tcp_proxy_way='redirect'
uci set passwall.@global_forwarding[0].ipv6_tproxy='0'
uci commit passwall
/etc/init.d/passwall restart
sleep 30 && uci set passwall.@global_forwarding[0].tcp_proxy_way='tproxy'
uci set passwall.@global_forwarding[0].ipv6_tproxy='1'
uci set passwall.@global[0].tcp_proxy_mode='global'
uci set passwall.@global[0].udp_proxy_mode='global'
uci commit passwall
/etc/init.d/passwall restart
sleep 30 && uci set passwall.@global[0].tcp_proxy_mode='chnroute'
uci set passwall.@global[0].udp_proxy_mode='chnroute'
uci commit passwall
/etc/init.d/passwall restart
```
结果还是不行，硬生生的就是无法访问境外网络，偏偏，什么延迟启动，自动执行重启啥的命令都不用加，直接重启系统后，手动SSH访问，直接执行`/etc/init.d/passwall restart`就正常了。这个BUG太奇怪了。

然后偏偏，如果passwall1不用CN列表以外的代理模式，而是用全局模式，那重启opwrt系统以后也是正常的，不用再手动重启了，也不需要设置延迟启动，这样那不就跟passwall2一样了。所以结论还是没有必要加入1那样的代理模式，别弄的连passwall2都不正常了。

我现在用的passwall 1 版本是4.60-4的，passwall 2 的版本是1.10-6的，结论是无论是1还是2，全局的代理模式下，如果要用TPROXY的代理方式+勾选ipv6透明代理，重启后都是正常的，但是如果用1，而且用CN列表以外的代理模式，重启openwrt系统后就不正常，必须要手动重启以下插件才正常。

BTW，之前用过的早一些版本的openwrt固件，passwall 1 版本是4.55-2，passwall 2 的版本是1.4-2。问题的情况恰恰相反了。
如果用1，而且用CN列表以外的代理模式，用TPROXY的代理方式+勾选ipv6透明代理，重启openwrt系统后是正常的。但是如果passwall 1 用全局的代理模式，或者直接用passwall 2（因为2就只有全局这一种模式），再用TPROXY的代理方式+勾选ipv6透明代理，重启Oenwrt系统后，代理就不正常了，情况就类似上面我说的那样，必须手动重启一次插件才正常，其他无论是延迟启动，还是用本地启动脚本自动执行重启插件，都不能正常，必须手动重启。

不知道这个到底是插件的问题bug，还是固件的问题，还是编译的过程出的问题。

**Comment by toniexly** [comment]
因为全部要走一遍判断，这还带来一个额外的副作用，有少量的直连站https访问会因此提示：无法建立安全连接。。。而关掉代理就可以正常访问。

**Comment by Deleted-Account** [comment]
可以参考v2ray的规则，弄成类GFW List模式  
https://github.com/Loyalsoldier/v2ray-rules-dat  

我的顺序是  

- QUIC——blackhole
- BT——直连
- 需要走特别代理的 分组0——代理0
- 需要代理的 分组1（类似 PW1 的代理列表都放这里）——代理1
- 直连（类似PW1的直连列表，都放这里，加上）——直连
- GFW（geosite:gfw geosite:greatfire)——代理1
- TCP+UDP（感觉这个分组好像不是必须，只是参考了 Loyalsoldier 的 GFW 配置）——直连
- 默认——直连

这样就可以实现类似 PW1 的 GFW 模式了  
稍微有一点点难度在于顺序的排列，数学的集合逻辑思维要好一点点  

我一直不太喜欢弄成全局或者白名单模式，一些可以直连而且速度很快的网站（比如京东国际，是 .hk 结尾的，直连很快，走代理很可能出问题，淘宝也可能偶尔解析到香港）用全局或者白名单容易出错，得不断维护不在订阅列表的一些网站填到直连，感觉很蠢

**Comment by xiaorouji** [comment]
可以试试最新源码，折中考虑了一下。
最新源码加入了直连域名到ipset的逻辑，例如：geosite:cn。
