### ISSUE TITLE
passwall2

### ISSUE THREAD

**Issue by jackson-lx** [xiaorouji/openwrt-passwall2#19]
新版本的passwall2 刚刚编译成功了，可以使用，变成是默认全局上网，找不到地方设置，国内很多网打不开了

**Comment by realsteam** [comment]
分流是个好东西，仔细看看就知道如何用了

**Comment by yangfang043** [comment]
请问下，默认TCP 默认代理模式是路由下全部，能像passwall一样设置访问控制指定的设备走代理吗？

**Comment by jackson-lx** [comment]
分流设置我没有搞懂怎么弄，新的passswall2就没有用。

yangfang043 ***@***.***>于2022年3月18日 周五17:36写道：

**Comment by WYC-2020** [comment]
这玩意是为分流的人准备的，不会用分流就不要用这个插件

**Comment by yaotthaha** [comment]
文档拿去学

https://xtls.github.io/config/routing.html#ruleobject
