### ISSUE TITLE
passwall2 分流后 机顶盒看电视出现地区版权限制

### ISSUE THREAD

**Issue by barney2022** [xiaorouji/openwrt-passwall2#192]
首先非常感谢作者, 用了passwall2以后完美解决了DNS泄露的问题
但有可能正是这个原因,导致了接下来的问题, 电视机顶盒里的电视剧和电影都播放不了,提示地区版权限制.
我的配置是大陆直连,  UDP直连, BT直连, QUIC黑洞, 其他都选默认, 默认选的是我的美国节点
DNS分流直连是阿里DOH 远程是cloudflare DOH

请大佬帮助

**Comment by yanghonghao6789** [comment]
你可以参考geoip geosite的规则
把默认的分流豆删了 全部自己添加规则  这俩文件分流很强大  pw1  我也用上分流了  
现在的模式smartdns+pw+adg  pw开启分流 负载均衡 访问控制   完美  某个节点不稳定也不会断网
![image](https://user-images.githubusercontent.com/73630536/208220779-156e4208-da4b-4a6b-91be-65cccdea6a91.png)

**Comment by yanghonghao6789** [comment]
分流规则 排序很重要 排不对  一样出错 
原则 想优先识别的小集合分流规则放到大集合上面去  这样就不会出错了
你可以看我的排序  最下面proxy  direct这俩 是两个大集合 上面小集合都没命中的情况下 先去查找代理里面有没有，比如谷歌有些域名大陆可以直连的 这样先查代理规则就防止走大路直连    最后没有再去查找直连规则    默认选择的负载均衡节点

**Comment by yanghonghao6789** [comment]
忘记了 pw2我在使用分流时有个问题：不知道是不是bug   直连分流必须在代理分流上面才能通网    这也是我现在转用pw分流的原因，  pw里没有这个问题 排序随意排序， pw2如果把代理放在直连上面  就不行  就是换一下顺序就能上网

**Comment by barney2022** [comment]
谢谢大佬 我重新排一下序列 再试试

**Comment by Recoba86** [comment]
> I forgot about pw2. I have a problem when using split: I don’t know if it’s a bug. The direct split must be on the proxy split to connect to the network. This is why I switch to pw split now. There is no such problem in pw. Sort at random, pw2 if Putting the agent on the direct connection will not work, just change the order and you can go online

so direct list on passwall2 don't work properly
because I put some ip in direct list shunt and put it at first row but they dont bypass vpn

**Comment by wyUshio** [comment]
> 首先非常感谢作者, 用了passwall2以后完美解决了DNS泄露的问题 但有可能正是这个原因,导致了接下来的问题, 电视机顶盒里的电视剧和电影都播放不了,提示地区版权限制. 我的配置是大陆直连, UDP直连, BT直连, QUIC黑洞, 其他都选默认, 默认选的是我的美国节点 DNS分流直连是阿里DOH 远程是cloudflare DOH
> 
> 请大佬帮助

问下有啥简单的解决办法吗?我腾讯视频tv版就版权限制...用其他的插件udp又不行...难受

**Comment by wyUshio** [comment]
> 你可以参考geoip geosite的规则 把默认的分流豆删了 全部自己添加规则 这俩文件分流很强大 pw1 我也用上分流了 现在的模式smartdns+pw+adg pw开启分流 负载均衡 访问控制 完美 某个节点不稳定也不会断网 ![image](https://user-images.githubusercontent.com/73630536/208221034-12de251f-fb57-416a-8c53-9bbd83d3383d.png)

大佬,你的规则能给我抄一下吗?

**Comment by yanghonghao6789** [comment]
咋炒啊   看这图自己新建  geoip geosite用这俩很好的

**Comment by phoenix-cn** [comment]
请问楼主后来解决了吗？

**Comment by kid-oh** [comment]
这个我也遇到了，应该是proxy规则里有国外流媒体的域名（比如爱奇艺），比direct规则优先级更高，所以就走到代理去了。我是把盒子设置为不代理，如果要代理的话新建一个规则然后排到proxy之上就好了
