### ISSUE TITLE
[Bug]: 通过外网 tcping tproxy 会导致死循环

### ISSUE THREAD

**Issue by aeeq** [xiaorouji/openwrt-passwall2#200]
### 描述您遇到的bug

用一段时间会出现cpu占用高，开了日志发现是其他主机扫了tproxy的端口，导致死循环

### 复现此Bug的步骤

用另一个网络 tcping tproxy 的端口

### 您想要实现的目的

改成监听 localhost

### 日志信息

2023/02/03 15:10:43 121.33.*.*:51400 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:43 [240e:*:*:*::*]:56332 accepted tcp:[2600:c05:3010:8888::58]:443 [tcp_redir -> direct]
2023/02/03 15:10:43 14.145.*.*:60334 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:44 14.145.*.*:60344 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:44 14.145.*.*:60352 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:44 14.145.*.*:60360 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:44 14.145.*.*:60372 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:44 14.145.*.*:60376 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60382 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 121.33.82.194:51402 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60388 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60400 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60414 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60424 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60436 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60438 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:45 14.145.*.*:60448 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60464 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60478 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60490 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60506 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60512 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60526 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]
2023/02/03 15:10:46 14.145.*.*:60528 accepted tcp:14.145.*.*:1041 [tcp_redir -> direct]

### 截图

![图片](https://user-images.githubusercontent.com/8926331/216535714-6e5e330f-7b4b-48fd-85bb-8abd2db4fd33.png)
![图片](https://user-images.githubusercontent.com/8926331/216536601-d4c5a6f1-5fa8-4110-97dc-f5afe74e16eb.png)

### 系统相关信息

版本号 git-23.365.31656-c3ae5db

**Comment by xiaorouji** [comment]
来源IP是否为wan口IP？
另外，你的防火墙默认全放行的吗？

**Comment by xiaorouji** [comment]
下面区域，wan防火墙。
一般情况下外网是不能直接连通的，出现这种情况估计是你把所有端口都放行了，被扫了。

**Comment by aeeq** [comment]
应该改哪里 ？
![图片](https://user-images.githubusercontent.com/8926331/216573143-d3ec9708-0b17-480e-a7e5-db5e755dc934.png)

**Comment by aeeq** [comment]
改 wan 入站数据为拒绝，好像就可以，在观察一段时间看看

**Comment by aeeq** [comment]
有个问题，拒绝入站，组播看不了

**Comment by aeeq** [comment]
解决了，默认拒绝，只打开 iptv 防火墙
