### ISSUE TITLE
[Bug]: 翻译不完全。

### ISSUE THREAD

**Issue by y9858** [xiaorouji/openwrt-passwall2#204]
### 描述您遇到的bug

![QQ截图20230211142141](https://user-images.githubusercontent.com/53130835/218244215-e61b8cfd-419b-4416-bd6c-28daf5490a70.png)

### 复现此Bug的步骤

点选 规则管理 页面。

### 您想要实现的目的

翻译完全。

### 日志信息

无

### 系统相关信息

luci-app-passwall2 v1.8-3

**Comment by smallprogram** [comment]
po/zh-cn/passwall2.po 自己添加上，然后提交个PR
