### ISSUE TITLE
[Feature Request]: 最新版passwall2怎么没有除vision以外的其他流控了？

### ISSUE THREAD

**Issue by whatpig** [xiaorouji/openwrt-passwall2#207]
### 描述你想要的新功能

xtls也没了，请添加回来吧

### 描述你想要的解决方案

请添加回来吧

**Comment by jh0072110** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.7.5
看Notices部分

**Comment by whatpig** [comment]
> https://github.com/XTLS/Xray-core/releases/tag/v1.7.5 看Notices部分

这个我看到了，但是也只是说可能移除啊，等1.8.0出来了真的移除了再在passwall2里面删除是不是更合理呢？

**Comment by jh0072110** [comment]
> > https://github.com/XTLS/Xray-core/releases/tag/v1.7.5 看Notices部分
> 
> 这个我看到了，但是也只是说可能移除啊，等1.8.0出来了真的移除了再在passwall2里面删除是不是更合理呢？

人要向前看🫤🫤
