### ISSUE TITLE
是否可以加入不配置DNS的选项

### ISSUE THREAD

**Issue by yaotthaha** [xiaorouji/openwrt-passwall2#21]
rt，用来搭配自定义dns

**Comment by snakwu** [comment]
> rt，用来搭配自定义dns

+1,应该是加进直接请求dns，而不是通过远程节点请求dns

**Comment by jtzgc** [comment]
同自建dns，用不惯新版，还是用回去年分开设置的版本好用

**Comment by yaotthaha** [comment]
有个办法，在dns那里选tcp，填mosdns的地址，用mosdns来分流

看了配置文件，ray会把所有域名解析都流入配置的dns

**Comment by snakwu** [comment]
> 有个办法，在dns那里选tcp，填mosdns的地址，用mosdns来分流
> 
> 看了配置文件，ray会把所有域名解析都流入配置的dns

但是对于dns是内网地址的不适用吧

**Comment by yaotthaha** [comment]
> > 有个办法，在dns那里选tcp，填mosdns的地址，用mosdns来分流
> > 看了配置文件，ray会把所有域名解析都流入配置的dns
> 
> 但是对于dns是内网地址的不适用吧

适用，不管你是否是内网地址，ray都会把dns请求发送到这个地址

**Comment by yaotthaha** [comment]
若是开发者头疼不知如何处理dns，我可以给个思路

像节点列表那样加个dns组，每组配置若干dns，并且配置是否走代理/直连。然后像分流选择节点那样增加一列选择每个分流规则用的dns组

**Comment by xiaorouji** [comment]
No plan, no need.

**Comment by snakwu** [comment]
> No plan, no need.

请问大佬，如果是内网的dns，如何可以实现不通过远程请求，而是直接请求，谢谢
