### ISSUE TITLE
[反馈]: 此次更新的DNS逻辑在解析国内域名时，该域名在国内外DNS服务上都有查询记录.

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall2#212]
### 描述您遇到的bug

https://github.com/xiaorouji/openwrt-passwall2/commit/b1231627b0cb9889065149a507d49794d7285946
最新版本：
解析国内直连域名时、国内外DNS服务器都有查询记录.

本地把`util_xray`修改成此次提交之前的：
国内直连域名在国内DNS服务器解析，国外代理域名在国外DNS服务器解析.

这是BUG还是此次提交的逻辑就是这样.

### 复现此Bug的步骤

.

### 您想要实现的目的

.

### 日志信息

.

### 系统相关信息

.

**Comment by xiaorouji** [comment]
非A和AAAA类型的DNS查询会直接请求国外DNS

**Comment by yunxi993** [comment]
> A和AAAA类型的DNS查询会使用内置Xray DNS分流， 其它类型的DNS查询会直接请求国外DNS

是的，国外DNS服务器上会应答HTTPS记录，但是仍有小部分明确直连的域名会在国内外DNS服务器上双查询，并且都会查询出A、AAAA记录，`util_xray`改回之前的就没这种情况.😊

**Comment by yunxi993** [comment]
所有的直连域名都会与直连DNS服务器生成相同数量的查询记录，区别在于直连DNS服务器是A和AAAA记录，远程DNS服务器全都是HTTPS.

**Comment by xiaorouji** [comment]
你可自行修改 `util_xray.lua ` 969行为：local type_dns = direct_type_dns

**Comment by yunxi993** [comment]
> 你可自行修改 `util_xray.lua ` 969行为：local type_dns = direct_type_dns

谢谢！
我之前就是这么改的，然后担心代理域名会漏到直连DNS服务器。然后改成指定DNS了: 
```
settings = {
    address = "8.8.8.8",
    port = tonumber(remote_dns_port) or 53,
    network = _remote_dns_proto or "tcp",
}
```
如果这样改，这些查询其实还是再用远程DNS查询，因为指定了 8.8.8.8 所以我设置的自定义DNS服务器看不见而已，对吗？
