### ISSUE TITLE
[Feature Request]: 希望能出现针对不同国家使用不同代理的功能

### ISSUE THREAD

**Issue by AntoineGao** [xiaorouji/openwrt-passwall2#215]
### 描述你想要的新功能

希望能在代理规则中添加不同国家走不同路线的功能

### 描述你想要的解决方案

设定不同国家ip或域名整体可以被代理，如美国：代理美国线路，日本：代理日本线路设置后所有美国和所有日本的IP或域名可以分别被代理

**Comment by xiaorouji** [comment]
请自定义 分流规则
用 geoip
