### ISSUE TITLE
[Bug]: 更新geoip 和geosite 文件后，无法访问Apple TV+

### ISSUE THREAD

**Issue by sky2016cn** [xiaorouji/openwrt-passwall2#233]
### 描述您遇到的bug

更新geoip 和geosite 文件后，就无法访问Apple TV+，更新前可以访问。

### 复现此Bug的步骤

更新geoip 和geosite 文件后，无法访问Apple TV+

### 您想要实现的目的

希望更新geoip 和geosite 文件后，可以正常访问Apple TV+

### 日志信息

无

### 系统相关信息

Passwall2-1.10最新版本

**Comment by jh0072110** [comment]
从direct里删了apple

**Comment by chancat87** [comment]
> 从direct里删了apple

apple-cn 可以用
