### ISSUE TITLE
[Bug]: 系统未安装iptables或ipset,无法透明代理

### ISSUE THREAD

**Issue by hu-boss** [xiaorouji/openwrt-passwall2#235]
### 描述您遇到的bug

刚编译了最新版的passwall2，安装到最新版openwrt-22.03.3上，仍然提示系统未安装iptables或ipset,无法透明代理，请问passwall现在支持openwrt-22.03了吗？

### 复现此Bug的步骤

系统未安装iptables或ipset,无法透明代理

### 您想要实现的目的

支持openwrt-22.03

### 日志信息

系统未安装iptables或ipset,无法透明代理

### 系统相关信息

passwall2

**Comment by xiaorouji** [comment]
`iptables-nft`
这个包装了吗

**Comment by hu-boss** [comment]
> `iptables-legacy` `iptables-nft` 这两个包有装吗？

楼下已经有人反馈了，装了也不行，希望能尽快适配，已经等了半年了

**Comment by lyd123qw2008** [comment]
> 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？

Dnsmasq软件包不满足nftables透明代理要求，如需使用请确保dnsmasq版本在2.87以上并开启nftset支持。大佬有遇到过吗？

**Comment by wangdaye078** [comment]
从snapshot里找到dnsmasq_2.89-4，装上，还是没用。
passwall2使用的是https://github.com/MoetaYuko/openwrt-passwall-build编译的版本。反正我还没实验成功。

**Comment by fragno** [comment]
> 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？

先升级 dnsmasq到2.87以上，然后再改配置，亲测生效

**Comment by hu-boss** [comment]
> > 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？
> 
> 先升级 dnsmasq到2.87以上，然后再改配置，亲测生效
怎么升级dnsmasq到2.87以上，openwrt源最新的只有2。86

**Comment by wangdaye078** [comment]
https://downloads.openwrt.org/snapshots/packages/x86_64/base/
这里可以找到新版本，装的时候还有其他一些库也需要从这边下载后才能安装。反正passwall2我没实验成功，楼上如果成功了详细说下。

**Comment by fragno** [comment]
> > > 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？
> > 
> > 
> > 先升级 dnsmasq到2.87以上，然后再改配置，亲测生效
> > 怎么升级dnsmasq到2.87以上，openwrt源最新的只有2。86

snapshot 源

**Comment by Steven-Graham-joe** [comment]
> > > 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？
> > 
> > 
> > 先升级 dnsmasq到2.87以上，然后再改配置，亲测生效
> 
> 这里下载https://downloads.openwrt.org/snapshots/packages/x86_64/base/
> 
> libubox20220927_2022-09-27-ea560134-1_x86_64.ipk libubus20220615_2022-06-15-9913aa61-1_x86_64.ipk dnsmasq-full_2.89-4_x86_64.ipk
> 
> 亲测有效 多谢

这个链接下已经下不到上边两个包了，需要去哪里找这两个包（我的也是22.03.4）

**Comment by sheiy** [comment]
> > > > 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？
> > > 
> > > 
> > > 先升级 dnsmasq到2.87以上，然后再改配置，亲测生效
> > 
> > 
> > 这里下载https://downloads.openwrt.org/snapshots/packages/x86_64/base/
> > libubox20220927_2022-09-27-ea560134-1_x86_64.ipk libubus20220615_2022-06-15-9913aa61-1_x86_64.ipk dnsmasq-full_2.89-4_x86_64.ipk
> > 亲测有效 多谢
> 
> 这个链接下已经下不到上边两个包了，需要去哪里找这两个包（我的也是22.03.4）

不用下一样的版本吧  前缀一样就行

**Comment by Steve-Graham0** [comment]
> > 在passwall的高级设置里设置防火墙工具为NFtables，似乎就可以正常工作了，不会再报上面的错误，passwall2没有这个设置。我一直有点疑问passwall和passwall2到底是什么关系，一般软件出了2以后，1基本就不更新了，比如caddy和caddy2，但是现在passwall的更新似乎有时候比passwall2还及时，所以他们到底是什么关系呢？
> 
> 先升级 dnsmasq到2.87以上，然后再改配置，亲测生效

升级dnsmasq之后，再改什么配置呀？

**Comment by sheiy** [comment]
> 

passwall 啊

**Comment by AoThen** [comment]
> 我的是OpenWrt 23.05.2，卸载dnsmasq，安装dnsmasq-full问题解决了，要在高级设置里把防火墙规则改为nftables

我刚刚想说，我也是这样成功的。。。

**Comment by hunter-xue** [comment]
> > 我的是OpenWrt 23.05.2，卸载dnsmasq，安装dnsmasq-full问题解决了，要在高级设置里把防火墙规则改为nftables
> 
> 我刚刚想说，我也是这样成功的。。。

2025-01-18 01:01:46: 清空并关闭相关程序和缓存完成。
2025-01-18 01:01:46: 系统未安装iptables或ipset或Dnsmasq没有开启ipset支持，无法使用iptables+ipset透明代理！
2025-01-18 01:01:46: 检测到fw4，使用nftables进行透明代理。
2025-01-18 01:01:47: 运行完成！

检测到fw4😄
