### ISSUE TITLE
今天刚编译了个新的pw2

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-passwall2#24]
怎么和以前比起来感觉少了很多菜单？是哪没对吗？

**Comment by yaotthaha** [comment]
就是这样的

**Comment by badgv** [comment]
> 就是这样的

是改进了吗？

**Comment by schen39** [comment]
分流挺好用，steam联机我目前加速器都不开，很流畅

**Comment by yaotthaha** [comment]
全部使用v2ray分流，学着用

**Comment by badgv** [comment]
> 分流挺好用，steam联机我目前加速器都不开，很流畅

分流上个版本就有这功能了的

**Comment by schen39** [comment]
上个版本没有direct，上个版本分流联机我要是要开加速器，这个版本后我不开了

**Comment by badgv** [comment]
> 上个版本没有direct，上个版本分流联机我要是要开加速器，这个版本后我不开了

可以操作的，你可能没搞清楚，这个版本比上个版本少了一些菜单了，上个版本有个直连配置，你直接填进去就行了
