### ISSUE TITLE
[Bug]: 进入界面报错.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#241]
### 描述您遇到的bug

/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute function dispatcher target for entry '/admin/services/passwall2'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/passwall2/settings'.
The called action terminated with an exception:
...r/lib/lua/luci/model/cbi/passwall2/client/global.lua:69: attempt to call field 'get_node_remarks' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 复现此Bug的步骤

进入passwall2界面.

### 您想要实现的目的

进入passwall2界面.

### 日志信息

/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute function dispatcher target for entry '/admin/services/passwall2'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/passwall2/settings'.
The called action terminated with an exception:
...r/lib/lua/luci/model/cbi/passwall2/client/global.lua:69: attempt to call field 'get_node_remarks' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 系统相关信息

625fe13

**Comment by xiaorouji** [comment]
`rm -rf /tmp/luci*`

**Comment by yunxi993** [comment]
> 

好了.

**Comment by mxm012337** [comment]
passwall和passwall2 开启就出现这样的错误

**Comment by xiaoshengshuohua** [comment]
> passwall和passwall2 开启就出现这样的错误

最新版本没这个问题.

**Comment by mxm012337** [comment]
分流模式出错

> > passwall和passwall2 开启就出现这样的错误
> 
> 最新版本没这个问题.

分流模式出错
