### ISSUE TITLE
xray/v2ray添加wireguard出口，字段不匹配

### ISSUE THREAD

**Issue by hululu1068** [xiaorouji/openwrt-passwall2#243]
### 描述您遇到的bug

xray/v2ray添加`wireguard`出口，发现`字段`不匹配,导致连接不上.

### 复现此Bug的步骤

对比了下，passwall的字段和wiki的字段，如下

<img width="649" alt="image" src="https://user-images.githubusercontent.com/68652362/233094357-ff7fcddf-cb24-4a08-92a2-b537a55f6a3b.png">
<img width="562" alt="2023-04-19_21-28-57" src="https://user-images.githubusercontent.com/68652362/233095702-66a227e7-94f8-41dc-99b7-7d68c43e989c.png">

官方文档给出的字段
<img width="796" alt="2023-04-19_21-29-38" src="https://user-images.githubusercontent.com/68652362/233095805-67561821-ea0f-45b6-b9c2-01482ec2b2ed.png">

### 您想要实现的目的

添加Cloudflare Warp节点.

### 日志信息

none

### 系统相关信息

luci-app-passwall - 4.64-3
luci-app-passwall2 - 1.11

**Comment by nftbty** [comment]
warp是支持的，不过现在warp都有routing id填在reserved参数的，3个字节。可以每个字节用10进制表示，用逗号隔开，比如`101,102,103`，或者有些软件获取的配置是base64编码的，比如`e3rj`，passwall可以直接填上去，passwall2这边还没把这个提交同步过来。

**Comment by hululu1068** [comment]
> warp是支持的，不过现在warp都有routing id填在reserved参数的，3个字节。可以每个字节用10进制表示，用逗号隔开，比如`101,102,103`，或者有些软件获取的配置是base64编码的，比如`e3rj`，passwall可以直接填上去，passwall2这边还没把这个提交同步过来。

我用官方文档推荐的[wgcf](https://github.com/ViRb3/wgcf.git) 提取的配置信息。。。方便的话能截个图上来看看吗

**Comment by nftbty** [comment]
![Screenshot_2023-04-20-15-00-38-220_io.github.forkmaintainers.iceraven.jpg](https://user-images.githubusercontent.com/10704839/233286275-d2eaff61-2d8e-4a54-a528-d1ceb6bf4ad2.jpg)

![Screenshot_2023-04-20-15-00-16-082_io.github.forkmaintainers.iceraven.jpg](https://user-images.githubusercontent.com/10704839/233286305-1988dae7-93ca-474f-8296-7480675654d1.jpg)

**Comment by nftbty** [comment]
连接不上是默认的域名和端口国内本来就连不上，只能用前置代理。或者找国内可以连的IP和端口。

**Comment by hululu1068** [comment]
> routing id

这个 `routing id`如何获取？

**Comment by hcym** [comment]
效果怎么样

**Comment by nftbty** [comment]
> 这个 `routing id`如何获取？

看你用的工具，应该有的吧，如果没有，那可能就是没有。原来warp是没有这个的，现在应该是都加了，利用reserved参数。你可以套个前置代理试试，看没有reserved通不通。

**Comment by hululu1068** [comment]
排查、测试了下，我这边不需要`routing id`,直接换可用的`Endpoint IP`就可以了。
分享几个可用的IP，有的解锁了流媒体，有的没有，速度还可以。。。
```
当前最优 Endpoint IP 结果如下：
端点 IP:PORT 丢包率  LOSS 平均延迟  DELAY
端点 162.159.192.89:968 丢包率 0.00% 平均延迟 166 ms
端点 162.159.192.47:968 丢包率 0.00% 平均延迟 167 ms
端点 162.159.192.68:854 丢包率 0.00% 平均延迟 167 ms
端点 162.159.195.175:968 丢包率 0.00% 平均延迟 167 ms
端点 162.159.192.68:968 丢包率 0.00% 平均延迟 168 ms
端点 162.159.192.69:968 丢包率 0.00% 平均延迟 168 ms
端点 162.159.192.74:854 丢包率 0.00% 平均延迟 168 ms
端点 162.159.192.47:854 丢包率 0.00% 平均延迟 170 ms
端点 162.159.192.17:854 丢包率 0.00% 平均延迟 171 ms
端点 162.159.192.101:3854 丢包率 0.00% 平均延迟 153 ms
端点 162.159.192.101:7559 丢包率 0.00% 平均延迟 182 ms
端点 162.159.192.104:3854 丢包率 0.00% 平均延迟 155 ms
端点 162.159.192.104:7559 丢包率 0.00% 平均延迟 150 ms
端点 162.159.192.122:7559 丢包率 0.00% 平均延迟 145 ms
端点 162.159.192.138:3854 丢包率 0.00% 平均延迟 164 ms
端点 162.159.192.138:7559 丢包率 0.00% 平均延迟 167 ms
端点 162.159.192.165:3854 丢包率 0.00% 平均延迟 167 ms
端点 162.159.192.165:7559 丢包率 0.00% 平均延迟 144 ms

当前最优 Endpoint IP 结果如下：
端点 IP:PORT 丢包率  LOSS 平均延迟  DELAY
端点 [2606:4700:d0::8dd4:da6:5aec:7770]:8886 丢包率 0.00% 平均延迟 175 ms
端点 [2606:4700:d1::396f:835f:4c76:127d]:8886 丢包率 0.00% 平均延迟 176 ms
端点 [2606:4700:d1::3c8b:6687:523a:b34c]:859 丢包率 0.00% 平均延迟 176 ms
端点 [2606:4700:d1::3d6a:4447:c408:18aa]:8886 丢包率 0.00% 平均延迟 176 ms
端点 [2606:4700:d1::3f47:284c:a305:1036]:859 丢包率 0.00% 平均延迟 176 ms
端点 [2606:4700:d1::3f47:284c:a305:1036]:8886 丢包率 0.00% 平均延迟 176 ms
端点 [2606:4700:d0::557d:fd90:b2c1:7c36]:859 丢包率 0.00% 平均延迟 177 ms
端点 [2606:4700:d1::41bf:f0:8944:7a9a]:859 丢包率 0.00% 平均延迟 177 ms
端点 [2606:4700:d1::bc92:acd3:3ac5:e13f]:8886 丢包率 0.00% 平均延迟 177 ms
端点 [2606:4700:d0::1bd1:1904:8d10:163f]:859 丢包率 0.00% 平均延迟 178 ms
端点 [2606:4700:d0::13be:cfd1:6b0c:6c29]:5279 丢包率 0.00% 平均延迟 140 ms
端点 [2606:4700:d0::13be:cfd1:6b0c:6c29]:7103 丢包率 0.00% 平均延迟 151 ms
端点 [2606:4700:d0::1910:c5eb:942d:9541]:5279 丢包率 0.00% 平均延迟 154 ms
端点 [2606:4700:d0::1910:c5eb:942d:9541]:7103 丢包率 0.00% 平均延迟 175 ms
端点 [2606:4700:d0::1a8:cec8:83f:9f24]:5279 丢包率 0.00% 平均延迟 154 ms
端点 [2606:4700:d0::1a8:cec8:83f:9f24]:7103 丢包率 0.00% 平均延迟 171 ms
端点 [2606:4700:d0::23ef:8621:5f9d:31e3]:5279 丢包率 0.00% 平均延迟 164 ms
端点 [2606:4700:d0::23ef:8621:5f9d:31e3]:7103 丢包率 0.00% 平均延迟 172 ms
端点 [2606:4700:d0::24bf:45b5:de62:81f1]:5279 丢包率 0.00% 平均延迟 157 ms
端点 [2606:4700:d0::24bf:45b5:de62:81f1]:7103 丢包率 0.00% 平均延迟 176 ms
```
<img width="600" alt="2023-04-21_13-00-45" src="https://user-images.githubusercontent.com/68652362/233549440-d1596ebf-bf0c-4181-9149-45bd16d3cf7f.png">
