### ISSUE TITLE
[Bug]: 开启自动切换，无法进入pw

### ISSUE THREAD

**Issue by feifan1113** [xiaorouji/openwrt-passwall2#245]
### 描述您遇到的bug

一旦启用自动切换，就无法进入pw的基本设置界面，但是其他功能菜单可以进入

### 复现此Bug的步骤

1，启用自动切换
2，点击基本设置

### 您想要实现的目的

修复该bug

### 日志信息

/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/passwall2/settings'.
The called action terminated with an exception:
...r/lib/lua/luci/model/cbi/passwall2/client/global.lua:70: attempt to index local 'n' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 截图

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/57245399/233748109-9dfa916f-1202-40db-9963-be6604bf432f.png">

### 系统相关信息

最新版的pw2

**Comment by imoldchen** [comment]
这个我复现是在添加自动切换提交之后。

**Comment by xiaorouji** [comment]
下个版本修复

**Comment by xiaorouji** [comment]
Fixed.
