### ISSUE TITLE
自动切换中当主节点是分流时增加能切其他自定义规则节点

### ISSUE THREAD

**Issue by imoldchen** [xiaorouji/openwrt-passwall2#246]
### 描述你想要的新功能

现在的自动切换功能，当主节点时分流时，只能切换前置或者默认节点，当默认节点是直连时，自动切换的选项只提供切换、切换默认、切换前置这三项就无用武之地了，希望能增加一个选项可以选择切换到自定义规则的节点，我个人偏向于在规则列表的 Proxy 中把剩下需要代理的规则都加进去，默认用直连，规则列表第二个在 AD 下面用 Dricet，这一组规则也不用增加 geosite:cn 和 geoip:cn，只把一些识别有误的单独加进去，这样减少查询量和代理流量，也比较快，就是无法故障时使用自动切换功能切换 Proxy 指定的 node。

### 描述你想要的解决方案

自动切换主节点为份流时，增加一个可以选择规则列表中的某一个来应用切换

**Comment by xiaorouji** [comment]
可以使用最新源码，haproxy做主备配合

**Comment by imoldchen** [comment]
这个好像并不是我描述的需求，负载均衡只能作为 Node 项选择，而不能在分流的规则项中选择。

**Comment by xiaorouji** [comment]
passwall内置逻辑可实现，参考 https://github.com/xiaorouji/openwrt-passwall/discussions/2420
