### ISSUE TITLE
[Bug]: 1.13-3 半小时前刚肝的码貌似有问题

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#247]
### 描述您遇到的bug

不能正常出门了
illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf

喵了一眼，第四句：
port=15355
server=127.0.0.1#15354
ipset=whitelist,whitelist6
port=11303
server=127.0.0.1#11302
ipset=whitelist,whitelist6

### 复现此Bug的步骤

。

### 您想要实现的目的

。

### 日志信息

hu Apr 27 00:41:03 2023 daemon.crit dnsmasq[24516]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Thu Apr 27 00:41:03 2023 daemon.crit dnsmasq[24516]: FAILED to start up
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: reading /etc/resolv.conf
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver 127.0.0.1#15354
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver 127.0.0.1#53
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver ::1#53
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: reading /etc/resolv.conf
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver 127.0.0.1#15354
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver 127.0.0.1#53
Thu Apr 27 00:41:08 2023 daemon.info dnsmasq[23752]: using nameserver ::1#53
Thu Apr 27 00:41:08 2023 cron.err crond[25601]: crond (busybox 1.36.0) started, log level 8

### 系统相关信息

1.13-3

**Comment by xiaorouji** [comment]
忽略了 ACL 的情况了。。。明天再修吧，躺床上了

**Comment by Travel2Here** [comment]
> 忽略了 ACL 的情况了。。。明天再修吧，躺床上了

奈何能力不足 不然帮一起修了 再学一阵 ，辛苦啦

**Comment by baodp** [comment]
是的。连不上外网了

**Comment by baodp** [comment]
作者更新了，修好了。

**Comment by Travel2Here** [comment]
> 作者更新了，修好了。

嗯嗯 看见，起床编译咯

**Comment by Travel2Here** [comment]
话说错误解决了，请问这个cache怎么是150条？跟我自己设过的dnsmasq不一样，是咱们APP单独新设的配置吗？能否调大
另外，compile time options这段也是APP设定的？


Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: started, version 2.88 cachesize 150
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-nftset no-auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: using nameserver 127.0.0.1#15354
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: reading /etc/resolv.conf
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: using nameserver 127.0.0.1#15354
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: using nameserver 127.0.0.1#53
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: using nameserver ::1#53
Thu Apr 27 14:44:28 2023 daemon.info dnsmasq[6189]: read /etc/hosts - 6 names

**Comment by necokeine** [comment]
这个问题好像在1.13-4上也存在，但是我现在不知道怎么确定性复现。
我研究下是怎么出现的。
`Wed Jul 26 15:24:58 2023 daemon.crit dnsmasq[11544]: FAILED to start up
Wed Jul 26 15:25:56 2023 daemon.crit dnsmasq[12747]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:25:56 2023 daemon.crit dnsmasq[12747]: FAILED to start up
Wed Jul 26 15:26:55 2023 daemon.crit dnsmasq[13959]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:26:55 2023 daemon.crit dnsmasq[13959]: FAILED to start up
Wed Jul 26 15:27:53 2023 daemon.crit dnsmasq[15159]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:27:53 2023 daemon.crit dnsmasq[15159]: FAILED to start up
Wed Jul 26 15:28:51 2023 daemon.crit dnsmasq[16316]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:28:51 2023 daemon.crit dnsmasq[16316]: FAILED to start up
Wed Jul 26 15:29:49 2023 daemon.crit dnsmasq[17516]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:29:49 2023 daemon.crit dnsmasq[17516]: FAILED to start up
Wed Jul 26 15:30:47 2023 daemon.crit dnsmasq[18695]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Jul 26 15:30:47 2023 daemon.crit dnsmasq[18695]: FAILED to start up
Wed Jul 26 15:31:45 2023 daemon.crit dnsmasq[19868]: illegal repeated keyword at line 4 of /tmp/etc/passwall2/dnsmasq_global_direct.conf`
