### ISSUE TITLE
XBox网络性能100%丢包

### ISSUE THREAD

**Issue by leochien0102** [xiaorouji/openwrt-passwall2#25]
用了新的passwall2分流，结果Xbox网络 100%丢包，访问其它受限站点都没问题。
需要添加自定义规则？规则怎么设定？
![微信截图_20220322141800](https://user-images.githubusercontent.com/3915276/159463072-627143e6-f8a6-425e-8b12-f8dfdebb447d.png)

**Comment by xiaorouji** [comment]
用Xray，V2fly没有FullCone

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/issues/4

**Comment by leochien0102** [comment]
> 用Xray，V2fly没有FullCone

改成xray分流，添加了一条新规则，网络UDP，放在China规则下面，选好节点，依旧100%丢包
![微信截图_20220322193642](https://user-images.githubusercontent.com/3915276/159473280-76d56f0e-91fe-4998-8f97-7a4fa87496ee.png)
相同节点在ssr plus下完全正常
![微信截图_20220322142516](https://user-images.githubusercontent.com/3915276/159472644-06c8db56-b442-4964-b53d-9bcdfd41bff6.png)
![微信截图_20220322193343](https://user-images.githubusercontent.com/3915276/159473091-c5615b2b-8cb6-4871-b623-0bcef0fe2944.png)
![微信截图_20220322193534](https://user-images.githubusercontent.com/3915276/159473105-be879752-6ede-4062-b2e9-03f611cc6596.png)

**Comment by xiaorouji** [comment]
自己找原因吧，我玩ns联机没有问题

**Comment by xiaorouji** [comment]
用passwall1试试看？

**Comment by leochien0102** [comment]
> 用passwall1试试看？

好，把passwall1拉回来试试

**Comment by xiaorouji** [comment]
用 NatTypeTester 测试能否连通？
没有Xbox，不清楚联机是否需要UDP加速或加速器
