### ISSUE TITLE
[Bug]: 直连出现图片无法刷新.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#252]
### 描述您遇到的bug

直连偶尔出现图片无法刷新.

还有就是系统日志的问题, 特别是`daemon.warn dnsmasq[2748]: Maximum number of concurrent DNS queries reached (max: 150)`

### 复现此Bug的步骤

每次passwall2有操作系统日志就会出现一堆日志.

### 您想要实现的目的

减少或禁用每次操作passwall2出现许多系统日志, 还有dnsmasq最大并发, 怀疑直连偶尔出现问题与dnsmasq最大并发有关.

### 日志信息

```
daemon.info dnsmasq[2748]: started, version 2.88 cachesize 150
daemon.info dnsmasq[2748]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset no-nftset no-auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#15354
daemon.info dnsmasq[2748]: reading /etc/resolv.conf
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#15354
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#53
daemon.info dnsmasq[2748]: using nameserver ::1#53
daemon.info dnsmasq[2748]: read /etc/hosts - 6 names
daemon.info dnsmasq[2748]: reading /etc/resolv.conf
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#15354
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#53
daemon.info dnsmasq[2748]: using nameserver ::1#53
daemon.info dnsmasq[2748]: reading /etc/resolv.conf
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#15354
daemon.info dnsmasq[2748]: using nameserver 127.0.0.1#53
daemon.info dnsmasq[2748]: using nameserver ::1#53
cron.err crond[4220]: crond (busybox 1.36.0) started, log level 5
daemon.warn dnsmasq[2748]: Maximum number of concurrent DNS queries reached (max: 150)
daemon.warn dnsmasq[2748]: Maximum number of concurrent DNS queries reached (max: 150)
daemon.warn dnsmasq[2748]: Maximum number of concurrent DNS queries reached (max: 150)
```

### 系统相关信息

passwall2: 1.14-2

xray-core: 1.8.1

**Comment by Travel2Here** [comment]
不用怀疑 就是最大并发当时满了。我也想解决这个问题，求xiaorouji关注~

**Comment by xiaorouji** [comment]
[app.zip](https://github.com/xiaorouji/openwrt-passwall2/files/11403183/app.zip)
把这个文件解压覆盖 /usr/share/passwall2/app.sh 再试试？

**Comment by Travel2Here** [comment]
> 

run_ipset_dnsmasq() {
	local listen_port server_dns ipset cache_size dns_forward_max config_file
	eval_set_val $@
	cat <<-EOF > $config_file
		port=${listen_port}
		server=${server_dns}
		ipset=${ipset}
		no-poll
		no-resolv
		cache-size=${cache_size:-0}
		dns-forward-max=${dns_forward_max:-1000}
	EOF
	ln_run "$(first_type dnsmasq)" "dnsmasq" "/dev/null" -C $config_file
}

看见区别了。已覆盖重启，观察一阵~

**Comment by xiaoshengshuohua** [comment]
> [app.zip](https://github.com/xiaorouji/openwrt-passwall2/files/11403183/app.zip) 把这个文件解压覆盖 /usr/share/passwall2/app.sh 再试试？


感谢修复!!!
使用了2个小时, 截至目前为止没有出现dnsmasq最大并发问题.

现在passwall2关闭时`cron.err crond[8245]: crond (busybox 1.36.0) started, log level 5`这条日志会出现两条.

还有就是, 现在每次操作passwall2时系统日志比之前减少了, 但是仍然会有这几条日志:
```
daemon.info dnsmasq[16710]: started, version 2.88 cache disabled
daemon.info dnsmasq[16710]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset no-nftset no-auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
daemon.info dnsmasq[16710]: using nameserver 127.0.0.1#15354
daemon.info dnsmasq[16710]: read /etc/hosts - 6 names
```
