### ISSUE TITLE
[Feature Request]: 什么固件集成了这个插件

### ISSUE THREAD

**Issue by kennylee60** [xiaorouji/openwrt-passwall2#255]
### 描述你想要的新功能

我不会编译，请问有固件集成这个插件的吗

### 描述你想要的解决方案

我不会编译，请问有固件集成这个插件的吗

**Comment by Travel2Here** [comment]
应该问哪个正常固件不集成这个？；）
哥们慎用issue，可以去讨论区发这类。

**Comment by jh0072110** [comment]
集成2的比较少吧，不过建议老哥这种问题发在
https://github.com/xiaorouji/openwrt-passwall2/discussions
虽然也不一定有人回就是了……
还得自己找

**Comment by wangdaye078** [comment]
https://github.com/MoetaYuko/openwrt-passwall-build
官方OPENWRT可以尝试这个。
https://op.supes.top/packages/
这也能找到编译好的。
其他地方应该还能找到一些个人定期编译的版本。
