### ISSUE TITLE
[Bug]: 分流配置，不支持负载均衡类节点

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#259]
### 描述您遇到的bug

不知道是这么规划的还是遗漏了。
在总节点为XRAY分流时，分流不支持选择负载均衡协议。（XRAY自带的那个）
而我看passwall里相同场景是可以的。

### 复现此Bug的步骤

。

### 您想要实现的目的

支持起~

### 日志信息

。

### 系统相关信息

1.5-1

**Comment by nftbty** [comment]
我看看
