### ISSUE TITLE
[Bug]: 系统日志中这个错误好几个版本了，是否需要修正？

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#260]
### 描述您遇到的bug

使用中没有感受到明显功能缺陷。
但看这段日志，以及涉及到的代码表明：-w的参数不是lua or sh可用的。
或许应该是bash所用，所以不能正常执行。

翻看具体文件代码（server_app.lua 文件中31行起），
这段意在写入防火墙，如果不成功，逻辑上看应该是影响功能的。

```
local function ipt(arg)
	cmd(ipt_bin .. " -w " .. arg)
end

local function ip6t(arg)
	cmd(ip6t_bin .. " -w " .. arg)
end
```

*奈何本人不是开发出生，只能读懂皮毛不敢贸然改动。劳烦xiaorouji或共建者给修复或指导。

### 复现此Bug的步骤

always~

### 您想要实现的目的

fix it

### 日志信息

系统日志：
Tue May 16 17:55:28 2023 daemon.notice procd: /etc/rc.d/S99passwall2_server: sh: -w: not found
Tue May 16 17:55:28 2023 daemon.notice procd: /etc/rc.d/S99passwall2_server: sh: -w: not found
Tue May 16 17:55:28 2023 daemon.notice procd: /etc/rc.d/S99passwall2_server: sh: -w: not found
Tue May 16 17:55:28 2023 daemon.notice procd: /etc/rc.d/S99passwall2_server: sh: -w: not found
Tue May 16 17:55:28 2023 daemon.notice procd: /etc/rc.d/S99passwall2_server: sh: illegal option -

### 系统相关信息

1.5-1

**Comment by xiaorouji** [comment]
执行一下
`echo -n $(/usr/share/passwall2/iptables.sh get_ipt_bin)`
`echo -n $(/usr/share/passwall2/iptables.sh get_ip6t_bin)`
看看输出什么

**Comment by Travel2Here** [comment]
已编译1.15-4，没有错误日志了。辛苦哥~
