### ISSUE TITLE
[Bug]: passwall2 xray服务端无法开启

### ISSUE THREAD

**Issue by Paris0-0** [xiaorouji/openwrt-passwall2#261]
### 描述您遇到的bug

passwall可以正常开，但passwall2不行，尝试不编译passwall只安装passwall2，还是不行，开启服务端无任何日志显示，就是个叉号，也不知道怎么排查，，ss服务端开启正常

### 复现此Bug的步骤

开启xray服务端

### 您想要实现的目的

可以开启服务端

### 日志信息

找不到服务端日志

### 系统相关信息

passwall2

**Comment by xiaorouji** [comment]
Xray 协议、传输方式 等信息提供一下

**Comment by xiaorouji** [comment]
已修复
