### ISSUE TITLE
[Bug]: 1.15-4版本，无法更新规则文件

### ISSUE THREAD

**Issue by terrytyc** [xiaorouji/openwrt-passwall2#265]
### 描述您遇到的bug

r4s环境，更新geoip和geodata时，实际下载和更新动作不执行

### 复现此Bug的步骤

规则管理，点击手动更新（manual update）时，实际/usr/share/v2ray下规则文件未更新
且未发现/tmp下有geoip、geosite相关下载文件和md5临时文件生成

### 您想要实现的目的

解决相关bug

### 日志信息

2023-05-27 12:22:54: geoip 开始更新...
2023-05-27 12:22:57: geosite 开始更新...
2023-05-27 12:22:58: 规则更新完毕...

### 系统相关信息

paswwall版本1.15-4
谷歌内核版本113.0.1774.50
openwrt版本OpenWrt R23.5.1 ，内核5.15.110
主机型号FriendlyElec NanoPi R4S

**Comment by Travel2Here** [comment]
应该是你环境问题，一路用过来没遇到过这情况，另外1.6也发了朋友可以更新下，更好用
*你也可以试下用其他APP全局代理再更新这俩文件

**Comment by xiaorouji** [comment]
测试没问题

**Comment by derekxi2021** [comment]
我发现了同样的问题。
paswwall2版本1.28-2
openwrt版本OpenWrt R24.2.2 ，内核6.1.82
主机型号Intel(R) Celeron(R) CPU J3160 @ 1.60GHz : 4C4T
