### ISSUE TITLE
[Bug]: passwall2 ipv6分流失效

### ISSUE THREAD

**Issue by chaoticjoy** [xiaorouji/openwrt-passwall2#269]
### 描述您遇到的bug

用ip.sb测试发现，passwall2分流规则只能对ipv4出口ip生效了走了指定ip出口，ipv6出口还没变，还是直连出口，请问是哪里设置的问题

### 复现此Bug的步骤

无

### 您想要实现的目的

ipv6实现分流

### 日志信息

无

### 系统相关信息

1.11-2

**Comment by xiaorouji** [comment]
请更新到最新版本再测试。
另外，ipv6透明代理请到 高级设置 里开启

**Comment by chaoticjoy** [comment]
> 请更新到最新版本再测试。
> 另外，ipv6透明代理请到 高级设置 里开启

升级后问题依旧，我是旁路由，查了下应该是旁路由问题，还有解决方法吗

**Comment by hululu1068** [comment]
这个报错是什么原因啊

<img width="383" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/68652362/dad4028b-7934-4aea-a183-48e432e6aeaf">

**Comment by BGzEroll** [comment]
> > 请更新到最新版本再测试。
> > 另外，ipv6透明代理请到 高级设置 里开启
> 
> 升级后问题依旧，我是旁路由，查了下应该是旁路由问题，还有解决方法吗

旁路由这方面没救，网关都不是旁路由的，所以ipv6代理是失效的

**Comment by hu-boss** [comment]
> 请更新到最新版本再测试。 另外，ipv6透明代理请到 高级设置 里开启

我的最新版passwall2 在高级设置里怎么没有 开启IPv6代理选项？
