### ISSUE TITLE
用Xray完全替代V2ray

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-passwall2#27]
碰到类似问题#25，但我的问题可能有些许不同。

**希望优化**：xray完全替代v2ray功能。

**理由**：自动订阅里的vmess总是用v2ray类型，无法正常udp，每次需要手动改xray。passwall1其实也存在类似问题。

**想得到的效果**，这样同时带来一些优点（在目前的遭遇的基础上）：
1）定时更新订阅时，无需再手动修改vmess的节点使用类型。
2）想全局分流。
3）无能力设立单独游戏分流规则条件下，需要单独开socks在PC上加速整个游戏应用（例：DOTA2，CS-GO）

**临时解决办法（passwall1）**：在编译过程中，不勾选include v2ray-core & v2ray-plugin，勾选include xray-core & xray-plugin。但**passwall2，v2ray-core是默认勾选**。

**当前使用截图**：
分流规则：![image](https://user-images.githubusercontent.com/31793080/159852718-3617614f-eec5-40e6-a857-a902ad49fe67.png)
Socks节点：![image](https://user-images.githubusercontent.com/31793080/159850592-7c9c4934-340f-47a4-805d-59cc981e23a8.png)
节点详情：![image](https://user-images.githubusercontent.com/31793080/159850563-5c20ba11-1da6-47d7-9814-696744ab4a10.png)

感谢大佬带来如此优秀的软件。

**Comment by xiaorouji** [comment]
目前来看的确有必要，否则UDP不能NAT A

**Comment by xiaorouji** [comment]
Complete.
Close.

**Comment by SakuraFallingMad** [comment]
感谢！include xray plugin是不是也添加上比较好，看上去xray+xray plugin看着舒服，虽然是个ss插件

**Comment by xiaorouji** [comment]
我没用过这个插件，所以没什么感觉。
