### ISSUE TITLE
可以添加一个一键测试所有节点的   可用性测试    的功能吗？

### ISSUE THREAD

**Issue by zzduci** [xiaorouji/openwrt-passwall2#271]
### 描述你想要的新功能

可以添加一个一键测试所有节点的   可用性测试    的功能吗？掉线后每次要全部单个点有点麻烦
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/122016328/3cc159ff-2b06-4245-a67f-cbae211fedee)

### 描述你想要的解决方案

可以添加一个一键测试所有节点的   可用性测试    的功能吗？掉线后每次要全部单个点有点麻烦，有个一键测试就再好不过了

**Comment by xpn282** [comment]
我觉得直接显示“ 可用性测试 “结果，也不用一键了，一键还要多按一次，麻烦

**Comment by zzduci** [comment]
> 我觉得直接显示“ 可用性测试 “结果，也不用一键了，一键还要多按一次，麻烦

你这个想法更先进，不错不错

**Comment by xiaorouji** [comment]
性能效率有限。
