### ISSUE TITLE
访问控制不能让指定设备走“直连”？

### ISSUE THREAD

**Issue by xpn282** [xiaorouji/openwrt-passwall2#273]
### 描述你想要的新功能

我想让某台设备走全局直连，在访问控制里没看到有可以设置直连的选择。有几个端口转发的选项和节点选择的选项而已，貌似不能让设备走直连。。
我记得Passwall是可以给设备走直连的。。

### 描述你想要的解决方案

访问控制增加直连选项

**Comment by xiaorouji** [comment]
访问控制内的 `TCP不转发端口` 和 `UDP不转发端口` 选 `所有`，即可

**Comment by xpn282** [comment]
ok，已解决

**Comment by opts98** [comment]
万分感谢看到这个issue
