### ISSUE TITLE
[Bug]: 订阅更新后，xray负载均衡内的节点列表失效

### ISSUE THREAD

**Issue by 0x01-0xff** [xiaorouji/openwrt-passwall2#278]
### 描述您遇到的bug

在开启机场订阅自动更新情况下，xray负载均衡节点里面的节点列表在订阅更新后全部失效，查看/etc/config/passwall2文件：
config nodes 'policy_HK'
	option remarks '香港节点'
	option type 'Xray'
	option protocol '_balancing'
	option balancingStrategy 'leastPing'
	option useCustomProbeUrl '1'
	option probeUrl 'https://www.google.com/generate_204'
	option probeInterval '15m'
	list balancing_node 'WWvvbpsj'
	list balancing_node 'h8WG2meT'
	list balancing_node '9TcTe2wI'
	list balancing_node 'bzzViT1a'
	list balancing_node 'cAoSpSCW'
发现由于订阅更新，所有机场节点的 config nodes 随机名称已经重新生成，但是xray负载均衡里添加的机场节点列表字段list balancing_node的值没有跟随改变，造成订阅更新之后该xray节点不可用。必须手动删除xray里失效的列表再次添加机场节点。

### 复现此Bug的步骤

1、开启机场订阅自动更新功能
2、新建一个协议为负载均衡的xray节点，在节点列表里添加机场节点
3、当机场订阅更新后，查看该xray节点内的节点列表，全部变成8位随机字符，不再显示机场节点名字

### 您想要实现的目的

想要实现机场订阅更新后，负载均衡的xray节点内的机场节点列表跟随更新

### 日志信息

无

### 系统相关信息

passwall2 版本：1.16-1

**Comment by HugoPresents** [comment]
我也发现了，看起来是每次重新生成了 node id 匹配不了

**Comment by HugoPresents** [comment]
而且这个 bug 不是稳定出现，某些天就会一直匹配不了，某些天又可以，真的神奇 @xiaorouji

**Comment by 0x01-0xff** [comment]
是的，有时没事。
但是在xray分流总节点里面对分流规则选取的节点是没有问题的，在更新后不会丢失，所以这个应该是node id读取机制的问题。希望修复。@xiaorouji

**Comment by HugoPresents** [comment]
我提了一个 pr 尝试修复了
