### ISSUE TITLE
请问插件里的geoip和geosite的来源是哪里？

### ISSUE THREAD

**Issue by roxsky** [xiaorouji/openwrt-passwall2#28]
现在流行的ip和site数据好像有好几种，请问插件中是用的哪个呢？

**Comment by SakuraFallingMad** [comment]
[https://github.com/Loyalsoldier/v2ray-rules-dat](url)

**Comment by roxsky** [comment]
> https://github.com/Loyalsoldier/v2ray-rules-dat

谢谢。
