### ISSUE TITLE
[Bug]: 1.16版里xray负载均衡节点里面的节点保存应用更改无法生效

### ISSUE THREAD

**Issue by freeme2019** [xiaorouji/openwrt-passwall2#282]
### 描述您遇到的bug

xray负载均衡节点里面的节点保存应用更改无法生效

### 复现此Bug的步骤

1.确保已经建立好xray负载均衡节点。
2、修改默认节点为任意节点然后点击下方的“保存&应用”，实际上并没有生效，“ 当前节点"里仍然是修改前的节点。

### 您想要实现的目的

希望尽快修改

### 日志信息

有别人反映了，和我问题差不多，是个普遍问题。

### 系统相关信息
x86_64
passwall 1.16.5-1.16.6  所有关联插件都已升级到最新版
chrome  114.0.5735.134（正式版本） （64 位）

**Comment by hululu1068** [comment]
配置负载均衡，是需要一定前提的。。。
看看日志

**Comment by freeme2019** [comment]
原来都正常的，就是这几个版本开始，无法保存更改，而且现在上网也出现卡顿。
