### ISSUE TITLE
[Feature Request]: 自动检测特定设置下依赖的tproxy模块，并在缺失时，在日志中进行提醒。

### ISSUE THREAD

**Issue by Yangleis** [xiaorouji/openwrt-passwall2#284]
### 描述你想要的新功能

最近两天在OpenWRT官方22.03.5镜像中安装passwall2，途中缺失ipset和dnsmasq-full高版本，都在日志中进行提醒，最终都得以解决。

但在使用后，发现透明代理无法对UDP进行转发，但排查日志无异常。经过搜索相关问题和仔细排查后，确定问题是缺少`kmod-nft-tproxy`、`kmod-nft-socket` 内核模块。

OpenWRT在22版本中移除了iptables，所以防火墙工具固定为使用nftables。使用tproxy还是redirect，在luci界面中没有设置的地方（我记得之前有，BUG？），TCP固定为redirect，UDP固定为tproxy。

管方镜像对tproxy相关几个内核模块进了裁剪，默认未安装，而且市面上流行的三方镜像都默认安装了。所以在这类镜像中安装passwall或者passwall2，可能会出现透明代理TCP正常，但UDP全被阻断的情况。而且日志一切正常，不太容易发现问题所在。

我在搜索相关话题时，也发现了不少UDP、游戏被阻断的Issue和discussion，我怀疑于此有关。

### 描述你想要的解决方案

在启用nftables和tproxy时，自动检测`kmod-nft-tproxy`、`kmod-nft-socket` 等依赖的模块，并在缺失时，像ipset、dnsmasq那样在日志中进行提醒。

### 描述你考虑过的替代方案
对所需的依赖统一进行检测，在专门的界面中显示安装情况。但工作量较大。

直接添加模块作为包依赖，安装passwall2时自动从opkg源进行安装。但在不使用nftables和tproxy时可能变成无用的依赖。

**Comment by hululu1068** [comment]
关了吧。。。
Makefile本来就有必要依赖，手动安装的话自己解决相关依赖。
<img width="495" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/68652362/584c1d4d-418c-4ee2-9c9e-780f637f6f4e">

**Comment by Yangleis** [comment]
> 关了吧。。。 Makefile本来就有必要依赖，手动安装的话自己解决相关依赖。 <img alt="image" width="495" src="https://user-images.githubusercontent.com/68652362/250260323-584c1d4d-418c-4ee2-9c9e-780f637f6f4e.png">

感谢回复，经您提醒，我查看了Makefile，发现确实里面都有定义依赖。

但我觉得自己编译安装的用户应该只是一部分，仍有很多用户都是像我一样，下载releases里构建好的ipk使用opkg进行安装，这样的话就会缺少依赖而不自知。

所以我认为在日志中进行提醒还是有必要的。既然缺少ipset和dnsmasq版本不正确都能提醒，那为什么不把这几个也加上呢。
