### ISSUE TITLE
无法添加xray/v2ray分流规则

### ISSUE THREAD

**Issue by roxsky** [xiaorouji/openwrt-passwall2#29]
![图片](https://user-images.githubusercontent.com/4097168/160085433-2bdbd7bb-fe28-44e2-9956-eb8e6c79d53d.png)
输入名字，点击添加后没有任何反应，好像passwall1也有这样的问题，我是使用firefox浏览器，edge浏览器也试了不行。

**Comment by xiaorouji** [comment]
固件问题
