### ISSUE TITLE
[Bug]: DNS泄露问题

### ISSUE THREAD

**Issue by Satisfy8375** [xiaorouji/openwrt-passwall2#300]
### 描述您遇到的bug

使用passwall2，节点用的自建vless协议，发现导入到openwrt的passwall2插件中，手机电脑测试会出现DNS泄露，同样的节点我在V2rayN客户端上开启全局或者绕过大陆模式就不会出现泄露，请问插件怎么配置才能防止DNS泄露呢

### 复现此Bug的步骤

测试DNS出现泄露

### 您想要实现的目的

防止DNS泄露

### 日志信息

无日志

### 截图
![QQ截图20230726133634](https://github.com/xiaorouji/openwrt-passwall2/assets/95027599/ce815e46-5150-45e7-b406-4bccec0ab76d)
_No response_

### 系统相关信息

passwall2

**Comment by etsam** [comment]
直连DNS 选自己的ISP的，远程选8.8.8.8 1.1.1.1都可以 用分流模式

**Comment by Satisfy8375** [comment]
> 直连DNS 选自己的ISP的，远程选8.8.8.8 1.1.1.1都可以 用分流模式
你看我这配置，一样漏
![QQ截图20230726133255](https://github.com/xiaorouji/openwrt-passwall2/assets/95027599/b8522597-c9b5-426a-8587-30233a8d7164)
![QQ截图20230726133356](https://github.com/xiaorouji/openwrt-passwall2/assets/95027599/69d338d3-0a28-4007-8391-78bb671cab2d)
![QQ截图20230726133634](https://github.com/xiaorouji/openwrt-passwall2/assets/95027599/58213fd2-77bb-4916-90a5-818d68eb3b47)

**Comment by Travel2Here** [comment]
你要是配了IP分流规则，在域名解析策略选了IPIfNonMatch or IPOnDemand的话肯定会泄露。
如果前面的域名规则没有match到需要代理的域名，就会优先用ISP的dns开始解析。
当然，即便是ASIS，也会漏，只是程度问题，除非所有DNS解析默认都用国外的，但弊端就是有可能国内网站也会解析到外面的服务器。

**Comment by Satisfy8375** [comment]
> 你要是配了IP分流规则，在域名解析策略选了IPIfNonMatch or IPOnDemand的话肯定会泄露。 如果前面的域名规则没有match到需要代理的域名，就会优先用ISP的dns开始解析。 当然，即便是ASIS，也会漏，只是程度问题，除非所有DNS解析默认都用国外的，但弊端就是有可能国内网站也会解析到外面的服务器。

听着有点复杂，其实我就是想达到V2rayN客户端的效果，目前我用V2rayN客户端，是可以完全阻止域名泄露的，只用passwall2插件的话是否支持这样的效果呢？
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/95027599/3135750a-b8ab-4263-a99d-90f379565cc7)

**Comment by etsam** [comment]
我的直连IP是指定的 没有选自动，别的设置跟你差不多，我没有设置代理游戏，别的多余的规则 我用不着的就删除了一部分，你可以这样设置，先把代理里面全部都关闭，然后一个一个开默认，一个一个测试。我目前测试是没有泄露的。V2RAYN确实可以做到不泄露。
对了 还有一个比较特殊的情况你可以参考排查一下，我另一台电脑，用V2RAYN也是显示泄露，不管怎么调试换版本都不行，甚至重装系统，最后发现安装了卡巴杀毒软件 里面有一个安全控制功能里的WEB控制，把这个关闭 就不泄露了。

**Comment by Travel2Here** [comment]
> > 你要是配了IP分流规则，在域名解析策略选了IPIfNonMatch or IPOnDemand的话肯定会泄露。 如果前面的域名规则没有match到需要代理的域名，就会优先用ISP的dns开始解析。 当然，即便是ASIS，也会漏，只是程度问题，除非所有DNS解析默认都用国外的，但弊端就是有可能国内网站也会解析到外面的服务器。
> 
> 听着有点复杂，其实我就是想达到V2rayN客户端的效果，目前我用V2rayN客户端，是可以完全阻止域名泄露的，只用passwall2插件的话是否支持这样的效果呢？ ![image](https://user-images.githubusercontent.com/95027599/256151753-3135750a-b8ab-4263-a99d-90f379565cc7.png)

V2rayN这个客户端我没用过，猜测是它全局dns都走的国外的，并且强制系统的代理也射到他上面了，就不会漏。
dns全用国外解析的缺点前面提过~
你把浏览器的安全DNS功能关闭，操作系统的dns地址写软路由的。效果（应该）就一样了~

**Comment by hululu1068** [comment]
@Satisfy8375 You sure didn't use "Sophie".
