### ISSUE TITLE
[Bug]: 访问控制里的代理设备无法FQ

### ISSUE THREAD

**Issue by Biercenter** [xiaorouji/openwrt-passwall2#304]
### 描述您遇到的bug

以前使用passwall2，主开关没开，只设置了访问控制里的几个设备可以FQ，一直都没问题，昨天更新之后无法使用了，重启之后也是几分钟后就打不开网页了。

### 复现此Bug的步骤

passwall2基础设置-主要-里的主开关关闭
访问控制-设置好局域网那些设备可以FQ并打访问控制里的主开关
几分钟后浏览网站提示找不到IP

### 您想要实现的目的

正常FQ

### 日志信息

路由器日志（命令行重启passwall2也会提示，多个设备会显示多条错误）：
Error: transport protocol mapping is only valid after transport protocol match
add rule inet fw4 PSW2_NAT ether saddr {XX:XX:XX:XX:XX:XX} ip daddr 198.18.0.0/16 counter redirect to :11201 comment "Proxy_Devices"
-------------------------------------------------------------------
2023-07-25 14:12:30: 删除相关防火墙规则完成。
2023-07-25 14:12:33: 清空并关闭相关程序和缓存完成。
2023-07-25 14:12:34: 分析 Socks 服务的节点配置...
2023-07-25 14:12:34:   - Socks节点：[分流总节点代理]，启动 0.0.0.0:1088
2023-07-25 14:12:34: 开始加载防火墙规则...
2023-07-25 14:12:34: 加入负载均衡的节点到nftset[passwall2_vpslist]直连完成
2023-07-25 14:12:34: 加入所有节点到nftset[passwall2_vpslist]直连完成
2023-07-25 14:12:34: 访问控制：
2023-07-25 14:12:35: 访问控制：
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用TCP节点[分流总节点代理] [全局代理](REDIRECT:11201)代理所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用UDP节点[分流总节点代理] [全局代理](TPROXY:11201)代理[0]除123外的所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用TCP节点[分流总节点代理] [全局代理](REDIRECT:11201)代理所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用UDP节点[分流总节点代理] [全局代理](TPROXY:11201)代理[0]除123外的所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用TCP节点[分流总节点代理] [全局代理](REDIRECT:11201)代理所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用UDP节点[分流总节点代理] [全局代理](TPROXY:11201)代理[0]除123外的所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用TCP节点[分流总节点代理] [全局代理](REDIRECT:11201)代理所有端口
2023-07-25 14:12:35:   - 备注【Proxy_Devices】，MAC【XX:XX:XX:XX:XX:XX】，使用UDP节点[分流总节点代理] [全局代理](TPROXY:11201)代理[0]除123外的所有端口
2023-07-25 14:12:35: 防火墙规则加载完成！
2023-07-25 14:12:35: 运行完成！

### 系统相关信息

passwall2 1.17-2

**Comment by xiaorouji** [comment]
试下最新的代码

**Comment by Biercenter** [comment]
> 试下最新的代码

还是一样，只要关闭主开关，刚开始没问题，过大概半小时至1小时后，访问控制里添加的几个可以代理的设备打开网页就会显示找不到IP

**Comment by Biercenter** [comment]
> 试下最新的代码
我日志模式开了debug还是只能显示基础信息吗？附上我的uci脚本，我一般是放在/etc/uci-defaults/zzzz-defaults文件里实现刷完固件自动设置完成后重启一次路由器。现在把uci set passwall2.@global[-1].node='myshunt'改成nil了再测试后看看效果。
`uci set passwall2.@global[-1].enabled='0'
uci set passwall2.@global[-1].node='myshunt'
uci set passwall2.@global[-1].localhost_proxy='0'
uci set passwall2.@global[-1].direct_dns_query_strategy='UseIPv4'
uci set passwall2.@global[-1].remote_fakedns='1'
uci set passwall2.@global_forwarding[-1].use_nft='0'
uci set passwall2.@global[-1].acl_enable='1'
uci set passwall2.myshunt=nodes
uci set passwall2.myshunt.remarks='分流总节点'
uci set passwall2.myshunt.type='Xray'
uci set passwall2.myshunt.protocol='_shunt'
uci del passwall2.myshunt.preproxy_enabled
uci set passwall2.myshunt.DirectGame='_direct'
uci set passwall2.myshunt.ProxyGame='_default'
uci set passwall2.myshunt.Direct='_direct'
uci set passwall2.myshunt.AD='nil'
uci set passwall2.myshunt.BT='_direct'
uci set passwall2.myshunt.Netflix='nil'
uci set passwall2.myshunt.OpenAI='nil'
uci set passwall2.myshunt.TVB='nil'
uci set passwall2.myshunt.Proxy='_default'
uci set passwall2.myshunt.China='_direct'
uci set passwall2.myshunt.QUIC='_blackhole'
uci set passwall2.myshunt.UDP='nil'
uci set passwall2.myshunt.domainStrategy='IPOnDemand'
uci set passwall2.myshunt.domainMatcher='hybrid'
uci set passwall2.myshunt.default_node='_direct'
uci set passwall2.bwgproxy=nodes
uci set passwall2.bwgproxy.remarks='分流总节点代理'
uci set passwall2.bwgproxy.type='Xray'
uci set passwall2.bwgproxy.protocol='_shunt'
uci set passwall2.bwgproxy.DirectGame='_direct'
uci del passwall2.bwgproxy.preproxy_enabled
uci set passwall2.bwgproxy.ProxyGame='_default'
uci set passwall2.bwgproxy.Direct='_direct'
uci set passwall2.bwgproxy.AD='nil'
uci set passwall2.bwgproxy.BT='_direct'
uci set passwall2.bwgproxy.Netflix='nil'
uci set passwall2.bwgproxy.OpenAI='nil'
uci set passwall2.bwgproxy.TVB='nil'
uci set passwall2.bwgproxy.Proxy='_default'
uci set passwall2.bwgproxy.China='_direct'
uci set passwall2.bwgproxy.QUIC='_blackhole'
uci set passwall2.bwgproxy.UDP='nil'
uci set passwall2.bwgproxy.default_node='bwgnaive'
uci set passwall2.bwgproxy.domainStrategy='IPOnDemand'
uci set passwall2.bwgproxy.domainMatcher='hybrid'
uci set passwall2.bwgnaive=nodes
uci set passwall2.bwgnaive.remarks='搬瓦工'
uci set passwall2.bwgnaive.type='Naiveproxy'
uci set passwall2.bwgnaive.protocol='https'
uci set passwall2.bwgnaive.address='www.xxxxxx.cf'
uci set passwall2.bwgnaive.port='443'
uci set passwall2.bwgnaive.username='xxxxxxx'
uci set passwall2.bwgnaive.password='xxxxxxxxxxxx'
uci add passwall2 acl_rule
uci set passwall2.@acl_rule[-1].enabled='1'
uci set passwall2.@acl_rule[-1].remarks='Proxy_devices'
uci set passwall2.@acl_rule[-1].sources='XX:XX:XX:XX:XX:XX XX:XX:XX:XX:XX:XX XX:XX:XX:XX:XX:XX XX:XX:XX:XX:XX:XX'
uci set passwall2.@acl_rule[-1].tcp_no_redir_ports='default'
uci set passwall2.@acl_rule[-1].udp_no_redir_ports='123'
uci set passwall2.@acl_rule[-1].tcp_redir_ports='default'
uci set passwall2.@acl_rule[-1].udp_redir_ports='default'
uci set passwall2.@acl_rule[-1].node='bwgproxy'
uci set passwall2.@acl_rule[-1].direct_dns_protocol='auto'
uci set passwall2.@acl_rule[-1].direct_dns_query_strategy='UseIPv4'
uci set passwall2.@acl_rule[-1].dns_hosts='cloudflare-dns.com 1.1.1.1
dns.google.com 8.8.8.8'
uci set passwall2.@acl_rule[-1].remote_dns_protocol='tcp'
uci set passwall2.@acl_rule[-1].remote_dns='1.1.1.1'
uci set passwall2.@acl_rule[-1].remote_fakedns='1'
uci set passwall2.@acl_rule[-1].remote_dns_query_strategy='UseIPv4'
uci commit passwall2`

**Comment by Biercenter** [comment]
主开关里的节点选择关闭nil还是一样，大概1-2小时后还是会无法打开网页，显示找不到这个网站的IP，但是有部分之前打开过的还是可以正常访问的，就算是需要代理的网站。

**Comment by Biercenter** [comment]
完全相同的配置，打开主开关就一切正常，几个星期都正常
uci set passwall2.@global[-1].enabled='1'

**Comment by Biercenter** [comment]
经过测试好像是cf的1.1.1.1的问题，我改成
uci set passwall2.@global[-1].node='nil'
uci set passwall2.@acl_rule[-1].remote_dns='8.8.8.8'
之后1天了没出现问题，还在测试当中

**Comment by Biercenter** [comment]
问题依然存在，用了最新版1.19.3和1.19.4还是会出现上面的bug，openwrt 22.03.5 imagebuilder，sdk 22.03.5 编译
有时可能几十分钟就会出现bug，有时需要几个小时。

**Comment by xiaorouji** [comment]
無法復現。
