### ISSUE TITLE
[Feature Request]:  访问控制主开关不能随passwall关闭而关闭

### ISSUE THREAD

**Issue by doumeki** [xiaorouji/openwrt-passwall2#309]
### 描述你想要的新功能

passwall开关与访问控制主开关同步

### 描述你想要的解决方案

当设置了访问控制来仅允许少量的机器有权限FQ后。如果不用了关闭psw开关，这时访问控制主开关并不能同时关闭，导致上网失败.

**Comment by Biercenter** [comment]
不知道是不是你说的问题，我之前不开主开关，只开访问控制开关正常使用。新版本不开主开关的话过几分钟后就会出现网站打不开，必须新建一个分流直连规则给主开关并启动，后面的访问控制设置才正常

**Comment by doumeki** [comment]
> 不知道是不是你说的问题，我之前不开主开关，只开访问控制开关正常使用。新版本不开主开关的话过几分钟后就会出现网站打不开，必须新建一个分流直连规则给主开关并启动，后面的访问控制设置才正常

逻辑上不确定，你说的是PSW启动后怎么上网问题。而我主要是想说怎么关闭的问题。

**Comment by jelly0925** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/3022023/5ca7a0bd-1ae4-4205-abe0-cff93389f8d8)
我b也遇到相同的问题了，运行一段时间开关就不起作用并且路由器CPU负载过高。只能强制重启软路由

**Comment by jelly0925** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/3022023/71b4fd14-8466-4c80-8d5e-f52084c54821)
主开关关闭了，可是passwall2还显示运行状态

**Comment by pangfeng161** [comment]
偶然发现 如果规则管理里面 开启规则自动更新就会导致各种问题

**Comment by xiaorouji** [comment]
访问控制的主开关和首页的主开关是分开独立的
