### ISSUE TITLE
Apple设备 APNs推送通知

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall2#31]
#### 怀疑是不是 passwall2 的DNS查询策略是 UseIPv4 优先、或者仅查询UseIPv4，导致防火墙里面已经丢弃了这个IP段、passwall2仍会查询IPv4.

**Comment by yunxi993** [comment]
https://github.com/XTLS/Xray-core/issues/774#issuecomment-947985204
看到这个相关问题.

**Comment by yunxi993** [comment]
@xiaorouji 测试出来了，我把流量嗅探关闭推送就正常了.
![image](https://user-images.githubusercontent.com/59167936/160394787-99ccb30e-b6fb-48d0-933b-00add83205fc.png)
可是下面注解说，使用分流必须开启嗅探，否则分流无效.
passwall的流量嗅探有开启.

还有passwall2的本地DNS查询是劫持53端口吗？

**Comment by mirthlesslk** [comment]
流量嗅探是有问题的，我和朋友联机，只要打开这个网络直接抽风了，关了什么事都没有

**Comment by yunxi993** [comment]
> 流量嗅探是有问题的，我和朋友联机，只要打开这个网络直接抽风了，关了什么事都没有

确实很怪异，还发现如果关闭嗅探、观看YouTube如果可以正常播放至少转圈加载十圈以上、要么就一直转圈加载（无论分辨率是高是低）、twitch直播也慢，反之就和passwall一样、4K60FPS视频基本秒开.

**Comment by xiaorouji** [comment]
youtube的问题，可以尝试新建一个分流规则，把QUIC给黑洞了。

**Comment by mirthlesslk** [comment]
> youtube的问题，可以尝试新建一个分流规则，把QUIC给黑洞了。

作者大大，能不能问一下分流选项里面黑洞实现的是什么功能，没有太理解这个选项的意思

**Comment by xiaorouji** [comment]
更新最新源码试试，亲测屏蔽QUIC后youtu秒开

**Comment by yunxi993** [comment]
> 更新最新源码试试，亲测屏蔽QUIC后youtu秒开

YouTube正常了
不过，又发现在 Direct 里面添加走直连的域名好像并没有生效，例如：
wallhaven.cc
![image](https://user-images.githubusercontent.com/59167936/161233001-93e09e6a-78f6-4815-85c7-71897f6bdaeb.png)

88hd.tv
![image](https://user-images.githubusercontent.com/59167936/161233103-1e9f9ba9-8f91-406d-9206-32066f853182.png)

确定这俩网站是可以直连的.
重启passwall2、完全关闭浏览器并清除DNS缓存，仍然没有根据规则连接.

**Comment by xiaorouji** [comment]
domainStrategy用IPOnDemand
而且估计可能你把流量嗅探给关了导致

**Comment by yunxi993** [comment]
> domainStrategy用IPOnDemand 而且估计可能你把流量嗅探给关了导致

的确是流量嗅探的问题,开启流量嗅探 domainStrategy 用AsIs也是正常的。
不过还是老问题 passwall2 只要开启流量嗅探 Apple设备便无法接收App推送通知.

还有目前 Cloud flare的DOH问题、会频繁报错：
[Error] app/dns: failed to retrieve response for api.day.app. > Post "https://cloudflare-dns.com/dns-query": context canceled
Google的DOH没有报错

改成如下是没有问题的
https://1dot1dot1dot1.cloudflare-dns.com/dns-query

**Comment by yunxi993** [comment]
> > youtube的问题，可以尝试新建一个分流规则，把QUIC给黑洞了。
> 
> 作者大大，能不能问一下分流选项里面黑洞实现的是什么功能，没有太理解这个选项的意思

丢弃 屏蔽的意思.

**Comment by yunxi993** [comment]
@xiaorouji 
![image](https://user-images.githubusercontent.com/59167936/161416897-447e48d8-7dc3-4ae1-b4ce-47fdf72551b5.png)
![image](https://user-images.githubusercontent.com/59167936/161416920-135a904b-7319-48b4-84cc-4e6fb221d158.png)
根据反复测试发现：
第一种情况，不开启 “流量嗅探 (V2ray/Xray)” 或开启 “流量嗅探 (V2ray/Xray)” 同时开启 “流量嗅探只供路由使用 (Xray)” 通知推送正常，尽管我已经在防火墙丢弃该IP段与端口，但如上图 仍然是IPv4连接，无IPv6连接。

第二种情况，仅开启 “流量嗅探 (V2ray/Xray)”无法正常接收通知推送，删除防火墙丢弃规则、断开WIFI连接、重启手机，路由器重启，在手机连接WIFI的几秒钟内、在连接里面可以看见17.57.145.*、但是几秒钟后连接就没了，无IPv6连接。

使用passwall2无论使用什么方法设置、无论是否使用防火墙丢弃规则，始终没看见Apple APNs推送通知服务的IPv6连接。

**Comment by yunxi993** [comment]
`      "settings": {
        "domainStrategy": "UseIPv4"`
会不会和 global.json 生成的配置有关.

**Comment by xiaorouji** [comment]
要代理IPv6要启用IPv6透明代理

**Comment by yunxi993** [comment]
> 要代理IPv6要启用IPv6透明代理

![image](https://user-images.githubusercontent.com/59167936/161528578-b5eb245d-feb9-470b-b7d8-2901457def48.png)
一直有开启 IPv6透明代理

**Comment by yunxi993** [comment]
可能不是passwall2的问题，使用v2rayA的routingA规则分流同样无法接收通知.

**Comment by xiaorouji** [comment]
试下把5223端口走直连或者高级设置里面的TCP不转发端口试试？

**Comment by yunxi993** [comment]
> 试下把5223端口走直连或者高级设置里面的TCP不转发端口试试？

尝试了，没有用.
![image](https://user-images.githubusercontent.com/59167936/161972502-c608ced3-724a-45b4-8853-116203499dea.png)
![image](https://user-images.githubusercontent.com/59167936/161972533-ca98b363-e0b5-4f94-aa10-5b5f5dfcdf66.png)


![image](https://user-images.githubusercontent.com/59167936/161971905-c7c8d669-6ec5-4e77-a122-dc3c06e157f9.png)
日志里面显示有连接（之前就是这样）但实际上在实时连接里面是没有这个连接的，只在设备连接WIFI几秒钟内有连接、然后没无了．

**Comment by xiaorouji** [comment]
我好不容易找到了一台IOS设备来做测试
把 `courier.push.apple.com` 加入到 `不进行流量嗅探的域名列表` 里面貌似是可以的

**Comment by xiaorouji** [comment]
Tproxy+TCP不转发端口原来有BUG，怪不得不行

**Comment by xiaorouji** [comment]
更新最新源码，用TCP不转发端口 5223，比较直接了。

**Comment by xiaorouji** [comment]
防火墙丢弃失效的原因大概是规则生成在passwall2后面了，前面已经被passwall处理了。

**Comment by yunxi993** [comment]
> 防火墙丢弃失效的原因大概是规则生成在passwall2后面了，前面已经被passwall处理了。

好的，使用新的源码编译.

那这该怎么办，我把 passwall remove了、也重启过，这样还是不行吗？

**Comment by yunxi993** [comment]
> 防火墙丢弃失效的原因大概是规则生成在passwall2后面了，前面已经被passwall2处理了。

这个会优化吗？
现在是直接TCP不转发5223端口，但IPv6也是5223端口，并且仅丢弃5223端口话、APNs在5223端口不可用会使用443端口连接，最好的方式还是 丢弃IP段的端口，不使用一刀切的方式.
