### ISSUE TITLE
[Bug]: Passwall 4.67-1版本升级包缺少2个依赖包

### ISSUE THREAD

**Issue by zhang-xinya** [xiaorouji/openwrt-passwall2#316]
### 描述您遇到的bug

在x86的openwrt上面更新完了Passwall 4.67-1版本的升级包，启动后日志显示 
iptables透明代理基础依赖 iptables-mod-socket 未安装...
iptables透明代理基础依赖 iptables-mod-iprange 未安装...
不知道能不能单独做这两个的ipk安装包

### 复现此Bug的步骤

系统日志

### 您想要实现的目的

增加 iptables-mod-socket 和 iptables-mod-iprange 基础依赖包

### 日志信息

 iptables透明代理基础依赖 iptables-mod-socket 未安装...
 iptables透明代理基础依赖 iptables-mod-iprange 未安装...

### 系统相关信息

Passwall 4.67-1版本

**Comment by dbsjacky** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/39028647/7ef8bc73-6121-4d52-b1dd-cd2c8c2feee1)
