### ISSUE TITLE
大佬,能不能把passwall的 规则列表功能,加到passwall2里面来?

### ISSUE THREAD

**Issue by jt8823** [xiaorouji/openwrt-passwall2#320]
### 描述你想要的新功能

passwall2怎么设置指定IP或mac直连或者绕过passwall2核心

### 描述你想要的解决方案

passwall2怎么设置指定IP或mac直连或者绕过passwall2核心

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/issues/273
