### ISSUE TITLE
[Feature Request]: Socks nodes support 

### ISSUE THREAD

**Issue by 662** [xiaorouji/openwrt-passwall2#323]
### 描述你想要的新功能

Socks nodes support 

### 描述你想要的解决方案

Passwall2 > Node List > Add > Type > Socks5

**Comment by snomile** [comment]
可以通过xray/v2ray插件支持socks5

<img width="445" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/4364681/ffd904fa-d2af-42f0-970a-d47a060aeb1f">
