### ISSUE TITLE
[Bug]: 最新版本的直连DNS设置只有自动可以选择

### ISSUE THREAD

**Issue by smdx** [xiaorouji/openwrt-passwall2#324]
### 描述您遇到的bug

最新版本的直连DNS设置只有自动可以选择

### 复现此Bug的步骤

PW2界面DNS菜单
点击直连DNS选项

### 您想要实现的目的

多个设置项

### 日志信息

没有

### 截图

![Screenshot-2023-08-14_090850](https://github.com/xiaorouji/openwrt-passwall2/assets/9279217/106f85b6-b797-449a-afca-5c1c2419976e)

### 系统相关信息

passwall2 1.18-1

**Comment by fxvbv** [comment]
我还以为是编译的时候漏选了什么选项。
