### ISSUE TITLE
[Bug]: Apple分流遇到的问题

### ISSUE THREAD

**Issue by devchenli** [xiaorouji/openwrt-passwall2#325]
### 描述您遇到的bug

本人用的Mac系统，在打开Appstore 的时候发现比较缓慢， 于是查看日志，发现在默认的passwall2规则下，Appstore，icloud均走的默认代理，

由于平时不开代理appstore，icloud等都正常使用，于是在Direct规则里加入geosite:apple,想让apple规则下的请求都走直连，但是发现这样反而导致appstore无法打开，查看日志确实是走了直连，但是无法打开appstore。
目前怀疑是分流中使用DNS不同导致的，也就是说，把apple相关的域名加入直连规则后，请求的dns并不是国内直连，而是国外dns。所以返回的请求也是匹配国外的，这样反而导致国内不能访问。
猜测：像apple这种网站，国内是有很多cdn加速的，如果用国内dns请求，就会匹配这些加速，所以正常访问，如果用国外dns请求，这些加速反而不能用了。

### 复现此Bug的步骤

1、默认passwall2规则下。
2、打开Appstore，观察日志，发现走代理。
3、在直连规则中加入geosite:apple，让其走直连。
4、打开appstore，发现无法连接。

### 您想要实现的目的

想法：对于国外域名想走直连的，应该给出选择使用国内dns还是国外dns请求的选项。
改善方法：对于分流的每项中，添加一个可以选择dns的选项，这样可以把想走国内的国外域名，单独列成一条规则，并控制其dns请求方式。

### 日志信息

2023/08/14 13:43:05 [Info] [648146207] app/dispatcher: sniffed domain: p212-contacts.icloud.com.cn
2023/08/14 13:43:05 [Info] [648146207] app/dispatcher: taking detour [default] for [tcp:p212-contacts.icloud.com.cn:443]

2023/08/14 13:46:51 [Info] [1805755722] app/dispatcher: sniffed domain: bag.itunes.apple.com
2023/08/14 13:46:51 [Info] app/dns: UDP:127.0.0.1:15356 got answer: bag.itunes.apple.com. TypeAAAA -> [] 439.179µs
2023/08/14 13:46:51 [Info] [292250292] proxy/socks: TCP Connect request to tcp:1.1.1.1:53
2023/08/14 13:46:51 [Info] [292250292] app/dispatcher: taking detour [default] for [tcp:1.1.1.1:53]

### 截图

<img width="898" alt="截屏2023-08-15 00 16 35" src="https://github.com/xiaorouji/openwrt-passwall2/assets/46481943/eb472a8d-f923-4e27-bae4-f1f0be1a9c86">

<img width="621" alt="截屏2023-08-14 23 58 08" src="https://github.com/xiaorouji/openwrt-passwall2/assets/46481943/2fec9419-5d83-4f0b-ace8-d74d0f0a4637">

### 系统相关信息

passwall 1.17-2

**Comment by kid-oh** [comment]
我也感受到了确实是会有一点点慢，不过似乎也算是规则不全的问题吧，因为单纯只是用geoip和geosite里的规则的话，和iPhone上其他代理软件所引用的规则还是有差距的

**Comment by Travel2Here** [comment]
加到直连里没问题的，你应该清空设备缓存。比如开关一次wifi。。。
