### ISSUE TITLE
[Bug]: 版本 1.18-1 中，直连 DNS 协议中缺失 TCP UDP DoH 选项

### ISSUE THREAD

**Issue by Zeezorn** [xiaorouji/openwrt-passwall2#329]
### 描述您遇到的bug

更新到 1.18-1 版本后，发现 DNS 模块中，直连 DNS 协议选项下拉框缺失 TCP UDP DoH 选项，
由于本地局域网中自建 ADGuard Home 为国内 DNS 解析，因此缺失选项导致国内 DNS 请求无法发送到本地 ADGuard Home 进行处理。

### 复现此Bug的步骤

1. 选择菜单：passwall2 -- DNS -- 直连 DNS 协议下拉框 -- 缺失 “TCP” “UDP” “DoH” 选项，只剩下 “自动” 。

### 您想要实现的目的

在下一版本中修复缺失的选项 （ 版本 1.17-1 没有缺失  ）

### 日志信息

无日志

### 截图

![doc_2023-08-18_11-18-25](https://github.com/xiaorouji/openwrt-passwall2/assets/31385055/0095ef10-fe0c-42c0-a193-804e64ea88b2)

### 系统相关信息

- Passwall 版本 1.18-1
- OpenWrt 版本 22.03.5
- 目标平台 x86/64
- 内核版本 5.10.176

**Comment by xiaorouji** [comment]
最新代码已经不建议配置直连DNS，若要自定义DNS，请配置dnsmasq上游DNS。

**Comment by smdx** [comment]
> 最新代码已经不建议配置直连DNS，若要自定义DNS，请配置dnsmasq上游DNS。

大佬你好，不能配置直连DNS的话如果配置dnsmasq上游DNS（smartdns端口6053）在passwall执行清空 IPSET
等设置后smartdns就会失效（不知道是不是防火墙规则被清除了），设置smartdns端口设置为53的话passwall显示国内dns为wan获取的运营商dns，请问如果smartdns端口设置为53怎么把passwall指向smartdns？谢谢

**Comment by Zeezorn** [comment]
> 最新代码已经不建议配置直连DNS，若要自定义DNS，请配置dnsmasq上游DNS。

感谢大佬回复。

另外有2个问题没有弄明白：

1. 在版本 1.18-1 取消配置直连 DNS 后，应该如何理解该版本的 “自动” 模式，默认是走的是 UDP 还是 DoH 还是 TCP ，以及他们自动会走哪些 DNS 服务器？

2. 如您所说，在 1.18-1 版本中，配置 dnsmaq 中的自定义 DNS 转发，经过测试，会造成 DNS 泄露，其原因也不难理解，是 dnsmaq 接管了所有 DNS 的请求，导致 DNS 国内外分流失效。

总体来说，在 1.18-1 版本取消配置直连 DNS 之后，似乎对自建 DNS 服务器的用户可能更不易配置了，方便的话希望大佬科普下不建议配置直连 DNS 的具体原因。

再次感谢，盼复。

**Comment by fxvbv** [comment]
> > 最新代码已经不建议配置直连DNS，若要自定义DNS，请配置dnsmasq上游DNS。
> 
> 感谢大佬回复。
> 
> 另外有2个问题没有弄明白：
> 
> 1. 在版本 1.18-1 取消配置直连 DNS 后，应该如何理解该版本的 “自动” 模式，默认是走的是 UDP 还是 DoH 还是 TCP ，以及他们自动会走哪些 DNS 服务器？
> 2. 如您所说，在 1.18-1 版本中，配置 dnsmaq 中的自定义 DNS 转发，经过测试，会造成 DNS 泄露，其原因也不难理解，是 dnsmaq 接管了所有 DNS 的请求，导致 DNS 国内外分流失效。
> 
> 总体来说，在 1.18-1 版本取消配置直连 DNS 之后，似乎对自建 DNS 服务器的用户可能更不易配置了，方便的话希望大佬科普下不建议配置直连 DNS 的具体原因。
> 
> 再次感谢，盼复。

测试了一下auto默认使用wan口下发的dns，旁路由用的则是读取当前设备本地dns，如果设置某个服务作为dnsmasq上游则是以这个服务的127.0.0.1:工作端口的格式。如果想用原来一样的效果，可以把dnsmasq对br-lan区域不工作，具体的做法是网络---dhcp/dns---基本设置----非全部地址勾选----排除接口填写br-lan，这样dnsmasq就不会对lan域工作。把国内组的插件（不能是adguard）工作模式勾选作为dnsmasq上游，国外组像原来一样设置。最后使用adguard dns只填写127.0.0.1:15353，工作模式改成重定向53端口至adguardhome。当然这样做53端口的劫持也就无效了，不清楚为什么查询其他dns重定向到53的数据被发送到对br-lan无效的dnsmasq而不是adguardhome。但是依然可以用无效的服务避免某些移动设备自带114dns查询（也就相当于客户端不用本地dns将无法从53端口查询解析）。

**Comment by Zeezorn** [comment]
> 

感谢解答。

我也测试了 1.18-1 的直连自动模式，发现很奇怪的一点。

在 WAN 口中不勾选自动获取 DNS 服务器，也不手动指定其他任何 DNS 服务器的前提下，PW2 的直连自动模式依然可以正常解析国内的域名。

照理说此时本地解析国内 DNS 的服务器已经不存在，在此环境下，国内网站应该是打不开的，国外网站是可以正常解析的。因此现在还不是很明白 1.18-1 版本中的直连自动模式使用了哪个 DNS 服务器，以及使用了哪种协议（ UDP TCP DoH）？

所以当 1.18-1 版本中只保留直连自动模式之后，想要使用直连自定义服务器这个问题似乎变得很复杂。

因为我尝试了你所说的配置，也存在 DNS 泄露的问题，似乎所有的 DNS 解析都会先走过一遍国内 DNS 解析，因此造成了 DNS 泄露。

我现在停留在了 1.17-2 版本，在此版本中，我可以在 PW2 中手动指定国内和国外的 DNS 都使用 DoH 协议，配置非常清晰简洁，而且没有遇到过 DNS 泄露的问题。

**Comment by xiaorouji** [comment]
自动的逻辑是：
优先使用dnsmasq的上游DNS（如果有），如果没有就再去获取WAN的DNS，如果还是没有，就用119.29.29.29（代码写死的）

**Comment by Zeezorn** [comment]
> 自动的逻辑是： 优先使用dnsmasq的上游DNS（如果有），如果没有就再去获取WAN的DNS，如果还是没有，就用119.29.29.29（代码写死的）

谢谢解答

**Comment by tujj99** [comment]
> > 测试了一下auto默认使用wan口下发的dns，旁路由用的则是读取当前设备本地dns，如果设置某个服务作为dnsmasq上游则是以这个服务的127.0.0.1:工作端口的格式。如果想用原来一样的效果，可以把dnsmasq对br-lan区域不工作，具体的做法是网络---dhcp/dns---基本设置----非全部地址勾选----排除接口填写br-lan，这样dnsmasq就不会对lan域工作。把国内组的插件（不能是adguard）工作模式勾选作为dnsmasq上游，国外组像原来一样设置。最后使用adguard dns只填写127.0.0.1:15353，工作模式改成重定向53端口至adguardhome。当然这样做53端口的劫持也就无效了，不清楚为什么查询其他dns重定向到53的数据被发送到对br-lan无效的dnsmasq而不是adguardhome。但是依然可以用无效的服务避免某些移动设备自带114dns查询（也就相当于客户端不用本地dns将无法从53端口查询解析）。
> 
> 感谢解答。 @fxvbv
> 
> 我也测试了 1.18-1 的直连自动模式，发现很奇怪的一点。
> 
> 在 WAN 口中不勾选自动获取 DNS 服务器，也不手动指定其他任何 DNS 服务器的前提下，PW2 的直连自动模式依然可以正常解析国内的域名。
> 
> 照理说此时本地解析国内 DNS 的服务器已经不存在，在此环境下，国内网站应该是打不开的，国外网站是可以正常解析的。因此现在还不是很明白 1.18-1 版本中的直连自动模式使用了哪个 DNS 服务器，以及使用了哪种协议（ UDP TCP DoH）？
> 
> 所以当 1.18-1 版本中只保留直连自动模式之后，想要使用直连自定义服务器这个问题似乎变得很复杂。
> 
> 因为我尝试了你所说的配置，也存在 DNS 泄露的问题，似乎所有的 DNS 解析都会先走过一遍国内 DNS 解析，因此造成了 DNS 泄露。
> 
> 我现在停留在了 1.17-2 版本，在此版本中，我可以在 PW2 中手动指定国内和国外的 DNS 都使用 DoH 协议，配置非常清晰简洁，而且没有遇到过 DNS 泄露的问题。
> 
> 个人还是希望能保留 PW2 中直连手动配置直连 DNS 的 UDP TCP DoH @@选项，因为这些配置非常简洁易懂，而且配置起来不容易出错，不知大佬是否有意向加回这些选项呢？@xiaorouji
> 
> 再次感谢！

确实1.17-2的本地DNS要好用很多，逻辑也很好理解，期待@xiaorouji大佬能加回这些功能！
