### ISSUE TITLE
[Bug]: 直连dns自定义为ipv6时， 后端配置文件写入错误

### ISSUE THREAD

**Issue by junx964** [xiaorouji/openwrt-passwall2#330]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/68261800/f3e08c98-8282-46f4-8e72-3c92d9c74aeb)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/68261800/0229f1eb-bb25-4fb1-9133-ba9189a8a980)

### 复现此Bug的步骤

在直连dns， 自定义为一个ipv6地址的dns

### 您想要实现的目的

可以使用ipv6 dns解析域名

### 日志信息

这问题很明显了，应该不需要日志了吧

### 系统相关信息

暂时没找到哪里看版本， 在2023.8.17 下午18点前update更新并编译的

**Comment by junx964** [comment]
@xiaorouji    大佬看一下呗

**Comment by xiaorouji** [comment]
最新代码已经不建议配置直连DNS，若要自定义DNS，请配置dnsmasq上游DNS。
