### ISSUE TITLE
[Feature Request]: 1.18以后不能指定DNS的话如何配合smartdns呢？

### ISSUE THREAD

**Issue by xyl94k** [xiaorouji/openwrt-passwall2#333]
### 描述你想要的新功能

是将smartdns的国内组端口改为53吗？

### 描述你想要的解决方案

1

**Comment by chenyajunai** [comment]
我还是喜欢之前的在passwall2里面可以设置国内 DNS 协议，现在虽然用上游，但是经常国外也会走上游了，只能点击清空 IPSET后恢复，然后不知道啥时候又那样了，之前在passwall2里面可以设置国内 DNS 协议，看日志都是各走各的
