### ISSUE TITLE
[Bug]: 纯 nft 模式下，DNS异常

### ISSUE THREAD

**Issue by pierre-primary** [xiaorouji/openwrt-passwall2#340]
### 描述您遇到的bug

1. 使用过程中发现 passwall2 必须之 dnsmasq 之后启动，不然DNS没法正常工作。passwall2 延迟 60s 可以解决问题。但如果其它一些原因自动重启了 dnsmasq ，DNS就蹦了。
2. passwall2 启动一段时间就会出问题。明明选择的防火墙工具是 NFT，刚开始 配置也是正常的如下：
```bash
# /tmp/etc/passwall2/dnsmasq_global_direct.conf
port=15355
server=127.0.0.1#15354
no-poll
no-resolv
cache-size=0
dns-forward-max=1000
nftset=4#inet#fw4#passwall2_whitelist,6#inet#fw4#passwall2_whitelist6
```
一段时间后就变成了 ipset
```bash
# /tmp/etc/passwall2/dnsmasq_global_direct.conf
port=15355
server=127.0.0.1#15354
no-poll
no-resolv
cache-size=0
dns-forward-max=1000
ipset=passwall2_whitelist,passwall2_whitelist6
```

### 复现此Bug的步骤

编译一个纯nft固件，就能复现

### 您想要实现的目的

支持纯 nft 

### 日志信息

因为是纯 nft 模式，不支持 ipset， 导致dnsmasq报错：
```log
Wed Aug 30 16:11:01 2023 daemon.crit dnsmasq[1126]: recompile with HAVE_IPSET defined to enable ipset directives at line 7 of /tmp/etc/passwall2/dnsmasq_global_direct.conf
Wed Aug 30 16:11:01 2023 daemon.crit dnsmasq[1126]: FAILED to start up
```

### 系统相关信息

- 自编译 ImmortalWrt 23.05 固件

**Comment by xiaorouji** [comment]
是否没有使用最新的源码并且是使用了自动切换的逻辑？

**Comment by pierre-primary** [comment]
> 是否没有使用最新的源码并且是使用了自动切换的逻辑？

是的使用了自动切换功能。包是上个 月编译的，我翻了tag和issues也没看到相关内容以为问题还在。
我先关闭该问题，等有空了重新打个包试一下。

**Comment by pierre-primary** [comment]
> 提问，用passwall绕过大陆模式，安卓谷歌商店应用可以安装更新，使用passwall2分流节点下则无法安装更新，切换到服务器节点就可以，是因为规则没有涵盖吗？
在代理规则中添加以下域名组：
```
geosite:google@cn
```
