### ISSUE TITLE
[Bug]: 1-19.5 iptables基础依赖

### ISSUE THREAD

**Issue by whatpig** [xiaorouji/openwrt-passwall2#343]
### 描述您遇到的bug

在日志里看到iptables基础依赖未安装，但是我明明有啊！

### 复现此Bug的步骤

如图

### 您想要实现的目的

如图

### 日志信息

2023-09-02 09:31:00: iptables透明代理基础依赖 iptables-mod-tproxy 未安装...
2023-09-02 09:31:00: iptables透明代理基础依赖 iptables-mod-socket 未安装...
2023-09-02 09:31:00: iptables透明代理基础依赖 iptables-mod-iprange 未安装...
2023-09-02 09:31:00: iptables透明代理基础依赖 iptables-mod-conntrack-extra 未安装...
2023-09-02 09:31:00: iptables透明代理基础依赖 kmod-ipt-nat 未安装...

### 截图

<img width="941" alt="截屏2023-09-02 10 08 41" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/6b701d08-d3e7-498d-a6c5-208dfd1c81ff">

<img width="1563" alt="截屏2023-09-02 10 09 05" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/b9a4906c-db89-4465-9a38-8076e72c4cf8">

<img width="1583" alt="截屏2023-09-02 10 09 34" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/d562345f-a9bc-4658-8825-f292674f3958">

<img width="1474" alt="截屏2023-09-02 10 09 47" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/dacae7e7-1669-471b-b9d0-ddf1b183ab52">

<img width="1732" alt="截屏2023-09-02 10 09 59" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/c77513c2-2ee9-4bea-b6d2-9129e8ed24db">

<img width="1602" alt="截屏2023-09-02 10 10 11" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/d82b609b-53dc-4823-b9d3-638004f98618">

### 系统相关信息

1.19-5

**Comment by Travel2Here** [comment]
同上，包括pw1也如此。我始终不能正常使用，还是只能用xray主分流~一旦切成singbox就不通。
已经是紧跟脚步的最新版1.20-7了。
