### ISSUE TITLE
[Bug]: 规则版本页面 手动更新没有翻译

### ISSUE THREAD

**Issue by etsam** [xiaorouji/openwrt-passwall2#349]
### 描述您遇到的bug

发现最近几个版本的“规则版本”页面内 “手动更新”选项没有翻译

### 复现此Bug的步骤

无

### 您想要实现的目的

请在passwall2.po文件内添加对应中文翻译
msgid "Manually update"
msgstr "手动更新"

### 日志信息

无

### 截图

![11111](https://github.com/xiaorouji/openwrt-passwall2/assets/24689501/4a87e84d-08b3-4764-9518-3279a8f07b32)

### 系统相关信息

版本 1.19.6

**Comment by Travel2Here** [comment]
应该是你的问题，我一直正常。可重装语言文件覆盖一下。
<img width="654" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/99887507/93cc5216-7931-46c4-b114-d0c6d5f82a25">

**Comment by etsam** [comment]
我只单独编译了passwall2  如果你还编译了passwall 那就是正常的，因为luci-app-passwall的po文件里面有翻译的代码，我看了luci-app-passwall2的passwall2.po文件，里面确实是没有这段代码的。
msgid "Manually update"
msgstr "手动更新"

**Comment by xiaorouji** [comment]
感谢反馈
