### ISSUE TITLE
[Bug]: passwall2无故退出，手动更新一次规则geoip geosite后才正常

### ISSUE THREAD

**Issue by swxk521** [xiaorouji/openwrt-passwall2#350]
### 描述您遇到的bug

passwall2一直无故退出，手动更新一次规则geoip geosite后才正常，使用的lean的x86最新固件。

### 复现此Bug的步骤

同上

### 您想要实现的目的

同上

### 日志信息

同上

### 系统相关信息

同上

**Comment by xiaorouji** [comment]
可能是 分流规则使用的geoip/geosite数据不存在
