### ISSUE TITLE
[Bug]: 一堆 ERROR [1234567891 00ms] inbound/tproxy[tproxy]: process connection from 192.168.10.X:port: name error

### ISSUE THREAD

**Issue by ghost** [xiaorouji/openwrt-passwall2#353]
### 描述您遇到的bug

不影响使用，问问怎么回事

### 复现此Bug的步骤

新建sing-box分流总节点，规则照抄xray，启用主开关，查看日志，出现一堆ERROR [1234567891 00ms] inbound/tproxy[tproxy]: process connection from 192.168.10.X:port: name error

默认节点是TUIC，其他设置页面请看下面截图

### 您想要实现的目的

如是bug，请修复
如非bug，请无视

### 日志信息

2023-09-06 02:21:08: 执行启动延时 60 秒后再启动!
2023-09-06 02:22:13: 清空并关闭相关程序和缓存完成。
2023-09-06 02:22:14: 开启实验性IPv6透明代理(TProxy)，请确认您的节点及类型支持IPv6！
2023-09-06 02:22:14: 127.0.0.1#15353 （ 直连DNS：202.96.128.166,202.96.134.133 远程DNS：https://8.8.4.4/dns-query）
2023-09-06 02:22:15:   - [0]节点列表中的域名(vpslist)：202.96.128.166,202.96.134.133
2023-09-06 02:22:15:   - [0]默认：127.0.0.1#15353
2023-09-06 02:22:21: 开始加载防火墙规则...
2023-09-06 02:22:21: 加入负载均衡的节点到nftset[passwall2_vpslist]直连完成
2023-09-06 02:22:21: 加入所有节点到nftset[passwall2_vpslist]直连完成
2023-09-06 02:22:22: 加载路由器自身 TCP 代理...
2023-09-06 02:22:22:   - 启用 TPROXY 模式
2023-09-06 02:22:22: 加载路由器自身 UDP 代理...
2023-09-06 02:22:23: TCP默认代理：使用TCP节点[分流总节点] [全局代理](TPROXY:1041)代理所有端口
2023-09-06 02:22:23: UDP默认代理：使用UDP节点[分流总节点] [全局代理](TPROXY:1041)代理所有端口
2023-09-06 02:22:23: 防火墙规则加载完成！
2023-09-06 02:22:27: 重启 dnsmasq 服务
2023-09-06 02:22:28: 配置定时任务：自动更新规则。
2023-09-06 02:22:28: 运行完成！

--------------------------------------------------------------------------------------
http://192.168.10.1/cgi-bin/luci/admin/services/passwall2/get_redir_log?id=global
--------------------------------------------------------------------------------------
+0000 2023-09-05 18:23:26 WARN router: geoip database not exists: /tmp/singbox/geoip.db
+0000 2023-09-05 18:23:31 WARN router: geosite database not exists: /tmp/singbox/geosite.db
+0000 2023-09-05 18:23:39 ERROR [2778233044 267ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58848: name error
+0000 2023-09-05 18:23:40 ERROR [114824066 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58850: name error
+0000 2023-09-05 18:23:43 ERROR [3212038120 38ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58860: name error
+0000 2023-09-05 18:23:43 ERROR [1971748067 36ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58861: name error
+0000 2023-09-05 18:23:51 ERROR [3479241892 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58875: name error
+0000 2023-09-05 18:23:51 ERROR [1564643161 21ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58876: name error
+0000 2023-09-05 18:24:00 ERROR [1981608546 31ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58894: name error
+0000 2023-09-05 18:24:01 ERROR [327963220 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58895: name error
+0000 2023-09-05 18:24:16 ERROR [1294663227 35ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58900: name error
+0000 2023-09-05 18:24:16 ERROR [377897954 25ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58901: name error
+0000 2023-09-05 18:24:46 ERROR [212898936 22ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58904: name error
+0000 2023-09-05 18:24:47 ERROR [4081481602 24ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58905: name error
+0000 2023-09-05 18:25:47 ERROR [4049373098 238ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58913: name error
+0000 2023-09-05 18:25:48 ERROR [331369422 29ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58914: name error
+0000 2023-09-05 18:26:26 ERROR [111701266 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58545: name error
+0000 2023-09-05 18:26:26 ERROR [1428388879 35ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58546: name error
+0000 2023-09-05 18:26:27 ERROR [1057780125 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58547: name error
+0000 2023-09-05 18:26:27 ERROR [2621323000 39ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58548: name error
+0000 2023-09-05 18:27:48 ERROR [3189225131 276ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58973: name error
+0000 2023-09-05 18:27:48 ERROR [3874358221 21ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:58974: name error
+0000 2023-09-05 18:27:59 ERROR [2125667257 50ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58549: name error
+0000 2023-09-05 18:27:59 ERROR [2170068332 32ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58550: name error
+0000 2023-09-05 18:28:04 ERROR [3314091226 22ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58551: name error
+0000 2023-09-05 18:28:04 ERROR [3471333569 40ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58552: name error
+0000 2023-09-05 18:29:51 ERROR [2936293841 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58553: name error
+0000 2023-09-05 18:29:51 ERROR [438735345 21ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58554: name error
+0000 2023-09-05 18:29:57 ERROR [519135589 25ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58556: name error
+0000 2023-09-05 18:29:58 ERROR [1211645483 20ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:58557: name error
+0000 2023-09-05 18:32:01 ERROR [1694676531 282ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:49182: name error
+0000 2023-09-05 18:32:01 ERROR [1483169482 39ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:49184: name error

### 截图

<img width="1000" alt="main" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/8c7b07e3-5ffe-4b30-bff6-aede7ed59559">

<img width="1020" alt="Asettings" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/0e74632f-8721-4737-b612-809f9eda9585">

### 系统相关信息

PKG_VERSION:=1.20-4
CHROME_VERSION:=116.0.5845.140
OPENWRT_VERSION:=23.05-SNAPSHOT r23407-e685162a78

**Comment by whatpig** [comment]
小白问一哈，你这高级设置的防火墙工具怎么会有nftbales，我在passwall2里选了nftables但是编译出来的固件没有这项，只有iptables。

**Comment by hcym** [comment]
nf跟着系统的，官方源码2103以后的都是默认nf，1905以前或者大雕的才是你说的

**Comment by xiaorouji** [comment]
iptables+tproxy暂时未复现，nftables还未测试

**Comment by Travel2Here** [comment]
话说能不能直接改原本xray分流类型为singbox啊？还是必须得新建？
我刚试了下直接改后完全不可用，不知道是不是我手贱先更新了sb到1.5beta4的缘故。

**Comment by swxk521** [comment]
sing-box分流无法使用 1.20-6， 改回xray算了，sing-box使用hysteria2是UDP无法使用，TCP正常

**Comment by imace3** [comment]
nftables+tproxy确实是出现很多这样的报错，有些域名还会被自动解析到aaaa，换回xray就正常。

**Comment by smdx** [comment]
iptables+tproxy也遇到很多error

```
+0000 2024-01-17 21:51:05 ERROR router: failed to initialize geosite: read geosite: code google-cn not exists!
+0000 2024-01-17 21:51:05 ERROR router: failed to initialize geosite: read geosite: code google-cn not exists!
+0000 2024-01-17 22:00:17 ERROR [2126588212 5m32s] inbound/tproxy[tproxy]: process connection from 10.0.0.247:39812: upload: splice read: connection timed out
+0000 2024-01-17 22:03:52 ERROR [3600007209 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.247:40382: dial tcp 106.11.61.137:443: i/o timeout
+0000 2024-01-17 22:06:21 ERROR [1388091782 5m27s] inbound/tproxy[tproxy]: process connection from 10.0.0.247:48148: upload: splice read: connection timed out
+0000 2024-01-17 22:07:03 ERROR [1303295318 4m38s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:41294: upload: splice write: connection timed out
+0000 2024-01-17 22:22:44 ERROR [1755749921 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:47160: dial tcp 120.92.215.64:80: i/o timeout
+0000 2024-01-17 22:52:07 ERROR [3256172879 37m9s] inbound/tproxy[tproxy]: process connection from 10.0.0.11:43284: upload: splice write: connection timed out
+0000 2024-01-17 22:58:47 ERROR [1635133639 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:45402: dial tcp 120.92.215.64:80: i/o timeout
+0000 2024-01-17 23:00:32 ERROR [1873271915 13m12s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:56286: upload: splice read: connection timed out
+0000 2024-01-17 23:15:11 ERROR dns: exchange failed for www.baidu.com. IN A: context deadline exceeded
+0000 2024-01-17 23:16:46 ERROR [828235907 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:38902: upload: splice write: connection timed out
+0000 2024-01-17 23:16:55 ERROR [3029494466 5m16s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:46026: upload: splice write: connection timed out
+0000 2024-01-17 23:28:17 ERROR [542757933 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:55504: dial tcp 120.92.215.64:80: i/o timeout
+0000 2024-01-17 23:34:22 ERROR [347592256 5.0s] inbound/tproxy[tproxy]: process connection from 116.22.59.113:57898: dial tcp 54.223.125.228:80: i/o timeout
+0000 2024-01-17 23:36:18 ERROR [657602203 16m51s] inbound/tproxy[tproxy]: process connection from 10.0.0.229:52832: upload: splice read: connection timed out
+0000 2024-01-17 23:39:31 ERROR [371780049 6m18s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:52852: upload: splice read: connection timed out
+0000 2024-01-17 23:39:35 ERROR [2514168731 19m24s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:60330: upload: splice read: connection timed out
+0000 2024-01-17 23:39:35 ERROR [2915294557 19m24s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:47564: upload: splice read: connection timed out
+0000 2024-01-17 23:39:42 ERROR [2801029801 19m30s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:38630: upload: splice read: connection timed out
+0000 2024-01-17 23:39:43 ERROR [723482751 4m37s] inbound/tproxy[tproxy]: process connection from 10.0.0.13:40242: upload: splice read: connection timed out
+0000 2024-01-17 23:41:07 ERROR [1061437389 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.23:44410: dial tcp 106.11.61.137:443: i/o timeout
+0000 2024-01-17 23:41:51 ERROR dns: exchange failed for hiai-mars-drcn.emui.dbankcloud.com. IN A: context deadline exceeded
+0000 2024-01-17 23:42:50 ERROR dns: exchange failed for pgw-tel-cld-sl.alicdn.com. IN A: context deadline exceeded
+0000 2024-01-17 23:45:18 ERROR [63387641 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.23:52636: upload: splice write: connection timed out
+0000 2024-01-17 23:46:29 ERROR [3955978144 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:55600: dial tcp 111.210.233.56:443: i/o timeout
+0000 2024-01-17 23:47:00 ERROR [1193562496 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:33990: upload: splice write: connection timed out
+0000 2024-01-17 23:47:03 ERROR [3439100870 5m3s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:55930: upload: splice write: connection timed out
+0000 2024-01-17 23:47:11 ERROR [4083676254 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:46596: upload: splice write: connection timed out
+0000 2024-01-17 23:49:57 ERROR [445028469 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:41510: dial tcp 111.210.233.59:443: i/o timeout
+0000 2024-01-17 23:53:52 ERROR [1938196632 5.0s] inbound/tproxy[tproxy]: process connection from 116.22.59.113:42086: dial tcp 52.81.119.187:80: i/o timeout
+0000 2024-01-17 23:55:00 ERROR [499375945 17m6s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:36502: upload: splice read: connection timed out
+0000 2024-01-17 23:55:00 ERROR [3093523099 17m6s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:36494: upload: splice read: connection timed out
+0000 2024-01-17 23:55:04 ERROR [3613846883 17m10s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:36504: upload: splice read: connection timed out
+0000 2024-01-17 23:55:39 ERROR [3257392921 17m48s] inbound/tproxy[tproxy]: process connection from 10.0.0.211:58188: upload: splice read: connection timed out
+0000 2024-01-17 23:56:53 ERROR dns: exchange failed for pss.alicdn.com. IN AAAA: context deadline exceeded
+0000 2024-01-17 23:57:17 ERROR dns: exchange failed for apd-pcdnwxstat.teg.tencent-cloud.net. IN A: context canceled
+0000 2024-01-17 23:58:32 ERROR [1621081820 6m29s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:42034: upload: splice write: connection timed out
+0000 2024-01-18 00:00:11 ERROR dns: exchange failed for ali-adaptive.pull.yximgs.com. IN A: context deadline exceeded
+0000 2024-01-18 00:03:42 ERROR [1427717898 2m36s] inbound/tproxy[tproxy]: process connection from 10.0.0.23:40160: upload: splice read: connection timed out
+0000 2024-01-18 00:06:39 ERROR [1739944370 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:57812: upload: splice write: connection timed out
+0000 2024-01-18 00:07:25 ERROR [4116287540 5m45s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:32828: upload: splice write: connection timed out
+0000 2024-01-18 00:10:00 ERROR [3295481225 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:60472: dial tcp 120.92.215.64:80: i/o timeout
+0000 2024-01-18 00:12:39 ERROR [1831549868 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:58990: upload: splice write: connection timed out
+0000 2024-01-18 00:12:45 ERROR [1139984975 5m0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:48094: upload: splice write: connection timed out
+0000 2024-01-18 00:14:35 ERROR [1958398663 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:56146: dial tcp 120.92.215.64:80: i/o timeout
+0000 2024-01-18 00:14:40 ERROR [4114122647 5.0s] inbound/tproxy[tproxy]: process connection from 10.0.0.17:46140: dial tcp 120.92.215.64:80: i/o timeout
```
