### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 285480731** [xiaorouji/openwrt-passwall2#356]
### 描述您遇到的bug

客户端文件不适合当前设备。singbox__/tmp/singbox_extract.afJDnb/singbox

### 复现此Bug的步骤

这是还没有支持吗

### 您想要实现的目的

singbox无法安装

### 日志信息

singbox__/tmp/singbox_extract.afJDnb/singbox

### 系统相关信息

passwall最新版

**Comment by xiaorouji** [comment]
什么设备？
