### ISSUE TITLE
[Bug]: 协议显示和hysteria问题

### ISSUE THREAD

**Issue by swxk521** [xiaorouji/openwrt-passwall2#358]
1.20-6

经测试 sing-box实现的hysteria2 udp协议有BUG，经常断线，过会又好了。 自己电脑端sing-box测试同样问题，但是原生hysteria2测试没问题，希望大老更新hysteria2的UI，替换hysteria1,还有程序更新那里hysteria，没有hysteria也显示最新版，

没有安装brook  hysteria时，  主界面协议选项里也有，这时BUG吗？

**Comment by xiaorouji** [comment]
能否提供一下 hysteria2 服务端配置文件，我明天有空测试下
