### ISSUE TITLE
[Feature Request]: 请求1.20版本加回自动切换节点功能

### ISSUE THREAD

**Issue by caoolong** [xiaorouji/openwrt-passwall2#360]
### 描述你想要的新功能

如题，因为有些订阅不能通过直连订阅链接节点，需要代理状态下才能订阅，新版本少了自动切换节点功能会造成很多麻烦

### 描述你想要的解决方案

1.20版本加回自动切换节点功能

**Comment by xiaorouji** [comment]
Socks
