### ISSUE TITLE
[Bug]: 死活启动不了哦

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#365]
### 描述您遇到的bug

通过ipk更新，并重置pw2配置。
默认为xray分流，于是新增singbox分流并选择后，启动不了。
日志提示：[31mFATAL[0m[0000] start service: open geoip database: error opening database: invalid MaxMind DB file

回退用xray分流则正常使用。

### 复现此Bug的步骤

。

### 您想要实现的目的

。

### 日志信息

。

### 截图

<img width="598" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/99887507/7abb3b38-a1fe-410c-82b2-5f21d77e8378">

### 系统相关信息

1.20-7
lede 5.15

**Comment by yunxi993** [comment]
去手动下载两个geo文件, 然后覆盖掉 `/usr/share/singbox` 内原有的.

**Comment by Travel2Here** [comment]
> 去手动下载两个geo文件, 然后覆盖掉 `/usr/share/singbox` 内原有的.

嗯 刚在配置文件里找到这目录了 感谢，覆盖后欧了，但是又来了个新问题…singbox和xray用的不是同一套geoip和site，导致之前我有个配置geosite:gfw用不了（sb里没这个标签）

**Comment by yunxi993** [comment]
用这个.
`geosite:geolocation-!cn`

**Comment by Travel2Here** [comment]
> 用这个.
> 
> `geosite:geolocation-!cn`

好 感谢思路，就是辐射范围大了点 浪费流量 哈哈 暂时切回xray了，如果它这个sites库能用那个loyalsoldier的大而全就好了
