### ISSUE TITLE
[Bug]: tuic无法连接

### ISSUE THREAD

**Issue by mkeco** [xiaorouji/openwrt-passwall2#366]
### 描述您遇到的bug

添加tuic 节点无法启动

### 复现此Bug的步骤

添加节点保存应用 pw无法运行

### 您想要实现的目的

正常连接

### 日志信息

[31mFATAL[0m[0000] decode config at /tmp/etc/passwall2/global.json: outbound options: json: cannot unmarshal number into Go struct field TUICOutboundOptions.heartbeat of type string

### 截图

无

### 系统相关信息

最新版本
sing-box 15.0 b6
pw 12.0 7

### 其他信息

无

**Comment by Travel2Here** [comment]
还有singbox的socks也不通

**Comment by mkeco** [comment]
手机使用sing-box正常

**Comment by mkeco** [comment]
新版可以了
