### ISSUE TITLE
[Bug]: 导入分享URL不全

### ISSUE THREAD

**Issue by kay-zhu** [xiaorouji/openwrt-passwall2#367]
### 描述您遇到的bug

导入分享URL，原先REALITY有公钥，现在需要自己填入

### 复现此Bug的步骤

节点列表-添加-节点配置-导入分享URL

### 您想要实现的目的

REALITY有公钥也可以导入

### 日志信息

无

### 系统相关信息

1.19-6

**Comment by swxk521** [comment]
提议导入订阅默认使用xray分流

**Comment by xiaorouji** [comment]
试过最新版本了吗？

**Comment by kay-zhu** [comment]
新版完全安装不上
