### ISSUE TITLE
[Bug]: 直接安装新版失败

### ISSUE THREAD

**Issue by kay-zhu** [xiaorouji/openwrt-passwall2#368]
### 描述您遇到的bug

直接安装1.19.-6以上的版本显示：Unknown package 'luci-app-passwall2'.

在1.19-6上升级显示：Package luci-app-passwall2 (1.19-6) installed in root is up to date.

### 复现此Bug的步骤

同上

### 您想要实现的目的

可以直接安装新版或正常升级

### 日志信息

无

### 系统相关信息

内核版本 6.1.46

**Comment by kay-zhu** [comment]
补充一下，是x64构架的openwrt

**Comment by Yangleis** [comment]
补充一下，系统是OpenWrt 22.03.5，详细报错是缺少sing-box依赖，官方源没有提供。
```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall2
```

**Comment by catsimple** [comment]
feeds里添加passwall

**Comment by kay-zhu** [comment]
> feeds里添加passwall
具体在哪里？

**Comment by kay-zhu** [comment]
src/gz openwrt-passwall2 后面链接怎么填？

**Comment by catsimple** [comment]
> src/gz openwrt-passwall2 后面链接怎么填？

echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
用passwall的源，里面有sing-box

**Comment by kay-zhu** [comment]
似乎添加了还是不行

**Comment by catsimple** [comment]
> 似乎添加了还是不行

添加了以后要./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by kay-zhu** [comment]
-ash: ./scripts/feeds: not found

**Comment by catsimple** [comment]
> -ash: ./scripts/feeds: not found

兄啊，我以为你是在编译环境里，单独安装编译好的ipk我不清楚

**Comment by seeson** [comment]
我安装1.20也遇到这个问题了，单独找了sing-box但是也不能安装，需要‘kmod-netlink-diag’，目前使用1.19-3

**Comment by lzclzc999** [comment]
What am I
