### ISSUE TITLE
有个分流的问题咨询下！

### ISSUE THREAD

**Issue by sundaqiang** [xiaorouji/openwrt-passwall2#37]
1. 不在分流规则里面的是不是走的默认那一栏的选择项？
2. 如果是走的默认那一栏的选择项。如果我想默认选择直连，那么是否有必要增加一个独立节点项供“自动切换”和“Proxy”之类的使用？

![QQ截图20220331171438](https://user-images.githubusercontent.com/34206512/161021252-7c23dc88-fece-48c3-88e7-070df574ddca.png)

**Comment by dengchan0416** [comment]
黑洞是什么意思

**Comment by XMD0718** [comment]
> 

丢弃请求

**Comment by XMD0718** [comment]
> 黑洞是什么意思

丢弃请求

**Comment by QuantumNingen** [comment]
现在还有防火墙表模式吗

**Comment by sundaqiang** [comment]
> 现在还有防火墙表模式吗

分流规则添加一个gfw 域名内容为geosite:geolocation-!cn

**Comment by chancat87** [comment]
> 1. 不在分流规则里面的是不是走的默认那一栏的选择项？
> 2. 如果是走的默认那一栏的选择项。如果我想默认选择直连，那么是否有必要增加一个独立节点项供“自动切换”和“Proxy”之类的使用？
> 
> ![QQ截图20220331171438](https://user-images.githubusercontent.com/34206512/161021252-7c23dc88-fece-48c3-88e7-070df574ddca.png)

默认这个规则，文档里有写属于兜底性质，如果设置分流规则，建议默认为直连，其他走分流规则。

**Comment by chancat87** [comment]
> > 现在还有防火墙表模式吗
> 
> 分流规则添加一个gfw 域名内容为geosite:geolocation-!cn

geo里面不是有条geosite:gfw规则吗

**Comment by chancat87** [comment]
> 

我之前也这么设置的，简单粗暴，但是有个问题，像一些国外网站，如google ，微软，苹果，steam等在国内有节点且在geocn列表里面的话，访问他们也会被代理了。
