### ISSUE TITLE
[Bug]: 更新版本后编译出错

### ISSUE THREAD

**Issue by qqsir-dev** [xiaorouji/openwrt-passwall2#371]
### 描述您遇到的bug

版本更新后云编译出错

### 复现此Bug的步骤

1234

### 您想要实现的目的

正确编译

### 日志信息

 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall-zh-cn:
 * 	brook
 * 	sing-box
 * 	trojan-go
 * 	trojan-plus
 * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall2
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall2 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall2.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall2-zh-cn:
 * 	sing-box
 * opkg_install_cmd: Cannot install package luci-i18n-passwall2-zh-cn.
 * resolve_conffiles: Existing conffile /home/runner/work/AutoLede/AutoLede/workspace/openwrt/build_dir/target-aarch64_generic_musl/root-rockchip/etc/config/socat is different from the conffile in the new package. The new conffile will be placed at /home/runner/work/AutoLede/AutoLede/workspace/openwrt/build_dir/target-aarch64_generic_musl/root-rockchip/etc/config/socat-opkg.
make[1]: *** [package/Makefile:70: package/install] Error 255
make: *** [/home/runner/work/AutoLede/AutoLede/workspace/openwrt/include/toplevel.mk:231: package/install] Error 2
Error: Process completed with exit code 2.

### 系统相关信息

啊啊啊

**Comment by sbwml** [comment]
Accordance with:
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/16485166/cb31dbb2-020a-4ad6-8fdf-4195c2487cf0)


```shell
cd openwrt
git clone https://github.com/xiaorouji/openwrt-passwall-packages package/passwall-packages
echo "CONFIG_PACKAGE_luci-app-passwall2=y" >> .config
rm -rf tmp/*
make defconfig
make -j16
```

Good luck!

**Comment by qqsir-dev** [comment]
Same

**Comment by hcym** [comment]
编译没事，就是不能用，p1的正常，干脆p2退回老版本，

**Comment by qqsir-dev** [comment]
> Accordance with: ![image](https://user-images.githubusercontent.com/16485166/266946418-cb31dbb2-020a-4ad6-8fdf-4195c2487cf0.png)
> 
> ```shell
> cd openwrt
> git clone https://github.com/xiaorouji/openwrt-passwall-packages package/passwall-packages
> echo "CONFIG_PACKAGE_luci-app-passwall2=y" >> .config
> rm -rf tmp/*
> make defconfig
> make -j16
> ```
> 
> Good luck!

这样做了也不行
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall2
Configuring autosamba.
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall2 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall2.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall2-zh-cn:
 * 	sing-box
 * opkg_install_cmd: Cannot install package luci-i18n-passwall2-zh-cn.
 * pkg_hash_check_unresolved: cannot find dependency brook for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency sing-box for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency trojan-go for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency trojan-plus for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-passwall-zh-cn:
 * 	brook
 * 	sing-box
 * 	trojan-go
 * 	trojan-plus
 * opkg_install_cmd: Cannot install package luci-i18n-passwall-zh-cn.
 * resolve_conffiles: Existing conffile /home/runner/work/AutoLede/AutoLede/workspace/openwrt/build_dir/target-x86_64_musl/root-x86/etc/config/socat is different from the conffile in the new package. The new conffile will be placed at /home/runner/work/AutoLede/AutoLede/workspace/openwrt/build_dir/target-x86_64_musl/root-x86/etc/config/socat-opkg.
make[1]: *** [package/Makefile:70: package/install] Error 255
Configuring kmod-amazon-ena.
Configuring kmod-e1000e.
Configuring autocore-x86.
Configuring luci-i18n-upnp-zh-cn.
Configuring kmod-usb-net-sr9700.
Configuring luci-i18n-mwan3helper-zh-cn.
Configuring luci-i18n-base-en.
Configuring kmod-button-hotplug.
Configuring kmod-dummy.
Configuring kmod-fixed-phy.
Configuring luci-i18n-bonding-en.
Configuring kmod-fs-squashfs.
Configuring v2ray-geosite.
Configuring iperf3.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-mhi-bus.
Configuring kmod-qrtr-mhi.
Configuring wireless-tools.
Configuring luci-i18n-ps3netsrv-zh-cn.
Configuring kmod-bnx2.
Configuring v2ray-geoip.
Configuring kmod-usbip-server.
Configuring urngd.
Configuring ddns-scripts_freedns_42_pl.
Configuring nginx.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Configuring luci-i18n-minidlna-en.
Configuring luci-proto-ncm.
make[1]: Leaving directory '/home/runner/work/AutoLede/AutoLede/workspace/openwrt'
make: *** [/home/runner/work/AutoLede/AutoLede/workspace/openwrt/include/toplevel.mk:231: package/install] Error 2
Error: Process completed with exit code 2.
