### ISSUE TITLE
passwall2里的自动切换功能缺失（已找到解决方案）

### ISSUE THREAD

**Issue by gtayoung** [xiaorouji/openwrt-passwall2#373]
### 描述你想要的新功能

passwall2里的自动切换功能缺失，目前无法在节点时效时自动切换

### 描述你想要的解决方案

希望可以恢复原有版本中的此功能

**Comment by gtayoung** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2739

**Comment by tedaz** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/2739这个页面已经无法打开了，请问具体解决方法是什么？
