### ISSUE TITLE
[Bug]: a53架构路由器无法安装升级l.20-9

### ISSUE THREAD

**Issue by RavenCage** [xiaorouji/openwrt-passwall2#374]
### 描述您遇到的bug

直接在路由器里安装失败，无法升级。提示缺文件，在路由器配置菜单中未发现有这个软件啊：luci-lua-runtime。

### 复现此Bug的步骤

安装失败

### 您想要实现的目的

成功安装升级

### 日志信息

有图

### 截图

![psw2](https://github.com/xiaorouji/openwrt-passwall2/assets/126802578/9f8cc719-3250-4dce-b2e8-08af8761238a)

### 系统相关信息

a53路由器

**Comment by xiaorouji** [comment]
忽略依赖包安装

**Comment by RavenCage** [comment]
> 忽略依赖包安装
已经搞定了，感谢大佬。
