### ISSUE TITLE
[Bug]: 1.20-9 压根安装不了

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#375]
### 描述您遇到的bug

如题。

### 复现此Bug的步骤

。

### 您想要实现的目的

。

### 日志信息

。

### 系统相关信息

。

**Comment by kay-zhu** [comment]
一样，1.19-6以上都没法装

**Comment by Biercenter** [comment]
应该是和我一样，提示需要什么lua-runtime的依赖吧，希望用现在最新的22正式版SDK，或者整个分支，大家想要哪个自己下载比较方便。

**Comment by kay-zhu** [comment]
一般人也不会编译，能否做一个ipk可以直接安装或升级新版的？现在是卡在1.96-6了

**Comment by xiaorouji** [comment]
opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends

**Comment by Biercenter** [comment]
> opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends
 试了不行，还是提示缺少依赖

**Comment by kay-zhu** [comment]
没用，还是装不了

**Comment by imvane** [comment]
安装1.20-9 1.20-10 1.20-11，提示Installing luci-lib-base (git-22.308.54612-9118452) to root..
安装luci-lib-base后，ow就打不开了，网页提示Bad Gateway
The process did not produce any response。

**Comment by lcuwx2016** [comment]
OpenWrt SDK Version: 23.05-rc3
需要以上版本OpenWrt

**Comment by kay-zhu** [comment]
算了，怎么都装不上

**Comment by Biercenter** [comment]
> 算了，怎么都装不上

我刚用OpenWrt 22.03.5正式版SDK编译了一份，有需要的可以自取https://wwpg.lanzouq.com/iUBg418qhthe
密码:3i2t

**Comment by lcuwx2016** [comment]
> > 算了，怎么都装不上
> 
> 我刚用OpenWrt 22.03.5正式版SDK编译了一份，有需要的可以自取https://wwpg.lanzouq.com/iUBg418qhthe 密码:3i2t

感恩老哥

**Comment by kay-zhu** [comment]
我是git-23.226.24689-eba8e8b，内核版本6.1.46
还是装不上

**Comment by Biercenter** [comment]
> 我是git-23.226.24689-eba8e8b，内核版本6.1.46 还是装不上

你内核怎么这么高？我最近都是直接用官方的imagebuilder自定义一下，懒得从源码编译。
