### ISSUE TITLE
[Bug]: please don't use 23.05 rc OpenWrt firmware in next your updates!

### ISSUE THREAD

**Issue by tredntredn** [xiaorouji/openwrt-passwall2#376]
### 描述您遇到的bug

firmware 23.05.rc isn't available for all devices yet. you limit users from download your updates because of their firmware!

### 复现此Bug的步骤

firmware 23.05.rc isn't available for all devices yet. you limit users from download your updates because of their firmware!

### 您想要实现的目的

firmware 23.05.rc isn't available for all devices yet. you limit users from download your updates because of their firmware!

### 日志信息

firmware 23.05.rc isn't available for all devices yet. you limit users from download your updates because of their firmware!

### 系统相关信息

firmware 23.05.rc isn't available for all devices yet. you limit users from download your updates because of their firmware!

**Comment by Travel2Here** [comment]
yes,agree

**Comment by Biercenter** [comment]
同意，昨天更新了下，提示没有lua-runtime，估计是23.05专有的包，放弃了

**Comment by RavenCage** [comment]
奇怪的是我通过源码编译路由器固件，在21.02的源码框架下就把1.20-10编译进去了，反而passwall最新版编译不进去，最终停留在4.68-1，好奇怪，有没有大佬可以给解惑的？谢谢。

**Comment by xiaorouji** [comment]
opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends

**Comment by Biercenter** [comment]
> opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends

试过，还是会提示缺少依赖。还有一个小问题，依赖的sing-box大小有9mb，我用的esxi虚拟机openwrt官方镜像，安装了xray后再安装会提示空间不足，需要用imagebuilder重新打包再把镜像sysupgrade进去。

**Comment by wangdaye078** [comment]
> > opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends
> 
> 试过，还是会提示缺少依赖。还有一个小问题，依赖的sing-box大小有9mb，我用的esxi虚拟机openwrt官方镜像，安装了xray后再安装会提示空间不足，需要用imagebuilder重新打包再把镜像sysupgrade进去。

如果你用的是generic-squashfs-combined包
可以在esxi里直接改大磁盘容量，然后进去后
opkg install cfdisk resize2fs
使用cfdisk resize sda2，然后write quit，
重启，再执行resize2fs /dev/loop0，再重启就可以看到扩容了。
我也是用的esxi装的官方镜像。方法简单，随时可以反复扩容。

**Comment by Biercenter** [comment]
> > > opkg 安装的时候忽略一下依赖试试 --nodeps --force-depends
> > 
> > 
> > 试过，还是会提示缺少依赖。还有一个小问题，依赖的sing-box大小有9mb，我用的esxi虚拟机openwrt官方镜像，安装了xray后再安装会提示空间不足，需要用imagebuilder重新打包再把镜像sysupgrade进去。
> 
> 如果你用的是generic-squashfs-combined包 可以在esxi里直接改大磁盘容量，然后进去后 opkg install cfdisk resize2fs 使用cfdisk resize sda2，然后write quit， 重启，再执行resize2fs /dev/loop0，再重启就可以看到扩容了。 我也是用的esxi装的官方镜像。方法简单，随时可以反复扩容。

谢谢解答，我后来发现是2个安装包都是放在/root目录下再安装，所以空间不够，还有一个虚拟机是debian11，imagebuilder还是挺快的，一键打包通过sysupgrade命令加刷入
