### ISSUE TITLE
[Bug]: error close node openwrt 23.05.0-rc3

### ISSUE THREAD

**Issue by predators46** [xiaorouji/openwrt-passwall2#377]
### 描述您遇到的bug

while selecting node close getting error. maybe it's a luci-base issue on 23.05.0-rc3

### 复现此Bug的步骤

1. node
2. close
3. save & apply

### 截图

![Screenshot_2023-09-13_092725](https://github.com/xiaorouji/openwrt-passwall2/assets/31931530/da887936-565a-412c-a1c6-8a312039877f)

### 系统相关信息

passwall2 1.20-10

**Comment by xiaorouji** [comment]
try the latest commit.

**Comment by predators46** [comment]
thanks
