### ISSUE TITLE
[Feature Request]: 关于内网192.168，10.网段可以被代理

### ISSUE THREAD

**Issue by chendx-github** [xiaorouji/openwrt-passwall2#378]
### 描述你想要的新功能

我想代理到家里的内网环境192.168.0.0/24，但是ssr plus+ 和此项目都无法实现

### 描述你想要的解决方案

我尝试了 ssr plus+ 修改路由的方式可以实现
但是此项目根本没办法找到路由查看源码发现已经将此网段写入规则屏蔽掉了
希望可以出配置的方式来自己定义这个规则

### 描述你考虑过的替代方案

我尝试使用分流的方式来 proxy 也无法生效

### 其他信息

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/55473491/03b2375f-cd5c-48f4-8241-d0e16c1b70d1)

**Comment by daifeilail** [comment]
家里内网换到一个公网地址段去。 比如 11.0.0.0/8

**Comment by chendx-github** [comment]
https://github.com/xiaorouji/openwrt-passwall2/issues/378#issuecomment-1718923088
这个方法并不好
我完全放弃了此项目的方案
使用 tun2socks 来实现了此需求

**Comment by xiaorouji** [comment]
这个改一下代码里的直连网段就好了
