### ISSUE TITLE
[Bug]: 用了passwall2这样设置，怎们显示的都是出国环境了

### ISSUE THREAD

**Issue by mmeiwenlong** [xiaorouji/openwrt-passwall2#386]
### 描述您遇到的bug

如图

### 复现此Bug的步骤

如图

### 您想要实现的目的

国内国外分清楚

### 日志信息

如图

### 截图

<img width="1085" alt="QQ20230916-162330@2x" src="https://github.com/xiaorouji/openwrt-passwall2/assets/44661424/48a0d5f9-571a-4fe3-9e6f-62c5a5152e1f">
<img width="862" alt="QQ20230915-222353@2x" src="https://github.com/xiaorouji/openwrt-passwall2/assets/44661424/887f63c3-f6c3-4317-9cc4-71f2d4bf67f1">
<img width="985" alt="QQ20230916-162717@2x" src="https://github.com/xiaorouji/openwrt-passwall2/assets/44661424/b70ca607-ffd7-457d-9197-1ead2090b9e3">

### 系统相关信息

如图

**Comment by xiaorouji** [comment]
你没有使用分流类型当然是全局啦

**Comment by mmeiwenlong** [comment]
> 你没有使用分流类型当然是全局啦

![Screenshot_2023-09-16-18-07-27-371_com.android.chrome.jpg](https://github.com/xiaorouji/openwrt-passwall2/assets/44661424/d5dc965a-95f2-4425-ad6b-d4d9cb3c7e5d)

这样可以了吧
