### ISSUE TITLE
[Bug]: 为什么不同Hysteria 速度差距这么大啊

### ISSUE THREAD

**Issue by jt8823** [xiaorouji/openwrt-passwall2#387]
### 描述您遇到的bug

是我设置不对吗?
第一次用Hysteria 2   
同一个节点,用v2rayN  可以跑满,  在passwall2 中  测速只有3Mb

### 复现此Bug的步骤

自编译的 固件 23.8   内核6.1
J4125

### 您想要实现的目的

自编译的 固件 23.8   内核6.1
J4125

### 日志信息

自编译的 固件 23.8   内核6.1
J4125

### 系统相关信息

自编译的 固件 23.8   内核6.1
J4125

**Comment by Gzxhwq** [comment]
因为测速网站所用到的端口8080，并不包含在passwall的常用tcp端口中。你用passwall+常用tcp端口来测，就是直连的速度

**Comment by jt8823** [comment]
> 因为测速网站所用到的端口8080，并不包含在passwall的常用tcp端口中。你用passwall+常用tcp端口来测，就是直连的速度

youtube 也是这个情况啊,   v2rayN 可以跑到10w+   挂在passwall2  一万都不稳定...

**Comment by Gzxhwq** [comment]
passwall2默认没有屏蔽udp 443端口，youtube可能走了quic

**Comment by jt8823** [comment]
> passwall2默认没有屏蔽udp 443端口，youtube可能走了quic

quic 我在passwall中设置了 屏蔽了啊

**Comment by swxk521** [comment]
> > passwall2默认没有屏蔽udp 443端口，youtube可能走了quic
> 
> quic 我在passwall中设置了 屏蔽了啊

规则排序到第一，passwall默认规则排序有问题，自己改改，记住规则越往前越优先，443规则放到最后，压根就用不上

**Comment by jt8823** [comment]
> > > passwall2默认没有屏蔽udp 443端口，youtube可能走了quic
> > 
> > 
> > quic 我在passwall中设置了 屏蔽了啊
> 
> 规则排序到第一，passwall默认规则排序有问题，自己改改，记住规则越往前越优先，443规则放到最后，压根就用不上

感谢感谢!!!!!   好了
