### ISSUE TITLE
[Bug]: sing-box内网分流异常

### ISSUE THREAD

**Issue by catsimple** [xiaorouji/openwrt-passwall2#392]
### 描述您遇到的bug

在运行passwall2路由中部署了一个容器服务，使用该路由下的设备访问容器服务时会被代理
![QQ截图20230921143924](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/d2175a31-1887-4a75-aa6d-ebc4bc6b3f48)

### 复现此Bug的步骤

使用分流总节点，类型为sing-box时，出现该问题
代理方式为iptables+redirect，iptables+tproxy都会有该问题
分流总节点类型换回xray时正常

### 您想要实现的目的

-

### 日志信息

-

### 系统相关信息

passwall2 1.20-14
singbox v1.5.0-rc.1
xray 1.8.4

**Comment by catsimple** [comment]
分流类型Xray，节点类型Xray或Sing-box均分流正常
分流类型Sing-box，节点类型Xray或Sing-box均分流异常

**Comment by Gzxhwq** [comment]
同样问题

https://github.com/xiaorouji/openwrt-passwall2/issues/389

**Comment by xiaorouji** [comment]
试下最新 commit

**Comment by catsimple** [comment]
> 试下最新 commit

问题依旧
![QQ截图20230922000128](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/48134020-bbbe-48f1-b080-2c5aaab3e73f)

**Comment by catsimple** [comment]
更新1.2.0-15问题依旧，然后重新开关sfe和bbr后好了，不知道是什么bug

**Comment by catsimple** [comment]
didn't fixed somehow, maybe it's a bug with flowoffload or tcp bbr.
