### ISSUE TITLE
[Bug]: openwrt 系统日志里出现大量错误日志

### ISSUE THREAD

**Issue by hu-boss** [xiaorouji/openwrt-passwall2#397]
### 描述您遇到的bug

openwrt 系统里出现大量错误日志

### 复现此Bug的步骤

日志出现大量错误

### 您想要实现的目的

消除错误

### 日志信息

Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: Error: syntax error, unexpected number
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: add set inet fw4 passwall2_global_whitelist { type 0; flags interval, timeout; auto-merge; }
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2:                                                    ^
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: Error: set definition does not specify key
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: add set inet fw4 passwall2_global_whitelist { type 0; flags interval, timeout; auto-merge; }
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2:                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: Error: syntax error, unexpected number
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: add set inet fw4 passwall2_global_whitelist6 { type 0; flags interval, timeout; auto-merge; }
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2:                                                     ^
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: Error: set definition does not specify key
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: add set inet fw4 passwall2_global_whitelist6 { type 0; flags interval, timeout; auto-merge; }
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2:                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2: add rule inet fw4 PSW2_OUTPUT_MANGLE ip daddr @passwall2_global_whitelist counter return
Fri Sep 22 16:40:32 2023 daemon.notice procd: /etc/rc.d/S99passwall2:                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Fri Sep 22 16:40:43 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:40:55 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:40:55 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist6 Error: No such file or directory; did you mean set ‘passwall2_lanlist6’ in table inet ‘fw4’?
Fri Sep 22 16:41:10 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:41:10 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:41:35 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:41:37 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Fri Sep 22 16:41:39 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist6 Error: No such file or directory; did you mean set ‘passwall2_lanlist6’ in table inet ‘fw4’?
Fri Sep 22 16:41:39 2023 daemon.err dnsmasq[3469]: nftset inet fw4 passwall2_global_whitelist6 Error: No such file or directory; did you mean set ‘passwall2_lanlist6’ in table inet ‘fw4’?

### 系统相关信息

passwall2 1.20-15
openwrt  23.05.0-rc3

**Comment by xwcoco** [comment]
/usr/share/passwall2/nftables.sh文件中第610，610行改成如下
 gen_nftset $nftset_global_whitelist ipv4_addr 0 0  
 gen_nftset $nftset_global_whitelist6 ipv6_addr 0 0 

代码参数次序错了

**Comment by hu-boss** [comment]
按照楼上的方法已经解决。看到源码仍没有修复再顶上来

**Comment by QSong000001** [comment]
我也按照楼上的方法已经解决。看到源码仍没有修复再顶上来
