### ISSUE TITLE
Sing-Box, DNS缓存与系统日志报错.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#398]
### 描述您遇到的bug

`app.sh`文件内`DNS_CACHE=$(config_t_get global dns_cache 0)`.

`global.json`文件内:
`  "dns": {
    "disable_cache": true,
`

`global_dns_direct.json`文件内:
`  "dns": {
    "disable_cache": false,
`

`global_dns_direct.json`的dns cache 并不受`app.sh`, `DNS_CACHE`布尔值的影响.

***

重刷固件或者重新启动路由器系统日志都有以下日志:
```
Fri Sep 22 11:44:17 2023 daemon.err sing-box[6023]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:22 2023 daemon.err sing-box[6063]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:27 2023 daemon.err sing-box[6098]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:32 2023 daemon.err sing-box[6144]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:37 2023 daemon.err sing-box[6190]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:37 2023 daemon.info procd: Instance sing-box::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
```
### 复现此Bug的步骤

如上描述.

### 您想要实现的目的

关于 `dns cache` 这种现象是否有意为之, 还是忽略了或是 `global_dns_direct.json` 内 dns cache 并无所谓.

### 日志信息

```
Fri Sep 22 11:44:17 2023 daemon.err sing-box[6023]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:22 2023 daemon.err sing-box[6063]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:27 2023 daemon.err sing-box[6098]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:32 2023 daemon.err sing-box[6144]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:37 2023 daemon.err sing-box[6190]: [31mFATAL[0m[0000] read config at ./config.json: open ./config.json: no such file or directory
Fri Sep 22 11:44:37 2023 daemon.info procd: Instance sing-box::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
```

### 系统相关信息

passwall2: 1.20-15

Chrome: 117.0.5938.92

**Comment by xiaoshengshuohua** [comment]
还有配置文件内分流规则:
```
        "domain_suffix": [
          ".push.apple.com",
        ],
        "domain": [
          "push.apple.com",
        ],
```

规则: domain:push.apple.com, 这是之前xray的写法, 匹配域名后缀.

现在使用 sing-box 分流, 仍然沿用这种写法, 同一个域名规则就会出现既有域名后缀匹配 `domain_suffix`, 又有完整域名匹配 `domain` .

**Comment by xiaoshengshuohua** [comment]
> `./config.json` 應該不是passwall2邏輯生成的文件名

祝节日快乐!

好的, 那么关于域名分流匹配模式呢?

使用的是domain的匹配方式, 现在却有完全匹配和后缀匹配.

还有Direct DNS的缓存不受`app.sh`内布尔值影响, `global_dns_direct.json` 的DNS缓存是否受`global.json`的影响.

**Comment by skefy** [comment]
我也遇到了这个问题，不知楼主解决了没有？

**Comment by xiaoshengshuohua** [comment]
> 我也遇到了这个问题，不知楼主解决了没有？

还没有.

**Comment by Travel2Here** [comment]
同发现这个问题，到底是singbox的什么初始化问题还是PW2调用的bug？
read config at ./config.json: open ./config.json: no such file or directory

**Comment by xiaoshengshuohua** [comment]
@xiaorouji 
@Travel2Here 

问题是 `sing-box` 配置示例造成的, 根据观察这个还有可能造成CPU高占用.
`https://github.com/xiaorouji/openwrt-passwall-packages/tree/main/sing-box/files`

根据日志 sing-box 调用的是 `./config.json`, `/etc/sing-box` 下示例名是 `config.json.example`.

尝试修改文件名后 singbox 可以正常读取示例, 但是里面错误多, 尝试修了一下没搞好, 你们来吧.

**Comment by Gzxhwq** [comment]
这个不用管的，示例也是故意留点错误所以运行不起来的，这是给sing-box包单独运行用的，懂的人自然会写json配置使他跑起来。Passwall不会调用/etc/sing-box下的所有文件来运行sing-box。如果不想看系统日志报错，那把service sing-box disable掉就可以了

**Comment by Travel2Here** [comment]
> 这些都是不用管的，这些问题和报错都与Passwall没有一点儿的关系。示例也是故意留点错误所以运行不起来的，这是给sing-box包单独运行用的，懂的人自然会写json配置使他跑起来。Passwall不会调用/etc/sing-box下的所有文件来运行sing-box。如果不想看系统日志报错，那把service sing-box disable掉就可以了。“千万不要”试图使sing-box单独跑起来又和Passwall一起使用。

这个听起来靠谱，我在luci里把启动项的singbox自启动禁止是不是一个意思？😂

**Comment by Gzxhwq** [comment]
> > 这些都是不用管的，这些问题和报错都与Passwall没有一点儿的关系。示例也是故意留点错误所以运行不起来的，这是给sing-box包单独运行用的，懂的人自然会写json配置使他跑起来。Passwall不会调用/etc/sing-box下的所有文件来运行sing-box。如果不想看系统日志报错，那把service sing-box disable掉就可以了。“千万不要”试图使sing-box单独跑起来又和Passwall一起使用。
> 
> 这个听起来靠谱，我在luci里把启动项的singbox自启动禁止是不是一个意思？😂

一样的

**Comment by xiaoshengshuohua** [comment]
ok!
