### ISSUE TITLE
[Bug]: ramips (mipsel_24kc) 经由sing-box跑tuic限速10Mbps

### ISSUE THREAD

**Issue by kvmcore** [xiaorouji/openwrt-passwall2#399]
### 描述您遇到的bug

ramips (mipsel_24kc) 平台跑TUIC下行限速10Mbps，上行完全跑不动，速度为0，切换VLESS恢复正常
ipq40xx (cortex-a7_neon-vfpv4) 平台无论是TUIC或VLESS都不会出现这个问题，可以拉满带宽
两个平台安装的passwall2版本一致，都是1.20-15

### 复现此Bug的步骤

新建sing-box分流总节点，默认规则，无新增，仅调整顺序

### 您想要实现的目的

烦请检查一下

### 日志信息

2023-09-23 04:29:04: 删除相关防火墙规则完成。
2023-09-23 04:29:08: 清空并关闭相关程序和缓存完成。
2023-09-23 04:29:09: 开启实验性IPv6透明代理(TProxy)，请确认您的节点及类型支持IPv6！
2023-09-23 04:29:09: 127.0.0.1#15353 （ 直连DNS：202.96.128.166,202.96.134.133 远程DNS：https://1.1.1.1/dns-query）
2023-09-23 04:29:10:   - [0]节点列表中的域名(vpslist)：202.96.128.166,202.96.134.133
2023-09-23 04:29:10:   - [0]默认：127.0.0.1#15353
2023-09-23 04:29:11: 开始加载防火墙规则...
2023-09-23 04:29:12: 加入负载均衡的节点到nftset[passwall2_vpslist]直连完成
2023-09-23 04:29:12: 加入所有节点到nftset[passwall2_vpslist]直连完成
2023-09-23 04:29:14: 加载路由器自身 TCP 代理...
2023-09-23 04:29:14:   - 启用 TPROXY 模式
2023-09-23 04:29:14: 加载路由器自身 UDP 代理...
2023-09-23 04:29:15: TCP默认代理：使用TCP节点[分流总节点] [全局代理](TPROXY:1041)代理所有端口
2023-09-23 04:29:15: UDP默认代理：使用UDP节点[分流总节点] [全局代理](TPROXY:1041)代理所有端口
2023-09-23 04:29:15: 防火墙规则加载完成！
2023-09-23 04:29:20: 重启 dnsmasq 服务
2023-09-23 04:29:21: 运行完成！

**http://192.168.10.1/cgi-bin/luci/admin/services/passwall2/get_redir_log?id=global**
+0000 2023-09-22 20:38:21 ERROR [977980573 36ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51533: name error
+0000 2023-09-22 20:38:21 ERROR [1620151280 59ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51535: name error
+0000 2023-09-22 20:41:29 ERROR [4188476740 38ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51537: name error
+0000 2023-09-22 20:41:30 ERROR [1952593454 33ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51538: name error
+0000 2023-09-22 20:41:50 ERROR [2222826972 24ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51539: name error
+0000 2023-09-22 20:41:50 ERROR [785754945 28ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51542: name error
+0000 2023-09-22 20:42:04 ERROR [3843963235 36ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:56001: too many open streams
+0000 2023-09-22 20:42:04 ERROR [850796604 37ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:56000: too many open streams
+0000 2023-09-22 20:42:05 ERROR [3821100722 22ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:56003: too many open streams
+0000 2023-09-22 20:42:05 ERROR [1777503269 28ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:56002: too many open streams
+0000 2023-09-22 20:42:05 ERROR [199568103 3ms] inbound/tproxy[tproxy]: process connection from 192.168.10.162:56004: too many open streams
+0000 2023-09-22 20:44:47 ERROR [501179995 37ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51544: name error
+0000 2023-09-22 20:44:48 ERROR [2960556950 25ms] inbound/tproxy[tproxy]: process connection from 192.168.10.114:51545: name error

### 截图

<img width="963" alt="01" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/29a062fc-1281-4461-9b5e-6337973e50e0">

<img width="979" alt="02" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/63d14581-c2b3-4054-a34d-9a6f96bef859">

<img width="830" alt="03" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/a92ee0b0-bf22-4748-8b85-3bf66eec4985">

<img width="980" alt="04" src="https://github.com/xiaorouji/openwrt-passwall2/assets/3048370/6601f526-f0b1-46c9-aa8a-7572698b4770">

### 系统相关信息

PKG_VERSION:=1.20-15
SING-BOX_VERSION:=v1.5.0-rc.2
SAFARI_VERSION:=16.6 (18615.3.12.11.2)
OPENWRT_VERSION:=23.05-SNAPSHOT r23459-fe1028e89c

**Comment by Gzxhwq** [comment]
应该向上游sing-box反映这个问题

**Comment by kvmcore** [comment]
> 应该向上游sing-box反映这个问题

sing-box支持列表里面就没有mipsel_24kc，去那边反映，除了close issues，不会得到任何答复

**Comment by Gzxhwq** [comment]
> > 应该向上游sing-box反映这个问题
> 
> sing-box支持列表里面就没有mipsel_24kc，去那边反映，除了close issues，不会得到任何答复

这个这边也是没有办法解决的。

你可以对比一下同样是Go实现的hysteria官方版和sing-box版。
如果表现也和tuic近似，则可能是quic-go或者Go的问题。否则就是sing-box tuic的实现有问题。

**Comment by Gzxhwq** [comment]
还有可以添加环境变量关闭gso试试

QUIC_GO_DISABLE_GSO=true

**Comment by kvmcore** [comment]
> 还有可以添加环境变量关闭gso试试
> 
> QUIC_GO_DISABLE_GSO=true

无效 :(

**Comment by Gzxhwq** [comment]
那就没有办法了，这种只在特定平台出现问题的，基本可以指向是Go自身的问题
