### ISSUE TITLE
希望能加入游戏加速相关默认规则…

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall2#4]
刚编译完大佬的psw2，学习了一下暂时感觉还不错，不过发现没办法做游戏加速（UDP）？
后来发现可以通过规则去添加=。=还没搞太懂规则部分，希望大佬能添加默认的UDP规则学习学习…
我知道项目还在早期阶段，加油！

**Comment by xiaorouji** [comment]
新建一个V2ray分流规则，网络选UDP，保存。移到China规则下面（如果你只想国外走代理）。然后选一个游戏节点应用即可。

**Comment by jh0072110** [comment]
> 新建一个V2ray分流规则，网络选UDP，保存。移到China规则下面（如果你只想国外走代理）。然后选一个游戏节点应用即可。

懂了懂了 谢谢大佬
