### ISSUE TITLE
[Bug]: sing-box分流，远程dns会代理私网地址

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-passwall2#402]
### 描述您遇到的bug

如下所示，当使用singbox进行分流时，如果远程dns选择内网内自行搭建的dns，会出现代理内网地址的情况，可以看见走的规则是default
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/44677306/e00378fb-bb93-4b14-a9dd-5b38732c2d57)
相比较，xray则是直连，没问题
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/44677306/af6868e1-134e-494e-9b9d-1951d1108ba0)

### 复现此Bug的步骤

分流使用sing-box，远程dns填写内网dns地址

### 您想要实现的目的

希望远程dns也能判断是否需要代理

### 日志信息

sing-box
```
+0000 2023-09-23 18:57:39 INFO outbound/socks[default]: outbound packet connection to 192.168.1.185:53
```
xray
```
2023/09/23 19:05:36 [Info] transport/internet/udp: establishing new connection for udp:192.168.1.185:53
2023/09/23 19:05:36 [Info] [2413928310] app/dispatcher: taking detour [direct] for [udp:192.168.1.185:53]
```

### 系统相关信息

 OpenWrt R23.7.7 / LuCI Master (git-23.198.59743-991daf5)
x86平台

**Comment by xiaorouji** [comment]
更新最新版本。
另外說下，sing-box的DNS已經足夠滿足日常使用了，如果你要使用自定義DNS。請自己配置對應的分流規則使用的DNS和對應的節點。
