### ISSUE TITLE
[Feature Request]:  能否把 hysteria1 加回来

### ISSUE THREAD

**Issue by rivernofish** [xiaorouji/openwrt-passwall2#403]
### 描述你想要的新功能

hysteria1 可以选择 faketcp 协议，这对 ISP QOS 有很大帮助，我用这个协议基本不会出现断流的情况。而hysteria2 不管怎么配置都避免不了断流，目前作者也没有打算在 hysteria2 上引入 faketcp。所以能否先同时保留 hysteria 1 和 2？

### 描述你想要的解决方案

同时保留 hysteria 1 和 2

**Comment by Gzxhwq** [comment]
hysteria 1和2 并没有做成两个ipk包，其他的openwrt源也没有分开做成2个包，所以无法同时兼容1和2。

**Comment by franklee628** [comment]
我之前也是这么想的，无奈一看都强行升级成2.0了，也只好硬着头皮上。

@rivernofish 说的断流问题我也有遇到过，不过经过几次passwall2的更新后，稍微好了点，今天又把DNS里Remote DNS Protocol从TCP改成了DoH，竟然意外的恢复到了以前用1.x的时候的感觉，有待观察。

不过其实Hysteria的作者说了，“Hysteria 1.x 将继续推出 bug 和安全修复，但不会再有重大功能变更。”

**Comment by swxk521** [comment]
> ### 描述你想要的新功能
> hysteria1 可以选择 faketcp 协议，这对 ISP QOS 有很大帮助，我用这个协议基本不会出现断流的情况。而hysteria2 不管怎么配置都避免不了断流，目前作者也没有打算在 hysteria2 上引入 faketcp。所以能否先同时保留 hysteria 1 和 2？

hy1用它本身的faketcp我这边还是不太好，最后在hy2上面加上了udp2raw，现在挺稳定的。

**Comment by rivernofish** [comment]
多谢各位提供的思路，回头我也试试看。不增加作者的工作量，issue 先关了。
