### ISSUE TITLE
[Bug]: 系统日志里面出现很多错误

### ISSUE THREAD

**Issue by gg4924** [xiaorouji/openwrt-passwall2#406]
### 描述您遇到的bug

使用起来没什么感觉，但是系统日志出现很多错误，xray和sing-box类型都试过。nftables和tproxy方式，我好像切换不了iptables。

### 复现此Bug的步骤

正常使用查看系统日志

### 您想要实现的目的

不再出现错误日志

### 日志信息

Tue Sep 26 04:25:02 2023 daemon.err dnsmasq[21916]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?

Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: syntax error, unexpected number
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add set inet fw4 passwall2_global_whitelist { type 0; flags interval, timeout; auto-merge; }
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                                    ^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: set definition does not specify key
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add set inet fw4 passwall2_global_whitelist { type 0; flags interval, timeout; auto-merge; }
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: syntax error, unexpected number
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add set inet fw4 passwall2_global_whitelist6 { type 0; flags interval, timeout; auto-merge; }
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                                     ^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: set definition does not specify key
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add set inet fw4 passwall2_global_whitelist6 { type 0; flags interval, timeout; auto-merge; }
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add rule inet fw4 PSW2_OUTPUT_MANGLE ip daddr @passwall2_global_whitelist counter return
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: No such file or directory; did you mean set ‘passwall2_lanlist6’ in table inet ‘fw4’?
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add rule inet fw4 PSW2_MANGLE_V6 ip6 daddr @passwall2_global_whitelist6 counter return
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: No such file or directory; did you mean set ‘passwall2_lanlist6’ in table inet ‘fw4’?
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add rule inet fw4 PSW2_OUTPUT_MANGLE_V6 ip6 daddr @passwall2_global_whitelist6 counter return
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]: add rule inet fw4 PSW2_MANGLE ip protocol tcp ip daddr @passwall2_global_whitelist counter return comment ""
Tue Sep 26 04:26:07 2023 daemon.err uhttpd[1707]:                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:08 2023 daemon.err uhttpd[1707]: Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?
Tue Sep 26 04:26:08 2023 daemon.err uhttpd[1707]: add rule inet fw4 PSW2_MANGLE ip protocol udp ip daddr @passwall2_global_whitelist counter return comment ""
Tue Sep 26 04:26:08 2023 daemon.err uhttpd[1707]:                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Tue Sep 26 04:26:08 2023 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM

### 系统相关信息

Passwall版本：1.20-15
Openwrt版本：23.05-rc3

**Comment by hsj1992** [comment]
#https://github.com/xiaorouji/openwrt-passwall2/issues/397#issuecomment-1732411488

**Comment by hsj1992** [comment]
Duplicate of #397 
#https://github.com/xiaorouji/openwrt-passwall2/issues/397#issuecomment-1732411488
