### ISSUE TITLE
v2ray-core云编译报错

### ISSUE THREAD

**Issue by Lancet-z** [xiaorouji/openwrt-passwall2#41]
v2ray-core在lede源码下编译会报错，不知是那一方的问题。我是希望用xray完全替代v2ray，请问编译的时候应该如何去修改。

make[3]: Entering directory '/workdir/openwrt/feeds/passwall/v2ray-core'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.v2ray-core-5.0.3.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "v2ray-core-5.0.3.tar.gz" "c0fe91f715293cfc39a5afeef71e1ff43d379ae0faa139c560fdc3ede88a458a" "" "https://codeload.github.com/v2fly/v2ray-core/tar.gz/v5.0.3?"    '
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v5" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v5/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOARM="" GOMIPS="" GOMIPS64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3=v2ray-core-5.0.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3=v2ray-core-5.0.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1649178380' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X github.com/v2fly/v2ray-core/v5.build=OpenWrt -X github.com/v2fly/v2ray-core/v5.version=5.0.3 -buildid '1649178380' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
github.com/marten-seemann/qtls-go1-18
# github.com/marten-seemann/qtls-go1-18
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:141:43: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:399:45: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:404:46: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:412:45: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/common.go:1496:41: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:177:10: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:183:13: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:211:62: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:973:14: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:1056:33: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:973:14: too many errors
note: module requires Go 1.18

make[3]: *** [Makefile:111: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/passwall/v2ray-core'
time: package/feeds/passwall/v2ray-core/compile#2.86#0.94#2.47
    ERROR: package/feeds/passwall/v2ray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/v2ray-core/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by sacrish** [comment]
是否是以前编译的时候勾选过v2ray，后来去掉了？
我遇到过类似的问题，猜测是去掉v2ray勾选之后，依赖项还保留着并且会被编译。解决办法是删掉.config，重新生成一个，并且不要选v2ray。

**Comment by Lancet-z** [comment]
> 是否是以前编译的时候勾选过v2ray，后来去掉了？ 我遇到过类似的问题，猜测是去掉v2ray勾选之后，依赖项还保留着并且会被编译。解决办法是删掉.config，重新生成一个，并且不要选v2ray。

新版的编译项里没有了xray，只有v2ray。应该如何选择，不勾选吗。。我现在是勾选v2ray，然后在.config里去除v2ray-core的选中，同时生成的.config中有xray-core被选中，但是编译选项中并没。不知道该如何操作

**Comment by sacrish** [comment]
> > 是否是以前编译的时候勾选过v2ray，后来去掉了？ 我遇到过类似的问题，猜测是去掉v2ray勾选之后，依赖项还保留着并且会被编译。解决办法是删掉.config，重新生成一个，并且不要选v2ray。
> 
> 新版的编译项里没有了xray，只有v2ray。应该如何选择，不勾选吗。。我现在是勾选v2ray，然后在.config里去除v2ray-core的选中，同时生成的.config中有xray-core被选中，但是编译选项中并没。不知道该如何操作

xray应该是自带的，不需要选v2ray。以下是我自己的配置。
![Screenshot 2022-04-06 175236](https://user-images.githubusercontent.com/8361680/161948943-a9e05135-38d0-415c-9218-958fa55c6558.png)
