### ISSUE TITLE
[Bug]: 错误向局域网内下发DDNS的IP

### ISSUE THREAD

**Issue by AxIauk** [xiaorouji/openwrt-passwall2#412]
### 描述您遇到的bug

拨号 ->正确更新DDNS -> 联通DNS正确同步DDNS -> passwall2正确获得DDNS的IP -> 下发至局域网。正常10多分钟后，passwall2开始下发错误的DDNS的IP（上次拨号IP）
此时查询DDNS服务商，联通服务商，公共DNS服务商都获得正确IP， 不知为何偏偏局域网passwall2从正常IP变更为上次拨号IP往局域网里下发。 重启 passwall2 就好了。 但过10分钟又出这个问题。重启1，2次后正常。

全新OpenWrt 23.05.0-rc3，未安全其他多余软件。DDNS更新脚本自己写的放在服务器里。（大意是5分钟查询一次IPV6，当发现IPV6变化时更新IPV4和IPV6至he.net）

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

无

### 其他信息

无

**Comment by AxIauk** [comment]
passwall2 DNS 选项为
远程 仅使用IPV4 TCP 8.8.8.8，未启动FakeDNS

**Comment by Biercenter** [comment]
你的问题不知道跟我的问题有没有关系。我是局域网下默认不代理所以关闭了主开关，只在访问控制里添加几台需要代理的设备并开启（访问控制里的开关），然后也是过了十来分钟，打开网页会显示找不到服务器IP

**Comment by AxIauk** [comment]
似乎跟服务器里systemd-resolved有关，他能干扰上游 DNS吗？
