### ISSUE TITLE
[Feature Request]: 规则列表中的直连ip能不能添加到passwall2_global_whitelist中？

### ISSUE THREAD

**Issue by maskedeken** [xiaorouji/openwrt-passwall2#413]
### 描述你想要的新功能

目前规则列表中直连域名是会添加到passwall2_global_whitelist中，实现不经过核心的直连，但ip则没有

### 描述你想要的解决方案

规则列表中直连ip也添加到passwall2_global_whitelist中，实现不经过核心的直连

**Comment by xiaorouji** [comment]
需要改core，我私下用的就是，不过暂时无法开源
