### ISSUE TITLE
[Bug]: Hysteria2 会导致Paswall2的DNS间歇性不正常工作

### ISSUE THREAD

**Issue by franklee628** [xiaorouji/openwrt-passwall2#416]
### 描述您遇到的bug

<img width="1128" alt="Screenshot 2023-10-09 at 11 06 23" src="https://github.com/xiaorouji/openwrt-passwall2/assets/10163908/73127047-915a-410d-ab5c-cc01f30db3d7">

如上图所示，默认节点使用Hysteria2协议时，经常会有几万甚至十几万ms的时候。

具体表现为已经打开的网页，刷新和访问都正常，但如果是打开新的网站，则会出现延迟几秒至几十秒的情况。怀疑是DNS的问题。而如果把默认节点切换成例如Vmess则完全没问题。

### 复现此Bug的步骤

使用 Xray_shunt 分流
默认节点选用 Hysteria2自建节点
其他选项默认

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

- Passwall 版本 git-24.270.44907-19931a8
- Xray 版本 1.8.4
- Openwrt 版本 23.05.0-rc4

**Comment by jliveusa** [comment]
不仅是Hysteria2，1.20后的版本有概率出现断网情况，经常提示PPPOE及WAN口断开重连，已经退回1.19

**Comment by franklee628** [comment]
更新一下，Hysteria2 服务端和客户端都升级到 2.1.0 后使用了一小时, 目前没有出现问题。

在此之前，根据网友的反馈，使用 Sing-box 实现 hysteria2 的时候也没有问题，不过暂时不支持端口跳跃而已。
