### ISSUE TITLE
[Feature Request]: 支持sing-box 加强版的geosite geoip 

### ISSUE THREAD

**Issue by rianjskis** [xiaorouji/openwrt-passwall2#417]
### 描述你想要的新功能

支持加强版的geoip.db geosite.db

### 描述你想要的解决方案
https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db
https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db
当使用加强版本的geosite geoip 时能启动但是外网连不通，默认的geosite 已经很久没更新了，请支持加强版

**Comment by Travel2Here** [comment]
同求解决方案，因为这个问题 我很难用起来SINGBOX 。不想用大陆以外全代理 默认的支持的类目太少了，换了别的类目足但功能又不正常

**Comment by Gzxhwq** [comment]
> ### 描述你想要的新功能
> 
> 支持加强版的geoip.db geosite.db
> ### 描述你想要的解决方案
> 
> https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db 当使用加强版本的geosite geoip 时能启动但是外网连不通，默认的geosite 已经很久没更新了，请支持加强版
> ### 描述你考虑过的替代方案
> 
> _No response_
> ### 其他信息
> 
> _No response_

我一直都是用这个规则，完全没问题哦

**Comment by xiaorouji** [comment]
测试可用

**Comment by rianjskis** [comment]
> 测试可用

您好，我在1.20-13版本中使用加强版的geosite geoip 第一次下载出来可以正常使用，如果切换一次节点的话就会不通，请问是版本问题吗，我用的协议是hy2跟tuic

**Comment by rianjskis** [comment]
> > ### 描述你想要的新功能
> > 
> > 支持加强版的geoip.db geosite.db
> > ### 描述你想要的解决方案
> > 
> > https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db 当使用加强版本的geosite geoip 时能启动但是外网连不通，默认的geosite 已经很久没更新了，请支持加强版
> > ### 描述你考虑过的替代方案
> > 
> > _No response_
> > ### 其他信息
> > 
> > _No response_
> 
> 我一直都是用这个规则，完全没问题哦


当使用加强版的geosite geoip ，我用ss节点是可以正常使用，使用singbox运行的hy2,tuic则显示外网不通

**Comment by Gzxhwq** [comment]
> > > ### 描述你想要的新功能
> > > 支持加强版的geoip.db geosite.db
> > > ### 描述你想要的解决方案
> > > https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db 当使用加强版本的geosite geoip 时能启动但是外网连不通，默认的geosite 已经很久没更新了，请支持加强版
> > > ### 描述你考虑过的替代方案
> > > _No response_
> > > ### 其他信息
> > > _No response_
> > 
> > 
> > 我一直都是用这个规则，完全没问题哦
> 
> 当使用加强版的geosite geoip ，我用ss节点是可以正常使用，使用singbox运行的hy2,tuic则显示外网不通

我自己在用的就有vless+vision+reality、trojan+reality+h2mux、ss、hy2、tuic，没法重现

**Comment by rianjskis** [comment]
> > > > ### 描述你想要的新功能
> > > > 支持加强版的geoip.db geosite.db
> > > > ### 描述你想要的解决方案
> > > > https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db 当使用加强版本的geosite geoip 时能启动但是外网连不通，默认的geosite 已经很久没更新了，请支持加强版
> > > > ### 描述你考虑过的替代方案
> > > > _No response_
> > > > ### 其他信息
> > > > _No response_
> > > 
> > > 
> > > 我一直都是用这个规则，完全没问题哦
> > 
> > 当使用加强版的geosite geoip ，我用ss节点是可以正常使用，使用singbox运行的hy2,tuic则显示外网不通
> 
> 我自己在用的就有vless+vision+reality、trojan+reality+h2mux、ss、hy2、tuic，没法重现

更新最新版后，可以正常使用加强版的geosite geoip 了
