### ISSUE TITLE
[Feature Request]: 能否新增一个移除Xray的选项

### ISSUE THREAD

**Issue by kvmcore** [xiaorouji/openwrt-passwall2#418]
### 描述你想要的新功能

编译passwall2 默认是勾选xray-core的，而且还不能移除，能否新增一个移除xray的选项？因为运行xray动不动就是oom，小内存设备用的很痛苦，sing-box不会出现这个情况

### 描述你想要的解决方案

新增移除Xray的选项

**Comment by hcym** [comment]
是的，好像7621也能折腾

**Comment by hxlls** [comment]
我也发现了，PW2好像不支持取消XRAY

**Comment by canmengxian** [comment]
在Makefile文件的34行把+xray-core 删除，试试看

**Comment by Deleted-Account** [comment]
不要Xray，那你用Passwall2的目的是？
不如考虑下隔壁的Passwall1？
