### ISSUE TITLE
[Bug]: hysteria 带宽参数

### ISSUE THREAD

**Issue by swxk521** [xiaorouji/openwrt-passwall2#419]
### 描述您遇到的bug

hysteria带宽参数无法为空值
hysteria源代码中为空值时使用BBR。
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/61259428/4c3716c8-a8c7-4fe3-8211-daf35cbce51d)
查看passwall2代码 
去掉默认值o.default = "100" 和将 		
bandwidth = {
			up = node.hysteria2_up_mbps and node.hysteria2_up_mbps .. " mbps" or "100 mbps",
			down = node.hysteria2_down_mbps and node.hysteria2_down_mbps .. " mbps" or "100 mbps"
		},
改为
bandwidth = {
			up = node.hysteria2_up_mbps and node.hysteria2_up_mbps .. " mbps" or nil,
			down = node.hysteria2_down_mbps and node.hysteria2_down_mbps .. " mbps" or nil,
		},

运行后配置文件有
bandwidth = {
		},
导致无法连接，希望当up和down都为空值时去除bandwidth

**Comment by Gzxhwq** [comment]
Try https://github.com/xiaorouji/openwrt-passwall2/pull/421

**Comment by swxk521** [comment]
> Try #421

测试成功。
