### ISSUE TITLE
在ipv6环境下，开启passwall2后会默认使用ipv4

### ISSUE THREAD

**Issue by sacrish** [xiaorouji/openwrt-passwall2#42]
使用的是LIenol最新源码。

在不开启passwall2的情况下，test-ipv6.com测试通过，ipv6.ustb.edu.cn获取到的也是ipv6地址。

开启passwall2，使用xray分流，节点本身支持ipv6（曾经用passwall是没问题的），勾选了ipv6透明代理。test-ipv6.com测试虽然通过，但显示浏览器默认使用ipv4；ipv6.ustb.edu.cn获取到的也是我的ipv4地址。

（并且有时访问直连网站会报 DNS_PROBE_FINISHED_NXDOMAIN 错误，不清楚是否与这个问题相关。）

不确定是passwall2本身的原因，还是我的配置不对。能否帮我分析一下是什么引起的问题？谢谢！

**Comment by yunxi993** [comment]
test有时候测试抽风，你看网站实际有没有使用IPv6连接.

**Comment by sacrish** [comment]
> test有时候测试抽风，你看网站实际有没有使用IPv6连接.

开启passwall2后， http://ipv6.ustb.edu.cn/ 和 https://ipw.cn/ 显示我在通过ipv4连接，并且上不去[清华的ipv6站](https://ipv6.tsinghua.edu.cn/)。但是[这个网站](http://speed.neu6.edu.cn/)的ipv6测速是能测到的。

关闭passwall2，上述网站都正常通过ipv6连接。

另外我觉得跟DNS可能有关。如果我先不开passwall2，打开那几个网站后，再开启passwall2。这时如果不刷新DNS缓存，是可以暂时正常用的。刷新DNS缓存后，就变成了前面描述的症状。

**Comment by yunxi993** [comment]
> > test有时候测试抽风，你看网站实际有没有使用IPv6连接.
> 
> 开启passwall2后， http://ipv6.ustb.edu.cn/ 和 https://ipw.cn/ 显示我在通过ipv4连接，并且上不去[清华的ipv6站](https://ipv6.tsinghua.edu.cn/)。但是[这个网站](http://speed.neu6.edu.cn/)的ipv6测速是能测到的。
> 
> 关闭passwall2，上述网站都正常通过ipv6连接。
> 
> 另外我觉得跟DNS可能有关。如果我先不开passwall2，打开那几个网站后，再开启passwall2。这时如果不刷新DNS缓存，是可以暂时正常用的。刷新DNS缓存后，就变成了前面描述的症状。

这俩玩意儿貌似都有问题，与你相同。
但是 在实际浏览支持IPv6的域名、仍然是IPv6连接优先，国内外都如此.

**Comment by sacrish** [comment]
> > > test有时候测试抽风，你看网站实际有没有使用IPv6连接.
> > 
> > 
> > 开启passwall2后， http://ipv6.ustb.edu.cn/ 和 https://ipw.cn/ 显示我在通过ipv4连接，并且上不去[清华的ipv6站](https://ipv6.tsinghua.edu.cn/)。但是[这个网站](http://speed.neu6.edu.cn/)的ipv6测速是能测到的。
> > 关闭passwall2，上述网站都正常通过ipv6连接。
> > 另外我觉得跟DNS可能有关。如果我先不开passwall2，打开那几个网站后，再开启passwall2。这时如果不刷新DNS缓存，是可以暂时正常用的。刷新DNS缓存后，就变成了前面描述的症状。
> 
> 这俩玩意儿貌似都有问题，与你相同。 但是 在实际浏览支持IPv6的域名、仍然是IPv6连接优先，国内外都如此.

又试了 http://ds.testmyipv6.com/ 这个测试网站。纯ipv6测试是通过的，但是双栈测试就会走ipv4。另外开passwall2后清华ipv6站上不去，所以我感觉还是有问题的。

顺便问下你的接口ipv6配置是什么样的？

**Comment by yunxi993** [comment]
> 又试了 http://ds.testmyipv6.com/ 这个测试网站。纯ipv6测试是通过的，但是双栈测试就会走ipv4。另外开passwall2后清华ipv6站上不去，所以我感觉还是有问题的。
> 
> 顺便问下你的接口ipv6配置是什么样的？


清华的我可以访问，不过是使用的ipv4

默认的，就是把ipv6的DHCP关了，仅使用SLAAC

**Comment by yunxi993** [comment]
> 

![image](https://user-images.githubusercontent.com/59167936/162892826-16b5233c-383f-4d6c-a243-bb7eff6b4c5d.png)

**Comment by badgv** [comment]
> 

你是用了什么配置吗？按现在PSW2的配置，不太可能解析出IPV6地址的。

**Comment by yunxi993** [comment]
> 你是用了什么配置吗？按现在PSW2的配置，不太可能解析出IPV6地址的。 你可以ps|grep xray，看下global.json的配置文件，UseIPv4你这能解析出IPV6也是奇怪了


不是一直都可以吗？
国内外一直都可以IPv6

就是防火墙有问题，根据 `xiaorouji` 的说法，规则生成在passwall2后面了，前面已经被passwall2处理了.

**Comment by badgv** [comment]
> > 你是用了什么配置吗？按现在PSW2的配置，不太可能解析出IPV6地址的。 你可以ps|grep xray，看下global.json的配置文件，UseIPv4你这能解析出IPV6也是奇怪了
> 
> 不是一直都可以吗？ 国内外一直都可以IPv6
> 
> 就是防火墙有问题，根据 `xiaorouji` 的说法，规则生成在passwall2后面了，前面已经被passwall2处理了.

新版本的psw2，默认xray配置文件使用的是UseIPv4，不太可能解析出IPV6的，可能你有其它配置导致这样的情况吧……

**Comment by sacrish** [comment]
> 你去看下现在的psw2的DNS处理过程就知道是怎么回事了。 默认dns请求会直接redirect给53端口(dnsmasq)，psw2对dnsmasq配置了 server=127.0.0.1#15353 all-servers no-poll no-resolv 这几个参数，也就是dnsmasq的DNS请求会无视WAN口的DNS配置，并把DNS请求发向xray的dns模块处理。 而XRAY的dns模块使用了domainStrategy = "UseIPv4"这个规则，也就是说xray只会查询ipv4地址。
> 
> 这样现在导致的结果就是： 1、DNS解析双栈的域名，只会返回IPV4的服务端地址。所以你用PSW2的时候，你是没办法访问拥有IPV6地址的域名的，你只能访问该站点的IPV4域名。
> 
> 2、DNS解析纯IPV6的域名，什么都不会返回，导致根本无法访问。 如下图所示： ![image](https://user-images.githubusercontent.com/45598380/162889835-8a04a6b5-3d63-43eb-881a-535b20c06e4f.png)
> 
> 总感觉现在的纯XRAY分流模式，不如以前psw完全使用的dnsmasq的DNS分流模式合理，特别是在有IPV6的情况下。 旧版本可以配置出，只对GFW域名或手动添加的需要代理的域名解析屏蔽IPV6地址。正常的国内域名和直连域名可以正常返回IPV6地址。

原来如此，感谢解惑。

记得passwall的DNS设置是选择UseIP/UseIPv4/UseIPv6，希望能把这个选项加回来。

**Comment by badgv** [comment]
> 

我是默认配置，没添加过其它的sysconfig配置，没试过你这样配置的情况。总的来说现在pw2的功能不太符合我的使用预期啊……。

**Comment by badgv** [comment]
> > 我是默认配置，没添加过其它的sysconfig配置，没试过你这样配置的情况。总的来说现在pw2的功能不太符合我的使用预期啊……。
> 
> 你有开启代理IPv6流量吗？

没有代理IPV6，我的预期功能是需要代理的全走IPV4，要走IPV6的肯定不会走代理

**Comment by zurica2013** [comment]
> 功能不太符合我的

感谢大佬解答了我多日的困惑。电信用户IPv6是刚需，没办法

**Comment by zurica2013** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/59167936/162892826-16b5233c-383f-4d6c-a243-bb7eff6b4c5d.png)

兄台你的主机名很销魂啊！

**Comment by zurica2013** [comment]
> 你去看下现在的psw2的DNS处理过程就知道是怎么回事了。 默认dns请求会直接redirect给53端口(dnsmasq)，psw2对dnsmasq配置了 server=127.0.0.1#15353 all-servers no-poll no-resolv 这几个参数，也就是dnsmasq的DNS请求会无视WAN口的DNS配置，并把DNS请求发向xray的dns模块处理。 而XRAY的dns模块使用了domainStrategy = "UseIPv4"这个规则，也就是说xray只会查询ipv4地址。
> 
> 这样现在导致的结果就是： 1、DNS解析双栈的域名，只会返回IPV4的服务端地址。所以你用PSW2的时候，你是没办法访问拥有IPV6地址的域名的，你只能访问该站点的IPV4域名。
> 
> 2、DNS解析纯IPV6的域名，什么都不会返回，导致根本无法访问。 如下图所示： ![image](https://user-images.githubusercontent.com/45598380/162889835-8a04a6b5-3d63-43eb-881a-535b20c06e4f.png)
> 
> 总感觉现在的纯XRAY分流模式，不如以前psw完全使用的dnsmasq的DNS分流模式合理，特别是在有IPV6的情况下。 旧版本可以配置出，只对GFW域名或手动添加的需要代理的域名解析屏蔽IPV6地址。正常的国内域名和直连域名可以正常返回IPV6地址。

感谢大佬解答了我多日的困惑。电信用户IPv6是刚需，没办法

**Comment by badgv** [comment]
新的源码已经可以自由定义dns了，很好用，赶紧更新吧，这个问题感觉可以关了

**Comment by yunxi993** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/59167936/162892826-16b5233c-383f-4d6c-a243-bb7eff6b4c5d.png)
> 
> 兄台你的主机名很销魂啊！

因为默认的运营商有时候会搞事情.

**Comment by zurica2013** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/59167936/162892826-16b5233c-383f-4d6c-a243-bb7eff6b4c5d.png)
> > 
> > 
> > 兄台你的主机名很销魂啊！
> 
> 因为默认的运营商有时候会搞事情.

不知道你说的运营商搞事情是指？
你这么一说我想起来了，原来在路由器里看到过这样的日志：
Tue Oct 26 22:07:50 2021 user.notice nft-qos-monitor: ACTION=update, MACADDR=74:c2:85:3b:22:cc, IPADDR=192.168.5.183, HOSTNAME=OpenWrt
但是这个主机名对应的IP明显不是软路由的IP，最后也没查明白是怎么回事

**Comment by sacrish** [comment]
1.3版本自定义DNS在IPv6下测试正常了。
