### ISSUE TITLE
[Bug]: passwall2启动守护进程仍会一段时间后会停止工作，ss-local invoked oom-killer

### ISSUE THREAD

**Issue by imace3** [xiaorouji/openwrt-passwall2#424]
### 描述您遇到的bug

更新后，passwall2开机启动时间变长并且会自动停止工作。

设置开机延时启动1秒，开启守护进程，仍然是在运行一段时间后，自动停止工作。

### 复现此Bug的步骤

设置开机延时启动1秒，开启守护进程，仍然是在运行一段时间后，passwall2自动停止工作，页面显示Xray未运行，保存并应用后重启启动passwall2恢复正常。

### 您想要实现的目的

解决进程保护问题。

### 日志信息

Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.332246] ss-local invoked oom-killer: gfp_mask=0x1100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.334568] CPU: 0 PID: 27096 Comm: ss-local Not tainted 5.15.134 #0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.335146] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.336322] Call Trace:
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.336810]  <TASK>
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.337287]  dump_stack_lvl+0x4b/0x65
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.337820]  dump_stack+0x10/0x16
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.338323]  dump_header+0x4a/0x18a
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.338825]  oom_kill_process.cold+0xb/0x10
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.339351]  out_of_memory+0x1e5/0x280
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.339879]  __alloc_pages_slowpath.constprop.0+0xaee/0xc20
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.340463]  __alloc_pages+0x204/0x270
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.340989]  pagecache_get_page+0x120/0x390
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.341527]  filemap_fault+0x1a3/0x7a0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.342055]  __do_fault+0x32/0x90
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.342981]  __handle_mm_fault+0x9fd/0xdf0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.344912]  handle_mm_fault+0x111/0x300
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.345452]  exc_page_fault+0x1ad/0x5b0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.346001]  asm_exc_page_fault+0x27/0x30
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.346554] RIP: 0033:0x7ff04917f592
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.347096] Code: Unable to access opcode bytes at RIP 0x7ff04917f568.
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.347729] RSP: 002b:00007fff7044cfe0 EFLAGS: 00010206
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.348337] RAX: 00000000919c2169 RBX: 00007fff7044cfe0 RCX: 00007fff7044cfe0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.349002] RDX: 00007ff04904b190 RSI: 00007ff04904b170 RDI: 00007ff04904b18c
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.349677] RBP: 00007ff048f4c390 R08: 00007ff04904b1b0 R09: 00007fff7044d090
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.350353] R10: 0000000000000040 R11: 000000000000000c R12: 0000000000000000
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.351032] R13: 00007fff7044d090 R14: 00007fff7044d070 R15: 0000000000000000
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.351705]  </TASK>
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.352259] Mem-Info:
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224] active_anon:112460 inactive_anon:34869 isolated_anon:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  active_file:0 inactive_file:854 isolated_file:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  unevictable:0 dirty:3 writeback:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  slab_reclaimable:17306 slab_unreclaimable:68211
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  mapped:10 shmem:8593 pagetables:998 bounce:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  kernel_misc_reclaimable:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.353224]  free:5014 free_pcp:221 free_cma:0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.358830] Node 0 active_anon:449840kB inactive_anon:139476kB active_file:0kB inactive_file:3416kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:40kB dirty:12kB writeback:0kB shmem:34372kB writeback_tmp:0kB kernel_stack:3616kB pagetables:3992kB all_unreclaimable? no
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.360883] DMA free:4100kB min:248kB low:308kB high:368kB reserved_highatomic:0KB active_anon:9180kB inactive_anon:1176kB active_file:0kB inactive_file:84kB unevictable:0kB writepending:0kB present:15992kB managed:15360kB mlocked:0kB bounce:0kB free_pcp:12kB local_pcp:12kB free_cma:0kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.363802] lowmem_reserve[]: 0 965 965 965
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.365638] DMA32 free:15956kB min:16132kB low:20164kB high:24196kB reserved_highatomic:0KB active_anon:440660kB inactive_anon:138300kB active_file:0kB inactive_file:3332kB unevictable:0kB writepending:12kB present:1031616kB managed:993096kB mlocked:0kB bounce:0kB free_pcp:872kB local_pcp:872kB free_cma:0kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.368139] lowmem_reserve[]: 0 0 0 0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.368831] DMA: 5*4kB (UM) 4*8kB (U) 3*16kB (UM) 3*32kB (UM) 9*64kB (UM) 6*128kB (UM) 0*256kB 1*512kB (M) 2*1024kB (M) 0*2048kB 0*4096kB = 4100kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.370394] DMA32: 621*4kB (UME) 364*8kB (UME) 226*16kB (UME) 37*32kB (UME) 18*64kB (UME) 10*128kB (UM) 7*256kB (UM) 3*512kB (UM) 0*1024kB 0*2048kB 0*4096kB = 15956kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.372036] 9454 total pagecache pages
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.372754] 0 pages in swap cache
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.374252] Swap cache stats: add 0, delete 0, find 0/0
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.376013] Free swap  = 0kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.376714] Total swap = 0kB
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.377411] 261902 pages RAM
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.378108] 0 pages HighMem/MovableOnly
Sun Oct 22 21:50:51 2023 kern.warn kernel: [196031.378858] 9788 pages reserved
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.379613] Tasks state (memory values in pages):
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.380366] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.381268] [    976]    81   976      258       40    36864        0             0 ubusd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.382140] [    978]     0   978      191        8    36864        0             0 askfirst
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.383017] [   1013]     0  1013      208       16    40960        0             0 urngd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.385488] [   1469]   514  1469      252       38    45056        0             0 logd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.386532] [   1523]     0  1523      637      254    45056        0             0 rpcd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.387396] [   1732]     0  1732      238       14    32768        0             0 dropbear
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.388272] [   2126]     0  2126      345       48    40960        0             0 netifd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.389142] [   2254]     0  2254      282       32    36864        0             0 odhcpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.390002] [   2359]     0  2359      212       16    40960        0             0 odhcp6c
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.390860] [   2455]     0  2455     1185      109    45056        0             0 ocserv-main
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.391736] [   2509]     0  2509     1168       95    45056        0             0 ocserv-sm
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.392594] [   2719]     0  2719      302       60    45056        0             0 uhttpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.393439] [   2813]     0  2813      218       13    36864        0             0 xl2tpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.396074] [   3496]     0  3496   221154    19600   442368        0             0 AdGuardHome
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.396927] [   3795]     0  3795      544       28    40960        0             0 ntpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.397768] [   3801]   123  3801      286       13    40960        0             0 ntpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.398603] [   5141]  8118  5141      602      242    40960        0             0 privoxy
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.399441] [  12812]     0 12812     1808      405    53248        0             0 ssr-server
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.400292] [  12815]     0 12815   312635     1502   147456        0             0 sing-box
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.401131] [  12818]     0 12818   310360     1564   135168        0             0 hysteria
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.401980] [  12821]     0 12821   313342      874   151552        0             0 xray
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.402803] [  12873]     0 12873  1358464      366   114688        0             0 trojan-go
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.403640] [  12876]     0 12876     2300      239    53248        0             0 trojan-plus
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.406397] [  13029]     0 13029     1764      140    53248        0             0 ttyd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.407194] [   1786]     0  1786      304       31    45056        0             0 miniupnpd
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.407984] [  17864]     0 17864     5277     3705    90112        0             0 smartdns
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.408751] [  25682]     0 25682   313470     2296   172032        0             0 xray
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.409496] [  25717] 65534 25717     1854     1089    57344        0             0 dnsmasq
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.410239] [  25748]     0 25748   313598     2287   204800        0             0 xray
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.410966] [  25979]     0 25979      610      124    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.411706] [  26203]     0 26203      529       56    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.412410] [  26426]     0 26426      558       68    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.413096] [  26649]     0 26649      516       32    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.413772] [  26873]     0 26873      516       32    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.416185] [  27096]     0 27096      814      287    49152        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.416893] [  27319]     0 27319      568       83    40960        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.417513] [  27543]     0 27543      537       52    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.418116] [  27766]     0 27766      516       33    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.418711] [  27989]     0 27989      516       32    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.419302] [  28213]     0 28213      516       32    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.419887] [  28436]     0 28436      558       53    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.420473] [  28659]     0 28659      560       64    40960        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.421056] [  28883]     0 28883      818      268    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.421654] [  29106]     0 29106      518       44    40960        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.422236] [  29329]     0 29329      516       32    40960        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.422842] [  29552]     0 29552      518       44    45056        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.423455] [  29776]     0 29776      528       50    40960        0             0 ss-local
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.424036] [  29810]     0 29810   437592   101407  1196032        0             0 xray
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.426483] [  30362]     0 30362      544       28    49152        0             0 dnsmasq
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.427049] [  30369]   453 30369      967      174    40960        0             0 dnsmasq
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.427643] [  30433]     0 30433      290       16    40960        0             0 monitor.sh
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.428249] [  30479]     0 30479      287       14    40960        0             0 crond
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.428812] [   4045]     0  4045      262        8    45056        0             0 luci
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.429357] [   4047]     0  4047      260        6    36864        0             0 sleep
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.429904] [   4048]     0  4048      165        4    36864        0             0 askfirst
Sun Oct 22 21:50:51 2023 kern.info kernel: [196031.430462] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=xray,pid=29810,uid=0
Sun Oct 22 21:50:51 2023 kern.err kernel: [196031.431569] Out of memory: Killed process 29810 (xray) total-vm:1750368kB, anon-rss:405628kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1168kB oom_score_adj:0

### 系统相关信息

OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8

luci-app-passwall2 | 1.21-3

**Comment by hcym** [comment]
1秒不好吧，我一直用默认，60，最近几天的版本相当不错

**Comment by imace3** [comment]
> 1秒不好吧，我一直用默认，60，最近几天的版本相当不错

感觉60秒启动太久了。另外1秒和60秒对系统造成的影响差距是什么？为什么默认是60秒？

**Comment by dsyo2008** [comment]
> > 1秒不好吧，我一直用默认，60，最近几天的版本相当不错
> 
> 感觉60秒启动太久了。另外1秒和60秒对系统造成的影响差距是什么？为什么默认是60秒？

开机启动太多了，你说呢，不推荐1秒，建议10秒以上测试下
