### ISSUE TITLE
[Bug]: 直接使用Hysteria2官方客户端会导致测试页面延迟翻倍

### ISSUE THREAD

**Issue by w123456w30w** [xiaorouji/openwrt-passwall2#425]
### 描述您遇到的bug

直接使用Hysteria2官方客户端配置在主页面测试Github与Google延迟很高，Sing-box实现的Hysteria2和在终端里面单独启动一个Hysteria2监听socks没有这个问题

### 复现此Bug的步骤

直接使用Hysteria2官方客户端配置连接服务器
点击测试延迟

### 您想要实现的目的

连接延迟恢复正常

### 日志信息

无

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/30130993/bd6d3b48-5404-455f-9ad7-7612970c541b)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/30130993/4ffcc9ad-61ec-435b-99d3-957b749925e1)

### 系统相关信息

luci-app-passwall2 | 1.21-3

**Comment by eqfae** [comment]
你用的什么vps 还是机场 这延迟好厉害 能玩游戏了不丢包的话
