### ISSUE TITLE
[Feature Request]: Please add support for ShadowTLS 

### ISSUE THREAD

**Issue by mfat** [xiaorouji/openwrt-passwall2#426]
### 描述你想要的新功能

Please add support for shadowTLS protocol.

### 描述你想要的解决方案

Shadow TLS notes can be added to the node types.

**Comment by Gzxhwq** [comment]
Already had ShadowTLS support by sing-box.

**Comment by mfat** [comment]
Thanks. I can't find any menu item for ShadowTLS. Should I configure manually?

**Comment by Gzxhwq** [comment]
Upgrade to the latest Passwall, install sing-box

Select node type: Sing-Box ->  protocol: Shadowsocks/Vmess, then you should see the ShadowTLS option.

**Comment by mfat** [comment]
Thanks much!

**Comment by mfat** [comment]
One more question: when will you add support for hy2 links?

**Comment by Gzxhwq** [comment]
"Shadow"TLS is NOT TLS. You must know what is it.

**Comment by mfat** [comment]
Thanks. In my config file there is this part that's why I asked:

```
"tls": {
                "enabled": true,
                "server_name": "www.speedtest.net",
```

**Comment by Gzxhwq** [comment]
Sing-box reuse this tls struct to provide "server_name" parameter, and passwall name it to "ShadowTLS Domain".
