### ISSUE TITLE
删除singbox文件内domain_strategy可以实现域名分流吗?

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#427]
### 描述你想要的新功能

删除`util_sing-box.lua`文件内的两行:
`domain_strategy = (dns_query_strategy and dns_query_strategy ~= "UseIP") and "ipv4_only" or "prefer_ipv6",`

可以实现如Xray AsIs 的域名匹配吗?

根据Singbox文档 domain_strategy 优先级是最高的, 只要配置domain_strategy就是IP匹配.
```
domain_strategy
可选值： prefer_ipv4 prefer_ipv6 ipv4_only ipv6_only。

如果设置，请求的域名将在路由之前解析为 IP。
```

### 描述你想要的解决方案

删除`util_sing-box.lua`文件内的两行:
`domain_strategy = (dns_query_strategy and dns_query_strategy ~= "UseIP") and "ipv4_only" or "prefer_ipv6",`

**Comment by Gzxhwq** [comment]
你先搞清楚，这是插在outbound direct的，和你描述的并不是一个地方，dial和listene的行为也是不同的。

https://sing-box.sagernet.org/configuration/shared/dial/#domain_strategy

**Comment by xiaoshengshuohua** [comment]
> 你先搞清楚，这是插在outbound direct的，和你描述的并不是一个地方，dial和listen的行为也是不同的。
> 
> https://sing-box.sagernet.org/configuration/shared/dial/#domain_strategy

谢谢解释!
那么是否有方法可以实现类似 `AsIs` 域名分流.

**Comment by Gzxhwq** [comment]
你传入的是域名的话，现在就是只匹配域名路由规则，也就是*ray的AsIs，并不会多做DNS解析，因为passwall没有设置inbound domain_strategy。
但因为是透明代理，传入的基本就是IP，而不会是域名。

**Comment by xiaoshengshuohua** [comment]
> 你传入的是域名的话，现在就是只匹配域名路由规则，也就是*ray的AsIs，并不会多做DNS解析，因为passwall没有设置inbound domain_strategy。 但因为是透明代理，传入的基本就是IP，而不会是域名。

好吧, Thanks!
