### ISSUE TITLE
[Bug]: 当默认(final)节点设为直连时，丧失了正确进行DNS远程解析的能力。

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#439]
### 描述您遇到的bug

如果分流里为默认(final)配置了一个节点，能正常输出配置为remote 、 remote_fakeip以及多个分流标签下的dns servers。
如题，当默认(final)配置为直连，以黑名单的方式使用，则配置文件里的dns servers就会缺少对应节点的dns配置，导致丧失远程dns的能力。从而得到都是被污染的结果。

### 复现此Bug的步骤

以黑名单方式配置代理分流，默认节点设为直连。

### 您想要实现的目的

正确按分流方案对应其出口进行远程dns解析。

### 日志信息

来自/tmp/etc/passwall2/global.json。
选择默认(final)为直连得到的dns server配置，可见dns即便是选远程解析，出口依然是直连，并且没有其他几个分流出口对应的dns服务器配置内容：

    "servers": [
      {
        "address": "rcode:\/\/success",
        "tag": "block"
      },
      {
        "address_strategy": "prefer_ipv4",
        "address": "https:\/\/1.1.1.1\/dns-query",
        "address_resolver": "direct",
        "strategy": "ipv4_only",
        "detour": "direct",
        "tag": "remote"
      },
      {
        "strategy": "ipv4_only",
        "address": "fakeip",
        "tag": "remote_fakeip"
      },
      {
        "address_strategy": "prefer_ipv6",
        "address": "udp:\/\/127.0.0.1:15355",
        "strategy": "prefer_ipv6",
        "detour": "direct",
        "tag": "direct"
      }
    ],
    "reverse_mapping": true,
    "disable_expire": false,
    "final": "direct"
  }

### 系统相关信息

最新版1.22。singbox 1.7.8

### 其他信息

难得回归，祝新年顺意！

**Comment by xiaorouji** [comment]
尝试最新的代码

**Comment by Travel2Here** [comment]
> 尝试最新的代码

第一时间哇哇用上了 辛苦

**Comment by etsam** [comment]
好快就更新了！

**Comment by soffio** [comment]
@xiaorouji 我这边试还是有问题，默认节点为直连，不使用 FakeDNS，没有命中域名规则的就走本地 DNS 了，辛苦帮忙再看下
"servers": [
      {
        "queryStrategy": "UseIP",
        "port": 15354,
        "_flag": "default",
        "address": "127.0.0.1"
      },
      {
        "port": 15354,
        "_flag": "Direct",
        "address": "127.0.0.1",
        "queryStrategy": "UseIP",
        "domains": [
          "geosite:cn",
        ]
      },
      {
        "port": 15355,
        "_flag": "Proxy",
        "address": "127.0.0.1",
        "queryStrategy": "UseIPv4",
        "domains": [
          "geosite:geolocation-!cn"
        ]
      }
  ]
