### ISSUE TITLE
[Bug]: log时间问题

### ISSUE THREAD

**Issue by jiemo9527** [xiaorouji/openwrt-passwall2#440]
### 描述您遇到的bug

配置节点的日志，与系统时间不一致，好像不是东八区。希望可调

### 复现此Bug的步骤

开启节点，点击节点日志

### 您想要实现的目的

log记录时间与系统时间一致

### 日志信息

/

### 系统相关信息

最新版1.22-2

**Comment by xiaorouji** [comment]
这和passwall2没有关系，请检查设备的系统时间。

**Comment by soffio** [comment]
同样的问题，安装 `zoneinfo-asia` 可以解决
可以参考这个 https://github.com/v2ray/discussion/issues/570#issuecomment-596398454
