### ISSUE TITLE
[Feature Request]: 期待大佬服务器端sing-box中加入对VLESS-REALITY的支持

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-passwall2#443]
### 描述你想要的新功能

期待大佬服务器端sing-box中加入对VLESS-REALITY的支持

### 描述你想要的解决方案

期待大佬服务器端sing-box中加入对VLESS-REALITY的支持，目前xray中有，但sing-box中没有。

**Comment by lllrrr2** [comment]
![xray](https://github.com/xiaorouji/openwrt-passwall2/assets/61368564/219b132b-423f-4833-995f-6a43d629df7a)

**Comment by lllrrr2** [comment]
![singbox](https://github.com/xiaorouji/openwrt-passwall2/assets/61368564/a99281c8-95c2-4f98-b224-72091c253e86)

**Comment by davidtall** [comment]
有没有可能要勾选uTLS ?

**Comment by lllrrr2** [comment]
我说的是服务器端。

**Comment by swxk521** [comment]
确实，xray服务端没问题，sing-box服务端不完善。
