### ISSUE TITLE
[Feature Request]: 请尽快支持sing-box订阅链接JSON配置解析

### ISSUE THREAD

**Issue by hutao90888** [xiaorouji/openwrt-passwall2#446]
### 描述你想要的新功能

机场面板如v2board已经支持json配置raw链接，加参数&flag=sing-box即可获取，但是passwall2依旧不支持解析
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/143263411/90fe2d85-fe29-4814-b62a-33fce4b19376)

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/143263411/f9a3ed6f-8546-402c-9142-a4c23e446ec1)

### 描述你想要的解决方案

支持解析json配置

**Comment by xiaorouji** [comment]
這個需求暫時不大。
請繼續使用標準通用訂閱鏈接。
