### ISSUE TITLE
[Bug]: 向日葵远程无法使用

### ISSUE THREAD

**Issue by tiantaichenhui** [xiaorouji/openwrt-passwall2#447]
### 描述您遇到的bug

启动passwall2之后向日葵无法正常远程 会提示网络出现错误  关闭passwall2就好了

### 复现此Bug的步骤

passwall2运行状态下 向日葵无法使用

### 您想要实现的目的

请求修复

### 日志信息

没有错误日志

### 系统相关信息

passwall2几个月之前到现在一直有这个问题

**Comment by xiaorouji** [comment]
这是规则问题。
把 `oray.net` 和 `oray.com` 加入直连试试

**Comment by tiantaichenhui** [comment]
> 这是规则问题。 把`oray.net`和`oray.com`加入直连尝试

大佬好，我加过的 sunlogin.oray.com  oray.com  www.oray.com  oray.net等这些域名都加到直连列表里了 还是一样提示网络错误。
另外还有个问题  play商店无法下载APP  同样的节点 手机v2rayNG可以正常下载。路由端helloword 也可以正常下载APP 。
但是passwall2不行  会一直卡在等待下载中。  但是如果我在play等待下载的过程中 我改变一下passwall2的设置  比如 QUIC UDP 随便换个选项 点击应用 那么play就会完成下载  过一会再搜索APP又无法下载了  又得改一下passwall的设置才可以  但也只是一次性的。  请大佬修复

**Comment by bigbird1985** [comment]
一样，向日葵无法连接，愁死了

**Comment by Rivens7** [comment]
同样有这个问题，关闭passwall2可以远程了就，求助大佬修复

**Comment by Rivens7** [comment]
远程时会解析s1-tk.oray.com这个域名，对这个域名解析发现他对应了多个IP，查看geoip库发现部分IP没在名单中，谷歌了下好像解析出多IP最终会随机选择IP进行连接，这也是为什么有的时候可以远程，但有的时候不行，当随机选择了规则中没有IP就会无法连接。
目前的解决办法是将以下IP段加入direct规则中，就可以正常远程控制其他设备了。
112.124.0.0/17
59.110.0.0/16
120.26.0.0/16
47.96.0.0/14
121.40.0.0/15
101.37.0.0/17
116.62.0.0/16
以上都是通过我的猜测慢慢试出来的，不知道解释的是否正确，不能远程的大家可以尝试下。
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/26502940/4fabeaeb-d7f9-4d97-9a3f-fdee0281202c)

**Comment by tiantaichenhui** [comment]
> 远程的时候会解析sl-tk.oray.com这个域名，对这个域名解析发现他对应了多个IP，查看geoip库发现部分IP没在名单中，谷歌了下想解析出多个IP最终会随机选择IP进行连接，这也是为什么有的时候可以远程，但有的时候不行，当随机选择了规则中没有IP就会无法连接。 目前的解决办法只要以下IP段加入直接规则中，就正常可以远程控制101.37.0.0/17 112.124.0.0/17 116.62.0.0/16 120.26.0.0/16 121.40.0.0/15 47.96.0.0/14 以上都是通过我的猜测慢慢试出来的，不知道 解释的是否正确，不能远程的大家可以尝试下。 ![图像](https://private-user-images.githubusercontent.com/26502940/297283330-4fabeaeb-d7f9-4d97-9a3f-fdee0281202c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTU4MjQsIm5iZiI6MTcwNTU1NTUyNCwicGF0aCI6Ii8yNjUwMjk0MC8yOTcyODMzMzAtNGZhYmVhZWItZDdmOS00ZDk3LTlhM2YtZmRlZTAyODEyMDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA1MjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmM2I1ZmQxYjdmNDI0ZGUxZGQxYTczYmViMDkzYmIzZGVhMzZkNzQzODU0ZDg3NDM2ODFiMDg2MzVmYzQ4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.faENqCyWuUnOD3Ql3O8eH7gqZd9lb-hdBMg7sTCPiSQ)

谢谢大佬 我这就试试看

**Comment by tiantaichenhui** [comment]
> 远程时会解析sl-tk.oray.com这个域名，对这个域名解析发现他对应了多个IP，查看geoip库发现部分IP没在名单中，谷歌了下好像解析出多IP最终会随机选择IP进行连接，这也是为什么有的时候可以远程，但有的时候不行，当随机选择了规则中没有IP就会无法连接。 目前的解决办法是将以下IP段加入direct规则中，就可以正常远程控制其他设备了。 101.37.0.0/17 112.124.0.0/17 116.62.0.0/16 120.26.0.0/16 121.40.0.0/15 47.96.0.0/14 以上都是通过我的猜测慢慢试出来的，不知道解释的是否正确，不能远程的大家可以尝试下。 ![image](https://private-user-images.githubusercontent.com/26502940/297283330-4fabeaeb-d7f9-4d97-9a3f-fdee0281202c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjA1NTgsIm5iZiI6MTcwNTU2MDI1OCwicGF0aCI6Ii8yNjUwMjk0MC8yOTcyODMzMzAtNGZhYmVhZWItZDdmOS00ZDk3LTlhM2YtZmRlZTAyODEyMDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA2NDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MThmNGEwNzcyYWQ1ZGI5ZWE4NDU4MTRkOWYzNDllOTM3YjlkOTk4Y2ZhNWE1YWUyMDkyMGNlMDQzM2U5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8OIllukpkl1X3HYsspf3yUfxqjQ3VJLXTY6_iqWmzu4)

我加了这些IP段之后还是无法连接 奇怪了

**Comment by Rivens7** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/26502940/3df78846-949c-4dad-9384-67333aa9c8c9)
加在IP里，请检查规则位置是否正确，同时确定规则的主次是否正确

**Comment by Rivens7** [comment]
退出向日葵，重新打开尝试下

**Comment by tiantaichenhui** [comment]
> 退出向日葵，重新打开尝试下

向日葵重启过 passwall也重启过 甚至路由电脑都重启过 都不行 规则是加到Direct里面的
<img width="765" alt="bef5b64287c05c5ee5a51f3d7a95766" src="https://github.com/xiaorouji/openwrt-passwall2/assets/106894253/4d9df37d-49b7-46ef-9428-13f248039f68">

**Comment by Rivens7** [comment]
那就自行nslookup下这个地址sl-tk.oray.com，将域名全部放入白名单试试。如果再不行就只能抓包看了

**Comment by shouhujishu** [comment]
遇到相同问题 很奇怪我对国内地址全部放行优先级最高 也会走代理线路？

**Comment by shouhujishu** [comment]
我解析了sl-tk.oray.com所有的A类IP 添加到直连 结果连接中途提示网络异常未解决问题

**Comment by tiantaichenhui** [comment]
> 我解析了sl-tk.oray.com所有的A类IP 添加到直连 结果连接中途提示网络异常未解决问题

一样一样的 无法解决问题

**Comment by Rivens7** [comment]
把passwall日志改成info抓下包看看吧，可能有其他的域名解析的不对。

**Comment by Rivens7** [comment]
我这个也是暂时的解决办法，昨天发现向日葵无法更新，肯定有其他的ip没有走直连

**Comment by Moebyte** [comment]
同样有这个问题，期待有解决方法

**Comment by xiaorouji** [comment]
有問題的，請把日誌打開並設置日誌等級為debug，然後再測試一下。然後把日誌上傳上來

**Comment by tiantaichenhui** [comment]
> 有問題的，請把日誌打開並設置日誌等級為debug，然後再測試一下。然後把日誌上傳上來

打开了passwall2的debug日志模式 然后使用的向日葵 没有连接上 passwall2里面没有任何日志 系统日志也没有更新
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/106894253/7f007cf0-2d27-4470-b647-f8ed8a49acc6)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/106894253/bd8d71ff-0ba0-4213-83fc-faa64b0bc9b5)

**Comment by shouhujishu** [comment]
> 有問題的，請把日誌打開並設置日誌等級為debug，然後再測試一下。然後把日誌上傳上來

你好访问控制中的单独使用的节点如何查看日志? 我不能开启全局

**Comment by comnetwww** [comment]
经过半夜的折腾，终于弄好了。不知道对各位有没有用：
就是把passwall2升级到最新版，然后类型选：sing-box，就行了。
<img width="524" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/137212233/a6a23bf2-be2f-4e1a-aded-9b9e99c50576">

**Comment by zac-2020** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/59083664/f7574ff2-179b-4f70-85ec-6cc19c982473)

**Comment by zac-2020** [comment]
> ![image](https://private-user-images.githubusercontent.com/59083664/306544590-f7574ff2-179b-4f70-85ec-6cc19c982473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDMxMzAsIm5iZiI6MTcwODUwMjgzMCwicGF0aCI6Ii81OTA4MzY2NC8zMDY1NDQ1OTAtZjc1NzRmZjItMTc5Yi00ZjcwLTg1ZWMtNmNjMTljOTgyNDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA4MDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZmUxZjNmMDQ4NjMxNzM1MGY2YTllZjg2ZjMwMmM0YjliOGE2OWE0NmZjNzM3YjY3NGE0OTg4ZWJmYzNhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfCSpTL0q8oE9fv8Nsi0mnBcwH_KvFWhivmbk5Qy878)

调整为debug，查看日志，发现一个k203836640-1001951156lscab32879.rc.sunlogin.net的域名dns解析一直失败，在其他电脑nslookup这个域名也发现查询失败。目前卡在这一步了

**Comment by gearfox** [comment]
C:\Users\Administrator>nslookup sl-tk.oray.com
服务器:  UnKnown
Address:  10.0.0.30

*** UnKnown 找不到 sl-tk.oray.com: Non-existent domain

**Comment by Rivens7** [comment]
目前使用xray在高级设置里Xray Settings中流量嗅探只供路由使用勾上，可以使用向日葵了

**Comment by Rivens7** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/26502940/69a7fb54-7ebe-486f-aa47-48be9adc3d2d)
对于运行应该没有什么太大的影响

**Comment by Rivens7** [comment]
设置截图
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/26502940/83c42bf4-e2ea-479c-94fe-7732991fe4b0)

**Comment by tiantaichenhui** [comment]
> 设置截图 ![image](https://private-user-images.githubusercontent.com/26502940/311432702-83c42bf4-e2ea-479c-94fe-7732991fe4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTk2OTksIm5iZiI6MTcxMDI5OTM5OSwicGF0aCI6Ii8yNjUwMjk0MC8zMTE0MzI3MDItODNjNDJiZjQtZTJlYS00NzljLTk0ZmUtNzczMjk5MWZlNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNzdjZGU0NGNiY2VkNjg5YjM2N2E2ZmIwOWQ0Y2UzYjA4YjI2ODRlYjFmYzBlOTVmZmZhNjE0ZTMwYTQ3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JEpov0zi9aD6AZzFVvgbp850ujG2DJyuVCYD-_nIRU)

感谢大佬 按照设置确实能用了

**Comment by zac-2020** [comment]
> 设置截图 ![image](https://private-user-images.githubusercontent.com/26502940/311432702-83c42bf4-e2ea-479c-94fe-7732991fe4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDAwOTcsIm5iZiI6MTcxMDI5OTc5NywicGF0aCI6Ii8yNjUwMjk0MC8zMTE0MzI3MDItODNjNDJiZjQtZTJlYS00NzljLTk0ZmUtNzczMjk5MWZlNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MTEzODViNjEyNGU4M2VhNjQ4NDJmN2JmYjViODcxNmE3MWVlOGJmNGUyMGUzMjRhNWQxNjEyNzVkYmYwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d_KRLwGyIc867uONtE_AwLm0DsR0Gvs1SqMAZa12EQ4)

此设置可行。

**Comment by ppaet** [comment]
> ![image](https://private-user-images.githubusercontent.com/26502940/311432603-69a7fb54-7ebe-486f-aa47-48be9adc3d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTY5MzgsIm5iZiI6MTcyNzA5NjYzOCwicGF0aCI6Ii8yNjUwMjk0MC8zMTE0MzI2MDMtNjlhN2ZiNTQtN2ViZS00ODZmLWFhNDctNDhiZTlhZGMzZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEzMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NjNjN2E2NDcwYWE1N2Q5NzRlZTAwY2Y4NDk5MzNhZmIzNmYxZTRhYjVlMzIwMDY4ZTkxMDVlNzFiOTY3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HwxEtVFs1uD38Nh8qkFQolofSegFQqnZDa5kJgRzrnM) 对于运行应该没有什么太大的影响

确实可行，但是解释没看懂
