### ISSUE TITLE
[Bug]: 最新版编译后，没有自动切换的功能了

### ISSUE THREAD

**Issue by tedaz** [xiaorouji/openwrt-passwall2#448]
### 描述您遇到的bug

Auto Switch的tab无法显示出来，没有办法设置自动切换代理了

### 复现此Bug的步骤

在Luci中选择passwall，然后没有auto switch的tab了

### 您想要实现的目的

希望能显示auto switch，用来设置自动切换代理

### 日志信息

没有代理自动切换功能，日志中没有特别的错误

### 系统相关信息

Passwall Version【 4.72-1 】

**Comment by xiaorouji** [comment]
socks
