### ISSUE TITLE
[Bug]: 默认节点为直连时，不在规则中的域名没有使用远程 DNS 解析，部分 ip 路由规则失效

### ISSUE THREAD

**Issue by soffio** [xiaorouji/openwrt-passwall2#451]
### 描述您遇到的bug

在黑名单模式下，请求不在规则列表中的网站，比如`whatismyip.com`, 网页上显示的是直连 ip不是代理 ip，日志里看 DNS 也走了本地的 DNS 没有使用远程 DNS

### 复现此Bug的步骤

1. 默认节点直连
2. 添加规则`geoip:!cn`走代理
3. 访问`whatismyip.com`

### 您想要实现的目的

黑名单模式下，不在分流规则中的域名使用远程 DNS 解析，ip 规则可以正常分流

### 日志信息

`global.json` 的 DNS 默认是本地
```
"servers": [
      {
        "queryStrategy": "UseIP",
        "port": 15354,
        "_flag": "default",
        "address": "127.0.0.1"
      },
      {
        "port": 15354,
        "_flag": "Direct",
        "address": "127.0.0.1",
        "queryStrategy": "UseIP",
        "domains": [
          "geosite:cn",
        ]
      },
      {
        "port": 15355,
        "_flag": "Proxy",
        "address": "127.0.0.1",
        "queryStrategy": "UseIPv4",
        "domains": [
          "geosite:geolocation-!cn"
        ]
      }
  ]  
```
日志
```
2024/01/15 07:34:28 [Debug] app/dns: domain whatismyip.com will use the first DNS: [UDP:127.0.0.1:15354]
2024/01/15 07:34:28 [Debug] app/dns: UDP:127.0.0.1:15354 querying DNS for: whatismyip.com.
2024/01/15 07:34:28 [Debug] transport/internet/udp: dispatch request to: udp:127.0.0.1:15354
2024/01/15 07:34:28 [Info] transport/internet/udp: establishing new connection for udp:127.0.0.1:15354
2024/01/15 07:34:28 [Info] app/dispatcher: taking detour [direct] for [udp:127.0.0.1:15354]
2024/01/15 07:34:28 DNS accepted udp:127.0.0.1:15354 [dns-in1 -> direct]
2024/01/15 07:34:28 [Debug] transport/internet: dialing to udp:127.0.0.1:15354
2024/01/15 07:34:28 [Info] proxy/freedom: connection opened to udp:127.0.0.1:15354, local endpoint [::]:52664, remote endpoint 127.0.0.1:15354
2024/01/15 07:34:28 [Info] app/dns: UDP:127.0.0.1:15354 got answer: whatismyip.com. TypeA -> [104.21.89.158 172.67.189.152] 4.416294ms
2024/01/15 07:34:28 [Debug] app/dns: UDP:127.0.0.1:15354 updating IP records for domain:whatismyip.com.
```

### 系统相关信息

PassWall2 1.23-2
Xray 1.8.7

**Comment by Travel2Here** [comment]
楼主我来简单解释下这个逻辑，好像你误会了（或者是我没看懂你的情况而误会）：
黑名单，默认直连，达到的效果正如你现象里描述。如果访问的目标命中你的非直连规则，则使用远程DNS解析。
否则其他的目标都直连（即默认final规则），这时候的DNS终点必然是local dns。

**Comment by soffio** [comment]
> 楼主我来简单解释下这个逻辑，好像你误会了（或者是我没看懂你的情况而误会）： 黑名单，默认直连，达到的效果正如你现象里描述。如果访问的目标命中你的非直连规则，则使用远程DNS解析。 否则其他的目标都直连（即默认final规则），这时候的DNS终点必然是local dns。

感谢解答~ DNS 这块应该是我理解错了，`geoip:!cn`这个规则没有走代理是什么原因呢

**Comment by soffio** [comment]
> > > 楼主我来简单解释下这个逻辑，好像你误会了（或者是我没看懂你的情况而误会）： 黑名单，默认直连，达到的效果正如你现象里描述。如果访问的目标命中你的非直连规则，则使用远程DNS解析。 否则其他的目标都直连（即默认final规则），这时候的DNS终点必然是local dns。
> > 
> > 
> > 感谢解答~ DNS 这块应该是我理解错了，`geoip:!cn`这个规则没有走代理是什么原因呢
> 
> 可能是你的db版本本就不包含这种扩展数据 或是这个网站用了cdn并且有大陆服务器 自然解析成国内IP了就直连 可用nslookup或dig指定dns排查

日志里返回了两个ip`[104.21.89.158 172.67.189.152]`，这两个ip都不是国内的，主要把这两个ip单独加到代理规则里最后还是直连了就很奇怪

**Comment by xiaorouji** [comment]
> > > > 楼主我来简单解释下这个逻辑，好像你误会了（或者是我没看懂你的情况而误会）： 黑名单，默认直连，达到的效果正如你现象里描述。如果访问的目标命中你的非直连规则，则使用远程DNS解析。 否则其他的目标都直连（即默认final规则），这时候的DNS终点必然是local dns。
> > > 
> > > 
> > > 感谢解答~ DNS 这块应该是我理解错了，`geoip:!cn`这个规则没有走代理是什么原因呢
> > 
> > 
> > 可能是你的db版本本就不包含这种扩展数据 或是这个网站用了cdn并且有大陆服务器 自然解析成国内IP了就直连 可用nslookup或dig指定dns排查
> 
> 日志里返回了两个ip`[104.21.89.158 172.67.189.152]`，这两个ip都不是国内的，主要把这两个ip单独加到代理规则里最后还是直连了就很奇怪

清空一下ipset

**Comment by soffio** [comment]
> > > > > 楼主我来简单解释下这个逻辑，好像你误会了（或者是我没看懂你的情况而误会）： 黑名单，默认直连，达到的效果正如你现象里描述。如果访问的目标命中你的非直连规则，则使用远程DNS解析。 否则其他的目标都直连（即默认final规则），这时候的DNS终点必然是local dns。
> > > > 
> > > > 
> > > > 感谢解答~ DNS 这块应该是我理解错了，`geoip:!cn`这个规则没有走代理是什么原因呢
> > > 
> > > 
> > > 可能是你的db版本本就不包含这种扩展数据 或是这个网站用了cdn并且有大陆服务器 自然解析成国内IP了就直连 可用nslookup或dig指定dns排查
> > 
> > 
> > 日志里返回了两个ip`[104.21.89.158 172.67.189.152]`，这两个ip都不是国内的，主要把这两个ip单独加到代理规则里最后还是直连了就很奇怪
> 
> 清空一下ipset

试了下也没有用，默认选择一个不是direct的节点就可以正常根据ip规则分流，选择direct就不行，不能分流的时候日志里只看到了dns相关的日志，没有`accepted tcp:104.21.89.158:443 [tcp_redir -> Proxy]`的日志

**Comment by soffio** [comment]
> 你这个日志在哪个路径下的呢，我也看看我的

passwall2 主页面上红色的`节点`旁边有日志的按钮，或者直接去看这个文件`/tmp/etc/passwall2/global.log`
