### ISSUE TITLE
[Bug]: 重启服务会有这样的提示

### ISSUE THREAD

**Issue by NanJishen** [xiaorouji/openwrt-passwall2#453]
### 描述您遇到的bug

我使用的是 ImmortalWrt 的 openwrt ，硬件是 R2S，我安装 passwall2 每次重启服务后都无法玩腾讯游戏，然后我重启防火墙才行

### 复现此Bug的步骤

每次重启服务后都无法玩腾讯游戏，然后我重启防火墙才行

### 您想要实现的目的

每次重启服务后都无法玩腾讯游戏，然后我重启防火墙才行

### 日志信息

不会输出日志

### 截图

<img width="835" alt="Snipaste_2024-01-16_17-46-31" src="https://github.com/xiaorouji/openwrt-passwall2/assets/26486998/6ab4fc81-0ab4-4ac7-9804-f4cbde806010">

### 系统相关信息

 ImmortalWrt 的 openwrt ，硬件是 R2S

**Comment by xiaorouji** [comment]
有無裝 `kmod-nft-socket` `kmod-nft-tproxy` `kmod-nft-nat`
如果不需要玩外服遊戲，建議把UDP不轉發端口選所有。

**Comment by NanJishen** [comment]
> 有無裝 `kmod-nft-socket` `kmod-nft-tproxy` `kmod-nft-nat` 如果不需要玩外服遊戲，建議把UDP不轉發端口選所有。

安装 kmod-nft-socket kmod-nft-tproxy 后好了，果然是缺少包的问题，因为是小白，不太懂都所需什么包，我主要用软路由就是用 passwall2 所以如果还有其他包需要请告诉我 谢谢
