### ISSUE TITLE
[Bug]: 当分流总节点类型选择singbox，ip分流规则似乎不是很有效

### ISSUE THREAD

**Issue by fxvbv** [xiaorouji/openwrt-passwall2#454]
### 描述您遇到的bug

不太清楚是怎么回事，当具体节点类型使用singbox的时候节点正常，但是分流总节点选择singbox的时候，一部分国内网站是从代理访问了，触发了网站方的禁止国外ip访问的防火墙规则导致无法访问，此外还有一部分网站加载不全，只有文字，有些游戏的小程序无法加载。但是改回xray就比较正常了，那些有限制的国内网站都能访问。

### 复现此Bug的步骤

分流总节点选择singbox。

### 您想要实现的目的

分流总节点类型选择singbox，似乎没有xray三种域名解析策略。那么singbox默认的是什么域名解析策略？

### 日志信息

日志上没有明显的问题，只是一直输出singbox
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 32: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 33: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 34: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 35: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 36: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 37: procd_set_param: not found
日期 daemon.err uhttpd[3430]: sh: /etc/init.d/sing-box: line 38: procd_close_instance

### 系统相关信息

Passwall2 Version: 1.23-3

**Comment by xiaorouji** [comment]
規則問題吧，更新下geo資源文件看看。
另外sing-box和xray用的geo資源文件是不同的。

**Comment by smdx** [comment]
> 規則問題吧，更新下geo資源文件看看。 另外sing-box和xray用的geo資源文件是不同的。

大佬，sing-box的geo要怎么设定自动更新？有命令行之类的吗？谢谢

**Comment by Travel2Here** [comment]
> > 規則問題吧，更新下geo資源文件看看。 另外sing-box和xray用的geo資源文件是不同的。
> 
> 大佬，sing-box的geo要怎么设定自动更新？有命令行之类的吗？谢谢

最近两个版本作者xiaorouji增加了一个删除初始化文件的功能，可以自动再下载那俩文件。但不稳定，有时候没下完就断了导致启动不了；
你也可以自己下载了文件放过去或者用wget之类的命令。

**Comment by smdx** [comment]
好的，先用定时任务下载了，如果能合并到规则管理那里自动更新就好了。

**Comment by Travel2Here** [comment]
> 好的，先用定时任务下载了，如果能合并到规则管理那里自动更新就好了。

我也觉得是~奈何没有这方面的代码能力。期待有人PR或者作者抽空撸上~

**Comment by etsam** [comment]
奥是一同改到更新页面那最好了 是说singbox一开始怎么不启动  后来发现这两个库不一样，目前是删除让它自动更新或者直接上传

**Comment by chancat87** [comment]
这个问题和我发的差不多，因为singbox用的geosiet规则和xray的不一样，引起的，最终我还是选择了使用xray，规则多用的舒服。
