### ISSUE TITLE
[Bug]: 求助，切换到xray分流总节点就无法启动。

### ISSUE THREAD

**Issue by chancat87** [xiaorouji/openwrt-passwall2#455]
### 描述您遇到的bug

最近换上pw2用了，想体验一下singbox的hy2，然后发现测试完再切回xray分流总节点的时候，直接未运行，无法启动了。之前我一直都是用的reality协议，
pw2版本，xray. singbox.内核，包括服务端全是最近版。
另外日志文件在那个目录？请各位指点一下，谢谢。

### 复现此Bug的步骤

xray分流总节点就是没法使用，显示未运行，节点无问题

### 您想要实现的目的

可以正常运行，随便切换。

### 日志信息

没找到哪里看日志

### 截图

[![pFA2NJe.md.jpg](https://s11.ax1x.com/2024/01/19/pFA2NJe.md.jpg)](https://imgse.com/i/pFA2NJe)

### 系统相关信息

pw2 25.013.56205
chrome:120.0.6099.210
大雕qsdk固件。

**Comment by etsam** [comment]
xray 分流选项的下面不是日志的按钮吗，点开里面就是日志

**Comment by chancat87** [comment]
> xray分流选项的下面不是日志的按钮吗，点开里面就是日志

啊哈。。哈哈笑死，原来在这里😭，谢谢你搞定了。

**Comment by chancat87** [comment]
> 是不是要更新geosite.dat

找到日志就搞定了，和geosite也差不多有关吧，我用singbox配置的hy2，无法浏览tiktok，在NekoBox文档里有看到需要手动添加一个tiktok的geosite在cn列表上面才可以使用，但是当切到xray时无法启动，因为增强版的geosite没有tiktok这个列表，所以无法启动，错误日志里提示了:` infra/conf: invalid field rule > infra/conf: failed to load GeoIP: tiktok > infra/conf: code not found in geoip.dat: TIKTOK`
