### ISSUE TITLE
[Feature Request]: 一键备份导入导出? 花了大半天手动多机场多节点配置不侧漏...一不小心依赖冲突...重刷固件...又..

### ISSUE THREAD

**Issue by gowy222** [xiaorouji/openwrt-passwall2#457]
### 描述你想要的新功能

最近搞了台R2,R5好不容易配置成功一次完美dns不侧漏(各种手打规则!!!)......，
又想去试试ssr+ vss.结果依赖冲突...变得特别卡.....只能刷机.

能不能给个导出passwall2的全部设置/配置 备份下来，
反复刷机折腾/多机通刷直接上传备份就能立马启用..
折腾完了觉得性能不够还能迁移上X86...实在不想再去一个个复制..

### 描述你考虑过的替代方案

类似adg那样，导出yaml？导入yaml？json也行啊..

**Comment by xiaorouji** [comment]
/etc/config/passwall2
