### ISSUE TITLE
[Bug]: 自定義遠程DNS後仍然使用預設DNS解析

### ISSUE THREAD

**Issue by rootmelo92118** [xiaorouji/openwrt-passwall2#462]
### 描述您遇到的bug

自定義遠程DNS後仍然使用預設DNS解析

### 复现此Bug的步骤

1. 自定義DNS
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/32770959/dc6ac592-a97a-45b9-95e2-8997af7583ec)
2. 發現紀錄中有一堆1.1.1.1:53經過
3. 確認dns-in 後確認配置檔無連動進行更改
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/32770959/e9b2d055-bddd-44e5-b22f-e1d3355aa064)

### 您想要实现的目的

可以正確的依據自定義的DNS進行解析

### 日志信息

2024/01/21 21:29:48 192.168.31.197:47442 accepted tcp:36.155.169.249:5287 [tcp_redir -> direct]
2024/01/21 21:29:48 192.168.31.197:47424 accepted tcp:36.155.169.249:5287 [tcp_redir -> direct]
2024/01/21 21:29:48 127.0.0.1:40982 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:03 127.0.0.1:33555 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:08 127.0.0.1:51557 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:09 127.0.0.1:38829 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:09 127.0.0.1:57726 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:14 127.0.0.1:51255 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:15 127.0.0.1:48553 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:16 127.0.0.1:43821 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:17 127.0.0.1:58307 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:20 127.0.0.1:49865 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:20 DNS accepted udp:127.0.0.1:15354 [dns-in1 -> direct]
2024/01/21 21:30:23 127.0.0.1:44176 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/01/21 21:30:25 127.0.0.1:56187 accepted udp:1.1.1.1:53 [dns-in -> dns-out]

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/32770959/dc6ac592-a97a-45b9-95e2-8997af7583ec)

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/32770959/e9b2d055-bddd-44e5-b22f-e1d3355aa064)

### 系统相关信息

Passwall :1.23-3

**Comment by swxk521** [comment]
确实有这个问题，是在xray作为主程序时。
