### ISSUE TITLE
[Bug]: singbox分流是不是没有兜底的策略，有一些网站打不开。

### ISSUE THREAD

**Issue by xcf13363175** [xiaorouji/openwrt-passwall2#463]
### 描述您遇到的bug

singbox分流是不是没有兜底的策略，有一些网站打不开。xray不会。

### 复现此Bug的步骤

例如：https://rebang.today https://ali.gitcafe.ink/

### 您想要实现的目的

singbox有没有IPOnDemand的类似策略

### 日志信息

无

### 系统相关信息

最新版本

**Comment by Travel2Here** [comment]
原理不完全一样，建议看SB的官方分流和解析策略说明。这个问题跟此工具无关哟~

**Comment by xcf13363175** [comment]
好吧，先关掉，去学习SB策略了。
