### ISSUE TITLE
[Feature Request]: 希望在xray节点设置或高级设置中添加tcpNoDelay和tcpMpTcp项目

### ISSUE THREAD

**Issue by Natsuki-Kaede** [xiaorouji/openwrt-passwall2#464]
### 描述你想要的新功能

xray添加tcpNoDelay和tcpMpTcp启用支持

### 描述你想要的解决方案

在每个节点设置或高级设置-xray中添加上述两项配置

**Comment by iamyangyiok** [comment]
> ### 描述你想要的新功能
> xray添加tcpNoDelay和tcpMpTcp启用支持
> 
> ### 描述你想要的解决方案
> 在每个节点设置或高级设置-xray中添加上述两项配置
> 
> ### 描述你考虑过的替代方案
> _No response_
> 
> ### 其他信息
> _No response_

现在可以手工实现 参数开启不 ，直接XRAY的SHELL指令执行执行。

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/384bf39ae8eb38c9a42a9e124abbc756151a29eb
