### ISSUE TITLE
[Bug]: Nftables防火墙工具不可选择，是不是我的内核版本太低了？

### ISSUE THREAD

**Issue by szdosar** [xiaorouji/openwrt-passwall2#465]
### 描述您遇到的bug

我编译lede，系统内核5.15.105，无法在插件passwall2的【高级设置】防火墙工具中选择Nftables，只用Iptables选项。
即使我在编译前选择luci-app-passwall2的防火墙工具只勾选了[*] Nftables Transparent Proxy，成功编译，依然只用Iptables选项。
是不是我的内核版本太低了？还是我的理解问题？

### 复现此Bug的步骤

openwrt--服务-passwall2-高级设置-防火墙工具，下拉框中只有Iptables选项。而我编译时，明明只选择了[*] Nftables Transparent Proxy。已在更新固件是，选择重置配置文件。

### 您想要实现的目的

在插件passwall2的【高级设置】防火墙工具中可以正常选择使用Nftables

### 日志信息

内核日志件附件。
[status-dmesg.txt](https://github.com/xiaorouji/openwrt-passwall2/files/14031912/status-dmesg.txt)

### 截图

![20240124102930](https://github.com/xiaorouji/openwrt-passwall2/assets/6078432/d6c25e1f-341a-43c1-9577-c9b4747ef4c7)

### 系统相关信息

luci-i18n-passwall2-zh-cn_1.24-1_all.ipk
luci-app-passwall2_1.24-1_all.ipk
浏览器：Chrome 版本 120.0.6099.225(正式版本)(64 位)

**Comment by szdosar** [comment]
应该是lede的锅。我用最新版的lede编译，问题依然。换了原版openwrt源编译，就出现这个选项了。
![20240125110330](https://github.com/xiaorouji/openwrt-passwall2/assets/6078432/2870b7e0-60dd-4d8b-97d1-44d28fc518de)

**Comment by szdosar** [comment]
不过，我没选择编译IPtables，结果固件运行时的选项却有此选项（按我理解，没编译它，就不用向终端用户显示该选项），可能是哪里没弄好。

**Comment by Travel2Here** [comment]
> 不过，我没选择编译IPtables，结果固件运行时的选项却有此选项（按我理解，没编译它，就不用向终端用户显示该选项），可能是哪里没弄好。

我的经验不一定准确，但大概是：lede用的FW3，面只支持iptables。官方的是FW4，默认支持Nftables并兼容iptables。

**Comment by szdosar** [comment]
> > 不过，我没选择编译IPtables，结果固件运行时的选项却有此选项（按我理解，没编译它，就不用向终端用户显示该选项），可能是哪里没弄好。
> 
> 我的经验不一定准确，但大概是：lede用的FW3，只支持iptables。官方的是FW4，默认支持Nftables并兼容iptables。

你的判断是对的，
我按照[隔壁@ecrasy的建议](https://github.com/coolsnowwolf/lede/issues/11839)，
重新编译就好了。
>可以自行修改
`sed -i 's/+firewall/+uci-firewall/g' feeds/luci/applications/luci-app-firewall/Makefile`
>然後make menuconfig手動去掉firewall，選擇firewall4
