### ISSUE TITLE
[Feature Request]: fakeip改进

### ISSUE THREAD

**Issue by cjwddtc** [xiaorouji/openwrt-passwall2#466]
### 描述你想要的新功能

对于未在代理域名列表中，但是由geoip规则判定需要走代理的网站也返回fakeip，并提供一个选项只代理fakeip的流量。

### 描述你想要的解决方案

现有的fakeip功能仅适用于列表中的域名，但是对于未在列表中的域名，xray其实提供了通过expectIPs 的方式区分国内外域名的方案，如果未命中域名规则，最后通过dtoh解析配expectIPs 为geoip:!cn的时候就判定这个这个域名也应该走代理，直接返回fakeip,否则在下一个规则里面用正常解析返回真实地址。

### 描述你考虑过的替代方案

由于分流规则的设计，dns进行这种特判确实在设计上不太合理，能否给个调试模式之类的选项，让我们自定义dns servers数组？比如朴素的可以让我们填两个字符串插在原数组的前面和后面，或者高级一点的方式，直接提供一个后处理功能，让我们可以指定一个程序，对xray的配置文件进行后处理修改后再启动xray?

### 其他信息

该方案可以大幅度解决解决双路由模式下的分流问题，常见的比如旁路由或透明网桥模式可以方便的bypass直连流量，便于主路由对流量进行管理，同时还能解决upnp的问题。

**Comment by lovexiaofan123** [comment]
赞同，添加一个fakedns白名单和黑明单也可以，这样会方便很多很多
