### ISSUE TITLE
[Feature Request]: 关于订阅节点列表增加自动选择功能

### ISSUE THREAD

**Issue by yikexiaoyao** [xiaorouji/openwrt-passwall2#468]
### 描述你想要的新功能

希望实现像clash一样，实时测速，并根据测速结果自动选择节点

### 描述你想要的解决方案

印象中passwall好像有过类似的功能，但是以前用的时候似乎不太完善，实时测速和自动切换的效果不太理想

**Comment by Deleted-Account** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/48331538/f9547375-46db-473c-b731-9aec0fa7fd24)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/48331538/3cc25f42-6171-4de0-9214-16115ffe3a03)
