### ISSUE TITLE
[Feature Request]: ipt2socks怎么添加到passwall2类型选择里面

### ISSUE THREAD

**Issue by senkiss** [xiaorouji/openwrt-passwall2#469]
### 描述你想要的新功能

ipt2socks怎么添加到passwall2类型选择里面

### 描述你想要的解决方案

ipt2socks有安装在passwall里面有在passwall添加节点的时候没得选择

**Comment by xiaorouji** [comment]
passwall2沒有ipt2socks的邏輯，請使用sing-box或xray核心的socks
