### ISSUE TITLE
在make menuconfig选passwall2组件时，V2ray名称有误

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#47]
![1](https://user-images.githubusercontent.com/88967758/162472894-699dff0e-ae4e-424b-b61f-f5223d6e232a.jpg)

编译好后，查看core是Xray 1.5.4，这个选项的名称应该是Xray吧。

**Comment by Beginner-Go** [comment]
xray-core为必选依赖 ，不出现在此菜单里

**Comment by chika0801** [comment]
> xray-core为必选依赖 ，不出现在此菜单里

我选了这个选项后，进网页看也没有v2fly core。

那这个菜单的v2ray其实可以取消吧。
