### ISSUE TITLE
[Bug]: 代理fullcone每次启动后都失效，需要关闭fullcone-nat后再开启才生效

### ISSUE THREAD

**Issue by zjy2200656** [xiaorouji/openwrt-passwall2#473]
### 描述您遇到的bug

代理的fullcone-nat每次在重启后无效，需要在路由器turbo-acc中关闭fullcone-nat后再开启才生效，已测试证明passwall2的延时启动无影响

### 复现此Bug的步骤

1.重启路由器
2.nattype测试nat，直连国内stun为fullconenat，代理国外stun为Port Restricted Cone
3.turbo-acc中关闭fullcone-nat后再开启
4.再次测试国内外都为fullcone

### 您想要实现的目的

每次启动路由器代理fullcone自动生效，不需要重启turbo-acc中的fullcone-nat

### 日志信息

无相关日志

### 系统相关信息

- PassWall版本：1.25-1
- lede版本：OpenWrt R24.1.13 / LuCI Master (git-24.019.37088-cdf2b69)

**Comment by xiaorouji** [comment]
国外IP和这个ACC无关。
请在节点端开放高位UDP端口。

**Comment by zjy2200656** [comment]
> 国外IP和这个ACC无关。 请在节点端开放高位UDP端口。

节点默认高位udp已经为全开启

**Comment by zjy2200656** [comment]
和mwan3冲突了，改用passwall内置规则解决问题
