### ISSUE TITLE
[Bug]: Ping 0ms

### ISSUE THREAD

**Issue by lededev** [xiaorouji/openwrt-passwall2#476]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/30518126/2c443e79-c8af-41a6-9914-1c555f3c2fe5)

### 复现此Bug的步骤

点击图标

### 您想要实现的目的

0ms改回正确时间

### 日志信息

截图

### 系统相关信息

当前主干main dbd536ddd8a097bfb5bbb6d873ec2d2e98be0e43

**Comment by sbwml** [comment]
passwall2 也有这问题呀？passwall 也遇到同样的情况  https://github.com/xiaorouji/openwrt-passwall/discussions/2915

**Comment by sbwml** [comment]
不是passwall的问题，是openwrt snapshots 的 curl 更新的缘故，curl/8.6.0 的 **time_pretransfer** 存在bug，0到1字节的耗时永远变成  0.00000 秒，所以导致passwall 的检测 url 时也显示了 0 ms。

解决方法是使用发布版源码的固件（即OpenWrt 23.05.2）、或在未得到修复之前构建 snapshots 的时候回退 curl 版本到 8.5.0 即可解决。

**Comment by lededev** [comment]
@sbwml 感谢回复，把curl回退到8.5.0解决了。

**Comment by smdx** [comment]
@sbwml
你好，遇到同样的问题，云编译openwrt、lede源码应该怎么解决这个问题？谢谢

pushd package/net/curl
git checkout 6501290c17fb2c65e0fb589da94d121ff89e7d5e
popd
或者
pushd package/net/curl
git remote set-url origin https://github.com/openwrt/packages
git checkout 6501290c17fb2c65e0fb589da94d121ff89e7d5e
popd
都提示No such file or directory

**Comment by smdx** [comment]
@sbwml 
@lededev 
遇到同样问题，在云编译指定版本
pushd feeds/packages/net/curl
git checkout 986bdbcc1a0773434f04339d5ddee79da39fd948
popd
提示错误：
fatal: reference is not a tree: 986bdbcc1a0773434f04339d5ddee79da39fd948

请问怎么解决啊？谢谢

**Comment by lededev** [comment]
用git log看一下8.5.0的commit id，然后复制后checkout。

**Comment by smdx** [comment]
> @smdx 你的当前目录不对吧，packages和openwrt是两个不同的git仓库，你的pwd当前目录必须是feeds/packages/net/curl，才能看到packages的git log

刚才搞错了，本地的源码有段时间没更新了。更新后返回多个版本了。感谢回复

**Comment by sbwml** [comment]
> @sbwml @lededev 遇到同样问题，lede源码在云编译指定版本 pushd feeds/packages/net/curl git checkout 986bdbcc1a0773434f04339d5ddee79da39fd948 popd 提示错误： fatal: reference is not a tree: 986bdbcc1a0773434f04339d5ddee79da39fd948
> 
> 请问怎么解决啊？谢谢

我编译固件没有你们这些条条框框的，我是直接feeds 就绪后暴力删除替换

https://github.com/sbwml/r4s_build_script/commit/dd6d80ec5c0bb48d89e3e16c97bb6d6474195816

**Comment by smdx** [comment]
> > @sbwml @lededev 遇到同样问题，lede源码在云编译指定版本 pushd feeds/packages/net/curl git checkout 986bdbcc1a0773434f04339d5ddee79da39fd948 popd 提示错误： fatal: reference is not a tree: 986bdbcc1a0773434f04339d5ddee79da39fd948
> > 请问怎么解决啊？谢谢
> 
> 我编译固件没有你们这些条条框框的，我是直接feeds 就绪后暴力删除替换
> 
> [sbwml/r4s_build_script@dd6d80e](https://github.com/sbwml/r4s_build_script/commit/dd6d80ec5c0bb48d89e3e16c97bb6d6474195816)

感谢分享方法

**Comment by Fyred** [comment]
我是回退了libcurl4到8.5.0解决的，curl用8.6.0版本依然可以正确显示

**Comment by bikioxo** [comment]
> 不是passwall的问题，是openwrt snapshots 的 curl 更新的缘故，curl/8.6.0 的 **time_pretransfer** 存在bug，0到1字节的耗时永远变成 0.00000 秒，所以导致passwall 的检测 url 时也显示了 0 ms。
> 
> 解决方法是使用发布版源码的固件（即OpenWrt 23.05.2）、或在未得到修复之前构建 snapshots 的时候回退 curl 版本到 8.5.0 即可解决。
求指教编译时要怎么退回了

**Comment by bikioxo** [comment]
> @sbwml 感谢回复，把curl回退到8.5.0解决了。

请问编译时要怎么退回了

**Comment by fynhnt** [comment]
> 我是回退了libcurl4到8.5.0解决的，curl用8.6.0版本依然可以正确显示
请问大佬怎么回退，谢谢！

**Comment by flyhigao** [comment]
如果嫌改curl麻烦的话,可以修改: 
`/usr/lib/lua/luci/controller/passwall.lua`
把里面的time_starttransfer 改成 time_total 即可,  curl8.6有bug,太小的会归于0ms. time_total较大.
改完要重启下才会生效

**Comment by sbwml** [comment]
curl 8.7+  这个问题被修复了 

发自我的iPhone
