### ISSUE TITLE
更新提示缺少luci-lua-runtime

### ISSUE THREAD

**Issue by jt8823** [xiaorouji/openwrt-passwall2#480]
### 描述您遇到的bug

luci-lua-runtime
这个哪里能找到啊

### 复现此Bug的步骤

。

### 您想要实现的目的

root@OpenWrt:/tmp/myipk# opkg install *.ipk  --nodeps --force-depends
Upgrading brook on root from 20230606-1 to 20240214-1...
Upgrading hysteria on root from 2.0.2-1 to 2.2.4-1...
Package luci-app-passwall2 (1.20-15) installed in root is up to date.
Upgrading luci-i18n-passwall2-zh-cn on root from 1.20-15 to git-24.031.67339-535e365...
Installing naiveproxy (121.0.6167.71-1-1) to root...
Installing shadowsocks-rust-sslocal (1.17.1-1) to root...
Installing shadowsocks-rust-ssserver (1.17.1-1) to root...
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Installing shadowsocksr-libev-ssr-server (2.5.6-9) to root...
Installing simple-obfs (0.0.5-1) to root...
Upgrading sing-box on root from 1.5.0-rc.3-1 to 1.8.4-1...
sing-box is stopped!
Package tcping (0.3-1) installed in root is up to date.
Installing tuic-client (1.0.0-1) to root...
Upgrading v2ray-geoip on root from [202302090046-1](tel:202302090046-1) to [202311230040-1](tel:202311230040-1)...
Upgrading v2ray-geosite on root from [20230208103804-1](tel:20230208103804-1) to [20231122065640-1](tel:20231122065640-1)...
Upgrading v2ray-plugin on root from 5.7.0-1 to 5.13.0-1...
Upgrading xray-core on root from 1.8.4-1 to 1.8.7-1...
Configuring shadowsocksr-libev-ssr-server.
Configuring sing-box.
sing-box is started!
Configuring tuic-client.
Configuring hysteria.
Configuring shadowsocks-rust-ssserver.
Configuring naiveproxy.
Configuring v2ray-plugin.
Configuring shadowsocks-rust-sslocal.
Configuring xray-core.
Configuring v2ray-geoip.
Configuring v2ray-geosite.
Configuring brook.
Configuring luci-i18n-passwall2-zh-cn.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall2
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
        But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.

### 日志信息

root@OpenWrt:/tmp/myipk# opkg install *.ipk  --nodeps --force-depends
Upgrading brook on root from 20230606-1 to 20240214-1...
Upgrading hysteria on root from 2.0.2-1 to 2.2.4-1...
Package luci-app-passwall2 (1.20-15) installed in root is up to date.
Upgrading luci-i18n-passwall2-zh-cn on root from 1.20-15 to git-24.031.67339-535e365...
Installing naiveproxy (121.0.6167.71-1-1) to root...
Installing shadowsocks-rust-sslocal (1.17.1-1) to root...
Installing shadowsocks-rust-ssserver (1.17.1-1) to root...
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Installing shadowsocksr-libev-ssr-server (2.5.6-9) to root...
Installing simple-obfs (0.0.5-1) to root...
Upgrading sing-box on root from 1.5.0-rc.3-1 to 1.8.4-1...
sing-box is stopped!
Package tcping (0.3-1) installed in root is up to date.
Installing tuic-client (1.0.0-1) to root...
Upgrading v2ray-geoip on root from [202302090046-1](tel:202302090046-1) to [202311230040-1](tel:202311230040-1)...
Upgrading v2ray-geosite on root from [20230208103804-1](tel:20230208103804-1) to [20231122065640-1](tel:20231122065640-1)...
Upgrading v2ray-plugin on root from 5.7.0-1 to 5.13.0-1...
Upgrading xray-core on root from 1.8.4-1 to 1.8.7-1...
Configuring shadowsocksr-libev-ssr-server.
Configuring sing-box.
sing-box is started!
Configuring tuic-client.
Configuring hysteria.
Configuring shadowsocks-rust-ssserver.
Configuring naiveproxy.
Configuring v2ray-plugin.
Configuring shadowsocks-rust-sslocal.
Configuring xray-core.
Configuring v2ray-geoip.
Configuring v2ray-geosite.
Configuring brook.
Configuring luci-i18n-passwall2-zh-cn.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall2
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
        But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.

### 系统相关信息

Openwrt版本23.9
Passwall2版本1.20

**Comment by yfw918** [comment]
@xiaorouji 用了昨天更新的`luci-19.07_luci-app-passwall2_1.26-1_all.ipk`好像还是不行。使用[immortalwrt-mt798x](https://github.com/hanwckf/immortalwrt-mt798x)这个项目编译的固件，openwrt版本是21.02，路由器型号是rax3000m。
```
Unknown package 'luci-app-passwall2'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-passwall2
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall2 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall2.
```

**Comment by ilafz** [comment]
同样的问题 必须要安装runtime这个依赖 需要更新luci-base  但是更新之后后台就badgateway
