### ISSUE TITLE
能添加支持cortex-a76的插件吗？

### ISSUE THREAD

**Issue by Jonney111** [xiaorouji/openwrt-passwall2#484]
### 描述你想要的新功能

如题

### 描述你想要的解决方案

刚买的树莓派5想试试openwrt 但是支持的插件大都不兼容

**Comment by hcym** [comment]
用官方master再git这里完事了，不过内存4G以下的还是用v2raya稳妥，也有luci了，p1p2都非常吃内存，很容易就二三G , ssrplus也可以，就是udp不通，p1p2是udp最完美的

**Comment by xiaorouji** [comment]
自己編譯即可。
