### ISSUE TITLE
[Bug]: xray分流的netflix等分流失效

### ISSUE THREAD

**Issue by whatpig** [xiaorouji/openwrt-passwall2#485]
### 描述您遇到的bug

netflix，openai等分流选其他节点，结果访问netflix，openai还是使用默认节点访问

### 复现此Bug的步骤

netflix，openai等分流选其他节点，结果访问netflix，openai还是使用默认节点访问

### 您想要实现的目的

分流正常

### 日志信息

xray客户端1.8.7 
luci-app-passwall2	1.25-5
服务端1.8.1
服务端也做了分流（香港节点，只要是Netflix和openai就分流到新加坡节点）

### 系统相关信息

xray客户端1.8.7 
luci-app-passwall2	1.25-5
服务端1.8.1
服务端也做了分流（香港节点，只要是Netflix和openai就分流到新加坡节点）

**Comment by iamyangyiok** [comment]
没问题 你把2个分流提高到国外出口的上面 优先

**Comment by whatpig** [comment]
> 没问题 你把2个分流提高到国外出口的上面 优先

果然有效 原来这个顺序还能决定这个啊 我记得以前旧版本好像和顺序没关系啊
