### ISSUE TITLE
[Bug]: pw2添加hysteria2节点时无法选择证书或者pinSHA256指纹，pw1还有这个选项呢

### ISSUE THREAD

**Issue by namelessvon** [xiaorouji/openwrt-passwall2#487]
### 描述您遇到的bug

缺少了一个输入框以便填写hysteria2节点的pinSHA256指纹，当然最好还是能让用户选择是否加载证书，哪怕自己上传后指定证书文件位置呢。看了下passwall中是可以输入pinSHA256指纹参数的

### 复现此Bug的步骤

添加节点，hysteria2，勾选允许不安全连接（insecure），之后应该能输入pinSHA256指纹。或者不勾选的时候能够输入证书位置

### 您想要实现的目的

尽量安全一些，补足参数输入缺口

### 日志信息

无

### 系统相关信息

passwall2 git-25.042.56170-15ceb8e
[Powered by LuCI openwrt-23.05 branch (git-c66fc92)](https://github.com/openwrt/luci) / [ArgonTheme vgit-25.026.72358-0a2aa30](https://github.com/jerrykuku/luci-theme-argon) / OpenWrt 02.19.2024 by Kiddin'
hysteria2  v2.2.4

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/aea7eb8167cf6c32104efbdf08da5d7dc2d35dcf
