### ISSUE TITLE
DNS协议使用FakeDNS，Xray配置文件中的"dns"模块，无法正常分流CN IP走直连

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#49]
4月9日编译的Passwall2，设置方式如下

Main:
从上至下顺序
LAN 直连
AD 黑洞
China 直连
默认 <我的VPS节点>

DNS:
DNS 协议 FakeDNS

China 规则为默认的geosite:cn和geoip:cn。

查看生成的Xray配置文件如下 /tmp/etc/passwall2/global.json

<pre>
  "dns": {
    "disableFallback": true,
    "queryStrategy": "UseIPv4",
    "servers": [
      "fakedns",
      {
        "port": 53,
        "domains": [
          "geosite:cn"
        ],
        "address": "192.168.2.1"
      }
    ],
    "disableCache": false,
    "disableFallbackIfMatch": true,
    "tag": "dns-in1"
  },
</pre>

<pre>
 "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
//省略不重要的
      {
        "domains": [
          "geosite:cn"
        ],
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "direct"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "default"
      }
    ]
  },
</pre>

测试网站是 https://m-xxp-fp.bigfintax.com/?token=1000000520 一个超市开发票的网站，肯定不在geosite:cn数据库里。
查看debug日志，如下
<pre>
2022/04/10 01:36:15 [Debug] app/dns: domain m-xxp-fp.bigfintax.com will use the first DNS: [FakeDNS]
2022/04/10 01:36:15 [Info] app/dns: FakeDNS got answer: m-xxp-fp.bigfintax.com -> [198.18.80.174]
2022/04/10 01:36:15 [Debug] [2772470514] proxy/dokodemo: processing connection from: 192.168.10.151:7495
2022/04/10 01:36:15 [Info] [2772470514] proxy/dokodemo: received request for 192.168.10.151:7495
2022/04/10 01:36:15 [Info] [2772470514] app/dispatcher: fake dns got domain: m-xxp-fp.bigfintax.com for ip: 198.18.80.174
2022/04/10 01:36:15 [Info] [2772470514] app/dispatcher: fake dns got domain: m-xxp-fp.bigfintax.com for ip: 198.18.80.174
2022/04/10 01:36:15 [Info] [2772470514] app/dispatcher: sniffed domain: m-xxp-fp.bigfintax.com
2022/04/10 01:36:15 [Debug] app/dns: domain m-xxp-fp.bigfintax.com will use the first DNS: [FakeDNS]
2022/04/10 01:36:15 [Debug] app/dns: skip DNS resolution for domain m-xxp-fp.bigfintax.com at server FakeDNS
2022/04/10 01:36:15 [Info] features/routing/dns: resolve ip for m-xxp-fp.bigfintax.com > app/dns: returning nil for domain m-xxp-fp.bigfintax.com
2022/04/10 01:36:15 [Debug] app/dns: domain m-xxp-fp.bigfintax.com will use the first DNS: [FakeDNS]
2022/04/10 01:36:15 [Debug] app/dns: skip DNS resolution for domain m-xxp-fp.bigfintax.com at server FakeDNS
2022/04/10 01:36:15 [Info] features/routing/dns: resolve ip for m-xxp-fp.bigfintax.com > app/dns: returning nil for domain m-xxp-fp.bigfintax.com
2022/04/10 01:36:15 [Debug] app/dns: domain m-xxp-fp.bigfintax.com will use the first DNS: [FakeDNS]
2022/04/10 01:36:15 [Debug] app/dns: skip DNS resolution for domain m-xxp-fp.bigfintax.com at server FakeDNS
2022/04/10 01:36:15 [Info] features/routing/dns: resolve ip for m-xxp-fp.bigfintax.com > app/dns: returning nil for domain m-xxp-fp.bigfintax.com
2022/04/10 01:36:15 [Debug] app/dns: domain m-xxp-fp.bigfintax.com will use the first DNS: [FakeDNS]
2022/04/10 01:36:15 [Debug] app/dns: skip DNS resolution for domain m-xxp-fp.bigfintax.com at server FakeDNS
2022/04/10 01:36:15 [Info] features/routing/dns: resolve ip for m-xxp-fp.bigfintax.com > app/dns: returning nil for domain m-xxp-fp.bigfintax.com
2022/04/10 01:36:15 [Info] [2772470514] app/dispatcher: taking detour [default] for [tcp:m-xxp-fp.bigfintax.com:443]
2022/04/10 01:36:15 [Info] [2772470514] transport/internet/tcp: dialing TCP to tcp:我的节点:443
2022/04/10 01:36:15 [Debug] transport/internet: dialing to tcp:我的节点:443
</pre>

根据日志，解读到DNS查询流程是
1 FakeDNS返回Fake IP198.18.80.174
2 程序发起请求FakeDNS嗅探到后还原域名 m-xxp-fp.bigfintax.com for ip: 198.18.80.174
3 此域名进入"routing"按从上至下顺序匹配，因规则是 "IPOnDemand"，匹配到"ip": [ "geoip:cn"  ],时立即解析域名成为IP再进行IP匹配
4 进入Xray内置“DNS"，由于"servers"规则是FakeDNS和在geosite:cn里面的域名使用本地运营商DNS解析。此域名不会再用FakeDNS，此域名不是在geosite:cn中，不会使用本地运营商DNS解析。故没有返回结果
5 命中最后"default"规则 ，走我的VPS节点。
6 我在VPS节点的Xray配置文件中配置了禁止访问CN，客户端最终表现是本机打不开网页

建议在"dns"模块增加一个国外的DNS地址如1.1.1.1
<pre>
 "dns": {
    "servers": [
      "fakedns",
      “1.1.1.1”,
      {
        "port": 53,
        "domains": [
          "geosite:cn"
        ],
        "address": "192.168.2.1"
      }
    ]
  },</pre>

在"routing"模块增加对应的国外DNS地址走代理，这里的代理是tag"default"，顺序放于最顶层即可
<pre>
      {
        "ip": [
          "1.1.1.1"
        ],
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "default"
      },</pre>

**Comment by chika0801** [comment]
现在的DNS查询流程就成了

1-3不变

4 进入Xray内置“DNS"，由于"servers"规则是FakeDNS和在geosite:cn里面的域名使用本地运营商DNS解析。此域名不会再用FakeDNS，此域名不是在geosite:cn中，不会使用本地运营商DNS解析，使用1.1.1.1DNS解析
5 1.1.1.1命中"default"规则 ，走我的VPS节点。
6 我VPS访问1.1.11得到IP，返回给客户端
7 客户端查到此IP命中geoip:cn规则 ，走直连

**Comment by chika0801** [comment]
我在V2rayNG上一直使用的类似Xray分流规则+FakeDNS+分应用代理，只是 "domainStrategy": "IPOnDemand", 我用的是IPifnoMatch。这个不是问题。

禁止VPS端访问CN是因为 https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165 
我在全网第一次大规则封443端口后，在VPS端配置加了禁止访问CN，到现在自己的几个VPS再也没遇到被封端口。

我才开始用了解路由器翻墙，找了几个程序试了一下，感谢你的Passwall2真是非常的好用（也许对新手来说新人也搞不懂）
但是对熟悉Xray配置的人就太喜欢了，肯请你能小小改进一下。

**Comment by chika0801** [comment]
![屏幕截图 2022-04-10 103451](https://user-images.githubusercontent.com/88967758/162598713-06c91a76-75cb-4cdb-bf35-95dff6dd3c90.jpg)
可以在红框处增加对话框 ，输入用于查询不在geosite:cn中的域名，要用哪个DNS，比如1.1.1.1

**Comment by badgv** [comment]
我也觉得应该强化下DNS相关配置，现在只是把分流里面“直连”的域名，加到了DNS单独解析列表里面
应该还需要添加一组，把分流里面走“代理”的域名，也加到DNS解析模拟里面，使用默认的pw2全局DNS解析,比如下面这样
  "dns": {                                                   
    "disableFallback": true,                                 
    "queryStrategy": "UseIPv4",                              
    "servers": [                                             
      "tcp:\/\/1.1.1.1:53",                                  
      {                                                      
        "port": 53,                                          
        "domains": [                                                         
          "geosite:cn"                                                       
        ],                                                   
        "address": "180.76.76.76"                            
      },
      **{                                                      
        "port": 53,                                          
        "domains": [                                                         
          "geosite:cn"                                                       
        ],                                                   
        "address": "tcp:\/\/1.1.1.1:53"                            
      },**                                                      
    ],                                                       
    "disableCache": false,                                   
    "disableFallbackIfMatch": true,                          
    "tag": "dns-in1"                                  
  },

**Comment by badgv** [comment]
现在的xray DNS解析逻辑是：
匹配国内域名或直连域名走国内解析，这样假如访问的域名在国内，但不是geosite:cn里面，也不在自定义分流的直连域名里面，就会使用默认的代理解析，可能导致CDN的IP被解析到国外。

个人觉得使用：匹配geosite:gfw和自定义的代理域名列表走代理解析，dns解析里面默认使用国内代理服务器解析更合理。
"servers": [
      “1.1.1.1”,
      {
        "port": 53,
        "domains": [
          "自定义直连的域名",
          "geosite:cn"
        ],
        "address": "114.114.114.114"
      }
    ]
修改为下面这种逻辑：
"servers": [
      “114.114.114.114”,
      {
        "port": 53,
        "domains": [
          "自定义代理的域名",
          "geosite:gfw"
        ],
        "address": "8.8.8.8"
      }
    ]

更合理

**Comment by chika0801** [comment]
现在的xray DNS解析逻辑是：
匹配国内域名或直连域名走国内解析，这样假如访问的域名在国内，但不是geosite:cn里面，也不在自定义分流的直连域名里面，就会使用默认的代理解析，可能导致CDN的IP被解析到国外。


我自己的用法就是这个逻辑，域名不在geosite:cn，就用外国DNS1.1.1.1（走代理，远程的VPS解析后，返回IP给客户端）。
我不在乎这CDN的IP被解析到国外。


我这帖子主要是说在fakedns模式下，DNS服务器设置有问题

**Comment by badgv** [comment]
> 现在的xray DNS解析逻辑是： 匹配国内域名或直连域名走国内解析，这样假如访问的域名在国内，但不是geosite:cn里面，也不在自定义分流的直连域名里面，就会使用默认的代理解析，可能导致CDN的IP被解析到国外。
> 
> 我自己的用法就是这个逻辑，域名不在geosite:cn，就用外国DNS1.1.1.1（走代理，远程的VPS解析后，返回IP给客户端）。 我不在乎这CDN的IP被解析到国外。
> 
> 我这帖子主要是说在fakedns模式下，DNS服务器设置有问题

其实不管哪种逻辑，都是能用的，实际上目前这两种逻辑，使用起来细微差别是：
1、采用现在的DNS解析逻辑：当域名不在geosite:cn里面时，默认走代理解析，如果出现问题，那你可以到“规则管理”里面添加一组规则，添加你的CN域名到这个规则里面，并配置这组规则分流走直连模式，会自动添加这个域名到那个直连DNS domains列表里面。
2、使用我上面的逻辑：我访问国内域名是不会存在任何问题的，默认解析都是走国内解析，但是当我访问某一个网站打不开，说明这个网站被墙，那么我就需要去“规则管理”里面添加一组规则，添加这个被墙的域名，并配置这组规则走代理模式，此时会域名会自动添加到代理DNS的domains里面。

实际上配合分流规则的话，我认为后面这种逻辑更合理，“默认”全局直连，仅按个人需求配置代理的域名走代理更符合日常使用逻辑。

**Comment by chika0801** [comment]
实际上配合分流规则的话，我认为后面这种逻辑更合理，“默认”全局直连，仅按个人需求配置代理的域名走代理更符合日常使用逻辑。我打算先自己fork改个版本试试了……。

是这样的道理。我习惯了我的逻辑，因为我日常浏览网页，需求是大部分网站是国外的。

**Comment by chika0801** [comment]
> 更新最新源码重新配置一下DNS再体验反馈？

感谢你的回复，我去测试一下

**Comment by xiaorouji** [comment]
其实不太建议使用FakeDNS，建议直接使用TCP、DOH请求远程DNS，也不差那么点时间，毕竟第一次解析到IP后会有缓存，而且目前Xray的FakeDNS有个BUG，嗅探器没处理UDP，使用UDP是blocked的。

**Comment by chika0801** [comment]
> 其实不太建议使用FakeDNS，建议直接使用TCP、DOH请求远程DNS，也不差那么点时间，毕竟第一次解析到IP后会有缓存，而且目前Xray的FakeDNS有个BUG，嗅探器没处理UDP，使用UDP是blocked的。

感谢你的回复。FakeDNS那个BUG我是知道的。那我就不再执着用fakedns了。

**Comment by xiaorouji** [comment]
@badgv 打开IPv6透明代理就是UseIP

**Comment by badgv** [comment]
> @badgv 打开IPv6透明代理就是UseIP

好像psw2没有这个菜单呢，旧版的psw在高级设置有个IPV6透明代理选项。新版的没找到这菜单
新版的我设置了tcp代理方式为tproxy，xray配置文件还是用的UseIPv4

**Comment by chancat87** [comment]
> > @badgv 打开IPv6透明代理就是UseIP
> 
> 好像psw2没有这个菜单呢，旧版的psw在高级设置有个IPV6透明代理选项。新版的没找到这菜单 新版的我设置了tcp代理方式为tproxy，xray配置文件还是用的UseIPv4

psswall2，dns选择fakedns之后下面有个选项可以选择UseIP/UseIPv4
