### ISSUE TITLE
[Bug]: 无论xray还是sing-box做主程序dnsmasq都会出问题

### ISSUE THREAD

**Issue by SingTsang** [xiaorouji/openwrt-passwall2#491]
### 描述您遇到的bug

xray做主程序会出现
2024/02/23 19:47:17 127.0.0.1:47013 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:17 127.0.0.1:33508 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:18 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:18 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 127.0.0.1:56916 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:19 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:20 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:20 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:20 127.0.0.1:51717 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:20 127.0.0.1:53202 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:20 127.0.0.1:38695 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:20 127.0.0.1:33231 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request
2024/02/23 19:47:21 [Error] app/dns: UDP:127.0.0.1:15355 cannot find the pending request

大量的1.1.1.1:53dns的dns-in和dns-out
切换成sing-box也是如此

+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2-zj-shxcm.kwaicdn.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w4-pro.kskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ali-adaptive.pull.yximgs.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1-pro.kwaicdn.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for zt.v6.ksapisrv.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1-pro.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w1-pro.kskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for upload.gifshow.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ali2.a.yximgs.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1-pro.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for hw-adaptive.pull.yximgs.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ulogjs.gifshow.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ali2.a.yximgs.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2.oskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for api1.kwaixiaodian.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w4-pro.kskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w3-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w1-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ali2.a.yximgs.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ntp.nc.gifshow.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for ali2.a.yximgs.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1-pro.kwaicdn.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for api1.kwaixiaodian.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1.oskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w2-pro.kskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w5-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w3-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for p5-pro.a.yximgs.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1.kwaicdn.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w5-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for sfaf.ksapisrv.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for httpdns1.cc.cdnhwc5.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1.kwaicdn.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for api1.kwaixiaodian.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w1-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for kuaishou.httpdns.pro. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v1.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w5-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2.kwaicdn.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w4-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for httpdns.bcelive.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w5-pro.kskwai.com. IN A: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for w2-pro.kskwai.com. IN AAAA: context canceled
+0800 2024-02-23 19:56:29 ERROR dns: exchange failed for v2.kwaicdn.com. IN A: context canceled

大量的context canceled

导致过多的连接堵塞网络，dnsmasq进程cpu占用极高，最后导致系统崩溃，我的passwall2设置都是默认的设置，上游的dnsmasq也是默认的设置，关闭了passwall2就没问题了

![微信图片_20240223201454](https://github.com/xiaorouji/openwrt-passwall2/assets/21009275/c696e337-26ea-4fe5-9931-de03f068bebe)
![screenshot-1708690547360](https://github.com/xiaorouji/openwrt-passwall2/assets/21009275/88fbf64a-349a-4537-9308-98fcc23b1c0c)
![screenshot-1708690559734](https://github.com/xiaorouji/openwrt-passwall2/assets/21009275/25cc708f-94d0-4904-9f35-f6ad3ec05efd)
![screenshot-1708690576740](https://github.com/xiaorouji/openwrt-passwall2/assets/21009275/65a9cdd2-b5f9-4eaf-9830-51b363b4a670)

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

passwall2版本：1.21-3
dnsmasq：2.89
sing-box：1.5.2
xray：1.8.4

**Comment by xiaorouji** [comment]
請不要使用舊版本反饋問題。

**Comment by SingTsang** [comment]
> 請不要使用舊版本反饋問題。

今天更新的最新的还是一样的问题，核心都更新到最新了

**Comment by SingTsang** [comment]
> sing-box 不支持 vmess + tls 至少我官方docker sing-box 没成功过。而且也没有错误log。单纯vmess没问题。

不是tls，纯vmess，现在我都郁闷死了，无端端这样，电脑还好，手机打开快手或者抖音就一大堆dns请求，3秒内起码500以上+的请求，1台手机就这个样子了，如果3台或者以上的手机同时打开视频app，路由不知道会不会瞬间冒烟

**Comment by SingTsang** [comment]
ipv6关了也一样，看到一个老的issues，情况有点类似
[https://github.com/xiaorouji/openwrt-passwall2/issues/184](url)
不知道是不是这个原因了

**Comment by xiaorouji** [comment]
嘗試最新的commit
