### ISSUE TITLE
[Feature Request]:  添加SING-BOX  的TUN 模式。

### ISSUE THREAD

**Issue by daifeilail** [xiaorouji/openwrt-passwall2#494]
### 描述你想要的新功能

添加SING-BOX  的TUN 模式。

### 描述你想要的解决方案

IPTABLES/NFTABLES 这种拦截方式，不方便查找故障，特别是复杂分流场景下，  也不利于分析是否出现的路由泄漏。    SING-BOX  TUN 我已经用了一段时间感觉很方便。抓包排错很方便。希望增加进来。    使用TUN 模式， 可以直接使用内核原生 的路由匹配机制。 甚至XDP。

**Comment by davidtall** [comment]
支持

**Comment by hcym** [comment]
电脑上用的蛮好，路由器还不会

**Comment by Nicepaul** [comment]
同样，希望添加SING-BOX 的TUN 模式

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/057fdbccbf5b0d8446cb3b98af3b0a5b419b8d52
需要測試，目前只在iptables上測試通過。nftables是盲寫的，有待測試。

**Comment by eqfae** [comment]
> [057fdbc](https://github.com/xiaorouji/openwrt-passwall2/commit/057fdbccbf5b0d8446cb3b98af3b0a5b419b8d52) 需要測試，目前只在iptables上測試通過。nftables是盲寫的，有待測試。

合并到主分支 让action编译出支持的ipk以供测试

**Comment by xiaorouji** [comment]
發現一個問題，測試玩GTA5、PUBG、雙人同行這些無問題，但是玩L4D2無法直接在遊戲開本地服務器，只能作為玩家加入，用TProxy正常。目前得看看是什麼情況。
