### ISSUE TITLE
[Bug]: 域名解析策略似乎无法达到预期

### ISSUE THREAD

**Issue by nbMars1980** [xiaorouji/openwrt-passwall2#497]
### 描述您遇到的bug

自己注册的域名A记录 kr2.founded.eu.org指向到193.123.244.24
域名未加入任何规则中，将IP193.123.244.24添加到proxy里
域名解析策略为：IPIfNonMatch
访问 kr2.founded.eu.org时不走代理

### 复现此Bug的步骤

不然复现

### 您想要实现的目的

根据域名解析策略为：IPIfNonMatch描述，kr2.founded.eu.org找不到匹配规则，那么应该解析成IP后匹配到193.123.244.24，然后走代理

### 日志信息

2024/02/27 14:17:31 192.168.0.3:42647 accepted udp:114.114.114.114:53 [udp_redir -> direct]
2024/02/27 14:17:31 [Info] app/dns: UDP:127.0.0.1:15354 got answer: kr2.founded.eu.org. TypeA -> [193.123.244.24] 2.204719ms
2024/02/27 14:17:31 [Info] app/dns: UDP:127.0.0.1:15354 got answer: kr2.founded.eu.org. TypeAAAA -> [] 5.431551ms
2024/02/27 14:17:31 [Info] app/dns: failed to lookup ip for domain kr2.founded.eu.org at server UDP:127.0.0.1:15354 > empty response
2024/02/27 14:17:32 [Info] proxy/vless/outbound: tunneling request to tcp:v1.mux.cool:9527 via 152.70.239.162:18443
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 24 139 0
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 47 204 0
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 24 65 0
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 47 208 0
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 24 57 0
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 47 237 0
2024/02/27 14:17:32 [Info] proxy: Xtls Unpadding new block, content 16 padding 199 command 0
2024/02/27 14:17:32 [Info] proxy: Xtls Unpadding new block, content 122 padding 28 command 0
2024/02/27 14:17:32 [Info] proxy: Xtls Unpadding new block, content 16 padding 102 command 0
2024/02/27 14:17:32 [Info] proxy: XtlsFilterTls stop filtering16
2024/02/27 14:17:32 [Info] proxy: Xtls Unpadding new block, content 63 padding 118 command 0
2024/02/27 14:17:32 [Info] proxy: Xtls Unpadding new block, content 16 padding 124 command 1
2024/02/27 14:17:32 [Info] [1901399273] proxy/dokodemo: received request for [240e:390:1ae0:13d0:116a:d157:33f6:3460]:45185
2024/02/27 14:17:32 [Info] [1901399273] app/dispatcher: taking detour [Proxy] for [udp:[2403:300:a30:3000::1f2]:123]
2024/02/27 14:17:32 [Info] [1901399273] common/mux: dispatching request to udp:[2403:300:a30:3000::1f2]:123
2024/02/27 14:17:32 [Info] proxy: XtlsPadding 36 142 1

### 截图

![1](https://github.com/xiaorouji/openwrt-passwall2/assets/108038855/d081dbc7-6dbf-4ca2-ba81-e7b03e9f90e3)
![2](https://github.com/xiaorouji/openwrt-passwall2/assets/108038855/00772979-8e66-45a7-90c8-9983eef5cea1)

### 系统相关信息

passwall2版本：1.26-1

**Comment by soffio** [comment]
上个月也提过这个问题 #451

**Comment by 2fact** [comment]
域名解析策略为 IPIfNonMatch 时并不会生效，因为生成的 global.json 里路由规则最后总有一个 default，总能匹配上，所以并不会触发 IP 解析再匹配。
临时解决方法把策略改成 IPOnDemand 应该就可以。不过会导致额外解析成本。
Xray 好像没有计划增加像 Sing-Box 类似的指定默认路由的功能，所以要修复得把这条 default 规则去掉，确保 default outbound 在第一个。

```json5
      {
        "type": "field",
        "_flag": "default",
        "outboundTag": "default",
        "network": "tcp,udp"
      }
    ],
    "domainStrategy": "IPIfNonMatch", // <- Won't work
    "domainMatcher": "hybrid"
  },
```

**Comment by Deleted-Account** [comment]
> > 域名解析策略为 IPIfNonMatch 时并不会生效，因为生成的 global.json 里路由规则最后总有一个 default，总能匹配上，所以并不会触发 IP 解析再匹配。 临时解决方法把策略改成 IPOnDemand 应该就可以。不过会导致额外解析成本。 Xray 好像没有计划增加像 Sing-Box 类似的指定默认路由的功能，所以要修复得把这条 default 规则去掉，确保 default outbound 在第一个。
> > ```js
> >       {
> >         "type": "field",
> >         "_flag": "default",
> >         "outboundTag": "default",
> >         "network": "tcp,udp"
> >       }
> >     ],
> >     "domainStrategy": "IPIfNonMatch", // <- Won't work
> >     "domainMatcher": "hybrid"
> >   },
> > ```
> 
> 谢回复，我目前使用的AsIs还算够用，IPOnDemand这个是pw2默认的方式，这个不是基于ip的吗？ 另外我还是不清楚pw2里面使用sibgbox的hy2分流，他是和xray分流使用的一样的解析策略还是怎样？我有发现从xray分流切到sibgbox分流，有时候会不生效或者错误。 xiaorouji这次更新增加的“直连 DNS 解析结果写入到 IPSet”目前感觉还不错

Sing-box应该是类似AsIs。
Sing-box需要自己更新geodate，跟Xray的不一样不通用。

我最近也是用Sing-box跑Hysteria2。没遇到分流的问题。

用Sing-box，分流规则按之前的方式写，一样的。
也是
geosite:geolocation-!cn
domain:xxxxxxxxx
full:xxxxxxxxxxx
这些
xiaorouji大佬会帮你生成Sing-box的配置

**Comment by fanfanli1988** [comment]
同样的现象。

感谢各位的提醒，已参考设置解决了问题。
