### ISSUE TITLE
[Bug]: 更新新版本1.27.-1后，点击百度显示连接失败。

### ISSUE THREAD

**Issue by etsam** [xiaorouji/openwrt-passwall2#498]
### 描述您遇到的bug

更新新版本1.27.-1后，使用SINGBOX时 点击百度显示连接失败，google和github正常，但是也能正常上网,

回退到1.25版本后正常。
![309318442-f9158ee5-b9b4-4173-a004-a2ee9d3495dc](https://github.com/xiaorouji/openwrt-passwall2/assets/24689501/9f186c7e-76e4-4579-a3b7-55e73c161b92)

有在PASSWALL反馈区看到同样的问题。https://github.com/xiaorouji/openwrt-passwall/issues/2970

### 复现此Bug的步骤

更新最新版本出现

### 您想要实现的目的

恢复百度测试连接

### 日志信息

NA

### 系统相关信息

1.27-1
chrome浏览器。

**Comment by Deleted-Account** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/48331538/fc0634a9-c940-4d3d-a562-acf4dd119345)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/48331538/6e03b0c4-bed2-40d5-a1dc-8449d13d53f4)

**Comment by etsam** [comment]
你的Sing-box 有升级到最新的吗

**Comment by Deleted-Account** [comment]
> 你的Sing-box 有升级到最新的吗

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/48331538/24015692-12f4-4420-93c0-4c0b2a6c4086)

**Comment by Travel2Here** [comment]
前几天反馈了一次 没人遇到似的。我的情况跟楼主完全一样~
pw2 luci app最新版，sb最新版1.8.7（我实测1.8.4及之前的版本都能正常显示）

**Comment by Travel2Here** [comment]
> ![image](https://private-user-images.githubusercontent.com/48331538/309015066-fc0634a9-c940-4d3d-a562-acf4dd119345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQwNDAsIm5iZiI6MTcwOTI4Mzc0MCwicGF0aCI6Ii80ODMzMTUzOC8zMDkwMTUwNjYtZmMwNjM0YTktYzk0MC00ZDNkLWE1NjItYWNmNGRkMTE5MzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMGQwNDFmZTdkZGVmZWM4OTc4NTM5YzkwM2MwNjUxMzgwNGRjODEwMjQwOTQwNmJlODc2N2U2ZWE4OWEyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZoYJwjemgoeEaVYUhBysc5Kbk3sXeeXI27jeBqeCIMQ) ![image](https://private-user-images.githubusercontent.com/48331538/309015358-6e03b0c4-bed2-40d5-a1dc-8449d13d53f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQwNDAsIm5iZiI6MTcwOTI4Mzc0MCwicGF0aCI6Ii80ODMzMTUzOC8zMDkwMTUzNTgtNmUwM2IwYzQtYmVkMi00MGQ1LWExZGMtODQ0OWQxM2Q1M2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZWI2OGQyMWNmNmI1MzAwMTcwYjJlMmRjODhkNDc2YTZjMmFiMzI5ZmE2NDc3ZGY4OTcxOTA0ODRiMTA5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FPQHD93BkKx7M02DATTnCAEeGrmRb-6X5vhGLV61KU)
> 
> 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome

朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？

**Comment by etsam** [comment]
> 前几天反馈了一次没人遇到类似的。我的情况跟楼主完全一样~ pw2 luci app最新版本，sb最新版本1.8.7（我实测1.8.4及之前的版本都正常显示）

不知道是怎么回事，我用的LEAN的代码 别的插件都没添加 只加了PW2，这次是在原来的固件代码上将PW2升级到1.27-1 在刷进机器 开启PW2 百度就显示连接失败，但是国内 国外网站访问都是正常的，百度也能访问。
后来重新刷回1.25 就是正常的。

**Comment by Deleted-Account** [comment]
> > ![image](https://private-user-images.githubusercontent.com/48331538/309015066-fc0634a9-c940-4d3d-a562-acf4dd119345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQwNDAsIm5iZiI6MTcwOTI4Mzc0MCwicGF0aCI6Ii80ODMzMTUzOC8zMDkwMTUwNjYtZmMwNjM0YTktYzk0MC00ZDNkLWE1NjItYWNmNGRkMTE5MzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMGQwNDFmZTdkZGVmZWM4OTc4NTM5YzkwM2MwNjUxMzgwNGRjODEwMjQwOTQwNmJlODc2N2U2ZWE4OWEyOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZoYJwjemgoeEaVYUhBysc5Kbk3sXeeXI27jeBqeCIMQ) ![image](https://private-user-images.githubusercontent.com/48331538/309015358-6e03b0c4-bed2-40d5-a1dc-8449d13d53f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQwNDAsIm5iZiI6MTcwOTI4Mzc0MCwicGF0aCI6Ii80ODMzMTUzOC8zMDkwMTUzNTgtNmUwM2IwYzQtYmVkMi00MGQ1LWExZGMtODQ0OWQxM2Q1M2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZWI2OGQyMWNmNmI1MzAwMTcwYjJlMmRjODhkNDc2YTZjMmFiMzI5ZmE2NDc3ZGY4OTcxOTA0ODRiMTA5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FPQHD93BkKx7M02DATTnCAEeGrmRb-6X5vhGLV61KU)
> > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> 
> 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？

用docker装两个AGH，就可以实现国内国外DNS分组了

**Comment by Travel2Here** [comment]
> > > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> > 
> > 
> > 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
> 
> 用docker装两个AGH，就可以实现国内国外DNS分组了

不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？

**Comment by Deleted-Account** [comment]
> > > > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> > > 
> > > 
> > > 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
> > 
> > 
> > 用docker装两个AGH，就可以实现国内国外DNS分组了
> 
> 不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？

Passwall2，WAN重播或者运营商回收IP导致重播，会自动重启一次，这次重启目前版本还有问题，应该还没解决。需要自己手动重启或者 service passwall2 restart

**Comment by Deleted-Account** [comment]
> > > > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> > > 
> > > 
> > > 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
> > 
> > 
> > 用docker装两个AGH，就可以实现国内国外DNS分组了
> 
> 不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？

DNS污染？你分两个AGH，DNS分流正常的话，不会有污染啊。远程DNS上游只填国外DNS，直连DNS上游只填国内DNS（然后把这个AGH放到dnsmasq的dns forwardings）。

虽然PW2的远程DNS选直连，是直连到你的AGH，这个AGH上游的上游DNS还是可以走代理

**Comment by Deleted-Account** [comment]
> > > > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> > > 
> > > 
> > > 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
> > 
> > 
> > 用docker装两个AGH，就可以实现国内国外DNS分组了
> 
> 不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？

最近IP策略？

你DNS分流正常的话，
你直连DNS那个AGH，上游全是国内DNS，不走代理，肯定不绕路。不放心还可以加个EDNS，放个你们当地DNS的IP

远程DNS，上游全是国外DNS并且设置走代理，那就全是节点去连DNS服务器获得的DNS解析。

**Comment by 2eronia** [comment]
> 你的Sing-box 有升级到最新的吗

https://github.com/xiaorouji/openwrt-passwall2/issues/481
https://github.com/xiaorouji/openwrt-passwall2/issues/476

**Comment by etsam** [comment]
> > 你的Sing-box 有升级到最新的吗
> 
> #481 #476

这个我早看过了 这2个反馈是显示0 我这个是显示“连接失败”

**Comment by jt8823** [comment]
同样最新pw2  百度显示连接失败

**Comment by swxk521** [comment]
最新版，xray1.8.8  sing-box1.8.7  未使用DNS插件，pw2自带设置远程DNS 直连和代理  ping均显示正常。

**Comment by etsam** [comment]
我测试好久 无意间发现一个好奇怪的现象
![123123](https://github.com/xiaorouji/openwrt-passwall2/assets/24689501/f9158ee5-b9b4-4173-a004-a2ee9d3495dc)

在1.25的PW2下 把SINGBOX从1.8.4升级到1.8.7也会出现点击百度连接 显示“连接失败”
 我连续等待了5分钟左右 点击还是无法显示ping值，直到一次我无意识直接在浏览器上打开百度页面（本来就能打开），然后再点击PW2的“百度连接” 居然可以显示了数值了。

这个问题在我这个固件下复现很简单，什么都不更改，在PW2首页直接点保存应用后 ，”百度连接 “又会显示连接失败，但是只要你打开一次百度页面，再来点击，PING的数值就能显示。后面一直能显示，正常。（除非 你又点击“保存应用”）测试了不下5次

这是个什么原理，实在是搞不懂？

**Comment by Travel2Here** [comment]
> > > > > 用的Sing-box。直连和远程DNS分别是本地搭建的两个AdGuarHome
> 
> > > > 
> 
> > > > 
> 
> > > > 朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
> 
> > > 
> 
> > > 
> 
> > > 用docker装两个AGH，就可以实现国内国外DNS分组了
> 
> > 
> 
> > 不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？
> 
> 
> 
> 最近IP策略？
> 
> 
> 
> 你DNS分流正常的话，
> 
> 你直连DNS那个AGH，上游全是国内DNS，不走代理，肯定不绕路。不放心还可以加个EDNS，放个你们当地DNS的IP
> 
> 
> 
> 远程DNS，上游全是国外DNS（一般用DoH或者DoT），并且设置走代理，那就全是节点去连DNS服务器获得的DNS解析。

朋友这方式目的是啥？过滤广告+乐观缓存？
曾经用过pw2配国内dns走adg，体验不太理想，一开始缓存的爽 用一阵会远程dns泄露 分流失败  不甚烦恼 后来就只用pw2管理了 只是不确定是不是完全没缓存 每次刷都感觉重新解析了 稍微慢点

**Comment by Deleted-Account** [comment]
> 我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？

我有点烦了，很烦的那种烦。***我发的你不看也不理解。***


我先说了 PW2 目前有个情况下会DNS分流混乱：目前版本是 WAN口重播或者运营商回收IP导致的那次PW2重启，之后如果不手动强制重启PW2，DNS会分流失败。


然后我回答你 "我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的"
我的回答就是装两个AGH，分别对应国内DNS国外DNS，远程DNS或者说国外DNS填PW2的DNS设置，国内DNS填dnsmasq的上游。
只要DNS正常分流，就不会有DNS污染。
**这里我漏说了，Xray域名策略我用的AsIs，Sing-box没有这个选项，不过我用下来也是按域名分流的。**


只要不出现前面提的那种WAN重播后PW2重启导致的DNS分流混乱，PW2用Sing-box***DNS都是严格分流的***。前些日子PW2直接drop掉非A/AAAA的查询，应该也修好了Xray-core的DNS分流。


***你看清我说的，我装了2个AGH，你装1个，能跟我用的一样吗？***

**Comment by Travel2Here** [comment]
> > 我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？
> 
> 
> 
> 我有点烦了，很烦的那种烦。***我发的你不看也不理解。***
> 
> 
> 
> 
> 
> 我先说了 **PW2 目前有个情况会导致DNS分流混乱**：目前版本是 WAN口重播或者运营商回收IP导致的那次PW2重启，之后如果不手动强制重启PW2，DNS会分流失败。**表现就是一个域名同时向国内和国外，或者说远程和直连DNS发起DNS请求。**但是域名是走直连还是代理，看上去是正常的。
> 
> https://github.com/xiaorouji/openwrt-passwall2/issues/470
> 
> 看最近的commit，好像没修，到1.27-1应该还是存在这个问题
> 
> 
> 
> 远程DNS是PW2设置的概念，不是地域上的概念。你可以把远程DNS设置成本地架设的AGH的，outbound选直连。
> 
> **我装了两个AGH，分别用来给直连和远程DNS。你觉得多此一举也好，反正我可以看分流后的日志排查情况。**
> 
> (实际我装了3个，还有个做dnsmasq前端取代53端口。这个AGH不开Optimistic caching，开了的话，某个版本AGH更新后，会偶尔出现一堆 query 7秒的问题，我不晓得为何)
> 
> 
> 
> 然后我回答你 "我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的"
> 
> 我的回答就是装两个AGH，分别对应国内DNS国外DNS，远程DNS或者说国外DNS填PW2的DNS设置，国内DNS填dnsmasq的上游。
> 
> ***只要DNS正常分流，两个AGH，上游分别 只填国内DNS 或 国外DoH/DoT，就不会有DNS污染。***
> 
> 
> 
> **这里我漏说了，Xray域名策略我用的AsIs，Sing-box没有这个选项，不过我用下来也是按域名分流的。**
> 
> 
> 
> 
> 
> 只要不出现前面提的那种WAN重播后PW2重启导致的DNS分流混乱，PW2用Sing-box***DNS都是严格分流的***。前些日子PW2直接drop掉非A/AAAA的查询，应该也修好了Xray-core的DNS分流。
> 
> https://github.com/xiaorouji/openwrt-passwall2/discussions/471
> 
> https://github.com/xiaorouji/openwrt-passwall2/commit/f352501608c32b005963c69a6de2e3fd5f860d8a
> 
> 
> 
> 
> 
> ***你看清我说的，我装了2个AGH，你装1个，能跟我用的一样吗？***
> 
> 
> 
> 你再问来问去又不看我说的，我就把所有回答全删了，我觉得我好多管闲事

不要着急，你的回答都看了且都理解，我只是说曾经用过adg做直连上游体验一般，不代表不明白你是2个。
最后的疑问是既然pw2本体就能跟dnsmasq合作正常解析，为何要多此一举？目的是什么…仅此而已（没耐心的话可以不必再回答）

**Comment by Deleted-Account** [comment]
> > > 我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？
> > 
> > 
> > 我有点烦了，很烦的那种烦。_**我发的你不看也不理解。**_
> > 我先说了 **PW2 目前有个情况会导致DNS分流混乱**：目前版本是 WAN口重播或者运营商回收IP导致的那次PW2重启，之后如果不手动强制重启PW2，DNS会分流失败。**表现就是一个域名同时向国内和国外，或者说远程和直连DNS发起DNS请求。**但是域名是走直连还是代理，看上去是正常的。
> > #470
> > 看最近的commit，好像没修，到1.27-1应该还是存在这个问题
> > 远程DNS是PW2设置的概念，不是地域上的概念。你可以把远程DNS设置成本地架设的AGH的，outbound选直连。
> > **我装了两个AGH，分别用来给直连和远程DNS。你觉得多此一举也好，反正我可以看分流后的日志排查情况。**
> > (实际我装了3个，还有个做dnsmasq前端取代53端口。这个AGH不开Optimistic caching，开了的话，某个版本AGH更新后，会偶尔出现一堆 query 7秒的问题，我不晓得为何)
> > 然后我回答你 "我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的"
> > 我的回答就是装两个AGH，分别对应国内DNS国外DNS，远程DNS或者说国外DNS填PW2的DNS设置，国内DNS填dnsmasq的上游。
> > _**只要DNS正常分流，两个AGH，上游分别 只填国内DNS 或 国外DoH/DoT，就不会有DNS污染。**_
> > **这里我漏说了，Xray域名策略我用的AsIs，Sing-box没有这个选项，不过我用下来也是按域名分流的。**
> > 只要不出现前面提的那种WAN重播后PW2重启导致的DNS分流混乱，PW2用Sing-box_**DNS都是严格分流的**_。前些日子PW2直接drop掉非A/AAAA的查询，应该也修好了Xray-core的DNS分流。
> > #471
> > [f352501](https://github.com/xiaorouji/openwrt-passwall2/commit/f352501608c32b005963c69a6de2e3fd5f860d8a)
> > _**你看清我说的，我装了2个AGH，你装1个，能跟我用的一样吗？**_
> > 你再问来问去又不看我说的，我就把所有回答全删了，我觉得我好多管闲事
> 
> 不要着急，你的回答都看了且都理解，我只是说曾经用过adg做直连上游体验一般，不代表不明白你是2个。 最后的疑问是既然pw2本体就能跟dnsmasq合作正常解析，为何要多此一举？目的是什么…仅此而已（没耐心的话可以不必再回答）

？？解释下什么叫 "多此一举"？❔
你自己不会用，都用出 DNS 污染了，我觉得你叫"自以为是"……仅此而已。（你不觉得你自己是"自以为是"的话可以不必再回复）

**Comment by etsam** [comment]
> 同样最新pw2 百度显示连接失败

你试试 浏览器打开百度首页不关  再点PW2的百度测速，看是不是会好

**Comment by Deleted-Account** [comment]
> 别再回了。再多就是垃圾了~谢谢 （向本issue题主致歉，再者占用了这么多无效回复）

---

？？？？？**有病的是你吧**？！你要不要复盘一下啊？


你先问的：

```
朋友这远程也是个本地dns服务器，怎么保障正确获取解析？adg上游用的不是google或者cloudflare等dns？
```


我回答你：

```
用docker装两个AGH，就可以实现国内国外DNS分组了
```


然后你**居然接着问**：
```
不是，我的疑问是dns污染及最近ip策略的问题，怎么规避/保障的？
```


其实这时候我已经清楚知道你根本不会用了。
我还好心回答了你3条，
说明了只要规避当前版本 PW2 DNS 分流失败（已修复 https://github.com/xiaorouji/openwrt-passwall2/commit/9a63b3ca57100a446bd5619b68b5bc52e4536cb5 ），装两个 AGH 实现分组不会有无污染。
说了DNS是严格分流的，IP解析不会绕路。

结果你来一条什么？：

```
朋友这方式目的是啥？过滤广告+乐观缓存？
曾经用过pw2配国内dns走adg，体验不太理想，一开始缓存的爽 用一阵会远程dns泄露 分流失败 不甚烦恼 后来就只用pw2管理了 只是不确定是不是完全没缓存 每次刷都感觉重新解析了 稍微慢点
```

天哦，白回答那么多咯~
喵的，明明就是你自己不会用啊，还很自信很自以为是。
然后我才生气得回复了你一长串。

接着你怎么说的？

```
不要着急，**你的回答都看了且都理解**，我只是说曾经用过adg做直连上游体验一般，不代表不明白你是2个。
最后的疑问是既然pw2本体就能跟dnsmasq合作正常解析，为何要多此一举？目的是什么…仅此而已（没耐心的话可以不必再回答）
```

说难听点，**你理解个屁**！！
于是我才按你说话的方式回复你讽刺你

```
你自己不会用，都用出 DNS 污染了，我觉得你叫"自以为是"……仅此而已。
```

哦，然后我就变成有病了？
确实有病，教一个自以为是的人怎么用两个AGH，你不会用你有DNS污染我没没有，我真是有病哦真是按你说的"多此一举"！


居然还用"占用公共资源"那套低劣的手法企图封口。

**有病的是你**！
