### ISSUE TITLE
dns解析问题

### ISSUE THREAD

**Issue by hswmartin** [xiaorouji/openwrt-passwall2#5]
发现主分流节点选v2ray,默认节点选xray,不能解析DNS，其它组合则没有问题。

**Comment by hswmartin** [comment]
编译的时候没有勾选v2ray_plugin造成的

**Comment by hu-boss** [comment]
我有v2ray_plugin，也不能解析啊

**Comment by hswmartin** [comment]
> 我有v2ray_plugin，也不能解析啊

不知道什么原因，v2ray做分流节点不太稳定，我现在分流节点用xray,毛病少些
