### ISSUE TITLE
[Bug]: 与SNAPSHOT版的DNSmasq存在兼容问题

### ISSUE THREAD

**Issue by hululu1068** [xiaorouji/openwrt-passwall2#501]
### 描述您遇到的bug

最新版的DNSmasq有比较大的变化，如下↓
<img width="989" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/68652362/9f560d0d-b703-4dee-b30f-09437adbbef1">

如果访问的域名不在`已配置`的`黑名单`中，会解析不到`ip`,造成无法访问。
似乎是新版本的DNSmasq`监听接口`配置有调整。

### 复现此Bug的步骤

1. 如以往一样配置好passwall2,启动；
2. 在客户端访问一个`GFW`的域名，且这个域名没有配置在`passwall2`的`代理名单`中，如`www.yahoo.com`;
3. 会发现解析不到`ip`，非`GFW`，或已配置`代理名单`的域名则正常；
4. 或者`passwall2`启动后，在重启下`DNSmasq`也能正常访问。

### 您想要实现的目的

适配`dnsmasq-full - 2.89-4`

### 日志信息

nslookup www.yahoo.com
Server:		192.168.123.253
Address:	192.168.123.253#53

** server can't find 1: NXDOMAIN

### 系统相关信息

luci-app-passwall2 - 1.27-1
dnsmasq-full - 2.89-4

### 其他信息

最后期望大佬让DNS配置里的，`直连DNS`、`远程DNS`配置回归吧，简直太好用了。
相信大多数人都是自行配置上游DNS的.

**Comment by xiaorouji** [comment]
嘗試一下最新的commit，我覺得應該可以解決大部分異常的issue。

**Comment by ZhongMoDao** [comment]
原来不止我一个人遇到这个问题啊

**Comment by hululu1068** [comment]
> 嘗試一下最新的commit，我覺得應該可以解決大部分異常的issue。

问题还是存在，似乎是`重启DNSmasq`的问题，手动重启下就正常了。

<img width="508" alt="image" src="https://github.com/xiaorouji/openwrt-passwall2/assets/68652362/e3f3314e-491b-4370-8f10-92ad88059f1c">
