### ISSUE TITLE
[Bug]: 哔站tv版封面加载失败

### ISSUE THREAD

**Issue by cjlhll** [xiaorouji/openwrt-passwall2#504]
### 描述您遇到的bug

重新连接wifi就好了，是什么问题啊。过一段时间又不行了，我把bilibili.com加到直连里面了。

### 复现此Bug的步骤

1、打开电视哔站
2、封面无法加载

### 您想要实现的目的

可以正常加载封面

### 日志信息

暂时不在家，没有日志。想问问有没有历史的情况。

### 系统相关信息

1.27-1版本

**Comment by xiaorouji** [comment]
升級到最新版本再測試反饋。

**Comment by catsimple** [comment]
dnsmasq的策略肯定有点问题，我也遇到了，当然现在我拉一下最新的版本看看有没有解决

**Comment by cjlhll** [comment]
> dnsmasq的策略肯定有点问题，我也遇到了，当然现在我拉一下最新的版本看看有没有解决

有解决方案麻烦告诉我一下。谢谢

**Comment by cjlhll** [comment]
> > > dnsmasq的策略肯定有点问题，我也遇到了，当然现在我拉一下最新的版本看看有没有解决
> > 
> > 
> > 有解决方案麻烦告诉我一下。谢谢
> 
> 1.27-5已解决dnsmasq的逻辑，使用正常

长期也没问题呗。我是过一会就不行了 ，重新连wifi又好使了。然后反复如此。

**Comment by cjlhll** [comment]
> 今天master升级2.90了，晚上覆盖大雕的编译看看

怎么样，现在的版本还有问题吗？
