### ISSUE TITLE
[Bug]: Sing-Box 分流总节点 分流异常

### ISSUE THREAD

**Issue by catsimple** [xiaorouji/openwrt-passwall2#506]
### 描述您遇到的bug

当使用Sing-box作为分流总节点的内核时，分流出现异常
具体表现为：
访问部分大陆网站被代理，通过AdGuardHome发现部分大陆域名被带上了代理IP的ECS，可知这些域名被分流到了海外

*同时这几个版本使用xray总分流内核时都遇到了浏览信息流时图片加载缓慢、加载不出来的情况，如B站视频封面图、微博图片等，换成singbox问题缓解，但是一些国内域名也被错误分流到海外，如讯飞和阿里云的域名，导致访问异常。目前1.27-3版本尚未测试是否还存在这个问题

### 复现此Bug的步骤

DNS设置如图
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/55bd2af0-677e-4552-b430-32c0fb3c81ce)
5336为MOSDNS端口，作用为添加海外ECS并发送到上游AdGuardHome，当域名带有ECS海外IP时，可知域名被分流到了海外，也就是使用了远程DNS服务器进行解析

使用Sing-box作为分流总节点时
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/b692c21f-b9f1-4a14-b8a6-374b5d0dc2d6)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/b6890ea0-620e-439a-8ab1-ae951f27dcf5)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/ce065168-2d87-45cf-9c9a-76675d75a36f)

使用Xray则分流正常
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/925e5adc-3fe2-4162-b4b3-22f1bbbb29a4)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/23014926/5674e8a4-577b-40c7-a311-e1060d8d1c56)

在Direct节点里单独设置对这些分流异常的大陆域名则可解析正常

### 您想要实现的目的

正常分流

### 日志信息

singbox作为分流总节点内核时，日志为空白
xray作为分流总节点内核时，日志很多1.1.1.1:53的in and out，但是我并没有配置1.1.1.1的DNS

### 系统相关信息

passwall 1.27-3
openwrt x86_64  6.1.80
NFTABLES+TPROXY

**Comment by etsam** [comment]
换PW1了 PW2最近问题有点多

**Comment by Travel2Here** [comment]
同，感觉通过pw2得到的SB的配置，和sb的新版有兼容问题。最近切回xray可正常分流。
另外就是使用sb分流时，openai、copilot直接会拒绝服务，相同配置xray是可用的。

**Comment by xiaorouji** [comment]
Xray和Sing-Box用的資源文件是不同的。

**Comment by Travel2Here** [comment]
> Xray和Sing-Box用的資源文件是不同的。

是，两套自己的geosite和geoip。不过都是用的大而全的版本，结果会跑偏。我再研究下是否是规则策略有描述上的差异~

另外我现在都没解决baidu连接测试显示不可达的问题。xiaorouji可否点拨一下？
(lede的5.15核，启用sb在1.8.5版本及更新后显示不可达，xray、sb1.8.4及以下正常。)

**Comment by xiaorouji** [comment]
用路由器本機和設備分別nslookup或者dig一下 www.baidu.com 看看

**Comment by etsam** [comment]
> > Xray和Sing-Box用的资源文件是不同的。
> 
> 是，两套自己的geosite和geoip。不过都是用的又大又全的版本，结果会偏跑。我再研究下是否是规则策略有描述上的差异~
> 
> 另外我现在还没解决baidu连接测试显示不达标的问题。xiaorouji可否点拨一下？ （lede的5.15核，启用sb在1.8.5版本及更新后显示不达标，xray、sb1.8.4及以下正常。）


我用了最新的PW2编译后 还是不行（XRAY模式 百度是可以显示数值的） 在 SB模式下 经过多次测试 切换 在某个特定状态下 百度突然能通 显示数值，但是过不多久又会显示“连接失败”。

无奈昨天晚上改用PW，XRAY和SB都一切正常，暂时先这样了。。。

**Comment by Travel2Here** [comment]
> 用路由器本機和設備分別nslookup或者dig一下 [www.baidu.com](http://www.baidu.com) 看看

路由里nslookup www.baidu.com：
```
Server:		127.0.0.1
Address:	127.0.0.1:53

Non-authoritative answer:

Non-authoritative answer:
```

——
nslookup http://www.baidu.com如下：
```
Server:		127.0.0.1
Address:	127.0.0.1:53

** server can't find http:.lan: NXDOMAIN

** server can't find http:.lan: NXDOMAIN
```

设备中nslookup还没测，晚点回去再看~

**Comment by xiaorouji** [comment]
無法解析 www.baidu.com ，請檢查一下國內直連DNS，或提供passwall日誌、Sing-Box日誌、Sing-Box版本。

**Comment by Travel2Here** [comment]
> 無法解析 [www.baidu.com](http://www.baidu.com) ，請檢查一下國內直連DNS，或提供passwall日誌、Sing-Box日誌、Sing-Box版本。

**Sing-Box日志（版本1.8.8），删除了中间 一部分无关的。看是否够判断，目测解析正常。但NSLOOKUP和luci连通性测试却那样。
（设备实际使用时能访问百度的）**

```
+0000 2024-03-07 09:46:22 INFO router: updated default interface pppoe-wan, index 15
+0000 2024-03-07 09:46:22 INFO router: loaded geoip database: 259 codes
+0000 2024-03-07 09:46:22 INFO router: loaded geosite database: 1512 codes
+0000 2024-03-07 09:46:23 INFO inbound/socks[socks-in]: tcp server started at 0.0.0.0:1070
+0000 2024-03-07 09:46:23 INFO inbound/tproxy[tproxy]: tcp server started at [::]:1041
+0000 2024-03-07 09:46:23 INFO inbound/tproxy[tproxy]: udp server started at [::]:1041
+0000 2024-03-07 09:46:23 INFO inbound/direct[dns-in]: tcp server started at 127.0.0.1:15353
+0000 2024-03-07 09:46:23 INFO inbound/direct[dns-in]: udp server started at 127.0.0.1:15353
+0000 2024-03-07 09:46:23 INFO sing-box started (0.299s)
+0000 2024-03-07 09:46:46 DEBUG [3633567027 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-03-07 09:46:46 DEBUG dns: exchange www.baidu.com. IN AAAA
+0000 2024-03-07 09:46:46 DEBUG dns: exchange www.baidu.com. IN A
+0000 2024-03-07 09:46:46 DEBUG dns: exchanged www.baidu.com NOERROR 10
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com CNAME www.baidu.com. 10 IN CNAME www.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A www.a.shifen.com. 10 IN A 183.2.172.42
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A www.a.shifen.com. 10 IN A 183.2.172.185
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns4.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns1.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns5.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns3.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns2.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA ns5.a.shifen.com. 10 IN AAAA 240e:940:603:a:0:ff:b08d:239d
+0000 2024-03-07 09:46:46 DEBUG dns: exchanged www.baidu.com NOERROR 10
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA ns5.a.shifen.com. 10 IN AAAA 240e:bf:b801:1006:0:ff:b04f:346b
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com CNAME www.baidu.com. 10 IN CNAME www.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA www.a.shifen.com. 10 IN AAAA 240e:ff:e020:966:0:ff:b042:f296
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA www.a.shifen.com. 10 IN AAAA 240e:ff:e020:9ae:0:ff:b014:8e8b
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns2.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns1.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns5.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns1.a.shifen.com. 10 IN A 110.242.68.42
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns3.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns2.a.shifen.com. 10 IN A 220.181.33.32
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com NS a.shifen.com. 10 IN NS ns4.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns3.a.shifen.com. 10 IN A 153.3.238.162
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA ns5.a.shifen.com. 10 IN AAAA 240e:bf:b801:1006:0:ff:b04f:346b
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns3.a.shifen.com. 10 IN A 36.155.132.12
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com AAAA ns5.a.shifen.com. 10 IN AAAA 240e:940:603:a:0:ff:b08d:239d
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns4.a.shifen.com. 10 IN A 111.20.4.28
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns1.a.shifen.com. 10 IN A 110.242.68.42
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns4.a.shifen.com. 10 IN A 14.215.177.229
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns2.a.shifen.com. 10 IN A 220.181.33.32
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns3.a.shifen.com. 10 IN A 153.3.238.162
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns3.a.shifen.com. 10 IN A 36.155.132.12
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns4.a.shifen.com. 10 IN A 111.20.4.28
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns4.a.shifen.com. 10 IN A 14.215.177.229
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns5.a.shifen.com. 10 IN A 180.76.76.95
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com A ns5.a.shifen.com. 10 IN A 180.76.76.95
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. CNAME www.baidu.com. 10 IN CNAME www.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. CNAME www.baidu.com. 10 IN CNAME www.a.shifen.com.
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. A www.a.shifen.com. 10 IN A 183.2.172.42
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. A www.a.shifen.com. 10 IN A 183.2.172.185
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. AAAA www.a.shifen.com. 10 IN AAAA 240e:ff:e020:966:0:ff:b042:f296
+0000 2024-03-07 09:46:46 INFO dns: exchanged www.baidu.com. AAAA www.a.shifen.com. 10 IN AAAA 240e:ff:e020:9ae:0:ff:b014:8e8b
+0000 2024-03-07 09:46:48 DEBUG [3313568152 10.0s] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-03-07 09:46:48 DEBUG [3216925675 10.0s] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-03-07 09:46:49 DEBUG [4187062658 10.0s] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-03-07 09:46:49 DEBUG [3484652628 10.0s] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-03-07 09:46:50 INFO [3864018011 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:40464
+0000 2024-03-07 09:46:50 INFO [2508181916 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:46603
+0000 2024-03-07 09:46:50 DEBUG [3864018011 0ms] router: sniffed packet protocol: dns
+0000 2024-03-07 09:46:50 DEBUG [3864018011 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
```

**PW2日志（1.27-4）, （注：127.0.0.1#5533是个dnsmasq上游服务器，开启与否都不影响现在的现象）：**

```
2024-03-07 17:46:17: 删除相关防火墙规则完成。
2024-03-07 17:46:21: 清空并关闭相关程序和缓存完成。
2024-03-07 17:46:21: 分析 Socks 服务的节点配置...
2024-03-07 17:46:21:   - Socks节点：XXXXXX打码节点地址XXXXX，启动 0.0.0.0:10666
2024-03-07 17:46:21:   - Socks节点：XXXXXX打码节点地址XXXXX，启动 0.0.0.0:11810
2024-03-07 17:46:21:   - Socks节点：XXXXXX打码节点地址XXXXX，启动 0.0.0.0:11852
2024-03-07 17:46:21:   - Socks节点：XXXXXX打码节点地址XXXXX，启动 0.0.0.0:10101
2024-03-07 17:46:22: 127.0.0.1#15353 （直连DNS：127.0.0.1#5533 远程DNS：https://1.1.1.1/dns-query）
2024-03-07 17:46:22:   - [0]节点列表中的域名(vpslist)：127.0.0.1#5533
2024-03-07 17:46:22:   - [0]默认：127.0.0.1#15353
2024-03-07 17:46:22: 开始加载防火墙规则...
2024-03-07 17:46:22:   - [0]追加ISP IPv4 DNS到白名单：202.96.XX.XX
2024-03-07 17:46:22:   - [0]追加ISP IPv4 DNS到白名单：202.96.XX.XX
2024-03-07 17:46:22:   - [0]追加ISP IPv6 DNS到白名单：240e:1f:1::1
2024-03-07 17:46:22: 加入负载均衡的节点到ipset[passwall2_vpslist]直连完成
2024-03-07 17:46:22: 加入所有节点到ipset[passwall2_vpslist]直连完成
2024-03-07 17:46:22:   - [0]追加直连DNS到iptables：127.0.0.1:5533
2024-03-07 17:46:23: 加载路由器自身 TCP 代理...
2024-03-07 17:46:23:   - 启用 TPROXY 模式
2024-03-07 17:46:23: 加载路由器自身 UDP 代理...
2024-03-07 17:46:24: 访问控制：
2024-03-07 17:46:24:   - 备注【GAME】，MAC【5C:96:66:8E:XX:XX】，使用TCP节点[游戏-UDP全代理-香港组] [全局代理](TPROXY:11201)代理所有端口
2024-03-07 17:46:24:   - 备注【GAME】，MAC【5C:96:66:8E:XX:XX】，使用UDP节点[游戏-UDP全代理-香港组] [全局代理](TPROXY:11201)代理所有端口
2024-03-07 17:46:24: TCP默认代理：使用节点[主分流] [全局代理](TPROXY:1041)代理所有端口
2024-03-07 17:46:24: UDP默认代理：使用节点[主分流] [全局代理](TPROXY:1041)代理所有端口
2024-03-07 17:46:24: 防火墙规则加载完成！
2024-03-07 17:46:28: 重启 dnsmasq 服务
2024-03-07 17:46:28: 配置定时任务：自动更新规则。
2024-03-07 17:46:28: 运行完成！
```

**Comment by catsimple** [comment]
破案了

首先可以看到
0_default_config中默认为
`config global_singbox
	option sniff_override_destination '0'
	option geoip_path '/usr/share/singbox/geoip.db'
	option geoip_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db'
	option geosite_path '/usr/share/singbox/geosite.db'
	option geosite_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db'`

然后不知道为什么我的/etc/config/passwall2配置为
`config global_singbox
	option sniff_override_destination '1'
	option geoip_path '/tmp/singbox/geoip.db'
	option geoip_url 'https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db'
	option geosite_path '/tmp/singbox/geosite.db'
	option geosite_url 'https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db'`

看到判断逻辑如下
`global_singbox=$(uci -q get passwall2.@global_singbox[0])
[ -z "${global_singbox}" ] && {
	cfgid=$(uci add passwall2 global_singbox)
	uci -q set passwall2.${cfgid}.sniff_override_destination=0
	uci -q set passwall2.${cfgid}.geoip_path="/tmp/singbox/geoip.db"
	uci -q set passwall2.${cfgid}.geoip_url="https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
	uci -q set passwall2.${cfgid}.geosite_path="/tmp/singbox/geosite.db"
	uci -q set passwall2.${cfgid}.geosite_url="https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db"
	uci -q commit passwall2
}`

然后我还纳闷，哪里有单独设置sing-box geosite和geoip的地方，在节点设置里没看到，规则设置里也没看到，后来发现藏在了高级设置里，为啥不和xray一起放在规则配置里。
然后修改为
`https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db
https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db`
后，分流正常，印证了是分流规则不同导致的分流异常

嗯....

**Comment by Travel2Here** [comment]
> 破案了
> 
> 
> 
> 首先可以看到
> 
> 0_default_config中默认为
> 
> config global_singbox
> 
> 	option sniff_override_destination '0'
> 
> 	option geoip_path '/usr/share/singbox/geoip.db'
> 
> 	option geoip_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db'
> 
> 	option geosite_path '/usr/share/singbox/geosite.db'
> 
> 	option geosite_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db'
> 
> 
> 
> 
> 
> 然后不知道为什么我的/etc/config/passwall2配置为
> 
> config global_singbox
> 
> 	option sniff_override_destination '1'
> 
> 	option geoip_path '/tmp/singbox/geoip.db'
> 
> 	option geoip_url 'https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db'
> 
> 	option geosite_path '/tmp/singbox/geosite.db'
> 
> 	option geosite_url 'https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db'
> 
> 
> 
> 看到判断逻辑如下
> 
> global_singbox=$(uci -q get passwall2.@global_singbox[0])
> 
> [ -z "${global_singbox}" ] && {
> 
> 	cfgid=$(uci add passwall2 global_singbox)
> 
> 	uci -q set passwall2.${cfgid}.sniff_override_destination=0
> 
> 	uci -q set passwall2.${cfgid}.geoip_path="/tmp/singbox/geoip.db"
> 
> 	uci -q set passwall2.${cfgid}.geoip_url="https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
> 
> 	uci -q set passwall2.${cfgid}.geosite_path="/tmp/singbox/geosite.db"
> 
> 	uci -q set passwall2.${cfgid}.geosite_url="https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db"
> 
> 	uci -q commit passwall2
> 
> }
> 
> 
> 
> 然后我还纳闷，哪里有单独设置sing-box geosite和geoip的地方，在节点设置里没看到，规则设置里也没看到，后来发现藏在了高级设置里，为啥不和xray一起放在规则配置里。
> 
> 然后修改为
> 
> https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db
> 
> https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db
> 
> 后，分流正常，印证了是分流规则不同导致的分流异常
> 
> 
> 
> 嗯....

我也是用的这家的两个geo文件，OpenAI不行，你试试交流下。我的相关代理规则调用的是geosite:openai

**Comment by catsimple** [comment]
> > 破案了
> > 首先可以看到
> > 0_default_config中默认为
> > config global_singbox
> > option sniff_override_destination '0'
> > option geoip_path '/usr/share/singbox/geoip.db'
> > option geoip_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db'
> > option geosite_path '/usr/share/singbox/geosite.db'
> > option geosite_url 'https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db'
> > 然后不知道为什么我的/etc/config/passwall2配置为
> > config global_singbox
> > option sniff_override_destination '1'
> > option geoip_path '/tmp/singbox/geoip.db'
> > option geoip_url 'https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db'
> > option geosite_path '/tmp/singbox/geosite.db'
> > option geosite_url 'https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db'
> > 看到判断逻辑如下
> > global_singbox=$(uci -q get passwall2.@global_singbox[0])
> > [ -z "${global_singbox}" ] && {
> > cfgid=$(uci add passwall2 global_singbox)
> > uci -q set passwall2.${cfgid}.sniff_override_destination=0
> > uci -q set passwall2.${cfgid}.geoip_path="/tmp/singbox/geoip.db"
> > uci -q set passwall2.${cfgid}.geoip_url="https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
> > uci -q set passwall2.${cfgid}.geosite_path="/tmp/singbox/geosite.db"
> > uci -q set passwall2.${cfgid}.geosite_url="https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db"
> > uci -q commit passwall2
> > }
> > 然后我还纳闷，哪里有单独设置sing-box geosite和geoip的地方，在节点设置里没看到，规则设置里也没看到，后来发现藏在了高级设置里，为啥不和xray一起放在规则配置里。
> > 然后修改为
> > https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db
> > https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db
> > 后，分流正常，印证了是分流规则不同导致的分流异常
> > 嗯....
> 
> 我也是用的这家的两个geo文件，OpenAI不行，你试试交流下。我的相关代理规则调用的是geosite:openai

OpenAI走了QUIC，你试试浏览器关闭QUIC

**Comment by Travel2Here** [comment]
> 
> OpenAI走了QUIC，你试试浏览器关闭QUIC

确实规则没关QUIC，移动端浏览器貌似关不了，晚点我再试试

**Comment by catsimple** [comment]
> > OpenAI走了QUIC，你试试浏览器关闭QUIC
> 
> 确实规则没关QUIC，移动端浏览器貌似关不了，晚点我再试试

要是有什么问题你再提个issue吧，我先把这个关了
