### ISSUE TITLE
[Feature Request]: 国内ip直连不经过代理软件

### ISSUE THREAD

**Issue by eqfae** [xiaorouji/openwrt-passwall2#508]
### 描述你想要的新功能

以前在硬件加速没cpu占用 现在国内实测会占用cpu

### 描述你想要的解决方案

好像是防火墙规则让国内ip直连 关注过dae 那里有问题提到过 只是现在虽然有开源的能编译支持的内核 但用不了就是了

### 其他信息

1.27-4

**Comment by eqfae** [comment]
1.27-5 测速依旧占用

**Comment by hcym** [comment]
daed 效果好不好，编译几次不会用，哪个编译时间太太夸张

**Comment by eqfae** [comment]
没有测过 现在性能都过剩 无非想更快些

**Comment by hxlls** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/43886952/241828e6-8aeb-4006-8196-0e17f3c90766)
shi'c实测没问题啊。。

**Comment by eqfae** [comment]
![图片](https://github.com/xiaorouji/openwrt-passwall2/assets/120385812/77580e20-d1f2-4bc1-a4de-d34c14907db5)
问题出在这条规则
最近重新配置pw加上的 上传除非我是唯一的做种 偶尔看到速度断断续续 一看用户都是国内的机器这是怎么回事 在某博客看到就加了这种规则 关闭后我也没占用了
