### ISSUE TITLE
[Feature Request]: 可以考虑加入“客户端代理”的开关吗

### ISSUE THREAD

**Issue by lemontealin** [xiaorouji/openwrt-passwall2#513]
### 描述你想要的新功能

请求加入passwall(4.75-9)上的“客户端代理”开关 

### 描述你想要的解决方案

需求内网指定设备走代理默认不走代理，passwall最新版可以通过关闭客户端代理，访问控制中加入需要的代理实现。目前使用的passwall2（1.27.4）暂时没找到这项功能，请求在后续版本中加入

### 描述你考虑过的替代方案

当前版本上尝试过关掉全局节点，访问控制中挨个设置，但路由本机代理挂了

**Comment by xiaorouji** [comment]
有的，passwall2是我主力，下個版本就有。

**Comment by lemontealin** [comment]
> 有的，passwall2是我主力，下個版本就有。

好的！感谢大佬！我最近也换成passwall2了😊

**Comment by lemontealin** [comment]
好的，谢谢大佬，晚点试试！
