### ISSUE TITLE
[Feature Request]: 希望加入域名类节点的域名缓存

### ISSUE THREAD

**Issue by lemontealin** [xiaorouji/openwrt-passwall2#514]
### 描述你想要的新功能

可否在未来版本中考虑加入域名类节点的域名缓存，当前版本passwall2请求解析节点域名非常频繁，使用adguardhome查看dns解析记录没几分钟就一大堆记录

### 描述你想要的解决方案

加入域名类节点的域名缓存，减少DNS查询次数。
IP无法正常工作再重新解析域名是否可行？（说错大佬别见怪）

### 描述你考虑过的替代方案

尝试设定过host，但是dns记录里还是一大堆，不懂什么原因

**Comment by xiaorouji** [comment]
調大ttl，調大緩存

**Comment by lemontealin** [comment]
好的，我试试🥰
