### ISSUE TITLE
[Bug]: 微信视频号不正常

### ISSUE THREAD

**Issue by lemontealin** [xiaorouji/openwrt-passwall2#517]
### 描述您遇到的bug

不添加入访问控制即不走代理的设备一切正常，走代理的设备微信视频号头像丢失，有些视频加载不出来

### 复现此Bug的步骤

1.使用访问控制里的设备，打开微信视频号头像丢失部分视频无法加载
2.打开手机的“随机设备MAC”地址，让设备变成不走代理测试，一切正常

查看过DNS记录，没发现什么异常，重启过多次设备也排除DNS缓存问题

### 您想要实现的目的

不知道是不是转发的问题，直连是否可以直接转发到6553端口？

### 日志信息

![QQ截图20240315105544](https://github.com/xiaorouji/openwrt-passwall2/assets/18193702/48e008af-7f0e-486c-abe5-1428cc5ccb60)
![QQ截图20240315105618](https://github.com/xiaorouji/openwrt-passwall2/assets/18193702/b97af32c-08e0-49e3-9b62-9dea9dc3422e)
<img width="497" alt="屏幕截图 2024-03-15 103400" src="https://github.com/xiaorouji/openwrt-passwall2/assets/18193702/cd822f4c-4602-4c27-ac6e-48a4c29c5a68">

### 系统相关信息

旁路由环境，主路由开启DHCP且网关指向了旁路由，使用Passwall2最新的28版本，本地DNS是6553端口
“客户端代理”关闭，访问控制添加设备来实现指定设备走代理

### 其他信息

之前走代理设备的京东APP加载也有问题，用户页得等个十几秒才能加载好，不知道是不是升级了28的原因，目前是正常

**Comment by CharlesLocke** [comment]
京东APP加载慢的问题看看你有没有勾选IP 动态伪装😊

**Comment by lemontealin** [comment]
已经勾选了，感觉是分流问题，不懂，没搞定

**Comment by lemontealin** [comment]
换了smartdns也是一样，也不止微信，美团淘宝都有出现加载慢的情况，不知道是不是分流和V6的问题（DHCP/DNS已经禁用了V6）

**Comment by lemontealin** [comment]
😂我知道咋回事了，刚刚美团外卖也加载异常，看了下日志，好几个IP被转去走代理了...把这几个IP加到直连规则就正常了

**Comment by lemontealin** [comment]
奇怪了，查了下IPIP，这些IP应该是在geoip.dat里头，但还是走默认🥲，已经更新最新版并且重置过
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/18193702/5224d98c-1922-4e20-b554-b39f7c6849cd)

**Comment by lemontealin** [comment]
😂解决了解决了，是我脑抽了，我direct规则设置有问题，把tls和http勾上了，理解错了，以为是“包含tls和https”
