### ISSUE TITLE
第二组及以上的访问控制无效！

### ISSUE THREAD

**Issue by gujyflii** [xiaorouji/openwrt-passwall2#52]
访问控制只有置顶的那一组有效，第二组及以上的规则保存后无效，日志显示没有第二组及以上的规则。
想要通过访问控制实现不同设备走不同节点的时候发现的这个问题。亦或是我设置的问题？
我知道可以通过规则实现不同设备走不同节点。

**Comment by gujyflii** [comment]
我知道可以通过规则实现不同设备走不同节点。

**Comment by xiaorouji** [comment]
感谢反馈，已修复。

**Comment by gujyflii** [comment]
感谢大佬的付出，很高兴能参与。
