### ISSUE TITLE
[Bug]: tcp分片失效

### ISSUE THREAD

**Issue by zjy2200656** [xiaorouji/openwrt-passwall2#521]
### 描述您遇到的bug

开启tcp分片后无法联网

### 复现此Bug的步骤

1，开启tcp分片后，vless reality节点无法联网

### 您想要实现的目的

使tcp分片可用

### 日志信息

none

### 系统相关信息

- Passwall 版本：1.26-2

**Comment by swxk521** [comment]
经测试  luci: 1.28版本 tcp分片会在  "flow": "xtls-rprx-vision"  这个模式下失效 ，禁用这个的话，reality grpc   单纯TCP等测试正常。

**Comment by xiaorouji** [comment]
我不使用這個，無法測試。

**Comment by swxk521** [comment]
> 我不使用這個，無法測試。

我看xray那边的讨论，xtls-rprx-vision的入站问题，
经测试开启tcp分片， xtls-rprx-vision模式的节点作为默认分流规则节点时就会连接失败，作为其他分流规则就会成功，
不知道和链式代理等问题有没有联系？
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/61259428/fbd69616-ecd1-44af-b01b-edb556c676c5)
