### ISSUE TITLE
[Bug]: 1.28-2版本这里有俩代理 不知道是不是BUG

### ISSUE THREAD

**Issue by whatpig** [xiaorouji/openwrt-passwall2#522]
### 描述您遇到的bug

如图所示 感觉这俩是一个意思啊

### 复现此Bug的步骤

PASSWALL2首页

### 您想要实现的目的

修复

### 日志信息

PASSWALL2首页

### 截图

<img width="756" alt="无标题" src="https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/88e7c123-eb24-4ce6-927b-6ad66384ce46">

### 系统相关信息

1.28-2

**Comment by lemontealin** [comment]
客户端代理和本机代理？本机代理是路由器本身，客户端代理是别的接入设备，可以通过关掉客户端代理在访问控制中添加设备来实现制定设备走代理
