### ISSUE TITLE
[Bug]: 版本1.28-2，无法更新规则文件 

### ISSUE THREAD

**Issue by derekxi2021** [xiaorouji/openwrt-passwall2#526]
### 描述您遇到的bug

x86-64软路由，更新geoip和geodata时，实际下载和更新动作不执行

### 复现此Bug的步骤

规则管理，点击手动更新（manual update）时，实际/usr/share/v2ray下规则文件未更新
且未发现/tmp下有geoip、geosite相关下载文件和md5临时文件生成

### 您想要实现的目的

解决相关bug

### 日志信息

2024-03-19 19:35:25: 开始更新规则...
2024-03-19 19:35:25: geoip 开始更新...
2024-03-19 19:35:27: geosite 开始更新...
2024-03-19 19:35:28: 规则更新完毕...

### 截图

<img width="848" alt="无标题" src="https://github.com/xiaorouji/openwrt-passwall2/assets/88201015/149da4bd-7c44-4be0-a550-0a4268422fea">

### 系统相关信息

paswwall2版本1.28-2
openwrt版本OpenWrt R24.2.2 ，内核6.1.82
主机型号Intel(R) Celeron(R) CPU J3160 @ 1.60GHz : 4C4T

### 其他信息

试着恢复过出厂设置，问题依旧

**Comment by terada46** [comment]
8月30日编译的版本没有这个问题，昨天编译的开始使用出现这个问题了。不知道跟我使用上一个版本备份的配置文件有没有关系
