### ISSUE TITLE
[Feature Request]: 希望在节点类型中像pw1中一样加入socks节点

### ISSUE THREAD

**Issue by xcf13363175** [xiaorouji/openwrt-passwall2#527]
### 描述你想要的新功能

希望在节点类型中像pw1中一样加入socks节点，目前pw2中socks节点需要使用xray内核下面的socks，而很多硬路由的ROM比较小，塞20M的xray比较吃力，所以希望大佬加入socks节点类型，轻量化pw2，感谢
pw1
![pw1](https://github.com/xiaorouji/openwrt-passwall2/assets/28884815/939430ff-0bbe-4fe4-a905-46bb152aa26d)
pw2
![pw2](https://github.com/xiaorouji/openwrt-passwall2/assets/28884815/73297c54-466e-41a7-bad0-41f26dffc07d)

### 描述你想要的解决方案

希望在节点类型中像pw1中一样加入socks节点，目前pw2中socks节点需要使用xray内核下面的socks，而很多硬路由的ROM比较小，塞20M的xray比较吃力，所以希望大佬加入socks节点类型，轻量化pw2，感谢

**Comment by xiaorouji** [comment]
passwall2本來就是使用Xray/Sing-Box內核。
