### ISSUE TITLE
[Feature Request]: 疑问，用mosdns的话，远程dns出站选什么

### ISSUE THREAD

**Issue by leslieqwq** [xiaorouji/openwrt-passwall2#528]
### 描述你想要的新功能

没搞懂这个选项

### 描述你想要的解决方案

没搞懂这个选项

**Comment by hcym** [comment]
就是远程，另一个是直接吧，也是要用ipv6必需配套，不然没必要

**Comment by hexsen929** [comment]
都可以吧，我用的直连统一用mosdns来解析

**Comment by wyUshio** [comment]
> 都可以吧，我用的直连统一用mosdns来解析

老哥问下,我用mosdns ping 不通.xyz的域名,这个问题咋解决?
