### ISSUE TITLE
[Bug]: 同时安装 luci-app-passwall 和  luci-app-passwall2 文件 qrcode.min.js 冲突

### ISSUE THREAD

**Issue by hexsen929** [xiaorouji/openwrt-passwall2#529]
### 描述您遇到的bug

同时安装 luci-app-passwall 和  luci-app-passwall2 文件 qrcode.min.js 冲突

### 复现此Bug的步骤

重复编译

### 您想要实现的目的

编译通过

### 日志信息

Collected errors:
 * check_data_file_clashes: Package luci-app-passwall2 wants to install file /home/runner/work/OpenWrt-K/OpenWrt-K/workspace/openwrt/build_dir/target-x86_64_musl/root-x86/www/luci-static/resources/qrcode.min.js
	But that file is already provided by package  * luci-app-passwall
 * opkg_install_cmd: Cannot install package luci-app-passwall2.
 * check_data_file_clashes: Package luci-app-passwall2 wants to install file /home/runner/work/OpenWrt-K/OpenWrt-K/workspace/openwrt/build_dir/target-x86_64_musl/root-x86/www/luci-static/resources/qrcode.min.js
Configuring luci-i18n-frpc-ja.
	But that file is already provided by package  * luci-app-passwall
 * opkg_install_cmd: Cannot install package luci-i18n-passwall2-zh-cn.
make[1]: *** [package/Makefile:70: package/install] Error 255

### 系统相关信息

passwall2版本v1.28-3

**Comment by yyshell** [comment]
是的，我刚编译复现了。

**Comment by xiaorouji** [comment]
Try the latest commit.

**Comment by initzhu** [comment]
在immo snapshot中 启用 apk代替opkg作为包管理器时会出现相同问题 

ERROR: luci-app-passwall2-24.11.13-r1: trying to overwrite www/luci-static/resources/qrcode.min.js owned by luci-app-passwall-4.78.4.

> Try the latest commit.

**Comment by OldCoding** [comment]
ERROR: luci-app-passwall2-24.11.19-r2: trying to overwrite www/luci-static/resources/qrcode.min.js owned by luci-app-passwall-24.12.1-r1.
最新的immortalwrt源码又出先这个问题了
