### ISSUE TITLE
功能建议 DNS—远程 DNS 协议，增加UDP选项

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#53]
![1](https://user-images.githubusercontent.com/88967758/163002445-3438a1ab-6f37-4e9a-af1f-0d3a5f7622fb.jpg)

图中红框处，没有UDP选项，我想用UDP查询，我知道访问这个DNS地址也是会被VPS代理，由VPS访问的。

感谢。

**Comment by xiaorouji** [comment]
UDP麻烦一点，而且好多机场不提供UDP，今晚再弄

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/3b190d83adcd71c680d3d2872d8df666619e9b65

**Comment by chika0801** [comment]
thanks
