### ISSUE TITLE
[Bug]: Socks配置, 未勾选"启用日志", 仍然会有日志输出.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#531]
### 描述您遇到的bug

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/84071282/fcc4b983-2b0a-46f4-a1eb-4648bb044eb8)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/84071282/0a81c109-959f-42b2-9426-beafade9ee0a)

### 复现此Bug的步骤

Socks配置, 未勾选"启用日志", 仍然会有日志输出.

### 您想要实现的目的

正确实现启用与禁用日志.

### 日志信息

Socks配置, 未勾选"启用日志", 仍然会有日志输出.

### 系统相关信息

passwall2: 1.28-3

**Comment by xiaorouji** [comment]
Fix. 因為是從passwall cherry-pick過來，沒報衝突以為~~正常~~
