### ISSUE TITLE
[Bug]: passwall2启动守护进程仍会一段时间后会停止工作

### ISSUE THREAD

**Issue by VwEl** [xiaorouji/openwrt-passwall2#536]
### 描述您遇到的bug

运行一段时间后，passwall2自动停止工作，页面显示未运行，保存并应用后重启启动passwall2恢复正常。

### 复现此Bug的步骤

开启守护进程，仍然是在运行一段时间后，passwall2自动停止工作，页面显示Xray未运行，保存并应用后重启启动passwall2恢复正常。

### 您想要实现的目的

解决进程保护问题

### 日志信息

No response

    

### 截图

No response

### 系统相关信息

 luci-app-passwall2 | 1.26-1

### 其他信息

 No response

**Comment by yoier** [comment]
没出现停止问题
