### ISSUE TITLE
[Bug]: 最近这个版本只要打开之后，淘宝加载就特别慢

### ISSUE THREAD

**Issue by leslieqwq** [xiaorouji/openwrt-passwall2#537]
### 描述您遇到的bug

有遇到同样的情况吗？

### 复现此Bug的步骤

只要打开主开关，xray分流模式，mosdns接管整个dns，淘宝加载就特别慢，分流规则除了上面一些流媒体，底下就是禁quic，然后先代理掉geosite:geolocation-!cn，然后cn的domain和ip直连

### 您想要实现的目的

找了半天没发现哪里有问题，记得以前的版本刷淘宝没这个问题的

### 日志信息

无

### 系统相关信息

最新版

**Comment by leslieqwq** [comment]
多测试了下，发现网页端m.taobao是正常的，安卓app端也正常，但是ios app就特别慢，但是只要关掉passwall2就一切正常了

**Comment by Moexin** [comment]
> 多测试了下，发现网页端m.taobao是正常的，安卓app端也正常，但是ios app就特别慢，但是只要关掉passwall2就一切正常了

我也发现了，感觉不止淘系app，王者也会出现加载慢的情况，全部换成sing-box问题就解决了，原因不明。

**Comment by leslieqwq** [comment]
> > 多测试了下，发现网页端m.taobao是正常的，安卓app端也正常，但是ios app就特别慢，但是只要关掉passwall2就一切正常了
> 
> 我也发现了，感觉不止淘系app，王者也会出现加载慢的情况，全部换成sing-box问题就解决了，原因不明。

确实，同样的规则，换成singbox就好了

**Comment by tiantaichenhui** [comment]
> > 多测试了下，发现网页端m.taobao是正常的，安卓app端也正常，但是ios app就特别慢，但是只要关掉passwall2就一切正常了
> 
> 我也发现了，感觉不止淘系app，王者也会出现加载慢的情况，全部换成sing-box问题就解决了，原因不明。

确实是这样 换成sing-box 就什么问题都没有  xray模式下问题太多 向日葵无法连接 googleplay无法正常下载等问题只要换成sing-box就全部解决

**Comment by leslieqwq** [comment]
> > > 多测试了下，发现网页端m.taobao是正常的，安卓app端也正常，但是ios app就特别慢，但是只要关掉passwall2就一切正常了
> > 
> > 
> > 我也发现了，感觉不止淘系app，王者也会出现加载慢的情况，全部换成sing-box问题就解决了，原因不明。
> 
> 确实是这样 换成sing-box 就什么问题都没有 xray模式下问题太多 向日葵无法连接 googleplay无法正常下载等问题只要换成sing-box就全部解决

singbox开久了淘宝也会变卡，刚开不会

**Comment by VergilGao** [comment]
最近的版本无论是玩游戏还是刷b站都会随机性的出现掉线的情况，甚至会很长一段时间收不到微信消息等等，即使没开任何规则，只保留一个直连也会这样

**Comment by 2fact** [comment]
> 只要打开主开关，xray分流模式，mosdns接管整个dns，淘宝加载就特别慢，分流规则除了上面一些流媒体，底下就是禁quic，然后先代理掉geosite:geolocation-!cn，然后cn的domain和ip直连

淘宝iOS客户端有些地方会用QUIC，如果你的分流规则里屏蔽QUIC在China直连之前，同时淘宝客户端fallback不及时或者实效，就会卡住甚至没响应。如果是这种情况，把QUIC移到China下面就能解决。

**Comment by lemontealin** [comment]
我是遇到有些规则不生效，很奇怪的原因... 
outlook我绑定在第三方的邮件app，然后发现outlook默认规则是走代理，outlook疑似有某些限制，走代理第三方邮件APP就会登不上outlook，然后在direct里头添加规则，但是添加了不生效，查看日志（debug模式）甚至没有关于outlook相关域名的分流日志，非常奇怪...查了DNS日志才发现是被走代理了。

最后也不知道怎么解决的，把规则换成domian：XXX，并且从顶部移到底部（不是规则分类的排序，而是规则内匹配地址的排序）就好了...

你可以试试在direct里头加上 geosite:apple-cn，geosite:china-list，passwall2默认用的版本支持这两个分类，先更新一下geoip和geosite再添加

**Comment by VergilGao** [comment]
经过仔细排查和分析，目前问题集中在多wan口上，我家有两个wan口，一个负责上网的 internet， 一个看电视的 iptv 在mwan3中配置了 10.0.0.0/8 端的请求全部走 iptv， 其他请求走 internet
开启passwall2后，起初并没有什么问题，但是一旦 iptv 口重播或者 internet 口重播，大概率会出现问题。

目前我的方案是先关闭 iptv 口和mwan3插件，确定问题是否完全消失，然后等5月手写nftables规则来替代mwan3插件，看看是否能避免此问题。
