### ISSUE TITLE
[Feature Request]: Custom Direct DNS

### ISSUE THREAD

**Issue by fakhamatia** [xiaorouji/openwrt-passwall2#540]
### 描述你想要的新功能

Please add option to add Direct DNS for Passwall 2

### 描述你想要的解决方案

There is an option to add Remote DNS.
But we don't have an option to enter Direct DNS. Especially DoH

**Comment by Deleted-Account** [comment]
dnsmasq, DNS forwardings

u'd better take a look at Passwall2's "watch log".
Tons of guys never ever did that before.

**Comment by fakhamatia** [comment]
> dnsmasq, DNS forwardings

`dnsmasq` don't support DoH, must install extra package `https-dns-proxy`

> u'd better take a look at Passwall2's "watch log". Tons of guys never ever did that before.

Yes, because it's not English.
