### ISSUE TITLE
规则里面如何注释？

### ISSUE THREAD

**Issue by w316525096** [xiaorouji/openwrt-passwall2#544]
### 描述你想要的新功能

请问下，规则里面怎么注释。

### 描述你想要的解决方案

规则久了容易忘记是干什么的。希望可以有注释。

### 其他信息

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/25398881/3c489b6a-1581-4d83-afb6-4a0ba1f12a01)

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/76c450bdadd477ed0f74ba1142638b402ac42cb2
以 `#` 开头作为注释行
