### ISSUE TITLE
[Bug]: paswall 需要一个叫tcping 的包但官方源里没有

### ISSUE THREAD

**Issue by ss8688** [xiaorouji/openwrt-passwall2#547]
### 描述您遇到的bug

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall2
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall2 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall2.

### 复现此Bug的步骤

树莓派4用的官方镜像官方源，找不到tcping这个包

### 您想要实现的目的

tcping 这包哪里有？

### 日志信息

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall2
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall2 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall2.

### 截图

![Screenshot_2024-04-03-20-09-54-336_com kiwibrowser browser](https://github.com/xiaorouji/openwrt-passwall2/assets/59367202/6c767a31-2412-4a11-8a55-a8005b72b6e1)

### 系统相关信息

openwrt 23.05.3

**Comment by ss8688** [comment]
哦，谢谢

**Comment by r0achnnan9p** [comment]
> https://github.com/xiaorouji/openwrt-passwall-packages

怎么添加到opkg配置文件里面不能下载gz文件？

**Comment by sclsyin** [comment]
> https://github.com/xiaorouji/openwrt-passwall-packages
请问下这个添加到feeds.conf.default 文件中应该怎么写？
