### ISSUE TITLE
[Bug]: 远程 DNS 出站选直连的情况下Xray报错

### ISSUE THREAD

**Issue by sbcarp** [xiaorouji/openwrt-passwall2#553]
### 描述您遇到的bug

使用最新的lede openwrt，以及passwall2 1.28-5

`远程 DNS 出站`选直连的情况下Xray报错

`unsupported address for router: tcp://8.8.4.4`

### 复现此Bug的步骤

1. 重置Openwrt
2. 进入passwall2设定
3. 随便添加一个节点
4. 进入passwall2 DNS设定
5. 将`远程 DNS 出站`改成直连
6. 启动passwall2 
7. Xray报错
8.  将`远程 DNS 出站`改成远程
9. Xray不报错

### 您想要实现的目的

希望能确定是否为bug

### 日志信息

Xray 1.8.10 (Xray, Penetrates Everything.) OpenWrt (go1.22.1 linux/amd64)
A unified platform for anti-censorship.
2024/04/08 19:48:06 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/acl/default/global.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/acl/default/global.json] > infra/conf: invalid field rule > infra/conf: invalid IP: tcp://8.8.4.4 > infra/conf: unsupported address for router: tcp://8.8.4.4

### 系统相关信息

passwall2 1.28-5
Xray 1.8.10

**Comment by xiaorouji** [comment]
Fix.
