### ISSUE TITLE
Fragment won't Work

### ISSUE THREAD

**Issue by Ram3zani** [xiaorouji/openwrt-passwall2#554]
### 描述您遇到的bug

After enabling the fragment and setting it to tlshell and default values. i added a Vless+ws+tls config to passwall2.  But unfortunately, the Vless+ws+tls link doesn't work. my link is ok with V2rayNG ( Fragment enable ) on Android.

### 复现此Bug的步骤

1. Enable Fragment in passwall2 settings with tlshell and default value.
2. Add Vless+ws+tls link
3. use Node and enable 
4. i check xray server side my Vless config won't connect. 

### 您想要实现的目的

I want the fragment to work inside Passwall2

### 日志信息

Xray 1.8.10 (Xray, Penetrates Everything.) OpenWrt (go1.22.2 linux/amd64)
A unified platform for anti-censorship.
2024/04/09 14:43:57 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/acl/default/global.json

### 系统相关信息

OpenWrt 23.05.3
 luci-app-passwall2 1.28-5
Xray Version  1.8.10

**Comment by xiaorouji** [comment]
I don't using it, it may not be needed. Please compare the JSON configuration file generated by PassWall2 and V2rayNG.

**Comment by Daariush** [comment]
Fragment helps a lot here in Iran, we can use banned nodes

**Comment by xiaorouji** [comment]
Can you export the JSON configuration that can be used the fragment on V2RayNG ?

**Comment by Ram3zani** [comment]
> Can you export the JSON configuration that can be used the fragment on V2RayNG ?

[Fragment [ircf.space].json](https://github.com/xiaorouji/openwrt-passwall2/files/14970918/Fragment.ircf.space.json)

**Comment by xiaorouji** [comment]
You try to change `/usr/lib/lua/luci/passwall2/util_xray.lua` line 1426
`fragments` change to `fragment`
save it.
And then apply the passwall2 to retry.

**Comment by Recoba86** [comment]
> You try to change `/usr/lib/lua/luci/passwall2/util_xray.lua` line 1426 `fragments` change to `fragment` save it. And then apply the passwall2 to retry.

Thanks
Everything is now operational and the fragment is functioning as intended after that typo was fixed!
