### ISSUE TITLE
[Bug]: passwall 2 在官方 OpenWrt main分支下存在启动问题.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#558]
### 描述您遇到的bug

在main分支下passwall2主开关开反应, 修改配置 日志也没有信息打印.

### 复现此Bug的步骤

编译 OpenWrt main, 刷入固件操作passwall2.

### 您想要实现的目的

正常.

### 日志信息

passwall2 刷入固件后第一次开机日志输出, 检测防火墙: 找不到iptables 与 ipset, 检测到nftable 使用nftables.

然后在修改任何配置都没有日志打印, 系统日志也没有相关的日志打印.

重启设备, 有延迟启动的日志打印, 修改配置没有日志打印, 启动passwall2 无法启动, 没有日志打印.

### 系统相关信息

passwall2: 1.28-7
Device: x86-64

**Comment by xiaoshengshuohua** [comment]
是主线对ucitrack的更改.
https://github.com/openwrt/luci/pull/7056

**Comment by xiaorouji** [comment]
> 是主线对ucitrack的更改. [openwrt/luci#7056](https://github.com/openwrt/luci/pull/7056)

沒有使用master branch。
不過根據你發的這個commit，參考了一下。你可以試試在`/usr/share/ucitrack/` 目錄下創建一個文件`luci-app-passwall2.json`
內容為
```
{
	"config": "passwall2",
	"init": "passwall2"
}
```
然後重啟試試。

**Comment by hcym** [comment]
最近的master都不能用，大雕的ssrp也是，用2305吧

**Comment by HXTHETK** [comment]
添加完luci-app-passwall2.json后重启路由器可以成功启动。

**Comment by HXTHETK** [comment]
但是启动或关闭有几率卡住
2024-04-21 14:00:30: 删除nftables防火墙规则完成。
2024-04-21 14:00:33: 清空并关闭相关程序和缓存完成。
2024-04-21 14:00:33: 程序已启动，先停止再重新启动!
2024-04-21 14:00:33: 删除nftables防火墙规则完成。
2024-04-21 14:00:36: 清空并关闭相关程序和缓存完成。
然后不动了
