### ISSUE TITLE
openwrt 23.05  内核6.1.85，为什么passwall2高级设置没有 TCP代理选项？passwall2 v1.28.6[Feature Request]: 

### ISSUE THREAD

**Issue by zxymdaddy** [xiaorouji/openwrt-passwall2#559]
### 描述你想要的新功能

passwall2高级设置没有 TCP代理选项

### 描述你想要的解决方案

passwall2高级设置没有 TCP代理选项

### 其他信息

![QQ截图_2024年4月18日16时25分](https://github.com/xiaorouji/openwrt-passwall2/assets/35829110/9fcc371e-a421-47bb-aa3f-2d775dcf19bd)
![QQ截图_2024年4月18日16时23分13秒](https://github.com/xiaorouji/openwrt-passwall2/assets/35829110/dfd1a951-41e6-49e8-a46f-23f7445e9419)

**Comment by xiaorouji** [comment]
需要同時編譯 nft_redir 和 nft_tproxy 模塊才會顯示。
