### ISSUE TITLE
[Bug]: 谷歌商店 google play无法正常下载app

### ISSUE THREAD

**Issue by tiantaichenhui** [xiaorouji/openwrt-passwall2#561]
### 描述您遇到的bug

googlepay无法正常下载

### 复现此Bug的步骤

xray模式下 谷歌商店无法正常下载 会一直显示等待中 
临时解决方法是 手机WiFi关掉再开会开始下载 或者重启passwall2也可以 但一会又无法正常下载了 
按照这个帖子https://github.com/xiaorouji/openwrt-passwall2/issues/415 添加过很多域名到googlePlay 和Proxy里面 问题依旧存在
但如果把xary模式改为Sing-box那么就一切正常

### 您想要实现的目的

请求修复

### 日志信息

没有

### 系统相关信息

passwall2

**Comment by CharlesLocke** [comment]
规则问题，不是有个GooglePlay的规则么，这个不好用的话你就干脆新建规则geosite:google/geoip:google，放前面就行。
