### ISSUE TITLE
[Bug]: 使用最新源码编译后如果节点选择Shadowsocks Rust就报错

### ISSUE THREAD

**Issue by yyzh** [xiaorouji/openwrt-passwall2#562]
### 描述您遇到的bug

使用最新源码编译后如果节点选择Shadowsocks Rust就报错无法上网
选择Xray或者Sing-box就一切正常
应该是Shadowsocks Rust那边该了设定然后Passwall2这边没同步更改.

### 复现此Bug的步骤

节点类型选Shadowsocks Rust就行 要最新源码加依赖编译

### 您想要实现的目的

修好

### 日志信息

+0000 2024-04-20 09:26:10 ERROR [4065535617 4ms] inbound/tproxy[tproxy_udp]: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:10 INFO [3428600364 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:53070
+0000 2024-04-20 09:26:10 INFO [2672733219 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:60101
+0000 2024-04-20 09:26:10 DEBUG [3428600364 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:10 DEBUG [3428600364 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:10 DEBUG [2672733219 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:10 DEBUG [2672733219 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:10 DEBUG dns: exchange content-autofill.googleapis.com. IN A
+0000 2024-04-20 09:26:10 DEBUG dns: exchange content-autofill.googleapis.com. IN HTTPS
+0000 2024-04-20 09:26:10 DEBUG dns: match[5] domain=[googleapis.cn googleapis.com xn--ngstr-lra8j.com...] domain_suffix=[.googleapis.cn .googleapis.com .xn--ngstr-lra8j.com...] geosite=[google google-cn google@cn] => remote
+0000 2024-04-20 09:26:10 DEBUG dns: match[5] domain=[googleapis.cn googleapis.com xn--ngstr-lra8j.com...] domain_suffix=[.googleapis.cn .googleapis.com .xn--ngstr-lra8j.com...] geosite=[google google-cn google@cn] => remote
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 ERROR dns: exchange failed for content-autofill.googleapis.com. IN A: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:10 DEBUG [1255674313 2ms] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 ERROR dns: exchange failed for content-autofill.googleapis.com. IN HTTPS: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:10 DEBUG [1311326962 3ms] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-04-20 09:26:10 INFO [2440120058 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:60101
+0000 2024-04-20 09:26:10 DEBUG [2440120058 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:10 DEBUG [2440120058 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:10 DEBUG dns: exchange content-autofill.googleapis.com. IN A
+0000 2024-04-20 09:26:10 DEBUG dns: match[5] domain=[googleapis.cn googleapis.com xn--ngstr-lra8j.com...] domain_suffix=[.googleapis.cn .googleapis.com .xn--ngstr-lra8j.com...] geosite=[google google-cn google@cn] => remote
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:10 ERROR dns: exchange failed for content-autofill.googleapis.com. IN A: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:10 DEBUG [818979445 2ms] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-04-20 09:26:11 INFO [74086984 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:50638
+0000 2024-04-20 09:26:11 DEBUG [74086984 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:11 DEBUG [74086984 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:11 DEBUG dns: exchange n-cwm-device.tplinkcloud.com.cn. IN A
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:11 ERROR dns: exchange failed for n-cwm-device.tplinkcloud.com.cn. IN A: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:11 DEBUG [2787317013 4ms] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-04-20 09:26:11 INFO [1744801276 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:60101
+0000 2024-04-20 09:26:11 DEBUG [1744801276 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:11 DEBUG [1744801276 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:11 DEBUG dns: exchange content-autofill.googleapis.com. IN A
+0000 2024-04-20 09:26:11 DEBUG dns: match[5] domain=[googleapis.cn googleapis.com xn--ngstr-lra8j.com...] domain_suffix=[.googleapis.cn .googleapis.com .xn--ngstr-lra8j.com...] geosite=[google google-cn google@cn] => remote
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:11 ERROR dns: exchange failed for content-autofill.googleapis.com. IN A: dial tcp 127.0.0.1:2082: connect: connection refused
+0000 2024-04-20 09:26:11 DEBUG [836940510 2ms] inbound/direct[dns-in]: connection closed: io: read/write on closed pipe | upstream: context canceled
+0000 2024-04-20 09:26:11 INFO [1879723415 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:38687
+0000 2024-04-20 09:26:11 DEBUG [1879723415 0ms] router: sniffed packet protocol: dns
+0000 2024-04-20 09:26:11 DEBUG [1879723415 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0000 2024-04-20 09:26:11 DEBUG dns: exchange www.google.com. IN A
+0000 2024-04-20 09:26:11 DEBUG dns: match[5] domain=[googleapis.cn googleapis.com xn--ngstr-lra8j.com...] domain_suffix=[.googleapis.cn .googleapis.com .xn--ngstr-lra8j.com...] geosite=[google google-cn google@cn] => remote
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53
+0000 2024-04-20 09:26:11 INFO outbound/socks[default]: outbound connection to 8.8.8.8:53

### 系统相关信息

Lean LEDE 最新Passwall2源码加依赖.

**Comment by xiaorouji** [comment]
可用性測試看看通不通。
