### ISSUE TITLE
一个非常不重要的小bug

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall2#57]
远程DNS协议无法使用自定义DOH（直连没有试）

**Comment by chika0801** [comment]
<pre>
    "servers": [
      {
        "port": 443,
        "address": "https:\/\/8.91.2.1\/dns-query"
      },
      {
        "address": "https:\/\/8.91.2.1\/dns-query",
        "port": 443,
        "tag": "remote"
      },

<pre>


测试了一下DOH，随便乱写一个，看生成的配置文件，是生效了的。

**Comment by jh0072110** [comment]
自定义以后v2ray那个图标不会显示运行中 百度和谷歌检测均失败哎 重置新装的 所以也不会是没重置psw之类造成的

**Comment by xiaorouji** [comment]
例如自定义为什么？
不会显示运行中，就看下xray日志

**Comment by jh0072110** [comment]
> 例如自定义为什么？ 不会显示运行中，就看下xray日志

使用nextdns的doh地址
https://dns.nextdns.io/xxxxxx
日志显示：
Xray 1.5.4 (Xray, Penetrates Everything.) OpenWrt (go1.17.8 linux/amd64)
A unified platform for anti-censorship.
2022/04/13 07:52:29 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/global.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/global.json] > infra/conf/serial: failed to decode config: /tmp/etc/passwall2/global.json > infra/conf/serial: failed to read config file at line 1 char 1 > infra/conf: invalid DNS hosts > json: cannot unmarshal array into Go value of type map[string]*conf.HostAddress
按照原先psw1的方式设置
https://dns.nextdns.io/xxxxxx,8.8.8.8
日志显示：
Xray 1.5.4 (Xray, Penetrates Everything.) OpenWrt (go1.17.8 linux/amd64)
A unified platform for anti-censorship.
2022/04/13 07:53:52 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/global.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/global.json] > infra/conf/serial: failed to decode config: /tmp/etc/passwall2/global.json > infra/conf/serial: failed to read config file at line 1 char 1 > infra/conf: invalid DNS hosts > json: cannot unmarshal array into Go value of type map[string]*conf.HostAddress
