### ISSUE TITLE
请问有没有编译好的ikg文件可以直接上传安装？[Feature Request]: 

### ISSUE THREAD

**Issue by zhangwenbo681** [xiaorouji/openwrt-passwall2#573]
### 描述你想要的新功能

请问有没有编译好的ikg文件可以直接上传安装？

### 描述你想要的解决方案

请问有没有编译好的ikg文件可以直接上传安装？

### 描述你考虑过的替代方案

请问有没有编译好的ikg文件可以直接上传安装？

**Comment by yoier** [comment]
releases里不就有吗
