### ISSUE TITLE
[Feature Request]:支持 clash api 面板

### ISSUE THREAD

**Issue by drx1x2** [xiaorouji/openwrt-passwall2#574]
### 描述你想要的新功能

passwall2 log查看不方便，能否支持clash api面板，就方便多了

### 描述你想要的解决方案

passwall2 log查看不方便，能否支持clash api面板，就方便多了

**Comment by LeeRemember** [comment]
可以暂时先在/usr/lib/lua/luci/passwall2/util_sing-box.lua 这个文件里手动添加clash api的配置

**Comment by drx1x2** [comment]
> 可以暂时先在/usr/lib/lua/luci/passwall2/util_sing-box.lua 这个文件里手动添加clash api的配置

howto ?

**Comment by LeeRemember** [comment]
util_sing-box.lua里有个方法叫 gen_config
`
experimental.clash_api = {
				external_controller = "127.0.0.1:9090"
			}
`
添加到gen_config方法的 `if inbounds or outbounds then`之前

**Comment by LeeRemember** [comment]
> > 可以暂时先在/usr/lib/lua/luci/passwall2/util_sing-box.lua 这个文件里手动添加clash api的配置
> 
> how to ?
`
	if not experimental then
		experimental = {}
	end
	experimental.clash_api = {
		external_controller = "127.0.0.1:990"
	}
`
在util_sing-box.lua 文件中的 gen_config 方法里 。把上述代码添加到` if inbounds or outbounds then ` 之前

**Comment by drx1x2** [comment]
> > > 可以暂时先在/usr/lib/lua/luci/passwall2/util_sing-box.lua 这个文件里手动添加clash api的配置
> > 
> > 
> > how to ?
> > `	if not experimental then 		experimental = {} 	end 	experimental.clash_api = { 		external_controller = "127.0.0.1:9090" 	}`
> > 在util_sing-box.lua 文件中的 gen_config 方法里 。把上述代码添加到`if inbounds or outbounds then` 之前

sing-box version 1.8.13

Environment: go1.22.2 linux/arm64
Tags: with_gvisor,with_quic,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api
Revision: 742adacce77f5cdb9eeb0efd67e7fbf44c966a12
CGO: disabled

未成功

**Comment by LeeRemember** [comment]
[util_sing-box.zip](https://github.com/xiaorouji/openwrt-passwall2/files/15319611/util_sing-box.zip)
你把我这个文件替换到你原来的呢
