### ISSUE TITLE
[Bug]: xray 模式下不能上网

### ISSUE THREAD

**Issue by fmsonic** [xiaorouji/openwrt-passwall2#575]
### 描述您遇到的bug

在节点类型切换至 xray 之后，core为未运行状态，不能正常上网。节点类型切换为 sing box，就一切正常。
![WX20240512-210124@2x](https://github.com/xiaorouji/openwrt-passwall2/assets/19233314/3b609880-cd17-4744-8af9-2d207542d1fe)

### 复现此Bug的步骤

节点类型切换为 xray，保存并应用。

### 您想要实现的目的

如果是因为规则的原因造成，xray 启动失败的话。切换至sing box应该也是会失败的吧。

### 日志信息

Xray 1.8.11 (Xray, Penetrates Everything.) 45ab4cb (go1.22.2 linux/amd64)
A unified platform for anti-censorship.
2024/05/12 19:40:39 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/acl/default/global.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/acl/default/global.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: github > infra/conf: code not found in geoip.dat: GITHUB
failed to load config files

### 截图

geoip 都做过手动更新了
![WX20240512-210138@2x](https://github.com/xiaorouji/openwrt-passwall2/assets/19233314/448b6a32-dbf1-43a8-a9af-760273be5098)

### 系统相关信息

PassWall2_1.29-1
设备型号 BROUNION R86S
固件版本 iStoreOS 22.03.6 2024031514

**Comment by adfnkjasd** [comment]
geo库问题，singbox和xray用的不一样，得手动清除后下载放到目录里
[https://github.com/xiaorouji/openwrt-passwall2/issues/365](url)

**Comment by adfnkjasd** [comment]
> > geo库问题，singbox和xray用的不一样，得手动清除后下载放到目录里
> > > #365
> 
> 感谢，不过我看配置里面 sing box和 xray 的保存 geo 位置都不一样，前者是/usr/share/singbox/，后者是/usr/share/v2ray/

是的，根据issue365里的位置保存即可

**Comment by fmsonic** [comment]
> > > geo库问题，singbox和xray用的不一样，得手动清除后下载放到目录里
> > > > #365
> > 
> > 
> > 感谢，不过我看配置里面 sing box和 xray 的保存 geo 位置都不一样，前者是/usr/share/singbox/，后者是/usr/share/v2ray/
> 
> 是的，根据issue365里的位置保存即可

收到，非常感谢。
