### ISSUE TITLE
[Feature Request]: 希望加入定时重启功能

### ISSUE THREAD

**Issue by sbcarp** [xiaorouji/openwrt-passwall2#578]
### 描述你想要的新功能

Passwall2 运行久了网络变得有些卡顿，具体原因不明，但重启Passwall2 后一切恢复正常，希望加入定时重启功能来解决这个问题，谢谢

### 描述你想要的解决方案

定时重启功能
- 用户可以设置重启的时间间隔，例如每天、每周或每月的某个特定时间。
- 特定时间支持精确到小时或分钟

**Comment by flourishing** [comment]
兄弟，这个可以加个定时任务执行以下指令

```shell
/etc/init.d/passwall2 restart
```

**Comment by sbcarp** [comment]
> 兄弟，这个可以加个定时任务执行以下指令
> 
> ```shell
> /etc/init.d/passwall2 restart
> ```

好主意，谢谢！作者要是感觉这个功能不是很必要就关了吧

**Comment by LeeRemember** [comment]
更新规则后也会自动重启。
