### ISSUE TITLE
DNS选项的 远程DNS 协议 BUG

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#58]
最新源版版本，

远程 DNS 协议 TCP 远程 DNS 1.1.1.1

看生成的配置文件

<pre>
 "dns": {
    "disableFallback": true,
    "queryStrategy": "UseIPv4",
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "port": 53,
        "address": "tcp:\/\/1.1.1.1:53"
      },

      {
        "address": "tcp:\/\/1.1.1.1:53",
        "port": 53,
        "domains": [
          "geosite:category-ads-all"
        ],
        "tag": "remote"
      },
</pre>

 "tag": "remote" 这个tag没有对应的 ”routing" 里面的tag，它的值geosite:category-ads是AD规则里的域名值。如果这个值改为geosite:category-ads-123456，这种不存在的，全部打不开网页。

如果删除AD规则，或在Main里把AD设置为关闭，看配置文件恢复为
<pre>
      {
        "address": "tcp:\/\/1.1.1.1:53",
        "port": 53,
        "tag": "remote"
      },
</pre>

主要是没看明白多了这条规则的意义。可能是代码的BUG？

如果 DNS设置为自定义，"tag": "remote"和它上面的DNS值一起在变
<pre>
      {
        "port": 53,
        "address": "tcp:\/\/123.42.1.1:53"
      },
      {
        "address": "tcp:\/\/123.42.1.1:53",
        "port": 53,
        "tag": "remote"
      },
</pre>

**Comment by xiaorouji** [comment]
故意的，就是作为默认DNS用
