### ISSUE TITLE
[Bug]:跑路了 不问啦

### ISSUE THREAD

**Issue by whatpig** [xiaorouji/openwrt-passwall2#588]
跑路了 不问啦

**Comment by whatpig** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/5a0ac5c6-8981-4b94-8faf-f604883031cc)
正好发完issue后来了一次 有幸截图 从发现国内无法访问到正常 大概几十秒

**Comment by whatpig** [comment]
一上午又国内失联了 3-4次 每次几十秒 然后我把备份已久的旧版本的openwrt里面安装的时1.17-2的恢复使用 到目前俩小时一切正常

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/108253841/c4ef2e81-a020-4288-b3ad-e4cc6cd95c61)

**Comment by nczyw** [comment]
你把passwaall2的开关关掉，看看百度会不会间歇性的问题，有的话，换固件；没有的话给Passwall2升一下级，现在是1.19-1了。
