### ISSUE TITLE
[Feature Request]: 增加xray对协议的支持

### ISSUE THREAD

**Issue by hu-boss** [xiaorouji/openwrt-passwall2#591]
### 描述你想要的新功能

现在ps2的xray支持的协议太少了，比如TUIC，HY2多不支持，SS里的新的加密方式也很少，建议多增加一些协议和加密

### 描述你想要的解决方案

想要更多更全面的功能

**Comment by ohbaby30** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/62003514/277a01b3-b5bc-494c-9cce-231ca4de8675)

这不是支持吗？

**Comment by hu-boss** [comment]
> ![image](https://private-user-images.githubusercontent.com/62003514/334640228-277a01b3-b5bc-494c-9cce-231ca4de8675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTE0NTIsIm5iZiI6MTcxNjk5MTE1MiwicGF0aCI6Ii82MjAwMzUxNC8zMzQ2NDAyMjgtMjc3YTAxYjMtYjViYy00OTRjLTljY2UtMjMxY2E0ZGU4Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEzNTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZDM0MjUwOTRiOTdkNDg4NmI3NjE1YzBlMzVkNzJlOGZiMjRjZTNmMTczNTdkYmQzNTE3ZDQzOGJjMWQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h_flHJy2JGT_FIxOA0eLL5FhzUTUhiPT23wA76BORnA)
> 
> 这不是支持吗？

你这怎么弄的，ps2里只有xray sing-box hy2, ps2里sing-box的tuic有问题，我弄了一整天都不行，连以为服务端没弄好，没想到用其它软件就连上了

**Comment by ohbaby30** [comment]
> > ![image](https://private-user-images.githubusercontent.com/62003514/334640228-277a01b3-b5bc-494c-9cce-231ca4de8675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTE0NTIsIm5iZiI6MTcxNjk5MTE1MiwicGF0aCI6Ii82MjAwMzUxNC8zMzQ2NDAyMjgtMjc3YTAxYjMtYjViYy00OTRjLTljY2UtMjMxY2E0ZGU4Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEzNTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZDM0MjUwOTRiOTdkNDg4NmI3NjE1YzBlMzVkNzJlOGZiMjRjZTNmMTczNTdkYmQzNTE3ZDQzOGJjMWQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h_flHJy2JGT_FIxOA0eLL5FhzUTUhiPT23wA76BORnA)
> > 这不是支持吗？
> 
> 你这怎么弄的，ps2里只有xray sing-box hy2, ps2里sing-box的tuic有问题，我弄了一整天都不行，连以为服务端没弄好，没想到用其它软件就连上了

你用的别人的固件吧 找作者 他没编译进去 或者自己编译

**Comment by hu-boss** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/62003514/334640228-277a01b3-b5bc-494c-9cce-231ca4de8675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTE0NTIsIm5iZiI6MTcxNjk5MTE1MiwicGF0aCI6Ii82MjAwMzUxNC8zMzQ2NDAyMjgtMjc3YTAxYjMtYjViYy00OTRjLTljY2UtMjMxY2E0ZGU4Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEzNTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZDM0MjUwOTRiOTdkNDg4NmI3NjE1YzBlMzVkNzJlOGZiMjRjZTNmMTczNTdkYmQzNTE3ZDQzOGJjMWQ1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h_flHJy2JGT_FIxOA0eLL5FhzUTUhiPT23wA76BORnA)
> > > 这不是支持吗？
> > 
> > 
> > 你这怎么弄的，ps2里只有xray sing-box hy2, ps2里sing-box的tuic有问题，我弄了一整天都不行，连以为服务端没弄好，没想到用其它软件就连上了
> 
> 你用的别人的固件吧 找作者 他没编译进去 或者自己编译

用的官方原版op 官方原版ps2

**Comment by ohbaby30** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/62003514/839524ec-77cb-4405-af5e-4ecb98f80035)

你要的两个默认没勾选的

**Comment by hu-boss** [comment]
> ![image](https://private-user-images.githubusercontent.com/62003514/335057900-839524ec-77cb-4405-af5e-4ecb98f80035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDkyODQsIm5iZiI6MTcxNzA0ODk4NCwicGF0aCI6Ii82MjAwMzUxNC8zMzUwNTc5MDAtODM5NTI0ZWMtNzdjYi00NDA1LWFmNWUtNGVjYjk4ZjgwMDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2MDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZDdjZTllZDY3NGFkMGE1ODk2ZTI3OGFhZWY3N2JmMzRkOGI4N2E3NDFjODUyY2M1MWQ3YWZkZDcyN2Q1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q3DhFQU17UNDGmIOI4k0aBwxklD6RaWJVGOBO-06c5M)
> 
> 你要的两个默认没勾选的

不会编译只能这样了
