### ISSUE TITLE
[Bug]: dnsmasq高占用不明

### ISSUE THREAD

**Issue by eqfae** [xiaorouji/openwrt-passwall2#594]
### 描述您遇到的bug

![图片](https://github.com/xiaorouji/openwrt-passwall2/assets/120385812/aa7618d6-044d-4918-b58b-1173956c30ef)
打开国内网站说找不到地址 其他国外的到时能打开 但是youtube当时不显示推荐视频只有一个使用搜索的建议
重新拨号看到这个高占用持续 又重拨了一次 持续了一会 降到0 可当我打到这段字的时候又开始了
能否不用dnsmasq singbox直接接管
刚打开b站又降下去了 原因不明
![图片](https://github.com/xiaorouji/openwrt-passwall2/assets/120385812/e444a896-615d-417b-89c2-3ce28bf373a5)

### 复现此Bug的步骤

不清楚复现 

### 您想要实现的目的

不是第一次看到持续高占用 不用dnsmasq多一层转发 singbox直接 而且sing dns支持quic这些 但直连得设置 乐观缓存 持久化缓存 足够替代adg

### 日志信息

Sat Jun  8 09:02:12 2024 user.notice firewall: Reloading firewall due to ifup of wan_6 (pppoe-wan)
Sat Jun  8 09:02:12 2024 user.warn kernel: [1293288.031631] passwall2: restart when wan_6 ifup
Sat Jun  8 09:02:15 2024 daemon.info dnsmasq[5141]: started, version 2.90 cache disabled
Sat Jun  8 09:02:15 2024 daemon.info dnsmasq[5141]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack no-ipset nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Sat Jun  8 09:02:15 2024 daemon.info dnsmasq[5141]: using nameserver 10.0.0.1#54
Sat Jun  8 09:02:15 2024 daemon.info dnsmasq[5141]: read /etc/hosts - 6 names

### 系统相关信息

1.28-5

**Comment by eqfae** [comment]
![图片](https://github.com/xiaorouji/openwrt-passwall2/assets/120385812/0974bfdb-9ffd-4b0e-bb39-8941ab12fad2)
今天进ssh就这样

**Comment by organics2016** [comment]
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/16286533/90d213c1-9c79-4734-b640-634f9ae612f5)
我也有类型情况,但我的是 xray 占用很高, 外在表现和题主一样

**Comment by LeXwDeX** [comment]
能否提供抓包信息呢。

**Comment by eqfae** [comment]
> 能否提供抓包信息呢。

不知道提供什么信息 对应的直连dns没大问题
![图片](https://github.com/xiaorouji/openwrt-passwall2/assets/120385812/a8ea27fb-7927-483a-9a26-344a9409b73b)

**Comment by eqfae** [comment]
1
