### ISSUE TITLE
能否给PSW2添加直接定义dns解析的hosts功能

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-passwall2#60]
psw2直接接管了dnsmasq，XRAY内建的dns带hosts功能，能不能顺便把这个功能给加到luci设置里面，这样就更完美了:)
![image](https://user-images.githubusercontent.com/45598380/163140549-72a43e6f-33b3-4df1-87e1-4bcd065f22f9.png)

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall2/commit/3b190d83adcd71c680d3d2872d8df666619e9b65

**Comment by yunxi993** [comment]
`域名重写` 是这种写法吗，IP前面要不要空格.

![image](https://user-images.githubusercontent.com/59167936/163217769-3f82c4b5-778e-4e25-b646-f9a9f6cca62e.png)

**Comment by badgv** [comment]
大佬太6了，马上就加上了，点个赞，已测试，很好用！
