### ISSUE TITLE
[Bug]: url test didnt work 

### ISSUE THREAD

**Issue by Sepehrdibaj** [xiaorouji/openwrt-passwall2#601]
### 描述您遇到的bug

Hello , i use passwall 2 and its work but url test didnt work at al i test it with many server , the server work but in url test timeout !

### 复现此Bug的步骤

Hello , i use passwall 2 and its work but url test didnt work at al i test it with many server , the server work but in url test timeout !

### 您想要实现的目的

Openwrt snappshot version on ax3000t xiaomi 

### 日志信息

Last version passwall2 and last version of snappshots 

### 系统相关信息

Passwall 2 last verion and last version xray

**Comment by Sepehrdibaj** [comment]
I check curl its work , but in passwall both of url test and connection test didnt work

**Comment by yoier** [comment]
#603
