### ISSUE TITLE
[Bug]: 本地网络正常, 无法更新订阅.

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall2#603]
### 描述您遇到的bug

OpenWrt 官方主线分支编译的 passwall2 无法更新订阅.

组件获取版本信息也是失败.

导入的节点URL 测试失败, 谷歌连接测试失败, 但是可以正常访问Google, youtube.

### 复现此Bug的步骤

官方 OpenWrt 主线分支编译的固件 passwall2 无法正常订阅.

同样主线分支, 6月7日编译的固件 passwall2 可以正常订阅并使用.

### 您想要实现的目的

*

### 日志信息

系统日志: daemon.err dnsmasq[10996]: nftset inet fw4 passwall2_global_whitelist Error: No such file or directory; did you mean set ‘passwall2_lanlist’ in table inet ‘fw4’?

### 截图

![屏幕截图 2024-06-16 024546](https://github.com/xiaorouji/openwrt-passwall2/assets/59167936/49d474bb-8ddf-4523-82fc-bbfcaebc285f)
***
![屏幕截图 2024-06-16 024352](https://github.com/xiaorouji/openwrt-passwall2/assets/59167936/47395fa3-22e5-4e78-b9c9-298d451bef64)
***
![屏幕截图 2024-06-16 024340](https://github.com/xiaorouji/openwrt-passwall2/assets/59167936/8caf0866-9139-4b4a-8613-0d94eadc4594)

### 系统相关信息

passwall2 version: 1.29-1

**Comment by yoier** [comment]
我也遇到了相同情況，暫時回退到上周編譯的固件。這個版本用curl下載報錯：curl: (55) Error。

**Comment by yunxi993** [comment]
> 我也遇到了相同情況，暫時回退到上周編譯的固件。這個版本用curl下載報錯：curl: (55) Error。

23.05 分支正常使用, 还没找到是什么原因造成的.

**Comment by catsimple** [comment]
same

**Comment by catsimple** [comment]
check_status方法如下
```
curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" url
```
```
root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://baidu.com
302:0.175252
```
```
root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://google.com
000:0.000000
```

**Comment by yunxi993** [comment]
> check_status方法如下
> 
> ```
> curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" url
> ```
> 
> ```
> root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://baidu.com
> 302:0.175252
> ```
> 
> ```
> root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://google.com
> 000:0.000000
> ```

你解决了吗?

**Comment by catsimple** [comment]
> > check_status方法如下
> > ```
> > curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" url
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://baidu.com
> > 302:0.175252
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@OpenWrt:~# curl --connect-timeout 3 -o /dev/null -I -sk -w "%{http_code}:%{time_appconnect}" https://google.com
> > 000:0.000000
> > ```
> 
> 你解决了吗?

不知道，看起来应该是curl的问题，我先回退curl看看

**Comment by yunxi993** [comment]
> 
> 不知道，看起来应该是curl的问题，我先回退curl看看

我正在使用23.05分支 curl 版本: 8.7.1-r1, main分支可用的curl版本为: 8.7.1-r2

**Comment by catsimple** [comment]
> > 不知道，看起来应该是curl的问题，我先回退curl看看
> 
> 我正在使用23.05分支 curl 版本: 8.7.1-r1, main分支可用的curl版本为: 8.7.1-r2

main已经到8.8.0了

**Comment by yunxi993** [comment]
> 
> main已经到8.8.0了

目前已知这两个版本在 23.05 和 main 分支, paswall2 订阅正常.

**Comment by catsimple** [comment]
已确定是curl的问题
https://github.com/openwrt/packages/pull/24414

**Comment by yunxi993** [comment]
> 已确定是curl的问题 [openwrt/packages#24414](https://github.com/openwrt/packages/pull/24414)

 一会重新编译后试试.

**Comment by yunxi993** [comment]
已确认是 "curl" 导致, 替换 "curl" 版本后解决.
