### ISSUE TITLE
[Feature Request]: 是否可以增加一个输入域名或IP来测试匹配了哪条分流规则的功能？

### ISSUE THREAD

**Issue by MapleRecall** [xiaorouji/openwrt-passwall2#604]
### 描述你想要的新功能

最近在处理一些分流和预期不一致的问题，比如geosite规则嵌套导致优先级不对、新域名更新不及时或者或者手写规则不准确等，有些还可能是因为特定的dns解析问题。

但排查起来比较麻烦，得翻查geosite源码或者一条条开关分流规则，不停的nslookup来判断出口等。

### 描述你想要的解决方案

增加一个功能，输入域名或ip地址来测试命中了哪条分流规则，如果可以把对应请求的节点和dns之类的信息也一块输出就更好了~

**Comment by laaArmy** [comment]
https://ip.skk.moe/
