### ISSUE TITLE
[Bug]: url测试总是超时

### ISSUE THREAD

**Issue by asdjkm1234** [xiaorouji/openwrt-passwall2#605]
### 描述您遇到的bug

无论是v2ray节点还是ss节点。都超时。tcp测试可通。url测试不通。
节点已经在本机客户端里面测试过可以使用。
我是编译官方最新版openwrt。用网上现成编译好的固件同样的设置可以通。
试过passwall也是一样问题

### 复现此Bug的步骤

1.导入节点
2.URL 测试

### 您想要实现的目的

修复

### 日志信息

![Snipaste_2024-06-20_23-46-57](https://github.com/xiaorouji/openwrt-passwall2/assets/53368123/d2b83ca4-d5a3-4369-b9a2-d4fa5ac49fbe)

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall2/assets/53368123/eb16a5df-2fc6-48b9-88d0-0e27afc078bc)
![image](https://github.com/xiaorouji/openwrt-passwall2/assets/53368123/807abbd5-2d2f-40d3-ad22-9da26ea22a8a)

### 系统相关信息

- passwall版本：2
- openwrt版本：官方最新编译

**Comment by asdjkm1234** [comment]
解决了，是curl问题

**Comment by amirhosseinchoghaei** [comment]
> Solved, it was a curl problem

How Did you solved that ?

**Comment by asdjkm1234** [comment]
> > Solved, it was a curl problem
> 
> How Did you solve that ?



I have tested and found that selecting wolfSSL in menuconfig temporarily resolves the issue.

Navigate to:
Libraries  --->   -*- libcurl. A client-side URL transfer library  --->   Selected SSL library (wolfSSL)

please check:
https://github.com/openwrt/packages/pull/24414

**Comment by yoier** [comment]
The latest source code compilation has fixed this problem, just recompile it.

**Comment by tang2722** [comment]
我也是这个问题，大佬怎么解决的

**Comment by tang2722** [comment]
我是小白，有没有详细教程

**Comment by yoier** [comment]
> 我是小白，有没有详细教程

最新源码已经修复了，重新拉取编译一下就好了。

**Comment by tang2722** [comment]
> > 我是小白，有没有详细教程
> 
> 最新源码已经修复了，重新拉取编译一下就好了。

不会编译。有没傻瓜包

**Comment by yoier** [comment]
> > > 我是小白，有没有详细教程
> > 
> > 
> > 最新源码已经修复了，重新拉取编译一下就好了。
> 
> 不会编译。有没傻瓜包

你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。

**Comment by tang2722** [comment]
OPWRT的固件是吗？ 那得重装？

**Comment by tang2722** [comment]
我安装的是23.05.3，没看到最近编译的固件

**Comment by tang2722** [comment]
> > > > > 我是小白，有没有详细教程
> > > > 
> > > > 
> > > > 最新源码已经修复了，重新拉取编译一下就好了。
> > > 
> > > 
> > > 不会编译。有没傻瓜包
> > 
> > 
> > 你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。
> 
> 谢谢你的回答，那得重新装系统吗？
大师找到了固件，在OPENWRT里面，直接刷写新固件可以吗

**Comment by yoier** [comment]
> > > > > > 我是小白，有没有详细教程
> > > > > 
> > > > > 
> > > > > 最新源码已经修复了，重新拉取编译一下就好了。
> > > > 
> > > > 
> > > > 不会编译。有没傻瓜包
> > > 
> > > 
> > > 你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。
> > 
> > 
> > 谢谢你的回答，那得重新装系统吗？
> > 大师找到了固件，在OPENWRT里面，直接刷写新固件可以吗

那具体得看你固件能不能直接更新。

**Comment by yoier** [comment]
> > > > > > 我是小白，有没有详细教程
> > > > > 
> > > > > 
> > > > > 最新源码已经修复了，重新拉取编译一下就好了。
> > > > 
> > > > 
> > > > 不会编译。有没傻瓜包
> > > 
> > > 
> > > 你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。
> > 
> > 
> > 谢谢你的回答，那得重新装系统吗？
> > 大师找到了固件，在OPENWRT里面，直接刷写新固件可以吗

开不起机的话，就进breed恢复出厂设置再上传固件更新，x86就用电脑写盘。

**Comment by tang2722** [comment]
> > > > > > > 我是小白，有没有详细教程
> > > > > > 
> > > > > > 
> > > > > > 最新源码已经修复了，重新拉取编译一下就好了。
> > > > > 
> > > > > 
> > > > > 不会编译。有没傻瓜包
> > > > 
> > > > 
> > > > 你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。
> > > 
> > > 
> > > 谢谢你的回答，那得重新装系统吗？
> > > 大师找到了固件，在OPENWRT里面，直接刷写新固件可以吗
> 
> 开不起机的话，就进breed恢复出厂设置再上传固件更新，x86就用电脑写盘。

大神。更新了 内核显示没有更新，怎么保留设置更新呢，求指教

**Comment by yoier** [comment]
> > > > > > > > 我是小白，有没有详细教程
> > > > > > > 
> > > > > > > 
> > > > > > > 最新源码已经修复了，重新拉取编译一下就好了。
> > > > > > 
> > > > > > 
> > > > > > 不会编译。有没傻瓜包
> > > > > 
> > > > > 
> > > > > 你找你对应型号的固件，最近一周或者上个月编译的就行。这bug是3周前curl依赖的问题，不到一周就解决了，跟passwall2没有关系。
> > > > 
> > > > 
> > > > 谢谢你的回答，那得重新装系统吗？
> > > > 大师找到了固件，在OPENWRT里面，直接刷写新固件可以吗
> > 
> > 
> > 开不起机的话，就进breed恢复出厂设置再上传固件更新，x86就用电脑写盘。
> 
> 大神。更新了 内核显示没有更新，怎么保留设置更新呢，求指教

更新的时候有个保留配置的选项吧

**Comment by yoier** [comment]
> 哦，VMESS VLESS 都试过，软路由就不通，手机用小火箭就是通的

不用小火箭，手机连路由器的网不能用吗

**Comment by yoier** [comment]
> 哦，VMESS VLESS 都试过，软路由就不通，手机用小火箭就是通的

这个bug只是管理页面测试不通，curl的问题。实际上手机连上路由器的网还是可以直接用。

**Comment by yoier** [comment]
> 我现在的情况是，用PASSWALL 有几个节点用着用着就是URL不通，无法连接网络。小火箭可以正常连接

校园网？

**Comment by tang2722** [comment]
家庭网络，我在做TK。就是手机连上不能用。现在头大

**Comment by Richfifi** [comment]
大佬们，ping，tcping和url都显示超时怎么办？

**Comment by yoier** [comment]
检查节点配置是否有误

**Comment by Richfifi** [comment]
我是直接从V2rayN里面的节点复制过来到软路由的，这个节点配置有问题吗？

> 检查节点配置是否有误

**Comment by yoier** [comment]
> 我是直接从V2rayN里面的节点复制过来到软路由的，这个节点配置有问题吗？
> 
> > 检查节点配置是否有误

你看一下你的节点日志
