### ISSUE TITLE
动态dns错误。

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall2#61]
开启paswall2后，动态dns服务不断报错，不知道是不是我设置有问题：
073825       : #> /usr/bin/drill -V0 -4 -u vpn.snakwu.com @114.114.114.114 A >/var/run/ddns/xxx_snakwu_com.dat 2>/var/run/ddns/xxx_snakwu_com.err
 073840 ERROR : drill error: '1'
 073840       : Error: error sending query: Could not send or receive, because of network error
 073840  WARN : Get registered/public IP for 'xxx.snakwu.com' failed - retry 5/0 in 60 seconds

passwall2，分流用的是默认规则，ddns用的是cloudflare-v4，并设置114.114.114.114用来检测注册ip的。

**Comment by xiaorouji** [comment]
把你的域名和检测IP的域名加入直连规则里面

**Comment by snakwu** [comment]
> 把你的域名和检测IP的域名加入直连规则里面

已经加了的

**Comment by xiaorouji** [comment]
可以试试，如果域名是完整匹配，在前面加full:，这样匹配优先级最高。
full:xxx.snakwu.com
domain:snakwu.com

**Comment by snakwu** [comment]
> 可以试试，如果域名是完整匹配，在前面加full:，这样匹配优先级最高。 full:xxx.snakwu.com domain:snakwu.com

同样报错，不知道什么原因！

**Comment by xiaorouji** [comment]
我用aliddns没问题，没有cloudflare的ddns无法测试

**Comment by chancat87** [comment]
规则里加上
geosite:private
geoip:private
试试？
