### ISSUE TITLE
[Bug]: luci: 1.30-1 新版无法启动，恢复默认配置还是未运行

### ISSUE THREAD

**Issue by xcf13363175** [xiaorouji/openwrt-passwall2#618]
### 描述您遇到的bug

luci: 1.30-1 新版无法启动，恢复默认配置还是未运行

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

无

**Comment by hcym** [comment]
名字都没改对，呵呵，等更吧

**Comment by zht713** [comment]
我也出现一样的问题，无法启动。树莓派4B。

**Comment by redfrog999** [comment]
启动不了+1。

**Comment by Travel2Here** [comment]
启动不了+1
（xray1.8.19 ，app 1.3.0-2）

**Comment by xiaorouji** [comment]
Sorry, merging some commits caused errors, please try the latest version.

**Comment by hcym** [comment]
明天试试看

**Comment by Travel2Here** [comment]
v3 ojbk

**Comment by xcf13363175** [comment]
已测试ok了

**Comment by redfrog999** [comment]
我把PSW和PSW2集成到硬路由里，还是无法启动PSW2，PSW正常工作，现在不支持两个软件集成到一个固件使用吗？
