### ISSUE TITLE
[Feature Request]: 长期使用，非常喜欢pw和2，期望2能做到重启时网络不闪断

### ISSUE THREAD

**Issue by kylongteng** [xiaorouji/openwrt-passwall2#619]
### 描述你想要的新功能

长期使用1，最近换成2，可能因为1和2架构不同，代码量不同，感觉2更轻快些。
但是2有一个问题，就是修改配置重启时会导致整个网络闪断。1没有这个问题(不管是代理和分流)。
以前我也没发现，这几天玩jj象棋，每次2重启时都会断开，但很快会重新连上，100%出现。
又换回去1了

### 描述你想要的解决方案

2重启时不闪断

### 描述你考虑过的替代方案

不是很清楚技术实现原理，但感觉2应该是任何请求都全部走一遍xray核心，所以每次重启时闪断，1应该不是这样

**Comment by Zeezorn** [comment]
非常同意~

**Comment by xiaorouji** [comment]
I have a branch. It can achieve true direct connection instead of entering the core completely. for my own use, but it requires modifying the core source code, so it cannot be made public for the time being.

**Comment by kylongteng** [comment]
> I have a branch. It can achieve true direct connection instead of entering the core completely. for my own use, but it requires modifying the core source code, so it cannot be made public for the time being.

期待以后再passwall2能实现重启时不闪断
