### ISSUE TITLE
[Feature Request]: 开放赞助链接

### ISSUE THREAD

**Issue by sbcarp** [xiaorouji/openwrt-passwall2#621]
### 描述你想要的新功能

用p2也有一年多了，虽然有些小bug，但总体体验还是非常不错的，满足了大部分需求，所以希望这个项目能够长久发展，而自己没有时间精力投身于这个项目中，就想问下作者有没有开放赞助的打算，让我们有机会支持一下。

### 描述你想要的解决方案

开放赞助链接

**Comment by xiaorouji** [comment]
Thank, due to privacy issues. if you have cryptocurrency...

**Comment by sbcarp** [comment]
那可惜了，手上没有，不过好像有几个支持crypto的赞助平台。。。。
