### ISSUE TITLE
[Bug]: nftables和fw4分离后代理有点问题

### ISSUE THREAD

**Issue by Eternalklk** [xiaorouji/openwrt-passwall2#638]
### 描述您遇到的bug

1、具体表现为，访问控制打开之后，微软商店下载一直连不上。关闭访问控制功能之后微软商店下载正常，P1 P2皆有此问题
2、日志显示每隔一段时间会删除规则刷新一次，P1 P2都是

### 复现此Bug的步骤

启用访问控制功能

### 您想要实现的目的

1、修复正常
2、功能添加，访问控制能实现除指定设备外其他设备皆不代理

### 日志信息

回去上传，顺便提问上传那一部分能帮助到大佬们

### 系统相关信息

Passwall2最新代码，chrome浏览器（具体版本回去看看）

**Comment by xiaorouji** [comment]
@ShanStone 測試下PASS1的nftables 訪問控制是否正常？

**Comment by ShanStone** [comment]
![image](https://github.com/user-attachments/assets/8cc590a4-1be3-496d-aa13-5d3623868016)
我测试是正常的
