### ISSUE TITLE
远程 DNS 协议：UDP，生成的Xray配置文件中一处BUG

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#64]
我用的
远程 DNS 协议：UDP
远程 DNS：1.1.1.1

查看生成的Xray配置文件如下

1，DNS查询引入
<pre>
    {
      "port": 15353,
      "protocol": "dokodemo-door",
      "settings": {
        "port": 53,
        "network": "tcp,udp",
        "address": "1.1.1.1"
      },
      "tag": "dns-in",
      "listen": "127.0.0.1"
    }
</pre>
2，进入dns-out
<pre>
      {
        "type": "field",
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out"
      },
</pre>
3，在  "outbounds" 中 的配置
<pre>
    {
      "settings": {
        "network": "tcp",
        "address": "1.1.1.1"
      },
      "protocol": "dns",
      "tag": "dns-out"
    },
</pre>
"settings": 
"network": "tcp",
"address": "1.1.1.1"

根据文档https://www.v2fly.org/config/protocols/dns.html#outboundconfigurationobject
network: "tcp" | "udp"
(V2Ray 4.16+) 修改 DNS 流量的传输层协议，可选的值有 "tcp" 和 "udp"。当不指定时，保持来源的传输方式不变。
address: address
(V2Ray 4.16+) 修改 DNS 服务器地址。当不指定时，保持来源中指定的地址不变。
port: number
(V2Ray 4.16+) 修改 DNS 服务器端口。当不指定时，保持来源中指定的端口不变。

猜测，这个UDP流量因写了TCP，改成了TCP了吗？

建议settings不写。即改为
<pre>
    {
      "protocol": "dns",
      "tag": "dns-out"
    },
</pre>

DNS部分是
<pre>
 "dns": {
    "disableFallback": true,
    "queryStrategy": "UseIPv4",
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "port": 53,
        "_flag": "default",
        "address": "1.1.1.1"
      },

      {
        "_flag": "remote",
        "port": 53,
        "domains": [
          "geosite:category-ads-all"
        ],
        "address": "1.1.1.1"
      },

      {
        "_flag": "direct",
        "port": 53,
        "domains": [
          "geosite:cn",
          "geosite:category-games@cn"
        ],
        "address": "192.168.2.1"
      }
    ],
    "disableCache": false,
    "tag": "dns-in1"
</pre>

**Comment by badgv** [comment]
这个实测使用中好像得没有影响？
不管修不修改DNS请求的服务器network 和address，最终都是由DNS那块来处理的。

**Comment by chika0801** [comment]
感谢解答。强迫症还是希望改下好看点23333

**Comment by badgv** [comment]
> 感谢解答。强迫症还是希望改下好看点23333

你发的链接里面写了，DNS 是一个出站协议，主要用于拦截和转发 DNS 查询。此出站协议只能接收 DNS 流量（包含基于 UDP 和 TCP 协议的查询），其它类型的流量会导致错误。

假如从dnsmasq导入outbound的DNS查询不属于TCP和UDP流量，这时候XRAY估计会报错？没实测过。

所以我猜添加这组配置的目的就是不管进入这个protocol:dns里面的DNS查询类型是什么，都修改为tcp协议，IP为1.1.1.1,这样可以防止xray出错。

基本上面的考虑的话，可能还是保留这组配置比较好的。

**Comment by chika0801** [comment]
> > 感谢解答。强迫症还是希望改下好看点23333
> 
> 你发的链接里面写了，DNS 是一个出站协议，主要用于拦截和转发 DNS 查询。此出站协议只能接收 DNS 流量（包含基于 UDP 和 TCP 协议的查询），其它类型的流量会导致错误。
> 
> 假如从dnsmasq导入outbound的DNS查询不属于TCP和UDP流量，这时候XRAY估计会报错？没实测过。
> 
> 所以我猜添加这组配置的目的就是不管进入这个protocol:dns里面的DNS查询类型是什么，都修改为tcp协议，IP为1.1.1.1,这样可以防止xray出错。
> 
> 基本上面的考虑的话，可能还是保留这组配置比较好的。

我开客户端和服务器端开debug看日志，观察了一下
<pre>
    {
      "settings": {
        "network": "tcp",
        "address": "1.1.1.1"
      },
      "protocol": "dns",
      "tag": "dns-out"
    },</pre>

虽然上面写的是转成tcp 发1.1.1.1。在服务器端日志上显示 ，还是udp 的1.1.1.1，是没有影响。

不知道作者为什么原因这儿这样写的。

**Comment by badgv** [comment]
> > > 感谢解答。强迫症还是希望改下好看点23333
> > 
> > 
> > 你发的链接里面写了，DNS 是一个出站协议，主要用于拦截和转发 DNS 查询。此出站协议只能接收 DNS 流量（包含基于 UDP 和 TCP 协议的查询），其它类型的流量会导致错误。
> > 假如从dnsmasq导入outbound的DNS查询不属于TCP和UDP流量，这时候XRAY估计会报错？没实测过。
> > 所以我猜添加这组配置的目的就是不管进入这个protocol:dns里面的DNS查询类型是什么，都修改为tcp协议，IP为1.1.1.1,这样可以防止xray出错。
> > 基本上面的考虑的话，可能还是保留这组配置比较好的。
> 
> 我开客户端和服务器端开debug看日志，观察了一下
> 
>     {
>       "settings": {
>         "network": "tcp",
>         "address": "1.1.1.1"
>       },
>       "protocol": "dns",
>       "tag": "dns-out"
>     },
> 虽然上面写的是转成tcp 发1.1.1.1。在服务器端日志上显示 ，还是udp 的1.1.1.1，是没有影响。
> 
> 不知道作者为什么原因这儿这样写的。

按我上面的解释，写这个是为了防止XRAY收到非TCP或UDP的DNS请求导致XRAY出错，最后请求DNS并不是以这个TCP,1.1.1.1来请求的，是按DNS模块DNS地址请求，也就是说这里可以随便填个114.114.114.114 tcp，实际无任何影响。
