### ISSUE TITLE
[Bug]: 私有网络地址代理失效

### ISSUE THREAD

**Issue by Pik-4** [xiaorouji/openwrt-passwall2#644]
### 描述您遇到的bug

网关模式下，无法通过分流规则代理局域网地址。需要手动删除nft的lanlist才能生效。
```
nft delete element inet passwall2 passwall2_lanlist { 10.0.0.0/8 }
```

### 复现此Bug的步骤

1. 开启tcp、udp全部转发
2. 使用nftables防火墙+tproxy代理，劫持icmp
3. 规则管理中分流规则第一条添加ip的代理规则ruleA
    ```
    10.168.168.0/24
    ```
5. 基本设置主要中，xray分流ruleA选择xray节点代理
6. 局域网下设备访问10.168.168.0/24无法通过网关进行代理（socks代理正常）。

### 您想要实现的目的

可以修改passwall2_lanlist，如果无法修改passwall2_lanlist ，那么网关代理时有关局域网的代理规则将全部失效。

### 日志信息

        set passwall2_lanlist {
                type ipv4_addr
                flags interval,timeout
                auto-merge
                elements = { 0.0.0.0/8, 10.0.0.0/8,
                             100.64.0.0/10, 114.114.114.114,
                             127.0.0.0/8, 169.254.0.0/16,
                             172.16.0.0/12, 192.168.0.0/16,
                             224.0.0.0/3 }
        }

### 系统相关信息

- passwall2 1.31-1
- openwrt-23.05.4-x86-64-generic-ext4-combined
- LuCI openwrt-23.05 branch (git-23.233.52805-dae2684) / ArgonTheme v2.3.1 / OpenWrt 23.05.4 r24012-d8dd03c46f

**Comment by zxymdaddy** [comment]
我也是这个问题，开启TPROXY，只要REBOOT后，前几秒连接正常，过后外网就不通了。。
