### ISSUE TITLE
[Feature Request]: 请教开发老大，Passwall2的cpu架构组件包和passwall1是通用的吗？

### ISSUE THREAD

**Issue by jolly90s** [xiaorouji/openwrt-passwall2#647]
### 描述你想要的新功能

我的软路由是openwrt官方原版，只能手动安装，目前安装passwalll1一切正常，想升级passwall2的时候，发现下载列表里没有cpu架构的组件包和依赖包

### 描述你想要的解决方案

想问一下，passwall2和passwall1的组件包是通用的吗？是否可以用passwall1的组件包和passwall2的安装包一起上传安装？谢谢大佬！

**Comment by lwb1978** [comment]
因为pw不生产组件，只是组件的搬运工，所以pw2和1的组件是通用的，或者你从另外的渠道下载回来安装也是可以的，尽量使用最新版本组件就行。

**Comment by jolly90s** [comment]
> 因为pw不生产组件，只是组件的搬运工，所以pw2和1的组件是通用的，或者你从另外的渠道下载回来安装也是可以的，尽量使用最新版本组件就行。

谢谢！
