### ISSUE TITLE
希望 分流总节点 可以指向 Xray负载均衡节点

### ISSUE THREAD

**Issue by xuguangyuansh** [xiaorouji/openwrt-passwall2#65]
1、此需求针对 Passwall2；

## 你的功能请求是否与问题有关？ 请描述。(必填)
1、起初需求，只是哪些 “域名 or IP” 可以不走代理。看到可以用 “分流总节点” 来实现。
2、复合需求：我全家人访问时，单一节点无法承载流量，因此我建立了 “多条香港节点”，并启用了 “Xray负载均衡”。
3、问题：此时 “分流总节点”，的 “默认” 选项，只能选择单一 “真实节点”。

## 描述你想要的解决方案 (必填)
1、希望 “分流总节点”，的 “默认” 一项，可以选择 “Xray负载均衡” 节点 。

## 描述你考虑过的替代方案
1、PassWall 一代时，我直接使用了 “Xray负载均衡节点”，并配合 "直连/代理名单管理"，来实现 哪些流量不走 代理。

## 附加上下文
<img width="2023" alt="image" src="https://user-images.githubusercontent.com/13329376/163273070-dda0ab3b-3ba2-413b-95c4-3717dfae27b4.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/13329376/163274879-f9895d98-af6a-485b-9919-c240897b8bcd.png">

**Comment by SakuraFallingMad** [comment]
我是通过本地socks转发的，即分流的规则里都能用socks节点，然后socks里选择xray负载均衡

**Comment by xuguangyuansh** [comment]
1、是如何将 “Xray负载均衡” 加入到 Socks；
2、是 类型、协议，不管怎么换，分流总节点里面，仍看不到这个 Socks ：
<img width="724" alt="image" src="https://user-images.githubusercontent.com/13329376/163343684-5e10765c-89c0-451b-8e05-e95ba87800ce.png">

**Comment by SakuraFallingMad** [comment]
举个例子：节点俩，socks和负载均衡
![image](https://user-images.githubusercontent.com/31793080/163344849-3e7fefbc-a98b-473a-9be3-97929fb35c3f.png)
然后主界面：
![image](https://user-images.githubusercontent.com/31793080/163344959-466c6966-6573-447c-9015-acbd1e703f2b.png)
socks节点里的端口和socks转发端口一致，你试试，passwall一代就可以这么做。二代虽然我没这么做用过，但是应该也可以

**Comment by xuguangyuansh** [comment]
可以，可以，成功了 ！！！ 大佬 功底 好深厚 ！～～  跪拜 ！！～

**Comment by xuguangyuansh** [comment]
确实，只是临时方案 。。。
游戏总掉线，基本 10s 一掉。。.

**Comment by xiaorouji** [comment]
负载均衡，IP会变，不掉线才怪了

**Comment by xiaoyaozhilv** [comment]
这个确实实现不了一代的那种负载均衡，希望大佬尽快改进一下；负载均衡还是挺好用的。

**Comment by UncleUncleWang** [comment]
把分流主节点给删掉了该咋办.........

**Comment by 0987363** [comment]
确实，如果默认节点能选负载均衡就方便很多了

**Comment by Lancet-z** [comment]
确实还是需要这个功能，一般手上都会有不止一个节点做备用。还是希望能加入这个选项，也能最大化利用手头的资源。

**Comment by jyy5206** [comment]
我也有这个需求。
现在有了么？
