### ISSUE TITLE
[Bug]: 负载均衡会泄露DNS

### ISSUE THREAD

**Issue by xsj684135** [xiaorouji/openwrt-passwall2#652]
### 描述您遇到的bug

请见图3
设置负载均衡，会泄露DNS。
设置节点为非"负载均衡节点"不会泄露DNS

请问是我操作有误还是有bug

### 复现此Bug的步骤

开启负载均衡
节点列表，新建Socks，IP端口指向"负载均衡"
基本设置-主要里的，分流节点“默认”改为“负载均衡节点”

### 您想要实现的目的

不知道怎么处理。。。

### 日志信息

我浏览器用F12看了请求查询DNS的那条网址的IP 是[tcp_redir -> default]

### 截图

![image](https://github.com/user-attachments/assets/35990364-0f3d-43a7-9d3a-bc05017c8859)
![image](https://github.com/user-attachments/assets/35e5dede-4c7b-474d-a7a6-2031cf76a8be)
![image](https://github.com/user-attachments/assets/0d5c4396-42d4-4874-8254-1e2fc261fc50)

### 系统相关信息

[Powered by LuCI Master (git-24.182.36151-66d29de)](https://github.com/openwrt/luci) / [ArgonTheme v1.8.3](https://github.com/jerrykuku/luci-theme-argon) / OpenWrt Free-Mini-2024.09.01_by_Sirpdboy

luci-app-passwall2  1.31-1

**Comment by Pacalini** [comment]
你的 xray 版本？domainStrategy 是什么？
最新源码下无法复现，可能跟 #640 有关。你自己编译下试试，或者等 release。

**Comment by xsj684135** [comment]
> 你的 xray 版本？domainStrategy 是什么？ 最新源码下无法复现，可能跟 #640 有关。你自己编译下试试，或者等 release。

xray是最新版本，domainStrategy不知道是啥

我刚刚测试出来 这里选择使用Sing-Box就不会出现泄漏 选择xray就会泄露

https://github.com/xiaorouji/openwrt-passwall2/issues/652#issuecomment-2363865677

**Comment by xsj684135** [comment]
自己编译我不会，我等大佬更新吧0.0

**Comment by xsj684135** [comment]
知道domainStrategy是什么了，
下面这三个我都测试过会泄露
AsIs、IPIfNonMatch、IPOnDemand

**Comment by dtknight** [comment]
你用xray内核就好了，singbox会出问题
