### ISSUE TITLE
[Feature Request]: 服务器端功能，能否在出口增加直连选项？

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#655]
### 描述你想要的新功能

海外回国用

### 描述你想要的解决方案

在出站这个选单里，增加全直连选项：
<img width="746" alt="image" src="https://github.com/user-attachments/assets/f5e5c0b8-7b75-4def-b0f7-e8a101b40b35">

如果没空编写，指引我在哪修改代码也行。感谢~

**Comment by hululu1068** [comment]
> ### 描述你想要的新功能
> 海外回国用
> 
> ### 描述你想要的解决方案
> 在出站这个选单里，增加全直连选项： <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/99887507/369791457-f5e5c0b8-7b75-4def-b0f7-e8a101b40b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODE0NTQsIm5iZiI6MTcyNzA4MTE1NCwicGF0aCI6Ii85OTg4NzUwNy8zNjk3OTE0NTctZjVlNWMwYjgtN2I3NS00ZGVmLWIwZjctZThhMTAxYjQwYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmIwNDg2NmViYWI2MTgzMWY2YWUxZTg0ZmM2ZTM0OTg0MjEzMzM0OTA2MTI0MTUyM2I0YjIwYTYzNWYyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P7MVOV7xCJKO2kFx_ph6yFiVfL3HEUTRpEfkIyIgJWI">
> 
> 如果没空编写，指引我在哪修改代码也行。感谢~
> 
> ### 描述你考虑过的替代方案
> _No response_
> 
> ### 其他信息
> _No response_

- # 自己新建个直连的节点，出站选择这个新建的不就可以了

**Comment by Travel2Here** [comment]
> > ### 描述你想要的新功能
> > 海外回国用
> > ### 描述你想要的解决方案
> > 在出站这个选单里，增加全直连选项： <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/99887507/369791457-f5e5c0b8-7b75-4def-b0f7-e8a101b40b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODE0NTQsIm5iZiI6MTcyNzA4MTE1NCwicGF0aCI6Ii85OTg4NzUwNy8zNjk3OTE0NTctZjVlNWMwYjgtN2I3NS00ZGVmLWIwZjctZThhMTAxYjQwYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmIwNDg2NmViYWI2MTgzMWY2YWUxZTg0ZmM2ZTM0OTg0MjEzMzM0OTA2MTI0MTUyM2I0YjIwYTYzNWYyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P7MVOV7xCJKO2kFx_ph6yFiVfL3HEUTRpEfkIyIgJWI">
> > 如果没空编写，指引我在哪修改代码也行。感谢~
> > ### 描述你考虑过的替代方案
> > _No response_
> > ### 其他信息
> > _No response_
> 
> * # 自己新建个直连的节点，出站选择这个新建的不就可以了

没有这个能力啊，你试试

**Comment by hululu1068** [comment]
> > > ### 描述你想要的新功能
> > > 海外回国用
> > > ### 描述你想要的解决方案
> > > 在出站这个选单里，增加全直连选项： <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/99887507/369791457-f5e5c0b8-7b75-4def-b0f7-e8a101b40b35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODE0NTQsIm5iZiI6MTcyNzA4MTE1NCwicGF0aCI6Ii85OTg4NzUwNy8zNjk3OTE0NTctZjVlNWMwYjgtN2I3NS00ZGVmLWIwZjctZThhMTAxYjQwYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA4NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmIwNDg2NmViYWI2MTgzMWY2YWUxZTg0ZmM2ZTM0OTg0MjEzMzM0OTA2MTI0MTUyM2I0YjIwYTYzNWYyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P7MVOV7xCJKO2kFx_ph6yFiVfL3HEUTRpEfkIyIgJWI">
> > > 如果没空编写，指引我在哪修改代码也行。感谢~
> > > ### 描述你考虑过的替代方案
> > > _No response_
> > > ### 其他信息
> > > _No response_
> > 
> > 
> > 
> > * # 自己新建个直连的节点，出站选择这个新建的不就可以了
> 
> 没有这个能力啊，你试试 （我指的是利用国内本机的网络直连，不是搞个VPS直连哈）

可以[私聊](https://t.me/TH3L3TH3)
