### ISSUE TITLE
功能请求: 节点列表里的URL测试,能做出一键测试吗? 点一下,测所有. 或者是同一"订阅备注(机场)"的节点可以一键测试.

### ISSUE THREAD

**Issue by niu168** [xiaorouji/openwrt-passwall2#657]
### 描述你想要的新功能

节点列表里的URL测试,能做出一键测试吗? 点一下,测所有. 或者是同一"订阅备注(机场)"的节点可以一键测试.

### 描述你想要的解决方案

节点列表里的URL测试,能做出一键测试吗? 点一下,测所有. 或者是同一"订阅备注(机场)"的节点可以一键测试.

**Comment by lwb1978** [comment]
如果你稍微了解一点工作原理就不会想提这个需求了，url测试是要启动一个新的客户端来进行连接节点后再发起测试，假如你机场有50个节点，那么就需要同时启动50个客户端连接节点，这么大的工作量，x86主机估计都会耗尽资源而挂掉，更别说哪些硬路由刷openwrt的了。

**Comment by lwb1978** [comment]
这个需求在pw1那边已经不止一次解答了。

**Comment by lwb1978** [comment]
也许有人会说可以做成列队方式，但要知道发起一个url测试要经历生成客户端配置、启动客户端、连接节点服务端、测试url链接、生成结果等这几个过程，耗时2-5秒，一个机场列队测试下来要几分钟，这样做意义不大。

**Comment by niu168** [comment]
哦,还挺复杂.
但是工作原理,我是一点都不懂,我就是单纯的使用.
