### ISSUE TITLE
[Feature Request]: UDP Noise options

### ISSUE THREAD

**Issue by Graveyard9988** [xiaorouji/openwrt-passwall2#659]
### 描述你想要的新功能

in latest pre-release of xray core, some new parameters were added (udp noise parameteres) which use as fragment for Wireguard. please add udp noise parameters in "Other Settings" tab.

regards

### 描述你想要的解决方案

.

**Comment by Pacalini** [comment]
> thanks a lot. it works could you add it in Passwall2 too(#659)

#661 Merge pending.
