### ISSUE TITLE
[Bug]: 域名解析策略`IPIfNonMatch`不生效

### ISSUE THREAD

**Issue by yfw918** [xiaorouji/openwrt-passwall2#667]
### 描述您遇到的bug

当域名解析策略设置为`IPIfNonMatch`的时候，如果某个网站没有匹配到域名规则，就会进行 dns 解析然后进行 ip 规则匹配。但是本项目生成的规则中，`routing`的最后的一个兜底规则是：
```json
      {
        "type": "field",
        "_flag": "default",
        "outboundTag": "default",
        "network": "tcp,udp"
      }
```
这会导致直接走`default`的出站而不进行 ip 规则匹配，会导致类似`geoip:cn`的规则被跳过，并且不符合`IPIfNonMatch`的设计意图

### 复现此Bug的步骤

分流总节点的默认项选择任何一个节点即会生成这样的`global.json`

### 您想要实现的目的

由于没有匹配到任何规则的时候，xray 会选择`outbounds`的第一个出站，建议删去生成配置文件中 routing 的兜底规则。当默认节点不选 default 时，`outbounds`的第一个设置为此项设置的节点。至于默认节点选 default 的话，把`freedom`放在`outbounds`的第一个就好。

### 日志信息

https://github.com/xiaorouji/openwrt-passwall2/issues/497 这个issue里有类似的问题

### 系统相关信息

- Passwall2版本：1.13.1
- Xray版本：1.8.8

**Comment by Pacalini** [comment]
#640

**Comment by yfw918** [comment]
原来已经修了，等release了
