### ISSUE TITLE
DNS解析疑似BUG

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-passwall2#68]
1、XRAY在解析节点域名时，会使用内建的DNS模块处理，可以使用域名重写功能直接定义解析IP，此时XRAY使用域名重写定义的IP连接服务器。

2、dnsmasq根据/tmp/dnsmasq.d/passwall2/10-vpsiplist_host.conf的配置，会根据WAN口定义的DNS来解析节点域名并写入ipset中的vpsiplist，并配置iptables match vpsiplist dst 直接return

1和2和配置导致解析的IP不一致，建议让所有DNS请求直接进入XRAY并让DNS模块处理，取消/tmp/dnsmasq.d/passwall2/10-vpsiplist_host.conf的配置

**Comment by xiaorouji** [comment]
先有鸡or先有蛋
有无考虑过如果进程挂了，就再也连不上了

**Comment by badgv** [comment]
> 先有鸡or先有蛋 有无考虑过如果进程挂了，就再也连不上了

大佬，如果进程挂了，按现在的模式，也只能解析节点域名，解析不了其它域名了吧？
