### ISSUE TITLE
[Feature Request]: some RU providers blocked sourceforge.net in Russia

### ISSUE THREAD

**Issue by vm-project-repo** [xiaorouji/openwrt-passwall2#685]
### 描述你想要的新功能

Could you pls change repository of Passwall2 to another resourse because some RU internet providers blocked sourceforge.net
and your resouce with PassWall2 was block:
https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-$release/$arch/$feed
Yota / MegaPhone blocked the resource

### 描述你想要的解决方案

https://alternativeto.net/software/sourceforge/ <- this is list of sourceforge alternatives

### 描述你考虑过的替代方案

better will be Github or GitLab because this not blocked for personal use
If your will choose Gitea or other selfhosted service than pls choose hosting providers not blocked in RU, for example like OVH cloud

### 其他信息

or could you pls provide user manual for another way how i can install your PassWall2 and upgrade my OrangePi R1 Plus LTS with PassWall2.
I mean without using openwrt feed:
https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-$release/$arch/$feed

I think your recommendation will be useful for many RU users, and I can replace your recommendation on my sites with a user manual translated into Russian

Best regrads,
Viktor Malygin
WordPress Developer
[https://vm-project.ru](https://vm-project.ru)
[https://vm-project.pro](https://vm-project.pro)

**Comment by xiaorouji** [comment]
This is not something I can control.

**Comment by vm-project-repo** [comment]
Will you pls to help with another way to installation ?

**Comment by vm-project-repo** [comment]
This is was my mistake your Rom not working , i can't download it after add your repo to my OrangePI R1 Plus LTS, i mean any updating process was broken!!!!
i used both terminal and web ui
