### ISSUE TITLE
[Feature Request]: Need killswitch functionality

### ISSUE THREAD

**Issue by vm-project-repo** [xiaorouji/openwrt-passwall2#686]
### 描述你想要的新功能

I need killswitch functionality for PassWall2 because in Russia we have many low level hackers, i mean this is may be my neighbors
They try to use KaliLinux or ParrotOS or another hacker OS new functionality and try to hack my router.

### 描述你想要的解决方案

I use OrangePi R1 Plus LTS without WiFi, but they have access to the RU government traffic monitoring system, and I mean it's not a good practice if the government is going to destroy the workflow of ordinary RU developers, because anyone who has access to the RU government system and has personal issues with me will try to use the RU government system for personal purposes and without the law

They use some attack that reboot my internet connection and can see my real ip and first VPN server IP, i mean that i usually use Vless->TCP->Realty->CloudFlare Wrap with domain+ssl proxy 
If you add the default KILLSWITCH functionality, that fixes the problem because the internet connection should start after the passwall2 soft is loaded on my router, that is after remotely rebooting the internet connection, i mean, my cyberstalkers reboot my router remotely

### 描述你考虑过的替代方案

I cant find any alternative 
because i found only ways for wireguard or openvpn or other technology that have specific interface, i mean like WG0(wireguard), tunn(openvpn) or DHCP-client(wired connection) and passwall2 have no any interfaces and i cant implement killswitch

### 其他信息

If you will not implement this functionality in this year than could you pls advise how i can slove the problem.
I need some reffer to resouce with info or short user manuals and i can describe this way on my website for all RU users

Best regrads,
Viktor Malygin
WordPress Developer
[https://vm-project.ru](https://vm-project.ru)
[https://vm-project.pro](https://vm-project.pro)

**Comment by xiaorouji** [comment]
Passwall only a GUI app.

**Comment by vm-project-repo** [comment]
Hi again,

Hey friend I would like to help you with you development of you application.

Give me possibility to help you with kill switch problem, because i can create one click install bash script before you will add special web interface(like WG0 ot TUNN) to oficial program code

As you know I'm web developer PRO and with openwrt not PRO
Could you pls help me and advise list of parametrs that i should to change for openwrt services and process ordering changes, i mean after rebooting all soft on the router should load before the internet connection is started...


If it dificult for you than pls advise how i can install your application on my openwrt router without sourceforge.net repo using...
this is many RU users problem and i think that sourceforge.net blocked in many countries...
