### ISSUE TITLE
[Bug]: 使用最新的immortalwrt 源码编译会报ERROR: info field 'version' has invalid value: package version is invalid

### ISSUE THREAD

**Issue by davidtall** [xiaorouji/openwrt-passwall2#688]
### 描述您遇到的bug

最新的openwrt 使用apk 包管理软件，PKG_VERSION 不能有特殊字符，否则会报ERROR: info field 'version' has invalid value: package version is invalid 的错误。
只需要把Makefile 中的
```
PKG_VERSION:=1.31-1
PKG_RELEASE:=
```
改成
```
PKG_VERSION:=1.31
PKG_RELEASE:=1
```
就能正常编译

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 截图

无

### 系统相关信息

无

**Comment by xiaorouji** [comment]
The latest version will use the time as the version number.
