### ISSUE TITLE
[Bug]: 订阅自建的订阅链接时无效

### ISSUE THREAD

**Issue by dddd64693** [xiaorouji/openwrt-passwall2#689]
### 描述您遇到的bug

项目来自https://github.com/cmliu/CF-Workers-SUB
![image](https://github.com/user-attachments/assets/33e94f76-f408-4d49-80c7-258b267f9cb9)

### 复现此Bug的步骤

见bug描述

### 您想要实现的目的

能订阅

### 日志信息

![image](https://github.com/user-attachments/assets/95676965-e294-4004-b3ea-4252b7f3718c)

### 系统相关信息

PassWall2_1.30-3_x86_64_all_sdk_22.03.7

**Comment by lwb1978** [comment]
这个并不是什么bug，你的项目是小猫咪专用链接，pw只支持通用链接

**Comment by dddd64693** [comment]
> 这个并不是什么bug，你的项目是小猫咪专用链接，pw只支持通用链接

请教一下，有没有什么项目是能生成自建节点的集合的通用链接的呀

**Comment by xiaorouji** [comment]
Please use base64 format.
