### ISSUE TITLE
开启ipv6透明代理之后，无法通过ipv6地址外网访问路由器，关闭ipv6透明代理之后就可以了

### ISSUE THREAD

**Issue by 759071793** [xiaorouji/openwrt-passwall2#69]
开启ipv6透明代理之后，无法通过ipv6地址外网访问路由器，关闭ipv6透明代理之后就可以了

**Comment by 759071793** [comment]
之前一直使用的passwall1，没有这个问题，最近换到2后，高级设置里面打开ipv6透明代理，就没办法在外网用ddns解析的ipv6域名访问路由器了，直接用ipv6地址也不能访问，关闭ipv6透明代理后就秒开

**Comment by 759071793** [comment]
找到临时解决办法了，在tcp不转发端口处写上外网要访问的端口就可以访问了，不知道为什么，，，以前都不需要

**Comment by badgv** [comment]
大概原因应该开起tproxy后，默认的prerouting或output流量的TCP流量以及UDP流量，OP在处理回复包时，只要是非内网地址，被导入xray走了一道，然后数据包回复出去的时候，源端口发生变化导致的不通。
这个应该可以采用连接标记的方式处理。

**Comment by datout** [comment]
ipv4好像也是同样问题，关闭passwall2就能外网访问进来了

**Comment by datout** [comment]
> 找到临时解决办法了，在tcp不转发端口处写上外网要访问的端口就可以访问了，不知道为什么，，，以前都不需要

请问端口填写的格式是什么，我填写了 还是不行

**Comment by xiaorouji** [comment]
试一下最新源码
