### ISSUE TITLE
[Bug]: Hysteria2节点空闲超时字段没有实际作用

### ISSUE THREAD

**Issue by yoier** [xiaorouji/openwrt-passwall2#693]
### 描述您遇到的bug

由于Hysteria2配置文档中quic>maxIdleTimeout字段不是数字(~30~ 30s)，因此在添加hysteria2节点时空闲超时字段填写数字会导致节点不可用。

### 复现此Bug的步骤

1.添加hysteria2节点，2.选中空闲超时字段，3.填写30，4.保存并应用，5.出现Bug，配置文件生成"maxIdleTimeout": 30,导致节点不可用，6.重新修改空闲超时字段为30s，保存并应用，7.节点可用，但生成的配置文件里没有maxIdleTimeout字段。

### 您想要实现的目的

空闲超时字段填写30，配置文件生成30s
![image](https://github.com/user-attachments/assets/b3690f63-4204-424f-a779-443bb1e13b4e)

### 日志信息

null

### 系统相关信息

luci-app-passwall2  1.31-1

### 其他信息

![image](https://github.com/user-attachments/assets/8f42ee27-987b-4111-8c11-7777629778a3)
![image](https://github.com/user-attachments/assets/af437be3-e3c5-48fc-81cf-e9b6086efa59)

**Comment by lwb1978** [comment]
maxIdleTimeout除了用秒做单位还有其他吗？没用过不熟悉。确认后我先在pw1那边修改。

**Comment by yoier** [comment]
Hysteria2配置中maxIdleTimeout一般都是秒做单位，源码里定义的time.Duration类型。
![image](https://github.com/user-attachments/assets/c5cbe4f7-b118-4a1c-a798-93b0ea234ab3)
maxIdleTimeout指定了范围在4s-120s。
![image](https://github.com/user-attachments/assets/2c41e579-d180-43f2-beb2-1fc7a63a2621)
不太熟悉go大佬可以自己看看[hysteria/core/client/config.go](https://github.com/apernet/hysteria/blob/master/core/client/config.go)

**Comment by yoier** [comment]
我刚测试了以下，不填单位的话默认是纳秒，填写30000000000，节点可以正常使用。单位有ns,us,ms,s,m,h。
![image](https://github.com/user-attachments/assets/d3e3d54e-9590-41af-9b2a-21d40ae7a976)
![image](https://github.com/user-attachments/assets/bfef9ecc-6b36-47b0-9d96-ce504a4d4268)
![image](https://github.com/user-attachments/assets/56282899-dfd3-40c5-8747-ac7d6bfd1cf6)

**Comment by yoier** [comment]
这个跟端口跳跃的类型是一样的，希望能统一 一下。

**Comment by lwb1978** [comment]
我在pw1已经修改代码，等待 @xiaorouji 同步过来吧。

**Comment by yoier** [comment]
已修复，感谢
