### ISSUE TITLE
[Bug]: 默认节点选择直连时，会默认使用第一个outbound作为出口，不符合直连预期

### ISSUE THREAD

**Issue by morooi** [xiaorouji/openwrt-passwall2#694]
### 描述您遇到的bug

查看 /tmp/etc/passwall2/acl/default/global.json 配置文件
当默认节点选择直连时，会默认使用第一个outbound作为出口，而 freedom direct 为倒数第二个 outbound，会导致默认会走到第一个分流规则选择的节点上，不符合直连预期。

### 复现此Bug的步骤

1. 节点使用 Xray 分流总节点
2. 随意添加一个分流规则，选择出口节点 A
3. 默认节点选择直连
4. 访问分流规则之外的域名，查看日志走的是 [2] 中添加的分流规则-节点 A

### 您想要实现的目的

预期 -> 如果默认节点选择直连，outbounds 第一个应该是直连

### 日志信息

日志略，可直接复现

### 系统相关信息

passwall2: 24.11.17-r1

**Comment by lwb1978** [comment]
@Pacalini Xray配置你比较熟悉，有空的话看看。

**Comment by xiaorouji** [comment]
[util_xray.zip](https://github.com/user-attachments/files/17789307/util_xray.zip)
解壓縮後替換 `/usr/lib/lua/luci/passwall2/util_xray.lua` 後重啟試試

**Comment by xiaorouji** [comment]
順便測測 sing-box 的是否正常？
sing-box 的默認出口是由 `router.final`

**Comment by Pacalini** [comment]
> [util_xray.zip](https://github.com/user-attachments/files/17789307/util_xray.zip) 解壓縮後替換 `/usr/lib/lua/luci/passwall2/util_xray.lua` 後重啟試試

Xray 我试了下 没问题了

**Comment by morooi** [comment]
> [util_xray.zip](https://github.com/user-attachments/files/17789307/util_xray.zip) 解壓縮後替換 `/usr/lib/lua/luci/passwall2/util_xray.lua` 後重啟試試

替换后正常了 👍


> 順便測測 sing-box 的是否正常？ sing-box 的默認出口是由 `router.final`

试了下 sing-box 分流，没问题是正常的

**Comment by mofanxt** [comment]
[这次 commit](https://github.com/xiaorouji/openwrt-passwall2/commit/d89633c2cb0e6a15e92cb8462de9628fdb0b481f) 之后，默认分流选择的是负载均衡节点，xray dns 默认的规则变成了直连，导致 dns 解析代理规则下的域名会走到国内dns

```
    "dns": {
      "disableFallback": true,
      "queryStrategy": "UseIP",
      "disableFallbackIfMatch": true,
      "servers": [
        {
          "queryStrategy": "UseIP",
          "port": 15354,
          "_flag": "default",
          "address": "127.0.0.1"
        },
...
```

原来是：
```
    "dns": {
      "disableFallback": true,
      "queryStrategy": "UseIP",
      "disableFallbackIfMatch": true,
      "servers": [
        {
          "queryStrategy": "UseIP",
          "port": 53,
          "_flag": "default",
          "address": "1.1.1.1"
        },
...
```
