### ISSUE TITLE
[Bug]: Sing-box 与 Xray-core 规则匹配问题.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#700]
### Describe the Bug you encountered

![image](https://github.com/user-attachments/assets/f0b3d39b-6528-4361-85b6-f89ec9b5d71f)
Direct存在:`domain:push.apple.com`
Proxy存在:`geosite:geolocation-!cn`

### Xray使用`Loyalsoldier`规则, Sing-box使用`lyc8503`规则, lyc8503的规则是从Loyalsoldier移植的.
***
### Steps to reproduce this Bug

........

### Log information

......

### System related information

passwall2: 24.11.19-r1
OpenWrt: OpenWrt main分支.

**Comment by Travel2Here** [comment]
我也曾遇到一模一样的困惑，就是这些怪问题 让我从SB回退到XRAY了，再也不手贱。

**Comment by xiaoshengshuohua** [comment]
> 我也曾遇到一模一样的困惑，就是这些怪问题 让我从SB回退到XRAY了，再也不手贱。

是Xray分流有问题, 为什么你会从Sing-box退到Xray.

**Comment by Travel2Here** [comment]
> > 我也曾遇到一模一样的困惑，就是这些怪问题 让我从SB回退到XRAY了，再也不手贱。
> 
> 
> 
> 是Xray分流有问题, 为什么你会从Sing-box退到Xray.

我看反了，😆，反正之前有版本sb分流会漏我就退回去了，主要是漏openai相关的

**Comment by xiaorouji** [comment]
可能是 geosite 包含apple的域名。且用了 full: 匹配。
full 的優先級是最高的

**Comment by xiaoshengshuohua** [comment]
> 
> 我看反了，😆，反正之前有版本sb分流会漏我就退回去了，主要是漏openai相关的

漏openai是什么表现.

**Comment by Travel2Here** [comment]
> > 
> 
> > 我看反了，😆，反正之前有版本sb分流会漏我就退回去了，主要是漏openai相关的
> 
> 
> 
> 漏openai是什么表现.

…那不就是跟直连一个效果？😂拒绝服务啊

**Comment by xiaoshengshuohua** [comment]
> 
> …那不就是跟直连一个效果？😂拒绝服务啊

貌似没有遇到过.

会不会是上面这种情况, 域名只有A或AAAA记录, 导致空响应回退到直连DNS服务器查询了.
