### ISSUE TITLE
[Bug]: cant download your feed

### ISSUE THREAD

**Issue by vm-project-repo** [xiaorouji/openwrt-passwall2#702]
### Describe the Bug you encountered

My previos Issue about RU providers that bloked your soft feeds was mistake because problem only with feed for ARM RockChip devices 

My default openwrt devices
https://firmware-selector.openwrt.org/?version=23.05.5&target=rockchip%2Farmv8&id=xunlong_orangepi-r1-plus-lts
or
https://firmware-selector.openwrt.org/?version=23.05.5&target=rockchip%2Farmv8&id=friendlyarm_nanopi-r4s

And i use your installation user manual
https://github.com/Ramtiiin/install-passwall2-openwrt?ysclid=m3tfsdiq6k202066617

### Steps to reproduce this Bug

after comand from step7 is run, then i can see following problem...
![Screenshot_2024-11-23_04-44-16](https://github.com/user-attachments/assets/e5e6cb93-f310-4cc9-90e7-3a7fbae19118)
and i have same result in web ui
![Screenshot_2024-11-23_04-46-24](https://github.com/user-attachments/assets/8e2a959e-6bfc-489e-bb8e-779dfd5eb203)
I try to run your soft on my OrangePi R1 Plus LTS and NanoPi R4S 
This device with ARM RockChip
Could you pls check your repo with build for ARM RockChip devices i think that all ARM RockChip devices have same problem

### What you want to implement

you ARM RockChip devices repo need bug fixing

### Log information

Could you pls check:
https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-$release/$arch/$feed

### Screenshot

![Screenshot_2024-11-23_04-44-16](https://github.com/user-attachments/assets/ef507152-e38d-472b-892b-9c01ef412eff)
![Screenshot_2024-11-23_04-46-24](https://github.com/user-attachments/assets/030fafd7-a498-41c6-8066-e5724e4406a8)

### System related information

Mozilla Firefox 132.0.2
OrangePi R1 Plus LTS
NanoPi R4S

**Comment by Pacalini** [comment]
> And i use your installation user manual
> https://github.com/Ramtiiin/install-passwall2-openwrt?ysclid=m3tfsdiq6k202066617

You should ask the guy who wrote that or someone who's maintaining that sourceforge repo.
