### ISSUE TITLE
[Bug]: 访问控制设置XBOX所有端口不转发后，无法联网，无法进入XBOX商城，无法同步游戏存档。

### ISSUE THREAD

**Issue by lu989898** [xiaorouji/openwrt-passwall2#705]
### Describe the Bug you encountered

设置所有端口不转发后应走直连出口

### Steps to reproduce this Bug

![image](https://github.com/user-attachments/assets/c731d53a-8fed-42f4-9f09-fa8de9c43396)

### What you want to implement

不转发设备正常走直连出口。

### Log information

无log

### System related information

luci-23.05_luci-app-passwall2_24.11.19_all

**Comment by xiaorouji** [comment]
嘗試最新的代碼。
