### ISSUE TITLE
能否把分流最后的“默认”功能拆分下

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-passwall2#71]
拆分成“默认配置”和“默认代理”
默认配置：仅用来进行选择节点，以供上面的各种分流使用，不修改xray的routing分流行为。
可以选：直连，黑洞，各节点单独配置。
![image](https://user-images.githubusercontent.com/45598380/163742519-a3eb7a57-9ff6-47d5-a936-30e8bf2555dd.png)

默认代理：用来定义xray的routing分流行为。
可以选：直连，黑洞，默认配置，各节点单独配置

自动切换：
可以直接设置默认代理或默认配置或前置代理
![image](https://user-images.githubusercontent.com/45598380/163742767-54226c8c-9762-4a48-a73b-d75dffd450f4.png)

主要是现在的默认如果选择“直连”的情况下，自动切换没办法使用了:)

**Comment by kukuci** [comment]
主要是现在的默认如果选择“直连”的情况下，自动切换没办法使用了,这个问题确实存在，也困扰我好久，希望可以增加一个应用与proxy节点的选项。这样更灵活。

**Comment by MikoyChinese** [comment]
+1
