### ISSUE TITLE
[Bug]: Hysteria v1 url need to be replaced 

### ISSUE THREAD

**Issue by Lioncky** [xiaorouji/openwrt-passwall2#710]
### Describe the Bug you encountered

hysteria v1 legency version should using this url
`https://api.github.com/repos/apernet/hysteria/releases/tags/v1.3.5`
Two version should be seperated.

passwall2 build with this version can't get version even if put the file into the usr/bin/hysteria.

### Steps to reproduce this Bug

`

### What you want to implement

`

### Log information

`

### Screenshot

![image](https://github.com/user-attachments/assets/c70321d5-a7f1-444e-949c-382d5190fa55)

### System related information

passwall2 ver: 1.18-1

**Comment by xiaorouji** [comment]
No longer supports v1.

**Comment by Lioncky** [comment]
I think v1 is needed and nolonger update and it's still useful, just seperate them.
