### ISSUE TITLE
[Bug]: 节点正常连接大概一天左右或者一天不到会自动失去连接。

### ISSUE THREAD

**Issue by ssswww0004** [xiaorouji/openwrt-passwall2#716]
### Describe the Bug you encountered

在节点确认是正常的情况下（能够正常连接和使用），passwall2只能正常连接1天或者1天不到，就会在谷歌链接测试哪里显示无法连接，百度连接是正常的，但是节点确实是正常的，没有任何问题，这时不管换不换节点，都只有点击保存并应用，才能够重新连接并正常使用，并且要2次点击保存并应用，点一次好像并没有什么效果，只有第二次再点击保存并应用才能起效果。曾经选择passwall2恢复默认配置过，但是问题仍然会同样出现！

### Steps to reproduce this Bug

重新正常连接过后，一天左右或者一天内必然出现。

### What you want to implement

能够正常的工作，保持连接

### Log information

日志信息看不出来

### Screenshot
![image](https://github.com/user-attachments/assets/f8a7d005-2ced-433a-b2af-95632dc43e70)

![image](https://github.com/user-attachments/assets/25353d7e-c4dc-494f-818f-d7cc82468ee6)

**Comment by ssswww0004** [comment]
我现在暂时换用passwall，已经2天了，暂时没有出现问题！

**Comment by zjmsjla** [comment]
我也遇到了，我不需要一天，现在几小时就能断网

**Comment by zjmsjla** [comment]
> 我也遇到了，我不需要一天，现在几小时就能断网

已经没事了，禁用缓存，passwall2和sing-box更新到最新，我不确定是哪一点起作用了

**Comment by YEUNGWAIPANG** [comment]
> > 我也遇到了，我不需要一天，现在几小时就能断网
> 
> 已经没事了，禁用缓存，passwall2和sing-box更新到最新，我不确定是哪一点起作用了

请问禁用缓存是禁用哪里啊？我现在也会有同样的情况但是更新到最新也无用
