### ISSUE TITLE
[Bug]: 安卓Webrtc泄漏

### ISSUE THREAD

**Issue by DamonLee35** [xiaorouji/openwrt-passwall2#717]
### Describe the Bug you encountered

连接ipv6节点，安卓系统使用edge和chrome浏览器会导致webrtc泄漏本地ipv6地址，此问题会导致微软此copilot出现连接错误（可能使用webrtc检测代理），其他可能使用webrtc检测代理的服务可能也没法用

### Steps to reproduce this Bug

安卓手机使用edge和chrome浏览器打开https://ipleak.net/

### What you want to implement

webrtc检测不出现本地ipv6

### Log information

无

### System related information

passwall2 24.12.05
edge 131.0.2903.68
chrome 131.0.6778.81
安卓 14

**Comment by DamonLee35** [comment]
![Screenshot_2024-12-22-10-09-06-152_com microsoft emmx](https://github.com/user-attachments/assets/614d0555-8874-4e37-8d7e-6de9cca1a898)
最新版本还是会泄漏

**Comment by Laitinlok** [comment]
Same issue
