### ISSUE TITLE
[Bug]: 无法运行

### ISSUE THREAD

**Issue by LinusChen-yf** [xiaorouji/openwrt-passwall2#719]
### Describe the Bug you encountered

保存并运行之后显示core未运行 

### Steps to reproduce this Bug

---

### What you want to implement

---

### Log information

Xray 1.8.3 (Xray, Penetrates Everything.) OpenWrt (go1.19.13 linux/arm64)
A unified platform for anti-censorship.
2024/12/06 17:05:08 [Info] infra/conf/serial: Reading config: /tmp/etc/passwall2/acl/default/global.json
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/acl/default/global.json] > infra/conf: unknown router rule type:

### System related information

version：luci-23.05_luci-app-passwall2_24.12.05_all

**Comment by xiaorouji** [comment]
Xray 內核版本太舊了。
