### ISSUE TITLE
Cloudflare DOH无法解析 Twitch，TCP正常.

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall2#72]
2022/04/18 15:50:04[Error] app/dns: failed to retrieve response for cvp.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled
2022/04/18 15:50:04 [Error] app/dns: failed to retrieve response for irc-ws.chat.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled
2022/04/18 15:50:04 [Error] app/dns: failed to retrieve response for passport.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled
2022/04/18 15:50:04 [Error] app/dns: failed to retrieve response for passport.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled
2022/04/18 15:50:04 [Error] app/dns: failed to retrieve response for irc-ws.chat.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled
2022/04/18 15:50:04 [Error] app/dns: failed to retrieve response for cvp.twitch.tv. > Post "https://1.1.1.1/dns-query": context canceled

还有DNS协议不支持 
```
::1#Port
```

**Comment by xiaorouji** [comment]
干嘛要用IPv6的地址呢？

**Comment by yunxi993** [comment]
> 干嘛要用IPv6的地址呢？

好吧，那不用了.

gstatic.com这个域名在Proxy里面，但是实际上却走了直连：
fonts.gstatic.com   203.208.50.66
ssl.gstatic.com       203.208.50.66
www.gstatic.com   203.208.50.34
![image](https://user-images.githubusercontent.com/59167936/163805159-c7732862-ac8f-443c-90f3-d6b27e7051e4.png)

**Comment by yunxi993** [comment]
是 `gstatic.com` 在 geosite:cn 里面的原因吗？

**Comment by xiaorouji** [comment]
https://github.com/v2fly/domain-list-community/blob/master/data/google
看起来是的，full优先级最高

**Comment by yunxi993** [comment]
```
geosite:google
```
加入到 Proxy，`gstatic` 连接非中国IP.
