### ISSUE TITLE
[Bug]: unstability issue after firewall optimization

### ISSUE THREAD

**Issue by Mit0chrondr1a** [xiaorouji/openwrt-passwall2#720]
### Describe the Bug you encountered

unstable after upgrading to [24.12.05-1] from previous [24.11.19-2], i guess it was the firewall code optimization

### Steps to reproduce this Bug

/

### What you want to implement

/

### Log information

/

### System related information

/

**Comment by xiaorouji** [comment]
The description is not understand, how be unstable?

**Comment by xiaorouji** [comment]
Try the latest version first.
