### ISSUE TITLE
[Bug]: 23.05不会显示配置应用的进度

### ISSUE THREAD

**Issue by yuyu913gzs** [xiaorouji/openwrt-passwall2#726]
### Describe the Bug you encountered

23.05不会显示配置应用的进度

### Steps to reproduce this Bug

23.05不会显示配置应用的进度

### What you want to implement

23.05不会显示配置应用的进度

### Log information

23.05不会显示配置应用的进度

### System related information

passwall2 12.05-1

**Comment by xiaorouji** [comment]
和邏輯上合理。
