### ISSUE TITLE
[Feature Request]: 允许不下载不需要的内核或规则集

### ISSUE THREAD

**Issue by zjmsjla** [xiaorouji/openwrt-passwall2#727]
### Describe the new feature you want

因为我全部用sing-box，完全不使用xray或其他内核，所以V2ray的规则集和xray内核对我来说是多余的，因此想着能不能安装时不默认下载xray内核和V2ray规则集，并且将sing-box的规则更新从现在的V2ray那里分离出来，让sing-box和其他内核完全分开，从而节省点空间

### Describe the solution you want

1、安装时不默认下载任何内核，不默认下载任何规则，由自己选择
2、将sing-box的规则集更新另设一套控制开关

**Comment by xiaorouji** [comment]
自行修改 Makefile
