### ISSUE TITLE
端口映射无法访问

### ISSUE THREAD

**Issue by datout** [xiaorouji/openwrt-passwall2#73]
映射的端口在外网没法访问，关闭passwall2就没问题了。
在tcp不转发端口加上也没用。但是不转发所有却可以。

**Comment by datout** [comment]
编译更新了一版好像好了。

**Comment by xiaorouji** [comment]
试一下最新源码

**Comment by ritech** [comment]
新版本貌似解决了映射

**Comment by badgv** [comment]
看了下新版本的iptables处理过程，接道理说，应该是只解决了OP自身监听端口的公网访问问题，我OP自己监听了个8888的UDP，之前需要手动添加到不代理端口里面才通，现在不需要添加这个了。

端口映射到内网的数据包看iptables处理过程，NEW包进来的时候，在prerouting能匹配 dst laniplist，能直接return，但是内网数据包回复的时候，如果没有对LAN做masquerade，数据包在prerouting会被导打上TPROXY标记导入xray，导致可能不通（我OP是旁路模式，不用使用OP做端口映射，这个没具体测试过）

按理说应该还要添加下以下配置：
iptables -t mangle -N PSW2_CTMARK  #新建一个chain处理来自公网的访问端口映射的数据包标记
iptables -t mangle -A PSW2_CTMARK -j CONNMARK --restore-mark
iptables -t mangle -A PSW2_CTMARK -m mark ! -- mark 0 -j RETURN
iptables -t mangle -A PSW2_CTMARK -m addrtype --dst-type LOCAL -j MARK --set-mark 255 #要使用addrtype应该要添加个iptables-mod-extra的依赖包，使用这条后，端口映射的包，会打上0xff标记。
iptables -t mangle -A PSW2_CTMARK -j CONNMARK --save-mark

iptables -t mangle -I PREROUTING -i !lo -j PSW2_CTMARK #插入mangle prerouting第一条

#下面这条针对现在的源码可用可不用
iptables -t mangle -I OUTPUT -j PSW2_CTMARK

**Comment by xiaorouji** [comment]
最新源码应该正常了

**Comment by badgv** [comment]
> 最新源码应该正常了

大佬，我编译了一个最新源码，我看了下iptables规则，现在的规则，如果是端口映射，所有入站数据在PSW规则里面第一条，会直接匹配laniplist而直接return，内网主机回复的数据包，再次进入prerouting，会进入PSW2_RULE打上0x01标记，被导入xray处理，感觉和我上面写的思路不太一样，我上面思路是，端口映射进入的数据，打上0xff标记，再保存到连接，内网主机回复进OP的数据包，根据连接标记还原0xff标记，会绕过xray的处理，能保证数据是通的

**Comment by badgv** [comment]
> 最新源码应该正常了

好像现在的策略应该可以了，数据包回复的时候，匹配不了new或是tcp状态，不会被导入xray
