### ISSUE TITLE
[Bug]: luci-23.05 24.12.12 DNS泄露

### ISSUE THREAD

**Issue by wuwei-yu** [xiaorouji/openwrt-passwall2#730]
### Describe the Bug you encountered

分流或者全局，都存在DNS泄露问题，ipv6。
24.12.5版本正常

### Steps to reproduce this Bug

无

### What you want to implement

无

### Log information

无

### System related information

luci-23.05 24.12.12

**Comment by dogchild** [comment]
同样的情况，回退就没问题。12.12DNS环节改动的问题。

**Comment by xiaorouji** [comment]
把 `/tmp/etc/passwall2/acl/default/dnsmasq.conf` 和 `/tmp/etc`目錄下的`dnsmasq.conf.`開頭的文件發上來看看

**Comment by xiaorouji** [comment]
是否自行開啟了 Dnsmasq的 DNS劫持？
輸入 iptables -t nat -nvL 看看

**Comment by dogchild** [comment]
我多次测试以后发现，需要dnsmasq的劫持关掉，并且不能使用adghome和mosdns的转发才能不泄露。
12.05没这个问题，可以开劫持，也可以开adgh或者mosdns，12.12版本劫持关了也不行，必须还要不能使用adgh类软件。

**Comment by xiaorouji** [comment]
@wuwei-yu 是否使用了自定義DNS？

**Comment by wuwei-yu** [comment]
> @wuwei-yu 是否使用了自定義DNS？

直连DNS为：192.168.30.1
远程DNS为：1.1.1.1 udp
开启了fakeDNS
没开启dnsmasq DNS 重定向
没有其他插件

**Comment by xiaorouji** [comment]
@wuwei-yu 試試這個。
https://github.com/xiaorouji/openwrt-passwall2/issues/718#issuecomment-2543076533

**Comment by xiaorouji** [comment]
@dogchild 你也試試

**Comment by dogchild** [comment]
OK了，方法有效，adgh可以开了。

**Comment by xiaorouji** [comment]
沒問題我就 commit 。

**Comment by wuwei-yu** [comment]
> @wuwei-yu 試試這個。 [#718 (comment)](https://github.com/xiaorouji/openwrt-passwall2/issues/718#issuecomment-2543076533)

14版本测试正常

**Comment by ourines** [comment]
https://github.com/ourines/GateShift/pull/1

**Comment by Aluan1996** [comment]
> OK了，方法有效，adgh可以开了。

怎么解决？我的passwall更新了最新版，结果ADG不能拦截了
