### ISSUE TITLE
[Bug]: geoview依赖缺少

### ISSUE THREAD

**Issue by binge8** [xiaorouji/openwrt-passwall2#731]
### Describe the Bug you encountered

编译警告 WARNING: Makefile 'package/openwrt-packages/luci-app-passwall2/Makefile' has a dependency on 'geoview', which does not exist

### Steps to reproduce this Bug

正常拉取，make menuconfig 就提示

### What you want to implement

无

### Log information

WARNING: Makefile 'package/openwrt-packages/luci-app-passwall2/Makefile' has a dependency on 'geoview', which does not exist

### System related information

passwall2 最新代码

**Comment by lwb1978** [comment]
编译从基本功学起，你都没添加依赖仓库，当然缺少依赖
https://github.com/xiaorouji/openwrt-passwall-packages

**Comment by binge8** [comment]
> 编译从基本功学起，你都没添加依赖仓库，当然缺少依赖
> https://github.com/xiaorouji/openwrt-passwall-packages

基什么本功啊还基本功，没加的话会只报缺这一个吗

**Comment by lwb1978** [comment]
> > 编译从基本功学起，你都没添加依赖仓库，当然缺少依赖
> > https://github.com/xiaorouji/openwrt-passwall-packages
> 
> 基什么本功啊还基本功，没加的话会只报缺这一个吗

说得好像我们免费开发还欠你似的。

**Comment by binge8** [comment]
> > > 编译从基本功学起，你都没添加依赖仓库，当然缺少依赖
> > > https://github.com/xiaorouji/openwrt-passwall-packages
> > 
> > 
> > 基什么本功啊还基本功，没加的话会只报缺这一个吗
> 
> 说得好像我们免费开发还欠你似的。

抱歉我的锅，依赖库确实安装了，但正好把这个依赖过滤掉了，基本功有问题
