### ISSUE TITLE
使用非wan下发的dns时，网络不通（12-14版）

### ISSUE THREAD

**Issue by Travel2Here** [xiaorouji/openwrt-passwall2#735]
### Describe the Bug you encountered

如果在dnsmasq里设置了自定义dns，启用本软件后国内网络不通。且首页百度连接测试也表现为不通。

### Steps to reproduce this Bug

…

### What you want to implement

…

### Log information

…

### System related information

…

**Comment by xiaorouji** [comment]
無法復現。

**Comment by Travel2Here** [comment]
> 無法復現。

我一着急写错了，是wan接口设置里使用自定义dns
![image](https://github.com/user-attachments/assets/13aa2818-0c4f-4ead-b31b-96d9843c6080)

**Comment by xiaorouji** [comment]
無法復現。

**Comment by Travel2Here** [comment]
这么神？那再补充下环境：
我用的xray分流的，最新版24.12.15；昨晚pw2也更新到最新版12.16-2了依旧不行。
dnsmasq是2.88.
Openwrt是lede的老luci版~
升级的方式刷新的pw2.没有重置过配置~

**Comment by swxk521** [comment]
> 这么神？那再补充下环境：
> 
> * 我用的xray分流的，最新版24.12.15；
> * 单独安装了你包里的 geoview 及chinadns-ng ipk
> * 开启了最新的能力  Geo 数据解析；
> * dnsmasq是2.88.
> * Openwrt是lede的老luci版~
> * 升级方式是上传ipk刷新的pw2.没有重置过配置~
> 
> 昨晚pw2也更新到最新版12.16-2了依旧不行。

找找其他原因吧，同样lede,老版luci测试没问题
![Uploading Screenshot_2024-12-18-17-37-19-566_com.android.chrome.jpg…]()

**Comment by mofanxt** [comment]
我也有类似的问题，但和 wan 配置无关，我这边是勾选了 [直连 DNS 解析结果写入到 IPSet ]但没有chinadns-ng启动

**Comment by mofanxt** [comment]
我在 dnsmasq 打开DNS 重定向就好了，看起来passwall2在dnsmasq的重定向没打开的时候会使用chinadns-ng，而我本地chinadns-ng版本有问题无法正常的被passwall2拉起，打开dnsmasq 的DNS重定向后就不会使用chinadns-ng了

**Comment by swxk521** [comment]
> 我也有类似的问题，但和 wan 配置无关，我这边是勾选了 [直连 DNS 解析结果写入到 IPSet ]但没有chinadns-ng启动

https://github.com/xiaorouji/openwrt-passwall2/issues/728

**Comment by dawxy** [comment]
> 我也有类似的问题，但和 wan 配置无关，我这边是勾选了 [直连 DNS 解析结果写入到 IPSet ]但没有chinadns-ng启动

哦哦 我这里原因是装了低版本chinadns ng 换新版就好了

**Comment by mofanxt** [comment]
> 我也有类似的问题，但和 wan 配置无关，我这边是勾选了 [直连 DNS 解析结果写入到 IPSet ]但没有chinadns-ng启动

我这个是由于本地之前装了一个3.7日的 chinadns-ng，这个版本好像不兼容 passwall2 传入的参数，所以导致国内dns失败，升级chinadns-ng后就好了

**Comment by mofanxt** [comment]
> 这么神？那再补充下环境：
> 
> * 我用的xray分流的，最新版24.12.15；
> * 单独安装了你包里的 geoview 及chinadns-ng ipk
> * 开启了最新的能力  Geo 数据解析；
> * dnsmasq是2.88.
> * Openwrt是lede的老luci版~
> * 升级方式是上传ipk刷新的pw2.没有重置过配置~
> 
> 昨晚pw2也更新到最新版12.16-2了依旧不行。

你这边可以看看监听 15354 端口的进程是不是没启动
