### ISSUE TITLE
[Bug]: 没有代理时, 节点地址为域名URL测试超时, 代理时URL测试正常.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [xiaorouji/openwrt-passwall2#736]
### Describe the Bug you encountered

没有代理时, 节点地址为域名URL测试超时, 代理时URL测试正常.

若节点为IP地址, 没有代理时URL测试正常.

### Steps to reproduce this Bug

没有代理时, 节点地址为域名URL测试超时, 代理时URL测试正常.

若节点为IP地址, 没有代理时URL测试正常.

### What you want to implement

...

### Log information

...

### Screenshot

...

### System related information

Passwall2: 24.12.16-r1

**Comment by xiaoshengshuohua** [comment]
改版之前没有开启代理, URL测试节点地址为域名或IP地址均以节点连通性为基础.

Sing-box订阅.

**Comment by xiaorouji** [comment]
没有代理时（和passwall2一切無關係），域名超時。本地DNS沒配置正確。

**Comment by xiaoshengshuohua** [comment]
> 没有代理时（和passwall2一切無關係），域名超時。本地DNS沒配置正確。

本地DNS是正常的, 没代理时可以正常访问国内域名.

可能我表达有误, 节点是正常可用的, 没代理时如果节点地址为域名, 那么URL测试超时, 代理时URL测试正常显示延迟.

在我没代理时URL测试超时, 同时在itdog使用我正在使用的DNS测试节点地址的域名, 所有省份正常.

并不影响使用, 只是报告有这个问题.
