### ISSUE TITLE
[Bug]: immortalWrt 编译报错

### ISSUE THREAD

**Issue by cjlhll** [xiaorouji/openwrt-passwall2#738]
### Describe the Bug you encountered

之前正常，最近编译一直报错，
 make[3] -C feeds/luci/modules/luci-mod-admin-full compile
 make[3] -C feeds/luci/modules/luci-compat compile
 make[3] -C feeds/luci/libs/luci-lib-ipkg compile
 make[3] -C package/passwall2/luci-app-passwall2 compile
 make[3] -C feeds/luci/collections/luci-light compile
 make[3] -C feeds/luci/collections/luci compile
 make[3] -C package/emortal/default-settings compile
 make[3] -C feeds/packages/net/shadowsocks-rust compile
 make[2] package/install
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:248: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[3] diffconfig buildversion feedsversion
 make[4] scripts/config/conf
 make[2] package/cleanup

### Steps to reproduce this Bug

1、正常github actions编译流程
2、添加passwall2插件

### What you want to implement

正常编译

### Log information

 make[3] -C feeds/luci/modules/luci-mod-admin-full compile
 make[3] -C feeds/luci/modules/luci-compat compile
 make[3] -C feeds/luci/libs/luci-lib-ipkg compile
 make[3] -C package/passwall2/luci-app-passwall2 compile
 make[3] -C feeds/luci/collections/luci-light compile
 make[3] -C feeds/luci/collections/luci compile
 make[3] -C package/emortal/default-settings compile
 make[3] -C feeds/packages/net/shadowsocks-rust compile
 make[2] package/install
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:248: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[3] diffconfig buildversion feedsversion
 make[4] scripts/config/conf
 make[2] package/cleanup

### System related information

openwrt ubuntu20

**Comment by lwb1978** [comment]
make[3] -C package/passwall2/luci-app-passwall2 compile
pw都成功编译了，关pw啥事？

**Comment by xiaorouji** [comment]
1: It has nothing to do with passwall2
2: make -r world: build failed. Please re-run make with `-j1 V=s` or `V=sc` for a higher verbosity level to see what's going on
