### ISSUE TITLE
[Bug]: PW1卸载后，PW2主开关失效

### ISSUE THREAD

**Issue by cnjerry828** [xiaorouji/openwrt-passwall2#739]
### Describe the Bug you encountered

我之前在iStoreOS中安装过passwall，这几天才安装pw2。PW2调试正常后，就把PW1卸载了，却发现PW2的主开关失效。后来把PW1重新安装回去后，PW2的主开关正常了。是什么原因呢？

### Steps to reproduce this Bug

在iStoreOS的 系统-软件包 中卸载passwall，passwall2的主开关失效，勾选后保存核心未正常启动。通过命令/etc/init.d/passwall2 restart，核心可以运行。取消主开关勾选后保存，核心不会停止，仍然在运行。

### What you want to implement

卸载passwall后，passwall2的主开关仍正常

### Log information

日志显示正常

### System related information

passwall2 24.12.16
passwall 24.12.17

**Comment by MadMaxPayneNeo** [comment]
这俩很多共同依赖包，你卸载passwall时会一起卸载掉，想只保留passwall2下载完整依赖包reinstall

**Comment by MadMaxPayneNeo** [comment]
> > 这俩很多共同依赖包，你卸载passwall时会一起卸载掉，想只保留passwall2下载完整依赖包reinstall
> 
> 我上面没表述清楚。卸载了PW1后发现PW2的主开关失效，我重新安装过PW2，但主开关仍失效。尝试把PW2卸载再重新安装，主开关依然失效。不得已尝试把PW1安装回去，主开关才正常了。

geosite和geoip库没了

**Comment by cnjerry828** [comment]
> > > 这俩很多共同依赖包，你卸载passwall时会一起卸载掉，想只保留passwall2下载完整依赖包reinstall
> > 
> > 
> > 我上面没表述清楚。卸载了PW1后发现PW2的主开关失效，我重新安装过PW2，但主开关仍失效。尝试把PW2卸载再重新安装，主开关依然失效。不得已尝试把PW1安装回去，主开关才正常了。
> 
> geosite和geoip库没了

我用sing-box内核的。高级设置中有这么段说明啊？
Sing-Box 会在启动时自动下载资源文件，您可以使用此功能实现升级资源文件。

**Comment by cnjerry828** [comment]
重新安装了新版本，主开关失效的问题解决了。

**Comment by xiaorouji** [comment]
> 重新安装了新版本，主开关失效的问题解决了。

並沒有任何關係。

**Comment by zakizou** [comment]
我同时安装了passwall和passwall2，passwall2界面主开关无效，/etc/init.d/passwall2 start有用，文件权限一样
root@ImmortalWrt:/etc/init.d# ls -l /etc/init.d/passwall /etc/init.d/passwall2
-rwxr-xr-x    1 root     root          1290 Sep 27  2024 /etc/init.d/passwall
-rwxr-xr-x    1 root     root          1291 Jan 27  2025 /etc/init.d/passwall2
