### ISSUE TITLE
完全不能用咯…

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall2#74]
这个悲伤的issue还是让我来提吧…
在更新完最新的[022a565](https://github.com/xiaorouji/openwrt-passwall2/commit/022a5656e322180f60eea7567d4e080f84b6f8b6)后……
就是这么悲伤的故事……
完全不能用了……
重置完后完全保持默认设置（只改了tproxy）
【百度链接】与【谷歌链接】也都是测试失败……
实际测试能上去谷歌…
然后别的都上不去=。=
大佬加油……

**Comment by badgv** [comment]
还没编译测试，能把防火墙mangle表的几个chain发个出来看看吗？

**Comment by xiaorouji** [comment]
命令行输入 /etc/init.d/passwall2 看看有无报错

**Comment by badgv** [comment]
> 命令行输入 /etc/init.d/passwall2 看看有无报错

大佬，我刚编译了一个，启动后看了下iptables表，我看你昨天修改增加了连接追踪相关功能，特别是CONNMARK，但是编译的时候，没有添加connmark相关的依赖，好像是防火墙规则没有加载完全导致的问题。
在network-firewall菜单，有个iptables-mod-conntrack-extra的模块要勾上，才能给iptables内核加上CONNMARK功能。
我重新编译加上了这个包编译上，目前测试好像正常，再观察下

**Comment by jh0072110** [comment]
> 还没编译测试，能把防火墙mangle表的几个chain发个出来看看吗？
![IMG_2327](https://user-images.githubusercontent.com/50496854/163901632-8c7501b8-dcbe-4164-94fe-82ce02d2a147.jpg)

**Comment by badgv** [comment]
> > 还没编译测试，能把防火墙mangle表的几个chain发个出来看看吗？
> > ![IMG_2327](https://user-images.githubusercontent.com/50496854/163901632-8c7501b8-dcbe-4164-94fe-82ce02d2a147.jpg)

我已经自己编译查看了，你这确实是没有CONNMARK，编译的时候要先手动勾选上上面我说的包iptables-mod-conntrack-extra
目前正确的应该是有下面这2条
![image](https://user-images.githubusercontent.com/45598380/163901818-c33f803d-fd72-4120-87d7-9301ddaead4a.png)

**Comment by jh0072110** [comment]
> 命令行输入 /etc/init.d/passwall2 看看有无报错

<img width="613" alt="image" src="https://user-images.githubusercontent.com/50496854/163901941-3b755317-44e6-40c3-9302-8fb83f8cff6a.png">
貌似我操作的哪里不太对……

**Comment by jh0072110** [comment]
> > > 还没编译测试，能把防火墙mangle表的几个chain发个出来看看吗？
> > > ![IMG_2327](https://user-images.githubusercontent.com/50496854/163901632-8c7501b8-dcbe-4164-94fe-82ce02d2a147.jpg)
> 
> 我已经自己编译查看了，你这确实是没有CONNMARK，编译的时候要先手动勾选上上面我说的包iptables-mod-conntrack-extra 目前正确的应该是有下面这2条 ![image](https://user-images.githubusercontent.com/45598380/163901818-c33f803d-fd72-4120-87d7-9301ddaead4a.png)

收到 我试试康

**Comment by badgv** [comment]
你好，能否删除下上面这楼的图片，暴漏域名了

**Comment by xiaorouji** [comment]
@badgv  麻烦PR一下

**Comment by badgv** [comment]
> @badgv 麻烦PR一下

大佬，pr了一把，不知道弄的对不对

**Comment by jh0072110** [comment]
感觉还是有点问题，使用了两个小时（左右？）国内网站上不去了……

**Comment by badgv** [comment]
> 

我这没问题呢，测试国百度也正常的，你检查下你DNS解析问题呢？

**Comment by jh0072110** [comment]
> 我这没问题呢，测试国百度也正常的，你检查下你DNS解析问题呢？

关了就能用，也换了公共dns测试…就……挂掉了？

**Comment by jh0072110** [comment]
把2关掉重开了一下好了…原理未知…再看看吧……

**Comment by jh0072110** [comment]
受挫了，坏掉以后基本就没法用了…什么都打不开……

**Comment by badgv** [comment]
> 受挫了，坏掉以后基本就没法用了…什么都打不开……

你SSH到OP，nslookup www.baidu.com 127.0.0.1   nslookup www.google.com 127.0.0.1
先检查dns解析

**Comment by jh0072110** [comment]
> > 受挫了，坏掉以后基本就没法用了…什么都打不开……
> 
> 你SSH到OP，nslookup [www.baidu.com](http://www.baidu.com) 127.0.0.1 nslookup [www.google.com](http://www.google.com) 127.0.0.1 先检查dns解析

我是觉得…如果我关掉psw2就能打开的话…就没什么必要检查了不是么（狗头）（我国内dns用的自动）

**Comment by badgv** [comment]
> > > 受挫了，坏掉以后基本就没法用了…什么都打不开……
> > 
> > 
> > 你SSH到OP，nslookup [www.baidu.com](http://www.baidu.com) 127.0.0.1 nslookup [www.google.com](http://www.google.com) 127.0.0.1 先检查dns解析
> 
> 我是觉得…如果我关掉psw2就能打开的话…就没什么必要检查了不是么（狗头）（我国内dns用的自动）

按我的理解，要不一开始就用不了，要不一直能用，在没改过什么配置的情况下，不太可能用着用着突然不行，除非XRAY主进程挂了啥的。

**Comment by jh0072110** [comment]
> > > > 受挫了，坏掉以后基本就没法用了…什么都打不开……
> > > 
> > > 
> > > 你SSH到OP，nslookup [www.baidu.com](http://www.baidu.com) 127.0.0.1 nslookup [www.google.com](http://www.google.com) 127.0.0.1 先检查dns解析
> > 
> > 
> > 我是觉得…如果我关掉psw2就能打开的话…就没什么必要检查了不是么（狗头）（我国内dns用的自动）
> 
> 按我的理解，要不一开始就用不了，要不一直能用，在没改过什么配置的情况下，不太可能用着用着突然不行，除非XRAY主进程挂了啥的。

不造啊，我出门办事，晚上回来再研究研究…

**Comment by jh0072110** [comment]
> @badgv 麻烦PR一下

那个…大佬…不负责任的猜测一下…问题会不会出在这
![Jietu20220420-012123](https://user-images.githubusercontent.com/50496854/164060441-74eaba7e-5e61-4943-8ff6-8905ce7f09ee.jpg)
feel the same issue with https://github.com/xiaorouji/openwrt-passwall2/issues/80

**Comment by xiaorouji** [comment]
不应该啊。。你试试改回去看看

**Comment by jh0072110** [comment]
> 不应该啊。。你试试改回去看看

嗯，应该不是…依旧上不去…炸的要死要活的…
<img width="546" alt="image" src="https://user-images.githubusercontent.com/50496854/164061699-ac93c4e8-ad82-4263-a37c-a8dca08a4bb7.png">

**Comment by xiaorouji** [comment]
DNS选项用了什么？还有是谁的固件？

**Comment by jh0072110** [comment]
> DNS选项用了什么？还有是谁的固件？

国内DNS用了自动
用了https://github.com/immortalwrt/immortalwrt的openwrt-21.02

**Comment by xiaorouji** [comment]
我大概猜到原因了。。因为我用的TCP转发全部端口所以没问题

**Comment by jh0072110** [comment]
> 我大概猜到原因了。。因为我用的TCP转发全部端口所以没问题

我保持在默认设置的“常用的”，您的意思是换成“所有”？

**Comment by xiaorouji** [comment]
对的 我疏忽了...

**Comment by jh0072110** [comment]
> 对的 我疏忽了...

好的大佬～多嘴问一句…改成“所有”是现在的临时解决方案还是永久解决方案？

**Comment by xiaorouji** [comment]
临时。
明天再修了...躺床上了

**Comment by jh0072110** [comment]
> 临时。 明天再修了...躺床上了

好的好的，早点休息

**Comment by jh0072110** [comment]
嗯…告诉大佬一个不好的消息…改成所有也会崩……

**Comment by xiaorouji** [comment]
更新最新源码试下

**Comment by jh0072110** [comment]
> 更新最新源码试下

好～

**Comment by jh0072110** [comment]
好像是合适了，close了再观察一下

**Comment by 363843342** [comment]
楼主解决了吗？这边也遇到类似问题，只要是直连的都无法链接，一旦开启除非选了可用节点，直连的都无法连接，包括nslookup也超时
