### ISSUE TITLE
[Bug]: 最新版本嚴重bug

### ISSUE THREAD

**Issue by whwhwh93** [xiaorouji/openwrt-passwall2#740]
### Describe the Bug you encountered

啟動後任何網站無法打開

### Steps to reproduce this Bug

啟動後任何網站無法打開

### What you want to implement

能打開網站

### Log information

Xray 24.12.18 (Xray, Penetrates Everything.) OpenWrt (go1.23.4 linux/arm64)
A unified platform for anti-censorship.
Failed to start: main: failed to load config files: [/tmp/etc/passwall2/acl/default/global.json] > infra/conf/serial: failed to decode config: &{Name:/tmp/etc/passwall2/acl/default/global.json Format:json} > infra/conf/serial: failed to read config file > EOF

### System related information

luci-23.05_luci-app-passwall2_24.12.19

**Comment by xiaorouji** [comment]
Fix

**Comment by xiaorouji** [comment]
升級到最新版本請不要保留配置

**Comment by w931018h** [comment]
恢復過出廠設置了 而且為什麼每次release19.07都是-2，23.05都是-1

**Comment by w931018h** [comment]
> 升級到最新版本請不要保留配置

恢復過出廠設置了 而且為什麼每次release19.07都是-2，23.05都是-1
