### ISSUE TITLE
[Bug]: 24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

### ISSUE THREAD

**Issue by wangxian001** [xiaorouji/openwrt-passwall2#741]
### Describe the Bug you encountered

24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

### Steps to reproduce this Bug

24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

### What you want to implement

24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

### Log information

24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

### System related information

24.15版本开始，节点列表表格的首行颜色错乱，底色和文字同色，看不见文字了。24.14是ok的。

**Comment by hxlls** [comment]
![image](https://github.com/user-attachments/assets/6c7bfb7a-bae2-41ec-80e8-56d3f3ec16fc)
建议不保存配置更新，最新的版本

**Comment by xiaorouji** [comment]
這個是顯示當前使用的節點的CSS樣式，可能不同主題導致的效果不一。現已改成字體顏色標紅。
