### ISSUE TITLE
[Bug]: 在主设置页面点击保存，如果存在两个以上分流节点，不在主设置页中的分流节点选项被重置

### ISSUE THREAD

**Issue by XiaoMR1024** [xiaorouji/openwrt-passwall2#743]
### Describe the Bug you encountered

在主设置页面点击保存，如果存在两个以上分流节点，不在主设置页中的分流节点选项被重置

### Steps to reproduce this Bug

在主设置页面点击保存，如果存在两个以上分流节点，不在主设置页中的分流节点选项被重置
如下图，点击保存后第二个分流节点Overseas 选项被重置成关闭
![a836a939-2942-4aea-a987-9579d9d08d6e](https://github.com/user-attachments/assets/4ca7139a-9074-4b09-bcf5-90d871f5a4c7)
![2](https://github.com/user-attachments/assets/0af3cfce-a399-4769-85d9-18d0fae805f6)
![3](https://github.com/user-attachments/assets/7f528c7e-33db-4d2c-b74c-0ad7158f66b3)

### What you want to implement

主页面能够正常保存设置

### Log information

n/a

### System related information

-passwall2 version:24.12.19-2

**Comment by xiaorouji** [comment]
Fix

**Comment by XiaoMR1024** [comment]
thx
