### ISSUE TITLE
[Bug]:24.12.22-1 haproxy负载均衡本地socks地址不能再写127.0.0.1，需改成路由器地址如192.168.1.1

### ISSUE THREAD

**Issue by MadMaxPayneNeo** [xiaorouji/openwrt-passwall2#744]
### Describe the Bug you encountered

24.12.22-1如果使用hy2（无论singbox还是hy2内核）节点， haproxy负载均衡本地socks地址不能再写127.0.0.1，需改成路由器地址如192.168.1.1，否则几分钟后健康检测全部飘红导致haproxy以为线路全部中断无法使用。vless和vmess节点无此bug。退回旧版本问题依旧，也不算啥大bug，但折腾了一晚上才发现问题

### Steps to reproduce this Bug

haproxy负载均衡本地socks地址不能再写127.0.0.1，需改成路由器地址如192.168.1.1

### What you want to implement

能修就修，不好修声明下

### Log information

无log提供

### Screenshot

无

### System related information

尝试不同版本固件23.05分支和24.10.10分支、6.1.120和6.6.66内核，最新版passwall2都可复现

### Other Information

无

**Comment by xiaorouji** [comment]
並不會
