### ISSUE TITLE
[Feature Request]: 能否提供开关彻底关闭DNS相关配置

### ISSUE THREAD

**Issue by xymfs** [xiaorouji/openwrt-passwall2#746]
### Describe the new feature you want

我使用AdGuardHome作为DNS，无需pw2自动帮忙配置的dnsmasq等DNS相关功能。

### Describe the solution you want

能否提供一个开关，彻底关闭DNS的相关配置？包括iptables、dnsmasq等...

**Comment by lwb1978** [comment]
你连ipt都不要那直接用个xray的ui或者sing-box的ui就完事了，没必要用pw

**Comment by Zephor5** [comment]
附议，希望自己配置dns服务，目前使用pw2配置dns，总是有些访问比较慢。前一阵自己hack过代码禁掉dns相关的防火墙配置，以及dns启动配置，搭配smartdns用挺好的。换了x86路由，实在不想又折腾一遍。许愿一个dns相关功能开关

**Comment by Travel2Here** [comment]
+1，期待开放高级dns控制项。默认为小白配好就行，高级用户也能自主。

**Comment by bigbugcc** [comment]
+1

**Comment by Zephor5** [comment]
@xiaorouji  大佬，看了下提交记录好像没这个相关的。 麻烦问下现有的开关是哪个..  是app.sh 里面 DNS_CACHE 和 DNS_REDIRECT 两个变量吗？  禁用之后确实可以了，dnsmasq还是会启动，还得改启动dnsmasq的函数。  有没有一个后台开关的

**Comment by Zephor5** [comment]
留一个自己的改动吧

1. /usr/share/passwall2/app.sh
  a. 将最后的 DNS_CACHE 和 DNS_REDIRECT 设置为0
  b. 将 run_copy_dnsmasq 、run_ipset_dnsmasq、run_ipset_chinadns_ng 几个函数内部逻辑注释掉
2. /usr/share/passwall2/helper_dnsmasq.lua 脚本里末尾的func变量置空 local func = nil
3. （可选，如果使用搬瓦工访问chatgpt）/usr/share/passwall2/nftables.sh 和 iptables.sh 里面的 172.16.0.0/12 改成 172.16.0.0/16

有时候关passwall2可能防火墙53相关的规则没清理干净需要手动删

以上，设置之后passwall2 dns相关功能即可禁用

**Comment by ssd2077** [comment]
> 留一个自己的改动吧
> 
> 1. /usr/share/passwall2/app.sh
>    a. 将最后的 DNS_CACHE 和 DNS_REDIRECT 设置为0

我就单单会弄这两个，但是设置完。感觉网页打开延时感没了。
