### ISSUE TITLE
[Feature Request]: 添加对geosite:xxx@xx的支持

### ISSUE THREAD

**Issue by Dro9an** [xiaorouji/openwrt-passwall2#748]
### Describe the new feature you want

在添加分流规则时，域名栏内添加geosite:steam@cn时，在节点debug日志内发现对应域名无法命中，在换成geosite:steam后，才能成功命中对应域名，现在geosite内有很多规则都已经添加了@标签来精细区分，不知道是我使用有问题还是确实没这个功能

### Describe the solution you want

添加对geosite:xxx@xx的支持

### Other Information

使用内核：Xray

**Comment by XiaoMR1024** [comment]
我这边用的12.26版本 正常识别@cn后缀 没问题啊

**Comment by RoganLeon** [comment]
> 我这边用的12.26版本 正常识别@cn后缀 没问题啊

我这也是12.26，加上后缀以后重启steam看节点debug日志都没有命中geosite:steam@cn的纪录，去掉后缀才有geosite:steam命中的记录，就很奇怪

**Comment by lwb1978** [comment]
要支持@后缀需要两个条件，一个是geosite要新版，xray也需要新版，pw只负责生成配置文件给xray，不存在pw去支持的说法。

**Comment by Dro9an** [comment]
> 要支持@后缀需要两个条件，一个是geosite要新版，xray也需要新版，pw只负责生成配置文件给xray，不存在pw去支持的说法。

问题就出在geosite geoip，xray核心都已经更新到最新，日志内还是无法命中
