### ISSUE TITLE
用不了阿里云盘/阿里云盘webdav

### ISSUE THREAD

**Issue by samueler2016** [xiaorouji/openwrt-passwall2#79]
用了passwall2,就打不开阿里云盘/阿里云盘webdav😂

**Comment by davider2016** [comment]
用的是xray，vless+ws+cdn

**Comment by jh0072110** [comment]
不知道你设置如何 也不知道你aliyundrive插件版本为何 无法解答 只能说…我用着没问题……

**Comment by davider2016** [comment]
> 不知道你设置如何 也不知道你aliyundrive插件版本为何 无法解答 只能说…我用着没问题……

路由器设置:光猫+K2P+N1(71+)(单臂路由模式，N1拨号)
科学上网协议 Xray vless+ws+cdn(cloudflare免费节点，远程DNS是1.1.1.1)
问题:阿里网盘app/阿里网盘插件，磁力都无法使用（貌似还有些国内网站打不开），但可以打开fembed.net/PBS.org相关域名
对比:SSR Plus/Passwall可以打开阿里网盘/阿里webdav，磁力等，但打不开fembed.net/PBS.org域名

**Comment by chancat87** [comment]
那你换个插件alist试试呢
