### ISSUE TITLE
1.3-15 LOL连不上服务器啊

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall2#80]
![image](https://user-images.githubusercontent.com/59167936/164058423-02bfc94f-543d-4aa4-a98e-fa25c519920a.png)
关闭passwall2就正常了.

还有间歇性的 无法访问国内网站 显示 DNS错误

**Comment by xiaorouji** [comment]
已确定是bug。
临时解决方案：把TCP和UDP转发端口选所有

**Comment by yunxi993** [comment]
还有DNS解析暴毙，国内外网站DNS都无法解析，IP连接的正常：TG

**Comment by yunxi993** [comment]
关闭passwall2 在开启便恢复正常.

**Comment by xiaorouji** [comment]
更新最新源码试下

**Comment by yunxi993** [comment]
1.3-16 LOL服务器连接正常.

DNS解析间歇性暴毙问题、暂未出现.
