### ISSUE TITLE
fakedns模式把某一目标IP的端口放行。如何操作？

### ISSUE THREAD

**Issue by typeedd** [xiaorouji/openwrt-passwall2#82]
已解决

**Comment by badgv** [comment]
fakeip是处理DNS解析，你直连外部IP，又不是使用的域名，和fakeip没啥关系吧
主要是看你的分流策略是如何配置的
如果你分流最后的“默认”不是“直连”，而你要连的IP，没写在上面分流的“直连”IP列表，这个IP就会走代理

**Comment by xiaorouji** [comment]
Fix.
