### ISSUE TITLE
内网DNS解析问题

### ISSUE THREAD

**Issue by badgv** [xiaorouji/openwrt-passwall2#83]
最近的源码，如果UDP不代理端口为不使用，局域内网和OP自身，无法使用IPV4（除WAN口IP外）进行DNS解析。
OP的SHELL内，可以直接在127.0.0.1上面做nslookup查询，可以使用WAN口IP做nslookup查询，可以全用其它公网DNS做查询，但是无法指定LAN口IP做DNS查询

如果UDP不代理端口填上53，那就一切正常，不知道算不算BUG。

尝试分析过iptables，并添加相关iptables配置，处理不了，只有在prerouting直接匹配udp dport 53做return，才能正常，匹配接口或IP都不行，找不到原因。

**Comment by xiaorouji** [comment]
我似乎复现不了。
DNS选项那一栏和高级设置那一栏截图我看看？

**Comment by badgv** [comment]
![image](https://user-images.githubusercontent.com/45598380/164178281-a6e0a1bf-d1ea-4a77-80e3-6f89df2620bf.png)
![image](https://user-images.githubusercontent.com/45598380/164178329-ceecee35-00e6-4ecf-b428-499d459dae41.png)
DNS是套了2个本地的DNS插件，dnsforwarder做的国内并发UDP查询
mosdns只做国外查询prefer_ipv4模式，正常只返回IPV4地址

**Comment by badgv** [comment]
> 我似乎复现不了。 DNS选项那一栏和高级设置那一栏截图我看看？

如果我不在UDP不转发填上53，我ssh登陆OP，nslookup 任意域名 192.168.8.10(LAN口），都无法查询

**Comment by badgv** [comment]
不转发端口为“不使用”就是这种状态
![image](https://user-images.githubusercontent.com/45598380/164179229-6280cc61-d008-403e-a2fa-e061aa1da77a.png)

**Comment by badgv** [comment]
大佬，填上UDP不代理53，会在mangle的PSW2和PSW2_OUTPUT都插入了一条 dport 53 return，我尝试删除OUTPUT那条规则，DNS解析没有任何影响，但是如果删除PSW2里面那条dport 53规则，就和我上面现象一样了

**Comment by badgv** [comment]
op源码是大雕的那个源，自带了个NAT劫持DNS规则
![image](https://user-images.githubusercontent.com/45598380/164183831-2338d73a-29a9-4d1f-976d-c4bf984746c4.png)

**Comment by xiaorouji** [comment]
你把这一堆重定向DNS规则注释看看

**Comment by badgv** [comment]
> 你把这一堆重定向DNS规则注释看看

我试下

**Comment by badgv** [comment]
> 你把这一堆重定向DNS规则注释看看

大佬666，注释那4条真的可以，但是注释了，局域网就不能劫持设备的DNS请求了，只要DNS请求不是指向OP的LOCAL地址，就无法进行无污染解析和域名重写了，不知道有没有两全齐美的办法啊

**Comment by xiaorouji** [comment]
这个就要想想怎样兼容了

**Comment by xiaorouji** [comment]
这个应该和 https://github.com/xiaorouji/openwrt-passwall/issues/1677#issuecomment-1014203396  相同问题

**Comment by badgv** [comment]
> 这个就要想想怎样兼容了

大佬，我还有一个N1用docker跑的op，N1主机内核是5.3.0-aml-g12，同样的配置，似乎没有这种问题。

上面这个有问题的是我主OP，在群晖用虚拟机跑的，搞不懂到底是配置问题还是哪里有BUG了，按理说，虚拟机下的OP，带了完整的内核，应该BUG更少才对，难道N1的是因为什么BUG导致的能解析

**Comment by yunxi993** [comment]
N1 EMMC
![image](https://user-images.githubusercontent.com/59167936/164192020-8b5cee88-2d0d-45a6-911c-727a3d43f016.png)

**Comment by badgv** [comment]
> N1 EMMC ![image](https://user-images.githubusercontent.com/59167936/164192020-8b5cee88-2d0d-45a6-911c-727a3d43f016.png)

我N1+docker的OP也没这问题，我测试了的，就虚拟机的OP有这问题

**Comment by yunxi993** [comment]
> 我N1+docker的OP也没这问题，我测试了的，就虚拟机的OP有这问题

前两个版本有遇到一个问题，使用IPv4 DNS解析挂在CF上可直连的网站特别慢、大多还无法解析，使用IPv6 DNS解析就很快，跟你这个部分相似.

**Comment by badgv** [comment]
> > 我N1+docker的OP也没这问题，我测试了的，就虚拟机的OP有这问题
> 
> 前两个版本有遇到一个问题，使用IPv4 DNS解析挂在CF上可直连的网站特别慢、大多还无法解析，使用IPv6 DNS解析就很快，跟你这个部分相似.

我没这问题，我也有CF域名，我CF域名直接在psw2里面域名重写固定IP了的
