### ISSUE TITLE
geosite&geoip手动更新不成功

### ISSUE THREAD

**Issue by DearTanker** [xiaorouji/openwrt-passwall2#84]
日志提示更新成功，但是`/usr/share/v2ray/`下的文件没变

**Comment by chika0801** [comment]
我测试过，开打节点，能翻墙了，是能更新成功的。

不翻墙时，看了下下载地址是github的直连应该是太慢失败。

你可以用WINSCP等软件直接上传上去，再重启passwall生效，是一样的效果。

**Comment by DearTanker** [comment]
不是姿势的问题，代理都是正常的，但是文件没更新成功。
自己上传了最新的geodata到那个目录下以后再点击手动更新还是不会更新。
试了卸载插件、重置默认都没办法更新，不知道是不是缺了什么依赖（重新安装的时候没有出现报错）。

也不知道还有哪里可以查到更详细的日志。

![2022-04-21 142730](https://user-images.githubusercontent.com/1122669/164388240-6db2d645-1cfc-49da-bc58-cb3560d80b54.jpg)

![2022-04-21 142749](https://user-images.githubusercontent.com/1122669/164388328-cbdccc32-1f4e-47a8-a8ac-d87bf4c20cf8.jpg)

**Comment by chika0801** [comment]
> 不是姿势的问题，代理都是正常的，但是文件没更新成功。 自己上传了最新的geodata到那个目录下以后再点击手动更新还是不会更新。 试了卸载插件、重置默认都没办法更新，不知道是不是缺了什么依赖（重新安装的时候没有出现报错）。
> 
> 也不知道还有哪里可以查到更详细的日志。
> 
> ![2022-04-21 142730](https://user-images.githubusercontent.com/1122669/164388240-6db2d645-1cfc-49da-bc58-cb3560d80b54.jpg)
> 
> ![2022-04-21 142749](https://user-images.githubusercontent.com/1122669/164388328-cbdccc32-1f4e-47a8-a8ac-d87bf4c20cf8.jpg)

这情况我之前也遇到过，当时就手动拿WINSCP上传的。

今天重新编译重新版本，连上代理后，它自己更新又成了。

反正我是比较迷，供你参考。

**Comment by DearTanker** [comment]
@chika0801 了解，谢谢你

**Comment by DearTanker** [comment]
2个月来，不管是自动更新还是手动更新都没有成功过。最后自己写了个脚本用 cron 定期运行。。。
