### ISSUE TITLE
生成的Xray配置文件中 DNS 模块里的远程DNS 不能走代理的BUG

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#86]
查看生成的配置

<pre>
  "dns": {
    "disableFallback": true,
    "queryStrategy": "UseIPv4",
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "port": 53,
        "_flag": "default",
        "address": "8.8.8.8"
      },
      {
        "_flag": "remote",
        "port": 53,
        "domains": [
          "geosite:category-ads-all",
          "geosite:geolocation-!cn"
        ],
        "address": "8.8.8.8"
      },
      {
        "_flag": "direct",
        "port": 53,
        "domains": [
          "geosite:category-games@cn",
          "geosite:tld-cn",
          "geosite:cn"
        ],
        "address": "192.168.2.1"
      }
    ],
    "disableCache": false,
    "tag": "dns-in1"
  },
</pre>

routing
<pre>
      {
        "type": "field",
        "inboundTag": [
          "dns-in1"
        ],
        "outboundTag": "default"
      },
</pre>

<pre>
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "192.168.2.1"
        ]
      },
</pre>
看你的用意是 192.168.2.1 走"outboundTag": "direct"，是生效的。

其它的2组DNS，用 "tag": "dns-in1" 走 "outboundTag": "default" 。经测试这么写，是无效的。

**Comment by chika0801** [comment]
因为你在 Proxy 规则里默认加了8.8.8.8，暂时先删除，日志如下

<pre>
2022/04/21 05:45:31 [Info] [3619409411] app/dispatcher: taking detour [dns-out] for [udp:8.8.8.8:53]
2022/04/21 05:45:31 [Info] [3619409411] proxy/dns: handling DNS traffic to tcp:8.8.8.8:53
2022/04/21 05:45:31 [Debug] app/dns: domain moecm.com will use the first DNS: [UDP:8.8.8.8:53]
2022/04/21 05:45:31 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: moecm.com.
2022/04/21 05:45:31 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2022/04/21 05:45:31 [Info] transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2022/04/21 05:45:31 [Info] app/dispatcher: taking detour [direct] for [udp:8.8.8.8:53]
2022/04/21 05:45:31 [Info] proxy/freedom: opening connection to udp:8.8.8.8:53
2022/04/21 05:45:31 [Debug] transport/internet: dialing to udp:8.8.8.8:53
2022/04/21 05:45:31 DNS accepted udp:8.8.8.8:53 [direct]
2022/04/21 05:45:31 [Info] app/dns: UDP:8.8.8.8:53 got answer: moecm.com. TypeA -> [216.38.168.98] 48.585921ms
2022/04/21 05:45:31 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:moecm.com.
2022/04/21 05:45:31 [Debug] [2527294816] proxy/dokodemo: processing connection from: 192.168.10.20:3626
2022/04/21 05:45:31 [Info] [2527294816] proxy/dokodemo: received request for 192.168.10.20:3626
2022/04/21 05:45:31 [Info] [2527294816] app/dispatcher: sniffed domain: moecm.com
2022/04/21 05:45:31 [Info] [2527294816] app/dispatcher: taking detour [default] for [tcp:moecm.com:443]
2022/04/21 05:45:31 [Info] [2527294816] transport/internet/tcp: dialing TCP to tcp:我的VPS_IP:443
2022/04/21 05:45:31 [Debug] transport/internet: dialing to tcp:我的VPS_IP:443
2022/04/21 05:45:31 192.168.10.20:3626 accepted tcp:216.38.168.98:443 [default]
2022/04/21 05:45:31 [Info] [2527294816] proxy/vless/outbound: tunneling request to tcp:216.38.168.98:443 via 我的VPS_IP:443
</pre>

**2022/04/21 05:45:31 [Info] app/dispatcher: taking detour [direct] for [udp:8.8.8.8:53]**

8.8.8.8没有命中 "tag": "dns-in1" 走 "outboundTag": "default" 实际是直连

**Comment by chika0801** [comment]
在 Proxy 规则里默认加上8.8.8.8，日志如下
<pre>
2022/04/21 05:48:41 [Info] [835924798] app/dispatcher: taking detour [dns-out] for [udp:8.8.8.8:53]
2022/04/21 05:48:41 [Info] [835924798] proxy/dns: handling DNS traffic to tcp:8.8.8.8:53
2022/04/21 05:48:41 [Debug] app/dns: domain moecm.com will use the first DNS: [UDP:8.8.8.8:53]
2022/04/21 05:48:41 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: moecm.com.
2022/04/21 05:48:41 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2022/04/21 05:48:41 [Info] transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2022/04/21 05:48:41 [Info] app/dispatcher: taking detour [default] for [udp:8.8.8.8:53]
2022/04/21 05:48:41 [Info] transport/internet/tcp: dialing TCP to tcp:我的VPS_IP:443
2022/04/21 05:48:41 [Debug] transport/internet: dialing to tcp:我的VPS_IP:443
2022/04/21 05:48:41 DNS accepted udp:8.8.8.8:53 [default]
2022/04/21 05:48:41 [Info] proxy/vless/outbound: tunneling request to udp:8.8.8.8:53 via 我的VPS_IP:443
2022/04/21 05:48:41 [Info] app/dns: UDP:8.8.8.8:53 got answer: moecm.com. TypeA -> [216.38.168.98] 316.777236ms
2022/04/21 05:48:41 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:moecm.com.
2022/04/21 05:48:41 [Debug] [1140641435] proxy/dokodemo: processing connection from: 192.168.10.20:3669
2022/04/21 05:48:41 [Info] [1140641435] proxy/dokodemo: received request for 192.168.10.20:3669
2022/04/21 05:48:41 [Info] [1140641435] app/dispatcher: sniffed domain: moecm.com
2022/04/21 05:48:41 [Info] [1140641435] app/dispatcher: taking detour [default] for [tcp:moecm.com:443]
2022/04/21 05:48:41 [Info] [1140641435] transport/internet/tcp: dialing TCP to tcp:我的VPS_IP:443
2022/04/21 05:48:41 [Debug] transport/internet: dialing to tcp:我的VPS_IP:443</pre>

**Comment by chika0801** [comment]
v2fly文件(xray是和v2这边一样的)
https://www.v2fly.org/config/dns.html#dnsobject

**tag: string**

**（V2Ray 4.13+）由此 DNS 发出的查询流量，除 localhost 和 DOHL_ 模式外，都会带有此标识，可在路由使用 inboundTag 进行匹配。**

我写DNS规则 ，都没在DNS里用过 tag。习惯了在 routing里，为这个DNS的IP指定一个 出站 tag。

看到你的写法，特意验证了一下。

**Comment by badgv** [comment]
```
      {
        "type": "field",
        "inboundTag": [
          "dns-in1"
        ],
        "outboundTag": "default"
      },
```
这段是在routing的倒数第二个位置了，DNS查询先匹配了前面的 routing规则，感觉应该没啥毛病吧

**Comment by badgv** [comment]
为什么你的DNS模块里面，默认那个DNS是8.8.8.8啊？我的DNS，默认DNS是我配置的直连DNS，难道是你分流里面“默认”配置的代理模式？

**Comment by badgv** [comment]
我去看了下配置，我的默认分流模式是“直连”，生成的config配置里面outbound里面根本没有default这个tag的出口，所以
'''
      {
        "type": "field",
        "inboundTag": [
          "dns-in1"
        ],
        "outboundTag": "default"
      },
'''
所在在我的配置情况下，这条配置是无效果的，因为找不到出口，如果不在上面routing规则定义8.8.8.8走指定代理出口，那实际就是走的直连。

**Comment by chika0801** [comment]
> 我去看了下配置，我的默认分流模式是“直连”，生成的config配置里面outbound里面根本没有default这个tag的出口.
> 
> ```
>       {
>         "type": "field",
>         "inboundTag": [
>           "dns-in1"
>         ],
>         "outboundTag": "default"
>       },
> ```
> 
> 所在在我的配置情况下，这条配置是无效果的，因为找不到出口，如果不在上面routing规则定义8.8.8.8走指定代理出口，那实际就是走的直连。

我默认分流是代理，我把远程dns自定义为8.8.8.8方便观察日志。

代理规则里作者默认加了8.8.8.8代理，我平时默认删了的，就发现这问题了。

**Comment by chika0801** [comment]
> 为什么你的DNS模块里面，默认那个DNS是8.8.8.8啊？我的DNS，默认DNS是我配置的直连DNS，难道是你分流里面“默认”配置的代理模式？

我用的配置在这
https://github.com/chika0801/openwrt-passwall2/blob/149d2b01abc4aee3df1afc64f778e0ef1430cadd/luci-app-passwall2/root/usr/share/passwall2/0_default_config#L56

**Comment by xiaorouji** [comment]
我把dns-in1规则移到下面就是考虑了给你们自己自定义走哪个代理或者直连

**Comment by badgv** [comment]
> 我把dns-in1规则移到下面就是考虑了给你们自己自定义走哪个代理或者直连

"outboundTag": "default" ，在分流模式下，默认直连状态下，配置文件的outbound是没有tag:default这一组配置的吧？这时候这条routing规则是没效果的

**Comment by badgv** [comment]
> 默认直连那个我知道，其实现在这个逻辑没必要加这个dns-in1 rule了

我也觉得这条routing规则没啥用。正常情况下大家用的远程DNS，都会加到代理列表里面的吧。。

**Comment by chika0801** [comment]
> > 因为你在 Proxy 规则里默认加了8.8.8.8，暂时先删除，日志如下
> > 2022/04/21 05:45:31 [Info] [3619409411] app/dispatcher: taking detour [dns-out] for [udp:8.8.8.8:53]
> > 2022/04/21 05:45:31 [Info] [3619409411] proxy/dns: handling DNS traffic to tcp:8.8.8.8:53
> > 2022/04/21 05:45:31 [Debug] app/dns: domain moecm.com will use the first DNS: [UDP:8.8.8.8:53]
> > 2022/04/21 05:45:31 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: moecm.com.
> > 2022/04/21 05:45:31 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
> > 2022/04/21 05:45:31 [Info] transport/internet/udp: establishing new connection for udp:8.8.8.8:53
> > 2022/04/21 05:45:31 [Info] app/dispatcher: taking detour [direct] for [udp:8.8.8.8:53]
> > 2022/04/21 05:45:31 [Info] proxy/freedom: opening connection to udp:8.8.8.8:53
> > 2022/04/21 05:45:31 [Debug] transport/internet: dialing to udp:8.8.8.8:53
> > 2022/04/21 05:45:31 DNS accepted udp:8.8.8.8:53 [direct]
> > 2022/04/21 05:45:31 [Info] app/dns: UDP:8.8.8.8:53 got answer: moecm.com. TypeA -> [216.38.168.98] 48.585921ms
> > 2022/04/21 05:45:31 [Debug] app/dns: UDP:8.8.8.8:53 updating IP records for domain:moecm.com.
> > 2022/04/21 05:45:31 [Debug] [2527294816] proxy/dokodemo: processing connection from: 192.168.10.20:3626
> > 2022/04/21 05:45:31 [Info] [2527294816] proxy/dokodemo: received request for 192.168.10.20:3626
> > 2022/04/21 05:45:31 [Info] [2527294816] app/dispatcher: sniffed domain: moecm.com
> > 2022/04/21 05:45:31 [Info] [2527294816] app/dispatcher: taking detour [default] for [tcp:moecm.com:443]
> > 2022/04/21 05:45:31 [Info] [2527294816] transport/internet/tcp: dialing TCP to tcp:我的VPS_IP:443
> > 2022/04/21 05:45:31 [Debug] transport/internet: dialing to tcp:我的VPS_IP:443
> > 2022/04/21 05:45:31 192.168.10.20:3626 accepted tcp:216.38.168.98:443 [default]
> > 2022/04/21 05:45:31 [Info] [2527294816] proxy/vless/outbound: tunneling request to tcp:216.38.168.98:443 via 我的VPS_IP:443
> > **2022/04/21 05:45:31 [Info] app/dispatcher: taking detour [direct] for [udp:8.8.8.8:53]**
> > 8.8.8.8没有命中 "tag": "dns-in1" 走 "outboundTag": "default" 实际是直连
> > ```
> >   {
> >     "type": "field",
> >     "inboundTag": [
> >       "dns-in1"
> >     ],
> >     "outboundTag": "default"
> >   },
> > ```
> 
> 其实是命中了你的UDP规则

感谢你的回复。

经过你的提醒，我想了一下确实我的 routing 规则里 有UDP走直连，它确定是命中了这条，走的直连。

**Comment by xiaorouji** [comment]
会命中的，已测试过
