### ISSUE TITLE
使用 流量嗅探只供路由使用 (Xray) 后，如果 UDP不转发端口 为 不使用，则打不开网页

### ISSUE THREAD

**Issue by chika0801** [xiaorouji/openwrt-passwall2#90]
复现方法

1、UDP不转发端口 默认值是 不使用

2、选中 流量嗅探只供路由使用

3、重启路由器，开头10秒左右你感觉能打开网页，然后什么网页都打不开，刷新网页时日志中重复有出现下面的

192.168.10.1是我路由器的IP

<pre>
2022/04/22 08:50:18 192.168.10.200:21835 accepted udp:192.168.10.1:53 [direct]
2022/04/22 08:50:18 192.168.10.132:59731 accepted udp:192.168.10.1:53 [direct]
2022/04/22 08:50:18 192.168.10.132:49627 accepted udp:192.168.10.1:53 [direct]
</pre>

解决方法 UDP不转发端口 填 53，点保存应用。

**再重启路由，或关开一次Passwall2后生效。**

**Comment by xiaorouji** [comment]
没，另外我发现此问题大多数都是lean固件的

**Comment by chika0801** [comment]
> 没，另外我发现此问题大多数都是lean固件的
源是天灵的，路由是ax6，如果你没复现那算了。

**Comment by xiaorouji** [comment]
先开着吧，看看有多少人有这问题

**Comment by xiaorouji** [comment]
看了你这个日志，感觉不应该出现才对。
iptables应该会把laniplist直接return不会进入xray才对

**Comment by xiaorouji** [comment]
你看看你的固件 防火墙 自定义规则是否有DNS劫持规则。如果有估计就是可能和passwall一些规则不兼容了
他们都喜欢默认劫持DNS。。。。。

**Comment by chika0801** [comment]
防火墙——自定义规则 

# This file is interpreted as shell script.
# Put your custom iptables rules here, they will
# be executed with each firewall (re-)start.

# Internal uci firewall chains are flushed and recreated on reload, so
# put custom rules into the root chains e.g. INPUT or FORWARD or into the
# special user chains, e.g. input_wan_rule or postrouting_lan_rule.


Turbo AAC里，开了 DNS 缓存。这个选项关与开，我都测试了，如果不放行53是一样的结果。

**Comment by chika0801** [comment]
另外我有台AX6S，源是 https://github.com/Boos4721/openwrt，用默认配置，一会刷上我也复测一下这现象。

**Comment by xiaorouji** [comment]
SSH输入
iptables -t nat -nvL 看一下

**Comment by chika0801** [comment]
UDP 不转发端口 设置53
<pre>
root@ImmortalWrt:~# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 4572 packets, 1328K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 4953 1353K PSW2_REDIRECT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 5778 1476K prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
 3123  275K zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
 2562 1196K zone_wan_prerouting  all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
  376 24209 REDIRECT   udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* DNSMASQ */ udp dpt:53 redir ports 53

Chain INPUT (policy ACCEPT 1341 packets, 93340 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1221 packets, 85482 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 719 packets, 48494 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2296  161K postrouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
   19  3448 zone_lan_postrouting  all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
 1212 87580 zone_wan_postrouting  all  --  *      eth0    0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain PSW2 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            192.168.2.188        /* 'WAN_IP_RETURN' */
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* '默认' */

Chain PSW2_OUTPUT (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xff

Chain PSW2_REDIRECT (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain zone_lan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   19  3448 postrouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */

Chain zone_lan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 3123  275K prerouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */

Chain zone_wan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 1212 87580 postrouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
 1212 87580 FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 2562 1196K prerouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
 2562 1196K FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
</pre>

**Comment by xiaorouji** [comment]
我看到了DNS劫持规则了

**Comment by chika0801** [comment]
UDP 不转发端口 不转发

<pre>
root@ImmortalWrt:~# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 12 packets, 2480 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   22  4439 PSW2_REDIRECT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
   69  9645 prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
   68  9408 zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    1   237 zone_wan_prerouting  all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
    0     0 REDIRECT   udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* DNSMASQ */ udp dpt:53 redir ports 53

Chain INPUT (policy ACCEPT 3 packets, 1592 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 7 packets, 660 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 7 packets, 660 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  105  8787 postrouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
    7  1197 zone_lan_postrouting  all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
   79  6324 zone_wan_postrouting  all  --  *      eth0    0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain PSW2 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            192.168.2.188        /* 'WAN_IP_RETURN' */
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* '默认' */

Chain PSW2_OUTPUT (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xff

Chain PSW2_REDIRECT (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain zone_lan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    7  1197 postrouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */

Chain zone_lan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   68  9408 prerouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */

Chain zone_wan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   79  6324 postrouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
   79  6324 FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    1   237 prerouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
    1   237 FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
</pre>

**Comment by xiaorouji** [comment]
你看看是不是网络 DHCP/DNS 里面有个DNS重定向，去掉试试

**Comment by chika0801** [comment]
> 我看到了DNS劫持规则了

我不懂IPtable这方面知识，只搜了一下53

  376 24209 REDIRECT   udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* DNSMASQ */ udp dpt:53 redir ports 53

 这条符合

**Comment by chika0801** [comment]
> 你看看是不是网络 DHCP/DNS 里面有个DNS重定向，去掉试试

是有这选项，它是默认选中的。下面的日志是去掉以后，重启路由得到的结果。

<pre>
root@ImmortalWrt:~# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 309 packets, 49061 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  312 49193 PSW2_REDIRECT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  329 51452 prerouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
  279 30426 zone_lan_prerouting  all  --  br-lan *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */
   50 21026 zone_wan_prerouting  all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain INPUT (policy ACCEPT 154 packets, 11263 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 474 packets, 32795 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 263 packets, 18225 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  485 33357 postrouting_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
   14  2660 zone_lan_postrouting  all  --  *      br-lan  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
  221 15063 zone_wan_postrouting  all  --  *      eth0    0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain PSW2 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            192.168.2.188        /* 'WAN_IP_RETURN' */
    0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* '默认' */

Chain PSW2_OUTPUT (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xff

Chain PSW2_REDIRECT (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain postrouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_lan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain prerouting_wan_rule (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain zone_lan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   14  2660 postrouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */

Chain zone_lan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  279 30426 prerouting_lan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */

Chain zone_wan_postrouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  221 15063 postrouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
  221 15063 FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_prerouting (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   50 21026 prerouting_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
   50 21026 FULLCONENAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3 */

</pre>

**Comment by chika0801** [comment]
现在设置情况是

DHCP/DNS —— DNS重定向 取消勾选

UDP不转发端口—— 使用

流量嗅探只供路由使用——选中

我重启路由，故障现象已消息。

**Comment by chika0801** [comment]
感谢你的回复。

我总结了一下

1、流量嗅探只供路由使用 这个选项默认没什么人会用吧，只有它选中，且UDP不转发端口——不使用，就会故障。

2、我用的天灵源，DHCP/DNS —— DNS重定向 默认被选中，如果取消这里。再 选中 流量嗅探只供路由使用，保持UDP不转发端口——不使用，也不会有故障。

**Comment by xiaorouji** [comment]
我有空再看看怎样同样兼容吧

**Comment by chika0801** [comment]
> 我有空再看看怎样同样兼容吧

你以前的默认配置，我记得是 UDP不转发端口 你填的53，你最近才去掉的。要不你保留就行了。

DHCP/DNS —— DNS重定向，这个选项。我用过天灵的，LEAN，boos4721的源，编译AX6 都是默认选中的。

我是真不懂这怪技术，献丑了。

**Comment by xiaorouji** [comment]
没事，共同交流互相学习。

**Comment by chika0801** [comment]
> 没事，共同交流互相学习。

再反馈一下。DHCP/DNS —— DNS重定向，当默认开时，我用passwall1 + hy也有类似故障。刚刚用 DNS重定向 不勾选，测试了passwall1 + hy 类似故障再没发生。

**Comment by xiaorouji** [comment]
他们的劫持DNS规则，其实应该还要加入以下命令才好。
`iptables -t mangle -I PREROUTING -p udp --dport 53 -j RETURN`

**Comment by chika0801** [comment]
今天重新编译固件测试了，用的你最新的版本https://github.com/xiaorouji/openwrt-passwall2/commit/a54804deee327c6190c7b24575d2c5e73274bff0

天灵源 AX6：DHCP/DNS——DNS 重定向 默认开了

Turbo ACC 网络加速设置——DNS 缓存 打开

Passwall里是：直连 DNS 协议——自动

高级设置——流量嗅探只供路由使用 (Xray) 打开


没有出现上面的故障现象
