### ISSUE TITLE
原生openwrt如何添加该固件呢

### ISSUE THREAD

**Issue by xiaoyaozhilv** [xiaorouji/openwrt-passwall2#96]
我找了个ipk格式的，然后上传，安装，提示错误。我用得esir最新发布的原生openwrt固件。怎么才能安装上passwall2呢

**Comment by jh0072110** [comment]
自己编译

**Comment by xiaoyaozhilv** [comment]
> 自己编译

不会啊

**Comment by sacrish** [comment]
> 我找了个ipk格式的，然后上传，安装，提示错误。我用得esir最新发布的原生openwrt固件。怎么才能安装上passwall2呢

安装错误一般是缺少依赖。你仔细看错误信息，缺什么包就先装什么。
